# Generated by BehavEd
# ( "has homing beacon been taken?" )
beacon = getGameFlag("egyptpuz", 1 )
if beacon == 1
     # ( "if beacon has been taken, open compartment, use loose stone, remove triggers" )
     act("compartment", "compartment" )
     act("stone", "stone" )
     remove ( "trig_stone", "trig_stone" )
     remove ( "trig_beacon", "trig_beacon" )
endif
# ( "has tech station been raised?" )
station = getGameFlag("egyptpuz", 2 )
if station == 1
     # ( "if station has been used, act on switch_pit so everything is how the player left it" )
     act("switch_pit", "switch_pit" )
endif
# ( "has the Living Monolith been met?" )
metmono = getGameFlag("bosses", 29 )
if metmono == 1
     setEnable("arena_trigger", "TRUE" )
endif
# ( "has the Living Monolith been defeated?" )
monolith = getGameFlag("bosses", 30 )
if monolith == 1
     remove ( "trig_monolith", "trig_monolith" )
     remove ( "arena_trigger", "arena_trigger" )
     # ( "if monolith has been defeated, remove his spawner and triggers" )
     waittimed ( 0.500 )
     remove ( "sp_livingmonolith01", "sp_livingmonolith01" )
     remove ( "monolith", "monolith" )
     remove ( "monotrig_nw", "monotrig_nw" )
     remove ( "monotrig_sw", "monotrig_sw" )
     remove ( "monotrig_ne", "monotrig_ne" )
     remove ( "monotrig_se", "monotrig_se" )
     # ( "also open the door so the player can leave the room" )
     act("monolith_exit", "monolith_exit" )
endif

