# Generated by BehavEd
# ( "enter the omega red arena" )
setWaypointPath("monolith", "", 0 )
setRecallActive("FALSE" )
setEngageEnemy("monolith", "TRUE" )
setDefaultTarget("monolith" )
attackEntityWithType("monolith", "_ACTIVE_HERO_", "ANY", "FALSE" )

