# Generated by BehavEd
# ( "this is really the script for when monolith GROWS" )
# ( "sorry" )
waittimed ( 2.000 )
pillarsup = getZoneVar("pillarsup" )
pup2 = isub(pillarsup, 1 )
setZoneVar("pillarsup", pup2 )
if pup2 == 0
     alive = alive("monolith" )
     if alive == 1
          playBossSound("voice/livingmonolith/sunup", 0, 5.000 )
     endif
     # ( "15 feet tall - full size" )
     setInvulnerable("monolith", "TRUE" )
     setPatternSequence("monolith", "monolith1" )
     newsize = fadd(2.500, 0.000 )
elif pup2 == 1
     # ( "12 feet tall" )
     setInvulnerable("monolith", "FALSE" )
     setPatternSequence("monolith", "monolith2" )
     newsize = fadd(2.000, 0.000 )
elif pup2 == 2
     # ( "10 feet tall" )
     setInvulnerable("monolith", "FALSE" )
     setPatternSequence("monolith", "monolith3" )
     newsize = fadd(1.660, 0.000 )
elif pup2 == 3
     # ( "8 feet tall" )
     setInvulnerable("monolith", "FALSE" )
     setPatternSequence("monolith", "monolith4" )
     newsize = fadd(1.333, 0.000 )
endif
alive = alive("monolith" )
if alive == 1
     # ( "GROW!" )
     sound (  "PLAY_SOUND", "boss_battles/monolith/grow", "", "" )
     cameraShake(1.000, 1.500 )
     setActorScaleTimed("monolith", newsize, 1.000 )
     playanim (  "EA_ZONE1", "monolith", "NONE", "" )
endif

