# Generated by BehavEd
# ( "indicate that the Living Monolith has been defeated" )
setGameFlag("bosses", 30, 1 )
waittimed ( 4.000 )
setDefaultTarget("" )
# ( "open the door so the player can leave the room" )
act("monolith_exit", "monolith_exit" )
# ( "play a conversation in which the X-men bask in their glorious victory" )
startConversation("act5/egypt/egypt5/5_egypt5_0020" )

