# Generated by BehavEd
# ( "this is really the script for when monolith SHRINKS" )
# ( "sorry" )
waittimed ( 2.000 )
pillarsup = getZoneVar("pillarsup" )
pup2 = iadd(pillarsup, 1 )
setZoneVar("pillarsup", pup2 )
# ( "default to 6 feet tall" )
newsize = fadd(1.000, 0.000 )
if pup2 == 1
     # ( "12 feet tall" )
     setInvulnerable("monolith", "FALSE" )
     setPatternSequence("monolith", "monolith2" )
     newsize = fadd(2.000, 0.000 )
elif pup2 == 2
     # ( "10 feet tall" )
     setInvulnerable("monolith", "FALSE" )
     setPatternSequence("monolith", "monolith3" )
     newsize = fadd(1.660, 0.000 )
elif pup2 == 3
     # ( "8 feet tall" )
     setInvulnerable("monolith", "FALSE" )
     setPatternSequence("monolith", "monolith4" )
     newsize = fadd(1.333, 0.000 )
else
     # ( "6 feet tall" )
     setInvulnerable("monolith", "FALSE" )
     setPatternSequence("monolith", "monolith5" )
endif
alive = alive("monolith" )
if alive == 1
     # ( "SHRINK!" )
     playBossSound("voice/livingmonolith/sundown", 0, 5.000 )
     sound (  "PLAY_SOUND", "boss_battles/monolith/shrink", "", "" )
     setActorScaleTimed("monolith", newsize, 1.000 )
     playanim (  "EA_ZONE2", "monolith", "NONE", "" )
endif

