# Generated by BehavEd
# ( "load point script for genosha5" )
setCurrentAct(1 )
objective ( "act1_obj_1",  "EOBJCMD_COMPLETE" )
objective ( "act1_obj_2",  "EOBJCMD_COMPLETE" )
objective ( "act1_obj_3",  "EOBJCMD_COMPLETE" )
loadMap("act1/genosha/genosha5" )
# ( "shows all quests that should be shown for genosha" )

