# Generated by BehavEd
# ( "load point script for insect1" )
setCurrentAct(1 )
# ( "shows all quests that should be shown for insect tunnels" )
objective ( "act1_obj_2",  "EOBJCMD_SHOW" )
objective ( "act1_obj_2a",  "EOBJCMD_SHOW" )
objective ( "act1_obj_2b",  "EOBJCMD_SHOW" )
objective ( "act1_obj_2c",  "EOBJCMD_SHOW" )
objective ( "act1_obj_3",  "EOBJCMD_SHOW" )
objective ( "act1_obj_3a",  "EOBJCMD_SHOW" )
loadMap("act1/insect/insect1" )

