# Generated by BehavEd
# ( "comment" )
setCurrentAct(1 )
loadMap("act1/insect/insect2" )
objective ( "act1_obj_2",  "EOBJCMD_SHOW" )
objective ( "act1_obj_2a",  "EOBJCMD_SHOW" )
objective ( "act1_obj_2b",  "EOBJCMD_SHOW" )
objective ( "act1_obj_2c",  "EOBJCMD_SHOW" )
objective ( "act1_obj_3",  "EOBJCMD_SHOW" )
objective ( "act1_obj_3a",  "EOBJCMD_SHOW" )

