# Generated by BehavEd
# ( "comment" )
setCurrentAct(3 )
# ( "perform all necessary objective updates to simulate coming from military1" )
# ( "give major quest -- destroy core" )
objective ( "act3_obj_2",  "EOBJCMD_SHOW" )
# ( "objective -- talk to angel" )
objective ( "act3_obj_2a_1",  "EOBJCMD_SHOW" )
# ( "complete objective -- talk to angel" )
objective ( "act3_obj_2a_1",  "EOBJCMD_COMPLETE" )
# ( "objective -- take x-jet to the core" )
objective ( "act3_obj_2a_2",  "EOBJCMD_SHOW" )
loadMap("act3/corein/corein1" )

