# Generated by BehavEd
# ( "comment" )
setCurrentAct(3 )
# ( "set objectives as if you already spoke with people in military1" )
# ( "talked to profX" )
objective ( "act3_obj_3",  "EOBJCMD_SHOW" )
objective ( "act3_obj_3a_1",  "EOBJCMD_SHOW" )
# ( "talked to Heather Hudson" )
setGameFlag("act3_que", 3, 1 )
objective ( "act3_obj_3a_1",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_3a_2",  "EOBJCMD_SHOW" )
loadMap("act3/infinite/infinite2" )

