# Generated by BehavEd
# ( "comment" )
setCurrentAct(3 )
# ( "Setting this global variable allow the player to come back to Madri from the military complex" )
setGameFlag("act3_que", 2, 1 )
objective ( "act3_obj_6",  "EOBJCMD_SHOW" )
objective ( "act3_obj_6a_1",  "EOBJCMD_SHOW" )
objective ( "act3_obj_6a_1",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_6a_2",  "EOBJCMD_SHOW" )
objective ( "act3_obj_6a_2",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_6a_3",  "EOBJCMD_SHOW" )
objective ( "act3_obj_6a_3",  "EOBJCMD_COMPLETE" )
loadMap("act3/madri/madri1" )

