# Generated by BehavEd
# ( "set up bastion battle" )
setCurrentAct(4 )
objective ( "perimeter3_destroy_matrix",  "EOBJCMD_COMPLETE" )
objective ( "perimeter4_disable_array",  "EOBJCMD_COMPLETE" )
objective ( "mansion1_sentinel_invasion",  "EOBJCMD_COMPLETE" )
extractionUnlock("act4/mansion/mansion1" )
extractionUnlock("act4/sewers/sewers3" )
extractionUnlock("act4/newyork/newyork1" )
extractionUnlock("act4/newyork/newyork3" )
loadMap("act4/perimeter/perimeter5" )

