# Generated by BehavEd
# ( "comment" )
setCurrentAct(4 )
extractionUnlock("act4/mansion/mansion1" )
extractionUnlock("act4/sewers/sewers3" )
# ( "set objective so deadpool is enabled" )
objective ( "act4_obj_4a",  "EOBJCMD_SHOW" )
loadMap("act4/newyork/newyork5" )

