# Generated by BehavEd
# ( "" )
setCurrentAct(4 )
extractionUnlock("act4/mansion/mansion1" )
extractionUnlock("act4/sewers/sewers3" )
extractionUnlock("act4/newyork/newyork1" )
extractionUnlock("act4/newyork/newyork3" )
loadMap("act4/pens/pens1" )

