# Generated by BehavEd
# ( "comment" )
setCurrentAct(4 )
extractionUnlock("act4/mansion/mansion1" )
extractionUnlock("act4/sewers/sewers3" )
extractionUnlock("act4/newyork/newyork1" )
extractionUnlock("act4/newyork/newyork3" )
extractionUnlock("act4/perimeter/perimeter3" )
extractionUnlock("act4/perimeter/pens3" )
loadMap("act4/tower/tower2" )

