# Generated by BehavEd
# ( "gives the player all the armor pieces so Iron Man can be unlocked" )
setGameFlag("r_imarmor", 1, 1 )
setGameFlag("r_imarmor", 2, 1 )
setGameFlag("r_imarmor", 3, 1 )
setGameFlag("r_imarmor", 4, 1 )
loadMap("bonus/bonus5" )

