# Generated by BehavEd
# ( "set up sanctuary so I can continue to act 2" )
setGameFlag("act1_visit", 13, 1 )
setGameFlag("sanctuary", 5, 1 )
objective ( "act1_obj_6a",  "EOBJCMD_SHOW" )
objective ( "act1_obj_6a",  "EOBJCMD_COMPLETE" )
objective ( "act1_obj_6",  "EOBJCMD_SHOW" )
objective ( "act1_obj_6",  "EOBJCMD_COMPLETE" )
loadMap("act1/sanctuary/sanctuary1" )

