# Generated by BehavEd
# ( "comment" )
setCurrentAct(5 )
# ( "show and/or complete objectives that the player should've" )
# ( "encountered prior to reaching this map" )
loadMap("e3/egypt3" )
objective ( "act5_obj_1",  "EOBJCMD_SHOW" )
objective ( "act5_obj_1a",  "EOBJCMD_SHOW" )
objective ( "act5_obj_1a",  "EOBJCMD_COMPLETE" )
objective ( "act5_obj_1b",  "EOBJCMD_SHOW" )
objective ( "act5_obj_1b",  "EOBJCMD_COMPLETE" )
objective ( "act5_obj_1c",  "EOBJCMD_SHOW" )

