# Generated by BehavEd
# ( "If Objective 3 is active and initial meeting with Brotherhood Leader" )
# ( "1_SANCTUARY1_100_040" )
blink_rescued = getObjective("act1_obj_1a", "COMPLETE" )
# ( "The bit of the conversation should only be played once" )
if blink_rescued == 1
     # ( "If the Talk to Sabretooth object to finish the blink rescue quest is NOT hidden" )
     # ( "Then the quest is visable, so this startCondition should be set to true" )
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

