# Generated by BehavEd
# ( "This script checks of act1 is completed" )
ready_to_go = getObjective("act1_obj_6a", "COMPLETE" )
if ready_to_go == 0
     # ( "haven't defeated Abyss yet so don't show this chunk of dialog" )
     allowConversation("FALSE" )
else
     # ( "Abyss has been defeated, show this chunk of dialog" )
     allowConversation("TRUE" )
     # ( "Mark the last objective of act 1 done, Talk to Profx" )
     objective ( "act1_obj_6b",  "EOBJCMD_COMPLETE" )
endif

