# Generated by BehavEd
# ( "This start condictino is hidden until act1_obj_5d is show" )
# ( "1_SANCTUARY1_0120" )
once_only = getObjective("act1_obj_5d", "COMPLETE" )
if once_only == 0
     prisoners_saved = getObjective("act1_obj_5d", "HIDDEN" )
     if prisoners_saved == 0
          # ( "Also the Talk to Blink objective needs to be completed" )
          objective ( "act1_obj_5d",  "EOBJCMD_COMPLETE" )
          allowConversation("TRUE" )
     else
          allowConversation("FALSE" )
     endif
else
     allowConversation("FALSE" )
endif

