# Generated by BehavEd
# ( "1_SANCTUARY1_0120" )
once_only = getGameFlag("sanctuary", 1 )
if once_only == 0
     setGameFlag("sanctuary", 1, 1 )
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

