# Generated by BehavEd
# ( "This is the load script for the zone" )
setCurrentAct(1 )
# ( "This unlocks the extraction point" )
extractionUnlock("" )
setRecallActive("FALSE" )
first_vist = getGameFlag("act1_visit", 13 )
blink_briefing_viewed = getGameFlag("act1_visit", 29 )
# ( "Blink and Mystique only appears after Blink is rescused" )
blink_mystique = getObjective("act1_obj_1a", "COMPLETE" )
if blink_mystique == 1
     act("sp_blink01", "sp_blink01" )
     act("sp_mystique01", "sp_mystique01" )
     # ( "Now the blink portal is useable" )
     setRecallActive("TRUE" )
     objective ( "act1_obj_2b",  "EOBJCMD_SHOW" )
endif
# ( "Forge is only spawned After Beast is captured" )
forge = getGameFlag("act1_visit", 17 )
if forge == 1
     # ( "Beast has been captured, so Forge needs to be in his place" )
     remove ( "beast", "beast" )
     act("sp_forge01", "sp_forge01" )
else
     act("sp_beast01", "sp_beast01" )
endif
act("sp_cyclops01", "sp_cyclops01" )
# ( "Angel only appears afer the player can access Genosha" )
# ( "in script 'act1/codes_convo_obj'" )
angel = getObjective("act1_obj_2a", "COMPLETE" )
if angel == 1
     angel = getObjective("act1_obj_2b", "COMPLETE" )
     if angel == 1
          angel = getObjective("act1_obj_2c", "COMPLETE" )
          if angel == 1
               # ( "Got all three codes so Angel shows up" )
               act("sp_angel01", "sp_angel01" )
          endif
     endif
endif
# ( "Magneto is only spawned if he is not in your group and after player has gain access to Genosha and before the big boss battle" )
magneto = getObjective("act1_obj_3", "COMPLETE" )
if magneto == 1
     act("sp_magneto01", "sp_magneto01" )
endif
# ( "Check to see if Blink has something to say" )
blink = getObjective("act1_obj_5d", "HIDDEN" )
if blink == 0
     waittimed ( 0.500 )
     setHintType("blink", "importanttalk" )
endif
# ( "Check to see if Sabretooth has something to say" )
sabretooth = getObjective("act1_obj_1a_1", "COMPLETE" )
if sabretooth == 0
     if first_vist != 0
          waittimed ( 0.200 )
     endif
     # ( "Turn on Sabretooth importanttalk=true" )
     setHintType("sabretooth", "importanttalk" )
endif
# ( "Check to see if Profx has something to say" )
profx = getObjective("act1_obj_6b", "COMPLETE" )
if profx == 0
     # ( "Need to check if the obj is shown" )
     profx = getObjective("act1_obj_6b", "HIDDEN" )
     if profx == 0
          setHintType("profx", "importanttalk" )
     endif
endif
if first_vist == 0
     lockControls(0.000 )
     setallaiactive("FALSE" )
     # ( "This marks it so that the intro in only played once" )
     setGameFlag("act1_visit", 13, 1 )
     # ( "Plays sound of xjet landing" )
     sound (  "PLAY_SOUND", "zone_shared/special/xjet_power_down", "_HERO1_", "" )
     cameraFade(1.000, 0.000 )
     waittimed ( 1.700 )
     copyOriginAndAngles("_HERO1_", "hero_spot01" )
     copyOriginAndAngles("_HERO2_", "hero_spot02" )
     copyOriginAndAngles("_HERO3_", "hero_spot03" )
     copyOriginAndAngles("_HERO4_", "hero_spot04" )
     cameraToLocationAngles(" 2119.000 2064.000 -236.000 ", " 2107.000 2153.000 -280.500 ", 0.000 )
     waittimed ( 0.500 )
     cameraFade(0.000, 1.000 )
     objective ( "act1_obj_1",  "EOBJCMD_SHOW" )
     objective ( "act1_obj_1a_1",  "EOBJCMD_SHOW" )
     waittimed ( 1.000 )
     setallaiactive("TRUE" )
     lockControls(0.100 )
     # ( "Turn on Sabretooth importanttalk=true" )
     setHintType("sabretooth", "importanttalk" )
     startConversation("act1/sanctuary/1_sanctuary1_0010" )
endif
if blink_briefing_viewed == 1
     # ( "Reset this back to zero, so it isn't called again" )
     setGameFlag("act1_visit", 29, 0 )
     # ( "This turns off the light" )
     act("mission_briefing_light", "mission_briefing_light" )
     cameraFade(1.000, 0.000 )
     setallaiactive("FALSE" )
     lockControls(0.000 )
     waittimed ( 1.000 )
     copyOriginAndAngles("_HERO1_", "hero_spot05" )
     copyOriginAndAngles("_HERO2_", "hero_spot06" )
     copyOriginAndAngles("_HERO3_", "hero_spot07" )
     copyOriginAndAngles("_HERO4_", "hero_spot08" )
     waittimed ( 0.250 )
     act("open_gate_trigger", "open_gate_trigger" )
endif
gate_opened = getGameFlag("sanctuary", 2 )
if gate_opened == 1
     gate_is_open = getOpened("gate_door_san_a_sa01" )
     # ( "This makes sure that the gate to deadzone is open" )
     if gate_is_open == 0
          # ( "open gate" )
          setEnable("gate_door_san_a_sa01", "TRUE" )
          setEnable("link_deadzone1", "TRUE" )
          act("gate_door_san_a_sa01", "gate_door_san_a_sa01" )
          remove ( "complete_obj", "complete_obj" )
     endif
endif
# ( "This var is set in miltary.py after Holocaust has been defeated" )
angel_captured = getGameFlag("angel_gone", 1 )
if angel_captured == 1
     waittimed ( 0.500 )
     remove ( "angel", "angel" )
endif
numBeacons = getGameVarBitCount("beaconact1" )
if numBeacons >= 4
     # ( "you have all the beacons, activate portal next to Forge" )
     setEnable("blink_to_bonuses", "TRUE" )
     setEnable("link_bonus1", "TRUE" )
     waittimed ( 0.500 )
     act("blink_to_bonuses", "blink_to_bonuses" )
endif

