# Generated by BehavEd
# ( "This is a script for the start condiction." )
allow_conversation = getGameFlag("insect", 2 )
# ( "if objective3 is complete (gain entrance to Genosha), allow conversation" )
if allow_conversation == 1
     # ( "don't allow conv if seawall quest is already complete" )
     seawallComplete = getObjective("act1_obj_4", "COMPLETE" )
     if seawallComplete == 0
          # ( "haven't completed objective 4, so go ahead with this conv" )
          allowConversation("TRUE" )
     else
          allowConversation("FALSE" )
     endif
else
     allowConversation("FALSE" )
endif

