# Generated by BehavEd
# ( "This script no longer shows the blink quest.  It only completes the Talk to Sabretooth quest" )
objective ( "act1_obj_1a_1",  "EOBJCMD_COMPLETE" )
objective ( "act1_obj_1a",  "EOBJCMD_SHOW" )

