# Generated by BehavEd
# ( "just spoke with Profx, reveal objective 6 'defeat Abyss'" )
obj6hidden = getObjective("act1_obj_6", "HIDDEN" )
if obj6hidden == 1
     # ( "haven't shown objective 6, so show it" )
     objective ( "act1_obj_6",  "EOBJCMD_SHOW" )
endif
show_obj_hint = getGameFlag("sanctuary", 5 )
if show_obj_hint == 0
     setGameFlag("sanctuary", 5, 1 )
     createPopupDialogXml("act1/sanctuary/first_obj_hint" )
endif

