# Generated by BehavEd
# ( "just spoke with Angel, reveal objective 3 'Locate Genosha entrance'" )
obj3hidden = getObjective("act1_obj_3", "HIDDEN" )
# ( "complete objective 2" )
if obj3hidden == 1
     # ( "haven't shown objective 3, so show it" )
     objective ( "act1_obj_3",  "EOBJCMD_SHOW" )
     objective ( "act1_obj_3a",  "EOBJCMD_SHOW" )
endif

