# Generated by BehavEd
# ( "comment" )
awardXPToPlayable(25000 )
pid = getParentID("_OWNER_" )
# ( "need to un parent or we'll be removed when the parent is removed" )
setParent("_OWNER_", "" )
setEnable(pid, "TRUE" )
act(pid, pid )

