# Generated by BehavEd
# ( "This script loads the intro movie for act2 and loads the savage land map" )
startMovie("Cine02", "afterMovie" )
waitsignal ( "afterMovie" )
# ( "Unlock 60's and 70's skins" )
unlockCharacter("", "60s" )
unlockCharacter("", "70s" )
loadZone("act2/savage/savage1", "link_savage1" )

