# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept22.png" )
imageViewer("textures/concept/concept23.png" )
imageViewer("textures/concept/concept24.png" )

