# Generated by BehavEd
# ( "Abyss' pain script" )
# ( "calculate health percentage" )
stage = getZoneVar("stage" )
stage = iadd(stage, 1 )
health = getHealth("_OWNER_" )
healthmax = getHealthMax("_OWNER_" )
hamt = fdiv(health, healthmax )
# ( "figure out what the theshold for the next stage should be" )
if stage == 1
     hthresh = fadd(0.250, 0.000 )
elif stage == 2
     hthresh = fadd(0.200, 0.000 )
elif stage == 4
     hthresh = fadd(0.100, 0.000 )
endif
if hamt < hthresh
     setZoneVar("stage", stage )
     newhealth = fmul(hthresh, healthmax )
     setHealth("_OWNER_", newhealth )
     # ( "-- do the stuff --" )
     if stage == 1
          # ( "abyss runs out of council chamber" )
          act("fleetime", "fleetime" )
          setInvulnerable("abyss", "TRUE" )
     endif
     if stage == 2
          act("blimpBintro", "blimpBintro" )
          # ( "2nd airship shows up" )
     endif
     if stage == 4
          # ( "abyss sucks the player in" )
          act("last_stage", "last_stage" )
     endif
endif

