# Generated by BehavEd
# ( "end of abyss intro" )
controlPlayerHeroWithAI(0.100 )
setAIActive("_HERO1_", "TRUE" )
setAIActive("_HERO2_", "TRUE" )
setAIActive("_HERO3_", "TRUE" )
setAIActive("_HERO4_", "TRUE" )
cameraResetOldSchool( )
# ( "show objective, 'defeat Abyss'" )
objective ( "act1_obj_6a",  "EOBJCMD_SHOW" )
setDefaultTarget("abyss" )
setPatternSequence("abyss", "abyss1" )

