# Generated by BehavEd
# ( "comment" )
hittername = getName("_ACTIVATOR_" )
if hittername == "abyss_explosion"
     sound (  "PLAY_SOUND", "voice/abyss/blimp_bomb", "", "" )
     sound (  "PLAY_SOUND", "boss_battles/abyss/metal_bend", "", "" )
spawn("_ACTIVATOR_", "firefx", "firefx", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     playanim (  "EA_POWER15", "abyss", "NONE", "" )
     setAIActive("abyss", "FALSE" )
     startMotionPath("shipB", "abyss/blimp_shudder/mp_blimp", "FALSE", "shaky" )
     setNoGravity("abyss", "TRUE" )
     setNoClip("abyss", "TRUE" )
     startMotionPath("abyss", "abyss/blimp_shudder_at_origin/mp_blimp", "TRUE", "" )
     startMotionPath("firefx", "abyss/blimp_shudder_at_origin/mp_blimp", "TRUE", "" )
     blimphits = getZoneVar("blimphits" )
     blimphits2 = iadd(blimphits, 1 )
     setZoneVar("blimphits", blimphits2 )
     maxh = getHealthMax("shipB" )
     healthpip = fdiv(maxh, 5.000 )
     blimphealth = getHealth("shipB" )
     blimphealth2 = isub(blimphealth, healthpip )
     setHealth("_OWNER_", blimphealth2 )
     setHealth("blimpy_boy", blimphealth2 )
     waitsignal ( "shaky" )
     setAIActive("abyss", "TRUE" )
     setNoGravity("abyss", "FALSE" )
     setNoClip("abyss", "FALSE" )
     if blimphits2 >= 5
          # ( "blow up abyss blimp" )
          act("blimpBBOOM", "blimpBBOOM" )
     else
          startMotionPath("shipB", "abyss/blimp_loop/mp_blimp", "FALSE", "" )
     endif
endif

