# Generated by BehavEd
# ( "abyss_jumpsup" )
cameraMove(" -2640.320 5714.130 1857.510 ", 0.500 )
cameraPan(" 3.398 20.002 14.991 ", 0.500, "FALSE" )
setInvisible("abyss", "FALSE" )
copyOriginAndAngles("abyss", "abyssSpot01" )
playanim (  "EA_POWER16", "abyss", "NONE", "gotthere" )
waittimed ( 0.500 )
setNoGravity("abyss", "FALSE" )

