# Generated by BehavEd
# ( "spawns in and removes bombs" )
setZoneVar("bombson", 0 )
act("demon", "demon" )
act("demon_leader", "demon_leader" )
spawn("bombspot01", "da_bomb", "bomb", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
spawn("bombspot02", "da_bomb", "bomb", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
spawn("bombspot03", "da_bomb", "bomb", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
spawn("bombspot04", "da_bomb", "bomb", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
waittimed ( 60.000 )
remove ( "bomb", "bomb" )

