# Generated by BehavEd
# ( "spawn in and climb up the blimp" )
setNoCollide("_OWNER_", "TRUE" )
setNoClip("_OWNER_", "TRUE" )
setNoGravity("_OWNER_", "TRUE" )
playanim (  "EA_ZONE2", "_OWNER_", "NONE", "" )
waittimed ( 6.000 )
setNoCollide("_OWNER_", "FALSE" )
setNoClip("_OWNER_", "FALSE" )
setNoGravity("_OWNER_", "FALSE" )
attackEntityWithType("_OWNER_", "_ACTIVE_HERO_", "ANY", "FALSE" )

