# Generated by BehavEd
# ( "demon destroyed" )
setEnable("bomb2", "TRUE" )
remove ( "shield2", "shield2" )
sound (  "PLAY_SOUND", "voice/abyss/in_void", "", "" )
sound (  "PLAY_SOUND", "boss_battles/abyss/bomb_disappear", "bomb2", "" )
waittimed ( 120.000 )
act("demon_spawner02", "demon_spawner02" )

