# Generated by BehavEd
# ( "demon destroyed" )
enabled = getEnable("bomb3" )
if enabled == 0
     setEnable("bomb3", "TRUE" )
     act("bomb3", "bomb3" )
     bombson = getZoneVar("bombson" )
     bombson2 = isub(bombson, 1 )
     setZoneVar("bombson", bombson2 )
endif
setEnable("bomb3", "FALSE" )
spawn("bomb3", "shield", "shield3", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )

