# Generated by BehavEd
# ( "demon destroyed" )
setEnable("bomb4", "TRUE" )
remove ( "shield4", "shield4" )
sound (  "PLAY_SOUND", "boss_battles/abyss/bomb_disappear", "bomb4", "" )
waittimed ( 120.000 )
act("demon_spawner04", "demon_spawner04" )

