# Generated by BehavEd
# ( "demon destroyed" )
enabled = getEnable("bomb2" )
if enabled == 0
     setEnable("bomb2", "TRUE" )
     act("bomb2", "bomb2" )
     bombson = getZoneVar("bombson" )
     bombson2 = isub(bombson, 1 )
     setZoneVar("bombson", bombson2 )
endif
setEnable("bomb2", "FALSE" )
spawn("bomb2", "shield", "shield2", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )

