# Generated by BehavEd
# ( "demon destroyed" )
enabled = getEnable("bomb1" )
if enabled == 0
     setEnable("bomb1", "TRUE" )
     act("bomb1", "bomb1" )
     bombson = getZoneVar("bombson" )
     bombson2 = isub(bombson, 1 )
     setZoneVar("bombson", bombson2 )
endif
setEnable("bomb1", "FALSE" )
spawn("bomb1", "shield", "shield1", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )

