# Generated by BehavEd
# ( "demon destroyed" )
enabled = getEnable("bomb4" )
if enabled == 0
     setEnable("bomb4", "TRUE" )
     act("bomb4", "bomb4" )
     bombson = getZoneVar("bombson" )
     bombson2 = isub(bombson, 1 )
     setZoneVar("bombson", bombson2 )
endif
setEnable("bomb4", "FALSE" )
spawn("bomb4", "shield", "shield4", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )

