# Generated by BehavEd
# ( "demon destroyed" )
setEnable("bomb1", "TRUE" )
remove ( "shield1", "shield1" )
sound (  "PLAY_SOUND", "boss_battles/abyss/bomb_disappear", "bomb1", "" )
waittimed ( 120.000 )
act("demon_spawner01", "demon_spawner01" )

