# Generated by BehavEd
# ( "comment" )
remove ( "shield", "shield" )
remove ( "firefx", "firefx" )
donedat = getGameFlag("bosses", 7 )
if donedat == 1
     act("in_door", "in_door" )
     act("blinky", "blinky" )
     remove ( "abyss_spawner", "abyss_spawner" )
else
     setRecallActive("FALSE" )
     # ( "added by Sean 5/23/05. checked in genosha3" )
     setGameFlag("prisoners", 24, 1 )
endif
waittimed ( 0.5 )
remove ( "abyss_codex", "abyss_codex" )