# Generated by BehavEd
# ( "post abyss wrap up" )
setEnable("blinky", "TRUE" )
act("blinky", "blinky" )
setGameFlag("bosses", 7, 1 )
# ( "update objectives -- you defeated Abyss" )
objective ( "act1_obj_6a",  "EOBJCMD_COMPLETE" )
objective ( "act1_obj_6b",  "EOBJCMD_SHOW" )

