# Generated by BehavEd
# ( "comment" )
cameraMove(" -1704.350 3198.120 265.855 ", 0.000 )
cameraPan(" -1.275 24.839 35.354 ", 0.000, "FALSE" )
startConversation("act1/genosha/genosha4/abyss_on_blimp" )

