# Generated by BehavEd
# ( "after last stage intro is done" )
cameraReset( )
setZoneVar("bombson", 4 )
act("demon_spawner01", "demon_spawner01" )
act("demon_spawner02", "demon_spawner02" )
act("demon_spawner03", "demon_spawner03" )
act("demon_spawner04", "demon_spawner04" )

