# Generated by BehavEd
# ( "teleport elevator" )
zpos = getPosZ("_ACTIVATOR_" )
sound (  "PLAY_SOUND", "boss_battles/abyss/worm_hole", "", "" )
if zpos < 50
     setNoClip("_ACTIVATOR_", "TRUE" )
     setNoGravity("_ACTIVATOR_", "TRUE" )
     playanim (  "EA_ZONE1", "_ACTIVATOR_", "NONE", "up" )
     waitsignal ( "up" )
     setNoClip("_ACTIVATOR_", "FALSE" )
     setNoGravity("_ACTIVATOR_", "FALSE" )
     setPosZ("_ACTIVATOR_", 72 )
else
     setNoClip("_ACTIVATOR_", "TRUE" )
     setNoGravity("_ACTIVATOR_", "TRUE" )
     playanim (  "EA_ZONE5", "_ACTIVATOR_", "NONE", "down" )
     waitsignal ( "down" )
     setNoClip("_ACTIVATOR_", "FALSE" )
     setNoGravity("_ACTIVATOR_", "FALSE" )
     setPosZ("_ACTIVATOR_", -103 )
endif

