# Generated by BehavEd
# ( "This spawns the scarab" )
# ( "For this to work in your zone, the first zone animation must be the scarab animation" )
playanim (  "EA_ZONE1", "_OWNER_", "NONE", "" )
sound (  "PLAY_SOUND", "zone_shared/special/scarabs_crawling", "_OWNER_", "" )
setNoClip("_OWNER_", "TRUE" )
setInvulnerable("_OWNER_", "TRUE" )
waittimed ( 1.000 )
setInvulnerable("_OWNER_", "FALSE" )
setNoClip("_OWNER_", "FALSE" )

