# Generated by BehavEd
# ( "comment" )
setAIActive("_OWNER_", "FALSE" )
setInvisible("_OWNER_", "FALSE" )
setNoCollide("_OWNER_", "TRUE" )
# ( "this will be beasts dead animation" )
playanim (  "EA_KO_HEAD1", "_OWNER_", "STOP", "" )

