# Generated by BehavEd
# ( "comment" )
lockControls(0.100 )
cameraResetOldSchool( )
heroNoTarget("FALSE" )
setHintType("beast_alive", "importanttalk" )
# ( "complete the 'free beast' quest" )
objective ( "act2_obj_6d",  "EOBJCMD_COMPLETE" )
# ( "show the 'talk to profX' quest" )
objective ( "act2_obj_6e",  "EOBJCMD_SHOW" )

