# Generated by BehavEd
# ( "comment" )
setWaypointPath("natasha", "evilchick", 1 )
waittimed ( 2.000 )
fade("natasha", 0.000, 3.000, "FALSE" )
waittimed ( 1.500 )
remove ( "natasha", "natasha" )
lockControls(0.100 )
cameraResetOldSchool( )
heroNoTarget("FALSE" )

