# Generated by BehavEd
# ( "comment" )
lockControls(0.000 )
# ( "camera looks at the leader coming through the door" )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
cameraMove(" 1741.050 -1393.300 275.790 ", 1.000 )
cameraPan(" 0.000 48.400 39.200 ", 0.000, "FALSE" )
waittimed ( 1.000 )
cameraFade(0.000, 0.500 )
heroNoTarget("TRUE" )
# ( "moves the players to their spots" )
# ( "but checks to see if they are alive first" )
isHero1Alive = alive("_HERO1_" )
if isHero1Alive == 1
     # ( "hero1 is alive" )
     copyOriginAndAngles("_HERO1_", "win_spot01" )
else
     # ( "hero1 is dead as a doornail" )
endif
isHero2Alive = alive("_HERO2_" )
if isHero2Alive == 1
     # ( "hero2 is alive" )
     copyOriginAndAngles("_HERO2_", "win_spot02" )
else
     # ( "hero2 is dead as a doornail" )
endif
isHero3Alive = alive("_HERO3_" )
if isHero3Alive == 1
     # ( "hero3 is alive" )
     copyOriginAndAngles("_HERO3_", "win_spot03" )
else
     # ( "hero3 is dead as a doornail" )
endif
isHero4Alive = alive("_HERO4_" )
if isHero4Alive == 1
     # ( "hero4 is alive" )
     copyOriginAndAngles("_HERO4_", "win_spot04" )
else
     # ( "hero4 is dead as a doornail" )
endif
# ( "x-men have defeated mikhail's punk bodyguards" )
waittimed ( 2.000 )
setEnable("bg_door_trigger", "TRUE" )
startConversation("act2/mikhail/2_mikhail5_0020" )

