# Generated by BehavEd
# ( "clone of mikhail spawns in" )
playBossSound("voice/mikhail/clone", 0, 5.000 )
setEnable("_OWNER_", "TRUE" )
setInvulnerable("_OWNER_", "TRUE" )
playanim (  "EA_ZONE3", "_OWNER_", "NONE", "" )
waittimed ( 1.500 )
setInvulnerable("_OWNER_", "FALSE" )
setEnable("_OWNER_", "FALSE" )
attackEntityWithType("_OWNER_", "_ACTIVE_HERO_", "ANY", "FALSE" )

