# Generated by BehavEd
# ( "Mikhails's pain script" )
# ( "calculate health percentage" )
stage = getZoneVar("stage" )
stage = iadd(stage, 1 )
if stage < 10
     health = getHealth("_OWNER_" )
     healthmax = getHealthMax("_OWNER_" )
     hamt = fdiv(health, healthmax )
     # ( "figure out what the theshold for the next stage should be" )
     thresh = fmul(stage, 0.100 )
     hthresh = fsub(1.000000, thresh )
     if hamt < hthresh
          # ( "-- do the stuff --" )
          setZoneVar("stage", stage )
          alive = alive("_OWNER_" )
          if alive == 1
               playanim (  "EA_ZONE2", "_OWNER_", "NONE", "" )
               setInvulnerable("_OWNER_", "TRUE" )
               waittimed ( 1.000 )
               setEnable("_OWNER_", "TRUE" )
          endif
          spid = getNearestMonsterSpawner("_OWNER_", 0.000 )
          if spid == 0
               spid = getNearestMonsterSpawner("mikspot01", 0.000 )
          endif
          act(spid, spid )
          waittimed ( 1.500 )
          setInvulnerable("_OWNER_", "FALSE" )
          setEnable("_OWNER_", "FALSE" )
     endif
endif

