# Generated by BehavEd
# ( "remove ents that fall out of the world" )
remove ( "mikpanelB", "mikpanelB" )
remove ( "mikpanel", "mikpanel" )
remove ( "MikhailRanger_c", "MikhailRanger_c" )
remove ( "MikhailWarrior_b", "MikhailWarrior_b" )
# ( "check if battle is beat" )
beatmicky = getGameFlag("bosses", 14 )
if beatmicky == 1
     # ( "set up zone as if mikhail has been beaten here" )
     # ( "be sure to remove intro guards" )
     # ( "be sure to remove beast lab stuff" )
     remove ( "main_mikhail", "main_mikhail" )
     remove ( "bodyguard_trigger", "bodyguard_trigger" )
     remove ( "mik_intro", "mik_intro" )
     remove ( "save_beast_trig", "save_beast_trig" )
     killEntitySilent("computer_console_01_mik_b_ms03" )
     setEnable("blinky", "TRUE" )
     act("blinky", "blinky" )
     act("exit_door", "exit_door" )
     act("beast_revived", "beast_revived" )
     act("entrance_door04", "entrance_door04" )
     act("entrance_door03", "entrance_door03" )
else
     setRecallActive("FALSE" )
     # ( "start the spinners going" )
     startMotionPath("spinner", "mikhail/spinner_room_beam_10sec/mp_spinner_room_beam", "FALSE", "WAITNAME" )
     waittimed ( 5.000 )
     startMotionPath("spinner2", "mikhail/spinner_room_beam_10sec/mp_spinner_room_beam", "FALSE", "WAITNAME" )
endif
# ( "if first time entering this map, update quest to defeat mikhail" )
mikhailQuest = getObjective("act2_obj_6c", "HIDDEN" )
if mikhailQuest == 1
     # ( "quest has never been revealed, so reveal it" )
     objective ( "act2_obj_6c",  "EOBJCMD_SHOW" )
endif
waittimed ( 10.000 )
remove ( "monsterA", "monsterA" )

