# Generated by BehavEd
# ( "comment" )
noton = iadd(0, 0 )
enabled = iadd(0, 0 )
dist = getDistance("_OWNER_", "pad01" )
if dist <= 140
     noton = getEnable("pad01" )
     if noton == 1
          setZoneFlag("padon", 1, 1 )
          setEnable("_OWNER_", "TRUE" )
          enabled = iadd(0, 1 )
          pid = getID("pad01" )
     endif
endif
dist = getDistance("_OWNER_", "pad02" )
if dist <= 140
     noton = getEnable("pad02" )
     if noton == 1
          setZoneFlag("padon", 2, 1 )
          setEnable("_OWNER_", "TRUE" )
          enabled = iadd(0, 1 )
          pid = getID("pad02" )
     endif
endif
dist = getDistance("_OWNER_", "pad03" )
if dist <= 140
     noton = getEnable("pad03" )
     if noton == 1
          setZoneFlag("padon", 3, 1 )
          setEnable("_OWNER_", "TRUE" )
          enabled = iadd(0, 1 )
          pid = getID("pad03" )
     endif
endif
dist = getDistance("_OWNER_", "pad04" )
if dist <= 140
     noton = getEnable("pad04" )
     if noton == 1
          setZoneFlag("padon", 4, 1 )
          setEnable("_OWNER_", "TRUE" )
          enabled = iadd(0, 1 )
          pid = getID("pad04" )
     endif
endif
if noton == 1
     act(pid, pid )
     setEnable(pid, "FALSE" )
endif
if enabled == 0
     # ( "isn't usable, turn it back into a monster" )
     waittimed ( 5.000 )
     copyOriginAndAngles("mikmonster", "_OWNER_" )
     act("mikmonster", "mikmonster" )
     remove ( "_OWNER_", "_OWNER_" )
else
     # ( "wait a while and if the player doesn't use it, turn it back into a monster" )
     waittimed ( 30.000 )
     enabled = getEnable("_OWNER_" )
     if enabled == 1
          # ( "didn't get used" )
          setEnable(pid, "TRUE" )
          act(pid, pid )
          copyOriginAndAngles("mikmonsterB", "_OWNER_" )
          act("mikmonsterB", "mikmonsterB" )
          remove ( "_OWNER_", "_OWNER_" )
     endif
endif

