# Generated by BehavEd
# ( "spawn a mikhail ranger at this object" )
r = randomInt(1, 2 )
if r == 1
     spawn("_OWNER_", "MikhailRanger_c", "baddie", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
else
     spawn("_OWNER_", "MikhailWarrior_b", "baddie", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
endif
remove ( "_OWNER_", "_OWNER_" )

