# Generated by BehavEd
# ( "comment" )
hitter = getName("_ACTIVATOR_" )
if hitter == 'mikclone'
     spawn("_OWNER_", "miksplosion", "miksplosion", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     killEntity("_OWNER_" )
endif

