# Generated by BehavEd
# ( "comment" )
# ( "checks if this is the first artifact gotten" )
# ( "if it's the first, plays conversation" )
# ( "do nothing if not" )
first_artifact = getGameFlag("madri_conv", 4 )
if first_artifact == 0
     setGameFlag("madri_conv", 4, 1 )
     startConversation("act3/madri/3_SOMETIMEMADRI_0040" )
endif

