# Generated by BehavEd
# ( "comment" )
my_whatta_room = getGameFlag("madri_conv", 6 )
if my_whatta_room == 0
     startConversation("act3/madri/madri5/3_MADRI5_0005" )
     setGameFlag("madri_conv", 6, 1 )
endif

