# Generated by BehavEd
# ( "comment" )
remove ( "fake_artifact_3", "fake_artifact_3" )
act("trap_3", "trap_3" )
waittimed ( 2.000 )
setNoCollide("trap_3", "TRUE" )
act("trap_fx_3", "trap_fx_3" )
act("red_flame3", "red_flame3" )
setPartyLightColor(" 0.780 0.410 0.090 ", 1.000 )
setEnable("trap_area3", "TRUE" )
waittimed ( 0.500 )
setEnable("trap_harm_3", "TRUE" )
act("trap_harm_3", "trap_harm_3" )
waittimed ( 0.500 )
remove ( "trap_harm_3", "trap_harm_3" )
trapper = getGameFlag("madri_conv", 7 )
if trapper == 0
     setGameFlag("madri_conv", 7, 1 )
     startConversation("act3/madri/madri5/3_MADRI5_0020" )
endif

