# Generated by BehavEd
# ( "comment" )
remove ( "fake_artifact_1", "fake_artifact_1" )
act("trap_1", "trap_1" )
waittimed ( 2.000 )
setNoCollide("trap_1", "TRUE" )
act("trap_fx_1", "trap_fx_1" )
act("red_flame1", "red_flame1" )
setPartyLightColor(" 0.780 0.410 0.090 ", 1.000 )
setEnable("trap_area1", "TRUE" )
waittimed ( 0.500 )
setEnable("trap_harm_1", "TRUE" )
act("trap_harm_1", "trap_harm_1" )
waittimed ( 0.500 )
remove ( "trap_harm_1", "trap_harm_1" )
trapper = getGameFlag("madri_conv", 7 )
if trapper == 0
     setGameFlag("madri_conv", 7, 1 )
     startConversation("act3/madri/madri5/3_MADRI5_0020" )
endif

