# Generated by BehavEd
# ( "comment" )
remove ( "fake_artifact_5", "fake_artifact_5" )
act("trap_5", "trap_5" )
waittimed ( 2.000 )
setNoCollide("trap_5", "TRUE" )
act("trap_fx_5", "trap_fx_5" )
act("red_flame5", "red_flame5" )
setPartyLightColor(" 0.780 0.410 0.090 ", 1.000 )
setEnable("trap_area5", "TRUE" )
waittimed ( 0.500 )
setEnable("trap_harm_5", "TRUE" )
act("trap_harm_5", "trap_harm_5" )
waittimed ( 0.500 )
remove ( "trap_harm_5", "trap_harm_5" )
trapper = getGameFlag("madri_conv", 7 )
if trapper == 0
     setGameFlag("madri_conv", 7, 1 )
     startConversation("act3/madri/madri5/3_MADRI5_0020" )
endif

