# Generated by BehavEd
# ( "comment" )
remove ( "fake_artifact_2", "fake_artifact_2" )
act("trap_2", "trap_2" )
waittimed ( 2.000 )
setNoCollide("trap_2", "TRUE" )
act("trap_fx_2", "trap_fx_2" )
act("red_flame2", "red_flame2" )
setPartyLightColor(" 0.780 0.410 0.090 ", 1.000 )
setEnable("trap_area2", "TRUE" )
waittimed ( 0.500 )
setEnable("trap_harm_2", "TRUE" )
act("trap_harm_2", "trap_harm_2" )
waittimed ( 0.500 )
remove ( "trap_harm_2", "trap_harm_2" )
trapper = getGameFlag("madri_conv", 7 )
if trapper == 0
     setGameFlag("madri_conv", 7, 1 )
     startConversation("act3/madri/madri5/3_MADRI5_0020" )
endif

