# Generated by BehavEd
# ( "comment" )
remove ( "fake_artifact_4", "fake_artifact_4" )
act("trap_4", "trap_4" )
waittimed ( 2.000 )
setNoCollide("trap_4", "TRUE" )
act("trap_fx_4", "trap_fx_4" )
act("red_flame4", "red_flame4" )
setPartyLightColor(" 0.780 0.410 0.090 ", 1.000 )
setEnable("trap_area4", "TRUE" )
waittimed ( 0.500 )
setEnable("trap_harm_4", "TRUE" )
act("trap_harm_4", "trap_harm_4" )
waittimed ( 0.500 )
remove ( "trap_harm_4", "trap_harm_4" )
trapper = getGameFlag("madri_conv", 7 )
if trapper == 0
     setGameFlag("madri_conv", 7, 1 )
     startConversation("act3/madri/madri5/3_MADRI5_0020" )
endif

