# Generated by BehavEd
# ( "comment" )
gotbreath = getObjective("act3_obj_6d_a", "COMPLETE" )
if gotbreath == 1
     remove ( "true_breath_artifact", "true_breath_artifact" )
     remove ( "trap_light1", "trap_light1" )
     remove ( "trap_light2", "trap_light2" )
     remove ( "pre_gate2", "pre_gate2" )
     actSilent("secretdoor1", "secretdoor1" )
     actSilent("secretdoor2", "secretdoor2" )
     remove ( "pre_gate2", "pre_gate2" )
     setEnable("teleport_to_start", "TRUE" )
     setEnable("teleport_to_start4", "TRUE" )
     act("portcullis", "portcullis" )
     copyOriginAndAngles("fire_fx2", "f2spot01" )
endif
gotbreath = getObjective("act3_obj_5c", "COMPLETE" )
if gotbreath == 1
     remove ( "stepford_altar", "stepford_altar" )
endif

