# Generated by BehavEd
# ( "This death is script" )
setCurrentAct(3 )
objective ( "act3_obj_5c",  "EOBJCMD_COMPLETE" )
var1 = getObjective("act3_obj_5a", "COMPLETE" )
var2 = getObjective("act3_obj_5b", "COMPLETE" )
var3 = getObjective("act3_obj_5c", "COMPLETE" )
if var1 == 1
     if var2 == 1
          if var3 == 1
               # ( "all three altars have been destroyed" )
               getObjective("act3_obj_5", "COMPLETE" )
               startConversation("act3/madri/3_SOMETIMEMADRI_0010" )
          endif
     endif
endif
# ( "plays conv if this is first stepford altar destroyed" )
first_stepford = getGameFlag("madri_conv", 5 )
if first_stepford == 0
     startConversation("act3/madri/3_SOMETIMEMADRI_0012" )
     setGameFlag("madri_conv", 5, 1 )
endif

