# Generated by BehavEd
# ( "zonescript. checks if mind artifact has already been gotten" )
setCurrentAct(3 )
# ( "if so, removes it from map and opens end door." )
artifacts = getObjective("act3_obj_6e_a", "COMPLETE" )
if artifacts == 1
     remove ( "artifact_mind01", "artifact_mind01" )
     waittimed ( 2.000 )
     setEnable("link_madri1", "TRUE" )
     setEnable("teleport_team1", "TRUE" )
     setEnable("teleport_team04", "TRUE" )
     act("portal_looper", "portal_looper" )
     remove ( "secretdoor1", "secretdoor1" )
     remove ( "secretdoor2", "secretdoor2" )
     remove ( "door_death_head_madri_a_mt01", "door_death_head_madri_a_mt01" )
endif

