# Generated by BehavEd
# ( "comment" )
lockControls(-1.000 )
setallaiactive("FALSE" )
cameraFade(1.000, 0.500 )
waittimed ( 1.000 )
cameraToLocationAngles(" 67510.039 9243.785 364.826 ", " 6544.371 9262.479 120.000 ", 0.000 )
hero1 = alive("_HERO1_" )
if hero1 > 0
     copyOriginAndAngles("_HERO1_", "p1spot01" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     copyOriginAndAngles("_HERO2_", "p2spot01" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     copyOriginAndAngles("_HERO3_", "p3spot01" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     copyOriginAndAngles("_HERO4_", "p4spot01" )
endif
cameraFade(0.000, 0.500 )
cameraReset( )
setallaiactive("TRUE" )
lockControls(0.100 )

