# Generated by BehavEd
# ( "This doesn't allow the player to take the xjet unless they have talk to Havok" )
perimeter_ready = getObjective("act4_obj_1a_1", "COMPLETE" )
if perimeter_ready == 1
     startConversation("act4/mansion/4_mansion_0060" )
else
     startConversation("common/finish_obj" )
endif

