# Generated by BehavEd
# ( "This completes the quest to talk to Moira" )
objective ( "act4_obj_2a_1",  "EOBJCMD_COMPLETE" )
# ( "This shows the act4_obj_2a quest which is the Shaw quest" )
objective ( "act4_obj_2a",  "EOBJCMD_SHOW" )
# ( "Now that the player has talk to Moira, the zone_link is ready" )
setEnable("link_sewers1", "TRUE" )
remove ( "sewers_entrance", "sewers_entrance" )
# ( "This turns off Moira's hinttype to normal talk status" )
setHintType("moira", "talk" )
# ( "This game var is det to keep track of what objectives have been shown" )
setGameFlag("act4_que", 1, 1 )

