# Generated by BehavEd
# ( "This marks the first start condiction in Havoks conversation has done" )
talked_to_havok = getGameFlag("mansion", 6 )
if talked_to_havok == 0
     setGameFlag("mansion", 6, 1 )
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

