# Generated by BehavEd
# ( "This checks if the Pen quest is over" )
stryfe_defeated = getObjective("act4_obj_3b", "COMPLETE" )
talked_to_banshee = getObjective("act4_obj_3c", "HIDDEN" )
if stryfe_defeated == 1
     if talked_to_banshee == 1
          allowConversation("FALSE" )
     else
          objective ( "act4_obj_3c",  "EOBJCMD_COMPLETE" )
          allowConversation("TRUE" )
     endif
else
     allowConversation("FALSE" )
endif

