# Generated by BehavEd
# ( "This will only play if Colossus is not the first person to start the conversaton" )
play_once = getGameFlag("mansion", 4 )
if play_once == 0
     setGameFlag("mansion", 4, 1 )
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

