# Generated by BehavEd
# ( "This checks if Colossus starts the convesation" )
is_activator_colossus = isActorOnTeam("colossus" )
# ( "The run once will not be called proper and that is why a game var is used" )
play_once = getGameFlag("mansion", 4 )
if play_once == 1
     did_colossu_talk = getGameFlag("mansion", 5 )
     if is_activator_colossus == 1
          if did_colossu_talk == 0
               allowConversation("TRUE" )
               # ( "This turns off the important hint flag" )
               setHintType("kitty", "talk" )
               # ( "This second flag isn't needed, but I already did the work. :p" )
               setGameFlag("mansion", 5, 1 )
               # ( "Have colossus face kitty" )
               faceEntity("colossus", "kitty" )
               faceEntity("kitty", "colossus" )
          else
               allowConversation("FALSE" )
          endif
     else
          allowConversation("FALSE" )
     endif
else
     allowConversation("FALSE" )
endif

