# Generated by BehavEd
# ( "This checks if Colossus starts the convesation" )
is_activator_colossus = isActorOnTeam("colossus" )
# ( "The run once will not be called proper and that is why a game var is used" )
play_once = getGameFlag("mansion", 4 )
if play_once == 0
     if is_activator_colossus == 1
          setGameFlag("mansion", 4, 1 )
          # ( "Mark the converstoin that Colossus has talked to Kitty" )
          setGameFlag("mansion", 5, 1 )
          # ( "Have colossus face kitty" )
          faceEntity("colossus", "kitty" )
          faceEntity("kitty", "colossus" )
          allowConversation("TRUE" )
     else
          allowConversation("FALSE" )
     endif
else
     allowConversation("FALSE" )
endif

