# Generated by BehavEd
# ( "This checks if the periemter platform quest is over" )
bation_defeated = getObjective("act4_obj_1c", "COMPLETE" )
talked_to_havok = getObjective("act4_obj_1d", "HIDDEN" )
if bation_defeated == 1
     if talked_to_havok == 1
          allowConversation("FALSE" )
     else
          objective ( "act4_obj_1d",  "EOBJCMD_COMPLETE" )
          allowConversation("TRUE" )
     endif
else
     allowConversation("FALSE" )
endif

