# Generated by BehavEd
# ( "This script is called from 4_mansinon_20" )
tower_ready = getObjective("act4_obj_4a", "COMPLETE" )
if tower_ready == 0
     tower_ready = getObjective("act4_obj_4a", "HIDDEN" )
     if tower_ready == 0
          # ( "If the objective 4, Enter Apoc tower is shown and not complete then play conversation" )
          allowConversation("TRUE" )
     else
          allowConversation("FALSE" )
     endif
else
     allowConversation("FALSE" )
endif

