# Generated by BehavEd
# ( "THis script marks the shaw quest is over and starts the questions for the black queen" )
# ( "The sets that all three shaw quest are done" )
setGameFlag("mansion", 3, 1 )
# ( "Show black queen quest" )
objective ( "act4_obj_5",  "EOBJCMD_SHOW" )
objective ( "act4_obj_5a",  "EOBJCMD_SHOW" )
# ( "Also profx is set to have an important hint type" )
setHintType("profx", "importanttalk" )
# ( "Also shaw is set to have an important hint type" )
setHintType("shaw", "talk" )

