# Generated by BehavEd
# ( "This marks act4_obj_1a_2 (Take X-jet objective)  as done" )
objective ( "act4_obj_1a_2",  "EOBJCMD_COMPLETE" )
lockControls(1.000 )
waittimed ( 1.000 )
# ( "This script is used to start the perimeter zones" )
loadZone("act4/perimeter/perimeter3", "link_perimeter3" )

