# Generated by BehavEd
# ( "This is the load script for the zone" )
# ( "This unlocks the extraction point" )
extractionUnlock("" )
setCurrentAct(4 )
ny_quest_done = getObjective("act4_obj_2a", "COMPLETE" )
BansheeHidden = getObjective("act4_obj_3c", "HIDDEN" )
if ny_quest_done == 1
     # ( "Spawn in Shaw" )
     act("sp_shaw01", "sp_shaw01" )
endif
if BansheeHidden == 0
     # ( "Spawn in Banshee" )
     act("sp_banshee01", "sp_banshee01" )
endif
visited = getGameFlag("act4_visit", 2 )
if visited == 0
     setGameFlag("act4_visit", 2, 1 )
     setallaiactive("FALSE" )
     lockControls(0.000 )
     # ( "Plays sound of xjet landing" )
     sound (  "PLAY_SOUND", "zone_shared/special/xjet_power_down", "_HERO1_", "" )
     # ( "**************************************************" )
     # ( "Turn off icons for intro" )
     # ( "**************************************************" )
     # ( "turn off moira's talk icon" )
     setEnable("moira", "FALSE" )
     setEnable("forge_shop", "FALSE" )
     setEnable("forge", "FALSE" )
     cameraFade(1.000, 0.000 )
     # ( "The long pause is for the sound file used above" )
     waittimed ( 1.000 )
     # ( "Intro camera" )
     cameraMove(" 29.500 -1295.000 63.800 ", 0.000 )
     cameraPan(" 0.000 11.700 91.000 ", 0.000, "FALSE" )
     # ( "Setup character starting spot" )
     setInvisible("x_jet", "TRUE" )
     copyOriginAndAngles("_HERO1_", "hero_spot05" )
     copyOriginAndAngles("_HERO2_", "hero_spot06" )
     copyOriginAndAngles("_HERO3_", "hero_spot07" )
     copyOriginAndAngles("_HERO4_", "hero_spot08" )
     cameraFade(0.000, 1.000 )
     # ( "*************************************************" )
     # ( "This section shows off the destruction of the mansion" )
     waittimed ( 2.500 )
     cameraMove(" 17.850 -624.140 62.130 ", 4.000 )
     cameraPan(" 0.000 0.000 91.000 ", 4.000, "FALSE" )
     waittimed ( 4.000 )
     cameraMove(" 18.220 -645.320 360.840 ", 3.000 )
     cameraPan(" 0.000 33.300 90.000 ", 3.000, "FALSE" )
     waittimed ( 4.000 )
     cameraFade(1.000, 1.000 )
     # ( "*************************************************" )
     waittimed ( 1.000 )
     # ( "Camera next to profx" )
     cameraToLocationAngles(" 670.000 -82.000 108.000 ", " 670.000 -173.000 66.000 ", 0.000 )
     # ( "Put the player in the last postion" )
     copyOriginAndAngles("_HERO1_", "hero_spot01" )
     copyOriginAndAngles("_HERO2_", "hero_spot02" )
     copyOriginAndAngles("_HERO3_", "hero_spot03" )
     copyOriginAndAngles("_HERO4_", "hero_spot04" )
     waittimed ( 0.500 )
     cameraFade(0.000, 1.000 )
     waittimed ( 1.000 )
     setallaiactive("TRUE" )
     # ( "turn on character talk icons" )
     setEnable("moira", "TRUE" )
     setEnable("forge_shop", "TRUE" )
     setEnable("forge", "TRUE" )
     setInvisible("x_jet", "FALSE" )
     lockControls(0.100 )
     remove ( "intro_light", "intro_light" )
     startConversation("act4/mansion/4_mansion_0010" )
else
     # ( "Make sure that Moira is enable so the player can talk to her" )
     waittimed ( 0.500 )
     setEnable("moira", "TRUE" )
     moira_talk = getObjective("act4_obj_2a_1", "COMPLETE" )
     if moira_talk == 0
          waittimed ( 1.000 )
          setHintType("moira", "importanttalk" )
     endif
     havok_talk = getObjective("act4_obj_1a_1", "COMPLETE" )
     if havok_talk == 0
          waittimed ( 1.000 )
          setHintType("havok", "importanttalk" )
     endif
endif
# ( "When ArchAngel is defeated ProfX has the conversatoin to go on to the next act" )
act4_done = getObjective("act4_obj_6b", "COMPLETE" )
if act4_done == 1
     setHintType("profx", "importanttalk" )
endif
# ( "This checks if Colossus has spoke with Kitty" )
# ( "The script section below is not complete without a new script command" )
did_colossus_talk = getGameFlag("mansion", 5 )
if did_colossus_talk == 0
     a = isActorOnTeam("colossus" )
     if a == 1
          setHintType("kitty", "importanttalk" )
     else
          setHintType("kitty", "talk" )
     endif
endif
sewers_unlocked = getObjective("act4_obj_2a_1", "COMPLETE" )
if sewers_unlocked == 1
     setEnable("link_sewers1", "TRUE" )
     remove ( "sewers_entrance", "sewers_entrance" )
endif
numBeacons = getGameVarBitCount("beaconact4" )
if numBeacons >= 4
     # ( "you have all the beacons, activate portal next to Forge" )
     setEnable("blink_to_bonuses", "TRUE" )
     setEnable("link_bonus4", "TRUE" )
     waittimed ( 0.500 )
     act("blink_to_bonuses", "blink_to_bonuses" )
endif

