# Generated by BehavEd
# ( "This script makes the talk to Havok objective done and readys the perimeter" )
# ( "Complete the talk to Havok obejective" )
objective ( "act4_obj_1a_1",  "EOBJCMD_COMPLETE" )
# ( "Complete the talk to Havok obejective" )
objective ( "act4_obj_1a_2",  "EOBJCMD_SHOW" )
# ( "Havok gives the quest to destroy the defense matrix" )
objective ( "act4_obj_1a",  "EOBJCMD_SHOW" )
# ( "Havok gives the quest to destroy the radar arrays" )
objective ( "act4_obj_1b",  "EOBJCMD_SHOW" )
# ( "This turns off the important hint flag" )
setHintType("havok", "talk" )

