# Generated by BehavEd
# ( "comment" )
sewers_unlocked = getObjective("act4_obj_2a_1", "COMPLETE" )
if sewers_unlocked == 1
     setEnable("link_sewers1", "TRUE" )
     remove ( "sewers_entrance", "sewers_entrance" )
else
     startConversation("common/finish_obj" )
endif

