# Generated by BehavEd
# ( "if the player has all three items, shaw doesn't complain" )
gotdiscs = getObjective("act4_obj_2b", "COMPLETE" )
gotkey = getObjective("act4_obj_2c", "COMPLETE" )
paidmoney = getObjective("act4_obj_2d", "COMPLETE" )
if gotdiscs == 1
     if gotkey == 1
          if paidmoney == 1
               allowConversation("FALSE" )
          else
               allowConversation("TRUE" )
          endif
     else
          allowConversation("TRUE" )
     endif
else
     allowConversation("TRUE" )
endif

