# Generated by BehavEd
# ( "This script checks if shaws sub-quests have been complete and if so they" )
# ( "set a var and allow a conversation" )
# ( "Each of the following var relate to a quest Shaw requires before" )
# ( "making the tower quest available" )
# ( "-" )
key = getObjective("act4_obj_2c", "COMPLETE" )
discs = getObjective("act4_obj_2b", "COMPLETE" )
# ( "This var makes sure the player doesn't loses another 10,000" )
alreadypaid = getGameFlag("act4_que", 6 )
if alreadypaid == 0
     # ( "This checks if the player has enough bits" )
     enough_money = getInventoryCount("MONEY" )
     if enough_money >= 10000
          # ( "This removes 10000 bits from the player" )
          enough_money = iadd(enough_money, -10000 )
          setInventoryCount("MONEY", enough_money )
          # ( "This var makes sure the player doesn't loses another 10,000" )
          setGameFlag("act4_que", 6, 1 )
          alreadypaid = getGameFlag("act4_que", 6 )
          objective ( "act4_obj_2d",  "EOBJCMD_COMPLETE" )
     endif
endif
if alreadypaid == 1
     if key == 1
          if discs == 1
               # ( "All three quests must be down to get this far" )
               # ( "This var is used to mark that the player has talked to Shaw after all of the quests have been completed" )
               # ( " When act4_que(5) == 1 then profx will unlock deadpool" )
               setGameFlag("act4_que", 5, 1 )
               # ( "we returned the key so complete that subquest" )
               objective ( "act4_obj_2f",  "EOBJCMD_COMPLETE" )
               # ( "we returned the holodiscs so complete that subquest" )
               objective ( "act4_obj_2e",  "EOBJCMD_COMPLETE" )
               # ( "mark this entire major quest as complete" )
               objective ( "act4_obj_2",  "EOBJCMD_COMPLETE" )
               # ( "start new major quest -- enter Apoc tower" )
               objective ( "act4_obj_4",  "EOBJCMD_SHOW" )
               objective ( "act4_obj_4a",  "EOBJCMD_SHOW" )
          endif
     endif
endif
startConversation("act4/mansion/4_mansion_0070" )

