# Generated by BehavEd
# ( "This script is used to start the breeding pen zones" )
setCurrentAct(4 )
objective ( "tower1_apoctower",  "EOBJCMD_SHOW" )
# ( "This game var is det to keep track of what objectives have been shown" )
setGameFlag("act4_que", 3, 1 )
# ( "Profx X no longer loads the zone directly, but make the quest available" )
objective ( "deadpool",  "EOBJCMD_SHOW" )

