# Generated by BehavEd
# ( "This script is used to start the NY zones, but the player must go throught he sewers first" )
setCurrentAct(4 )
objective ( "act4_obj_2a",  "EOBJCMD_SHOW" )
objective ( "act4_obj_2a_1",  "EOBJCMD_COMPLETE" )
# ( "This game var is det to keep track of what objectives have been shown" )
setGameFlag("act4_que", 1, 1 )

