# Generated by BehavEd
# ( "comment" )
spawnEffect("_OWNER_", "map/common/scr_blinkportal_s", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
fade("_OWNER_", 0.000, 0.300, "TRUE" )
playanim (  "EA_IDLE1", "_OWNER_", "LOOP", "" )
waittimed ( 0.300 )
remove ( "_OWNER_", "_OWNER_" )
spawnEffect("_OWNER_", "map/common/scr_blinkportal_c", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )

