# Generated by BehavEd
# ( "prisoner sitting down" )
setNoCollide("_OWNER_", "TRUE" )
setAIActive("_OWNER_", "FALSE" )
setCanMove("_OWNER_", "FALSE" )
setNoGravity("_OWNER_", "TRUE" )
playanim (  "EA_ZONE3", "_OWNER_", "LOOP", "" )

