# Generated by BehavEd
# ( "Theses camrea cmds keep the camera in the same stop as before the conversaiton" )
lockControls(0.000 )
cameraMove(" 6825.000 4570.000 216.000 ", 0.000 )
cameraPan(" 0.000 21.900 84.000 ", 0.000, "FALSE" )
waittimed ( 0.200 )
cameraPan(" 0.000 18.100 282.700 ", 0.000, "FALSE" )
waittimed ( 2.000 )
setReactToEnemies("charlie", "FALSE" )
startConversation("act4/perimeter/perimeter4/4_perimeter4_0013" )

