# Generated by BehavEd
# ( "Theses camrea cmds keep the camera in the same stop as before the conversaiton" )
setReactToEnemies("charlie", "FALSE" )
startConversation("act4/perimeter/perimeter4/4_perimeter4_0013b" )

