# Generated by BehavEd
# ( "This script randomly determines of a convereation should be played" )
rand_int = randomInt(1, 3 )
if rand_int == 1
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

