# Generated by BehavEd
# ( "This makes the entitiy calling it invunerable" )
check_consle = getObjective("act4_obj_1b_2", "COMPLETE" )
if check_consle == 1
     setInvulnerable("_OWNER_", "FALSE" )
else
     setInvulnerable("_OWNER_", "TRUE" )
endif

