# Generated by BehavEd
# ( "Charlies death script" )
# ( "If reached_platform3 == 1 then Charlie has reached the third platform" )
reached_platform3 = getGameFlag("perimeter", 3 )
if reached_platform3 == 0
     playanim (  "EA_USE_BUTTON", "charlie", "", "" )
     waittimed ( 2.000 )
     gameover (  "GAMEOVER_CHARLIE" )
endif

