# Generated by BehavEd
# ( "This is the pain script for Charlie" )
# ( "********************************************************" )
# ( "max_hits is the maximum number hits that charlie can take before he dies" )
max_hits = randomInt(30, 30 )
# ( "****************************" )
# ( "This keeps track of the number of times Charlie is hit." )
num_charlie_hits = getZoneVar("charlie_var" )
num_charlie_hits = iadd(num_charlie_hits, 1 )
setZoneVar("charlie_var", num_charlie_hits )
# ( "****************************" )
max_health = getHealthMax("charlie" )
if num_charlie_hits == 4
     # ( "This sets chariles health to 60% of max" )
     health_percent_60 = fmul(max_health, 0.600 )
     setHealth("charlie", health_percent_60 )
elif num_charlie_hits == max_hits
     killEntity("charlie" )
else
     # ( "After Charlie 8 hits his health is only reduce by 10 percent, after that" )
     cur_health = getHealth("charlie" )
     new_health = fmul(cur_health, 0.900 )
     # ( "Change Charlie's health to the new current health" )
     setHealth("charlie", new_health )
endif
# ( "Check to see if the VO should be played" )
# ( "This is random generated, but is also set after the second hit" )
rand_int = randomInt(1, 4 )
if rand_int == 1
     sound (  "PLAY_SOUND", "voice/kilroy/4_perimeter4_012_001", "charlie", "" )
elif rand_int == 2
     sound (  "PLAY_SOUND", "voice/kilroy/4_perimeter4_012_002", "charlie", "" )
elif rand_int == 3
     sound (  "PLAY_SOUND", "voice/kilroy/4_perimeter4_012_003", "charlie", "" )
else
     sound (  "PLAY_SOUND", "voice/kilroy/4_perimeter4_012_004", "charlie", "" )
endif

