# Generated by BehavEd
# ( "This script restore charlies health" )
faceEntity("charlie", "_HERO1_" )
# ( "Make sure that Charlie is at max health" )
set_max_health = getHealthMax("charlie" )
setHealth("charlie", set_max_health )
# ( "Don't forget to reset the zone var" )
setZoneVar("charlie_var", 0 )

