# Generated by BehavEd
# ( "This script shows the death of Charlie" )
cameraToLocationAngles(" 3901.000 5982.000 411.000 ", " 3887.000 5893.000 369.500 ", 0.000 )
faceEntity("charlie", "light_yellow03" )
waittimed ( 0.250 )
act("charlie_boom", "charlie_boom" )
playanim (  "EA_POPUP_START", "charlie", "STOP", "" )
setVelocity("charlie", " 900.000 -900.000 2000.000 " )
waittimed ( 0.330 )
remove ( "charlie", "charlie" )
waittimed ( 0.750 )
startConversation("act4/perimeter/perimeter4/4_perimeter4_0014" )

