# Generated by BehavEd
# ( "This scritp is used for the first array" )
# ( "Only 1/3 the times does a sentinel respawn" )
rand_int = randomInt(1, 3 )
if rand_int == 1
     rand_int = randomInt(1, 4 )
     if rand_int == 1
          act("ss_charlie_sentinel_b01", "ss_charlie_sentinel_b01" )
     elif rand_int == 2
          act("ss_charlie_sentinel_b02", "ss_charlie_sentinel_b02" )
     elif rand_int == 3
          act("ss_charlie_sentinel_b03", "ss_charlie_sentinel_b03" )
     else
          act("ss_charlie_sentinel_b04", "ss_charlie_sentinel_b04" )
     endif
endif
sentinal_alive = alive("charlie_sentinel" )
# ( "When all the sentinels are killed they all are repond" )
if sentinal_alive == 0
     if rand_int == 2
          act("ss_charlie_sentinel_b03", "ss_charlie_sentinel_b03" )
     else
          act("ss_charlie_sentinel_b02", "ss_charlie_sentinel_b02" )
          waittimed ( 0.500 )
          act("ss_charlie_sentinel_b03", "ss_charlie_sentinel_b03" )
     endif
endif

