# Generated by BehavEd
# ( "This script checks of the perimeter3 objectives have been completed" )
# ( "If not then the Nick Fury conversaiton is played that tells the player they can't leave." )
perm3_done = getObjective("act4_obj_1b", "COMPLETE" )
if perm3_done == 1
     act("final_teleporter", "final_teleporter" )
     setEnable("link_perimeter5", "TRUE" )
     setEnable("zone_console", "FALSE" )
     # ( "This enables the teleporter and zone link back to perimeter3" )
     setEnable("old_teleporter", "TRUE" )
     setEnable("link_perimeter3", "TRUE" )
     act("old_teleporter", "old_teleporter" )
else
     startConversation("common/finish_obj" )
endif

