# Generated by BehavEd
# ( "Commpletes destroy security console quest" )
console_destroyed = getObjective("act4_obj_1b_2", "COMPLETE" )
if console_destroyed == 0
     objective ( "act4_obj_1b_2",  "EOBJCMD_COMPLETE" )
     # ( "This enables the next  phase" )
     setEnable("shield_console", "TRUE" )
     startConversation("act4/perimeter/perimeter4/4_perimeter4_0015" )
endif

