# Generated by BehavEd
# ( "This forces Charlie to go to the first platform" )
setFollowingHero("charlie", "FALSE" )
playanim (  "EA_ZONE4", "charlie", "LOOP", "" )
# ( "Start timer" )
timerStart(90.000, 10.000, "act4/perimeter/perimeter4/disable_array02_complete" )
waittimed ( 3.000 )
# ( "Remind the player that they need to protect Charile" )
sound (  "PLAY_SOUND", "voice/charlie/4_perimeter4_012_002", "", "" )

