# Generated by BehavEd
# ( "This forces Charlie to go to the first platform" )
setFollowingHero("charlie", "FALSE" )
playanim (  "EA_ZONE4", "charlie", "LOOP", "" )
# ( "Start timer" )
start_timer_yet = getGameFlag("perimeter", 2 )
if start_timer_yet == 1
     timerStart(60.000, 10.000, "act4/perimeter/perimeter4/disable_array01_complete" )
else
     # ( "If this is called then Charlie has reached the array before the conversaotin is finished" )
     # ( "So the timer should be start now in a conversatoin via the script start_timer.py" )
     setGameFlag("perimeter", 2, 1 )
endif
waittimed ( 3.000 )
# ( "Remind the player that they need to protect Charile" )
sound (  "PLAY_SOUND", "voice/kilroy/4_perimeter4_012_002", "", "" )

