# Generated by BehavEd
# ( "This resets the last array puzzle" )
# ( "The shield goes back up and the console has to be used again to lower it." )
objective ( "act4_obj_1b_3",  "EOBJCMD_INCOMPLETE" )
setInvulnerable("array_generator", "TRUE" )
spawn("array_generator", "generator_shield", "generator_shield", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
setEnable("shield_console", "TRUE" )
# ( "Shut off timer" )
timerStart(0.000, 0.000, "" )

