# Generated by BehavEd
# ( "Give destroy security console quest" )
objective ( "act4_obj_1b_2",  "EOBJCMD_SHOW" )
# ( "This is to make sure the console is destroyable" )
setInvulnerable("destroyable_consoel", "FALSE" )

