# Generated by BehavEd
# ( "Give destroy generator quest" )
once_only = getGameFlag("perimeter", 4 )
if once_only == 0
     cameraFocusToEntity("array_generator", 415.000, 43.700, 45.000, 3.000 )
     setGameFlag("perimeter", 4, 1 )
     waittimed ( 2.000 )
     remove ( "generator_shield", "generator_shield" )
     waittimed ( 2.000 )
     cameraReset( )
endif
# ( "Give destroy generator quest" )
objective ( "act4_obj_1b_4",  "EOBJCMD_SHOW" )
# ( "Give deactiving shield quest" )
objective ( "act4_obj_1b_3",  "EOBJCMD_COMPLETE" )
remove ( "generator_shield", "generator_shield" )
timerStart(20.000, 5.000, "act4/perimeter/perimeter4/generator_reset" )
setInvulnerable("array_generator", "FALSE" )

