# Generated by BehavEd
# ( "This shows the quests for perimeter4" )
setCurrentAct(4 )
# ( "This shows the quests for perimeter4" )
objective ( "act4_obj_1b",  "EOBJCMD_SHOW" )
# ( "Protect Charile quest" )
objective ( "act4_obj_1b_1",  "EOBJCMD_SHOW" )

