# Generated by BehavEd
# ( "This forces Charlie to go to the second platform" )
# ( "This removes the triggers" )
remove ( "trigger_array02_a", "trigger_array02_a" )
remove ( "trigger_array02_b", "trigger_array02_b" )
waittimed ( 0.200 )
setFollowingHero("charlie", "FALSE" )
setWaypointPath("charlie", "disable_secondplatform", 1 )
waittimed ( 1.000 )
sound (  "PLAY_SOUND", "voice/kilroy/4_perimeter4_011_001", "", "" )
setReactToEnemies("charlie", "FALSE" )

