# Generated by BehavEd
# ( "This checks to see if the timer should be start yet" )
# ( "The problem is that you don't want to start the timer until after the player has completed the conversation" )
start_timer_yet = getGameFlag("perimeter", 2 )
if start_timer_yet == 1
     timerStart(60.000, 10.000, "act4/perimeter/perimeter4/disable_array01_complete" )
else
     # ( "If this is called then the conversation has ended before Charlie has gotten into place" )
     # ( "So the timer should be start now in disable_array1.py" )
     setGameFlag("perimeter", 2, 1 )
endif
enemiesNoTarget("FALSE" )
heroNoTarget("FALSE" )
waittimed ( 0.100 )
setReactToEnemies("charlie", "FALSE" )

