# Generated by BehavEd
# ( "This script loads the intro movie for act5 and loads the teleport map" )
startMovie("Cine05", "afterMovie" )
waitsignal ( "afterMovie" )
loadZone("act5/teleport/teleport1", "link_teleport" )

