# Generated by BehavEd
# ( "fade out and reset camera" )
cameraFade(1.000, 0.500 )
waittimed ( 0.500 )
# ( "remove shaw" )
remove ( "shaw", "shaw" )
cameraReset( )
# ( "fade in and unlock controls" )
cameraFade(0.000, 1.000 )
waittimed ( 1.000 )
lockControls(0.100 )
enemiesNoTarget("FALSE" )
heroNoTarget("FALSE" )
# ( "UPDATE OBJECTIVES" )
# ( "complete findShaw objective" )
objective ( "act4_obj_2a",  "EOBJCMD_COMPLETE" )
# ( "show holodiscs objective" )
objective ( "act4_obj_2b",  "EOBJCMD_SHOW" )
# ( "have the holodiscs been found already?" )
discs = getObjective("act4_obj_2b", "COMPLETE" )
if discs == 1
     # ( "discs have been found--tell player to take them to shaw" )
     objective ( "act4_obj_2e",  "EOBJCMD_SHOW" )
endif
# ( "show masterKey objective" )
objective ( "act4_obj_2c",  "EOBJCMD_SHOW" )
# ( "has the master key been found already?" )
key = getObjective("act4_obj_2c", "COMPLETE" )
if key == 1
     # ( "key has been found--tell player to take it to shaw" )
     objective ( "act4_obj_2f",  "EOBJCMD_SHOW" )
else
     # ( "key hasn't been found--set hinttype=objective" )
     setHintType("master_key", "objective" )
endif
# ( "show 10,000 techbits objective" )
objective ( "act4_obj_2d",  "EOBJCMD_SHOW" )

