# Generated by BehavEd
# ( "remove the master key" )
remove ( "master_key", "master_key" )
# ( "indicate master key has been found" )
objective ( "act4_obj_2c",  "EOBJCMD_COMPLETE" )
# ( "has the player talked to shaw?" )
talk = getObjective("act4_obj_2a", "COMPLETE" )
if talk == 0
     # ( "player has not talked to shaw--run conversation" )
     startConversation("act4/newyork/newyork2/4_newyork2_0010" )
else
     # ( "tell the player to return the key to shaw" )
     objective ( "act4_obj_2f",  "EOBJCMD_SHOW" )
endif

