# Generated by BehavEd
# ( "WARNING--objective testing only--do not use" )
# ( "has the map been visited before?" )
visit = getGameFlag("newyork", 1 )
if visit == 0
     # ( "this is the first visit, so run an intro conversation" )
     # ( "is talking to shaw an objective?" )
     shaw = getObjective("act4_obj_2a", "HIDDEN" )
     if shaw == 1
          # ( "shaw is not an objective--play appropriate intro conversation" )
          startConversation("act4/newyork/newyork2/4_newyork1_0010b" )
          # ( "indiciate the map has been visited" )
          setGameFlag("newyork", 1, 1 )
     else
          # ( "shaw is an objective--play appropriate intro conversation" )
          startConversation("act4/newyork/newyork2/4_newyork1_0010" )
          # ( "indiciate the map has been visited" )
          setGameFlag("newyork", 1, 1 )
     endif
endif
# ( "has shaw been talked to?" )
talk = getObjective("act4_obj_2a", "COMPLETE" )
if talk == 1
     # ( "shaw has been talked to--remove him" )
     waittimed ( 1.000 )
     remove ( "shaw", "shaw" )
endif
# ( "has the master key become an objective?" )
keyobj = getObjective("act4_obj_2c", "HIDDEN" )
if keyobj == 0
     # ( "the master key is an objective--make sure hinttype=objective" )
     setHintType("master_key", "objective" )
endif
# ( "has the master key been found?" )
key = getObjective("act4_obj_2c", "COMPLETE" )
if key == 1
     remove ( "master_key", "master_key" )
endif
# ( "have the techbits been found?" )
bits = getGameFlag("newyork", 3 )
if bits == 1
     # ( "techbits have been found--make sure player doesn't get any more" )
     remove ( "techbits", "techbits" )
endif

