# Generated by BehavEd
# ( "comment" )
# ( "lock controls" )
lockControls(-1.000 )
enemiesNoTarget("TRUE" )
heroNoTarget("TRUE" )
# ( "focus camera on shaw" )
cameraFocusToEntity("cam_shaw", 320.000, 45.000, 135.000, 2.000 )
waittimed ( 2.000 )
# ( "start conversation" )
startCharConversation("act4/newyork/newyork2/4_newyork1_0020", "gambit", "act4/newyork/newyork2/4_newyork1_0021" )

