# Generated by BehavEd
# ( "This checks if the anitmetal has been returned" )
found_vibranium = getObjective("act2_obj_4a", "COMPLETE" )
if found_vibranium == 1
     # ( "Since the vibranium has been found and the player is talking to Kazar, then" )
     # ( "mark the quest as done" )
     objective ( "act2_obj_4b",  "EOBJCMD_COMPLETE" )
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

