# Generated by BehavEd
# ( "This checks if destiny has been rescued" )
rescue_destiny = getObjective("act2_obj_1b", "COMPLETE" )
if rescue_destiny == 1
     once_only = getGameFlag("savage", 13 )
     if once_only == 0
          setGameFlag("savage", 13, 1 )
          allowConversation("TRUE" )
     else
          allowConversation("FALSE" )
     endif
else
     allowConversation("FALSE" )
endif

