# Generated by BehavEd
# ( "This script is called at the end of the Mystique converstion" )
talk_once_mystique = getObjective("act2_obj_1c", "HIDDEN" )
if talk_once_mystique == 0
     objective ( "act2_obj_1c",  "EOBJCMD_COMPLETE" )
endif

