# Generated by BehavEd
# ( "This makes sure the first startcondiciton is only played once." )
once_only = getGameFlag("savage", 11 )
if once_only == 1
     allowConversation("FALSE" )
else
     setGameFlag("savage", 11, 1 )
     allowConversation("TRUE" )
endif

