# Generated by BehavEd
# ( "This script checks of act2 is completed" )
ready_to_go = getObjective("act2_obj_6d", "COMPLETE" )
if ready_to_go == 0
     allowConversation("FALSE" )
else
     # ( "This completes the last objective of act 2" )
     objective ( "act2_obj_6e",  "EOBJCMD_COMPLETE" )
     allowConversation("TRUE" )
endif

