# Generated by BehavEd
# ( "This script enable the owner" )
# ( "This is usually used on characters after cinematic so the conversation icon doesn't appear." )
setEnable("profx_intro", "TRUE" )
# ( "This fades the canvas back to it's normal state" )
fade("canvas_01_sav_e_sl07", 1.000, 0.000, "FALSE" )
# ( "show objective1 'find mystique'" )
objective ( "act2_obj_1",  "EOBJCMD_SHOW" )
objective ( "act2_obj_1a_1",  "EOBJCMD_SHOW" )

