# Generated by BehavEd
# ( "This is called when the player enters the area" )
# ( "This turns the wather back off" )
act("effect_jungle_weather", "effect_jungle_weather" )
act("effect_jungle_weather_rain", "effect_jungle_weather_rain" )

