# Generated by BehavEd
# ( "This is called when the player exits the area and returns the player to the party light" )
setPartyLightColor(" 0.930 0.740 0.000 ", 1.500 )
# ( "This turns the wather back on" )
act("effect_jungle_weather", "effect_jungle_weather" )

