# Generated by BehavEd
# ( "This checks if the monument quest should be given" )
objective ( "act2_obj_3",  "EOBJCMD_SHOW" )
objective ( "act2_obj_3a",  "EOBJCMD_SHOW" )
# ( "This var is check in the briefing conversation to know where to show a line or not" )
setGameFlag("savage", 8, 1 )

