# Generated by BehavEd
# ( "This checks if the anitmetal quest should be given" )
ready_vibranium = getObjective("act2_obj_4a", "HIDDEN" )
if ready_vibranium == 0
     allowConversation("TRUE" )
     # ( "This var is check in the briefing conversation to know where to show a line or not" )
     setGameFlag("savage", 9, 1 )
else
     allowConversation("FALSE" )
endif

