# Generated by BehavEd
# ( "This script choses what conversation to call" )
destiny_rescued = getObjective("act2_obj_1b", "COMPLETE" )
if destiny_rescued == 1
     startConversation("act2/savage/2_savage1_0130" )
else
     startConversation("act2/savage/2_savage1_0120" )
endif

