# Generated by BehavEd
# ( "This is the load script for the savage town center" )
# ( "This unlocks the extraction point" )
extractionUnlock("" )
first_vist = getGameFlag("act2_visit", 1 )
if first_vist == 0
     # ( "This turns off the tourch sounds" )
     act("tourch_sound01", "tourch_sound01" )
     act("tourch_sound02", "tourch_sound02" )
     setallaiactive("FALSE" )
     # ( "********************************************************************************************" )
     # ( "This marks that Beast has been captured, in case the player goes back to act 1" )
     setGameFlag("act1_visit", 17, 1 )
     # ( "********************************************************************************************" )
     lockControls(0.000 )
     cameraFade(1.000, 0.000 )
     waittimed ( 1.000 )
     cameraToLocationAngles(" 1794.000 1897.000 136.000 ", " 1885.000 1921.000 102.000 ", 0.000 )
     copyOriginAndAngles("_HERO1_", "hero_spot01" )
     copyOriginAndAngles("_HERO2_", "hero_spot02" )
     copyOriginAndAngles("_HERO3_", "hero_spot03" )
     copyOriginAndAngles("_HERO4_", "hero_spot04" )
     # ( "Allow a moment to make sure that profx is spawned, because disabling him" )
     waittimed ( 0.500 )
     cameraFade(0.000, 1.000 )
     waittimed ( 1.000 )
     lockControls(0.100 )
     setallaiactive("TRUE" )
     startConversation("act2/savage/2_savage1_0010" )
else
     waittimed ( 0.500 )
     setEnable("profx_intro", "TRUE" )
endif
# ( "Set Pyro with important talk if his objective is not complete" )
pryo_obj = getObjective("act2_obj_1a_1", "COMPLETE" )
if pryo_obj == 0
     setHintType("pyro", "importanttalk" )
else
     remove ( "trigger_pyro", "trigger_pyro" )
endif
# ( "Pyro spawns in the town center" )
check_pyro = isActorOnTeam("pyro_hero" )
if check_pyro == 0
     act("sp_pyro01", "sp_pyro01" )
else
     remove("pyro", "pyro" )
endif
# ( "Angel appears only after Destiny is saved" )
spawn_angel = getObjective("act2_obj_1b", "COMPLETE" )
if spawn_angel == 1
     act("sp_angel01", "sp_angel01" )
endif
# ( "Kazar is always in the town center" )
spawn_kazar = getObjective("act2_visit", "COMPLETE" )
if spawn_kazar == 0
     act("sp_kazar01", "sp_kazar01" )
endif
# ( "Shanna only appears after the atmospheric processors" )
spawn_shanna = getObjective("act2_obj_2a", "COMPLETE" )
if spawn_shanna == 1
     act("sp_shanna01", "sp_shanna01" )
endif
# ( "Mystique only appears after she is found in the Jungle" )
spawn_mystique = getObjective("act2_obj_1b_a", "COMPLETE" )
if spawn_mystique == 1
     act("sp_mystique01", "sp_mystique01" )
     # ( "This sets importanttalk=true, once only" )
     waittimed ( 0.500 )
     setHintType("mystique", "importanttalk" )
endif
# ( "Destiny only appears after she is resuced" )
spawn_destiny = getObjective("act2_obj_1b", "COMPLETE" )
if spawn_destiny == 1
     act("sp_destiny01", "sp_destiny01" )
endif
# ( "Garrok only appears after he is defeated" )
spawn_garokk = getObjective("act2_obj_1b_a", "COMPLETE" )
if spawn_garokk == 1
     act("sp_garokk01", "sp_garokk01" )
endif
# ( "After the player talks to Angel Jungle2 is available" )
jungle2_accessible = getGameFlag("savage", 6 )
if jungle2_accessible == 1
     remove ( "trigger_stop_player", "trigger_stop_player" )
     act("torch_lane01", "torch_lane01" )
     act("torch_lane02", "torch_lane02" )
     act("torch_lane03", "torch_lane03" )
     act("torch_lane04", "torch_lane04" )
     act("torch_lane05", "torch_lane05" )
     act("torch_lane06", "torch_lane06" )
     act("fire_light_ent01", "fire_light_ent01" )
     act("fire_light_ent02", "fire_light_ent02" )
     setEnable("link_savage2", "TRUE" )
endif
# ( "Mark that the town center has been visited" )
setGameFlag("act2_visit", 1, 1 )
# ( "The following section will set character correct talk icon state" )
# ( "*************************************************************" )
anti_metal_done = getObjective("act2_obj_4b", "HIDDEN" )
if anti_metal_done == 0
     # ( "Once the objective is complete it is hidden automatically" )
     setHintType("kazar", "importanttalk" )
endif
profx_talk = getObjective("act2_obj_6e", "HIDDEN" )
if profx_talk == 0
     setHintType("profx_intro", "importanttalk" )
endif
# ( "This var is set in miltary.py after Holocaust has been defeated" )
angel_captured = getGameFlag("angel_gone", 1 )
if angel_captured == 1
     waittimed ( 0.500 )
     remove ( "angel", "angel" )
endif
numBeacons = getGameVarBitCount("beaconact2" )
if numBeacons >= 4
     # ( "you have all the beacons, activate portal next to Forge" )
     setEnable("blink_to_bonuses", "TRUE" )
     setEnable("link_bonus2", "TRUE" )
     waittimed ( 0.500 )
     act("blink_to_bonuses", "blink_to_bonuses" )
endif

