# Generated by BehavEd
# ( "This script shows the find mystique objective (act2_obj_1a)" )
objective ( "act2_obj_1a",  "EOBJCMD_SHOW" )
# ( "This var is check in the briefing conversation to know where to show a line or not" )
setGameFlag("savage", 7, 1 )
# ( "just spoke with Pyro, complete act2_obj_1a_1" )
objective ( "act2_obj_1a_1",  "EOBJCMD_COMPLETE" )

