# Generated by BehavEd
# ( "This is the spawn script for Garokk" )
playanim (  "EA_ZONE1", "_OWNER_", "LOOP", "" )
waittimed ( 0.500 )
# ( "Acts on a loop effect that is center on the pivot of the spawner" )
act("loop_energy_cage", "loop_energy_cage" )

