# Generated by BehavEd
# ( "just spoke with Pyro, complete act2_obj_1a_1" )
completed = getObjective("act2_obj_1a_1", "COMPLETE" )
if completed == 0
     # ( "haven't completed act2_obj_1a_1 yet, so do it now" )
    objective ( "act2_obj_1a_1",  "EOBJCMD_COMPLETE" )
    pyro_unlocked = isCharacterUnlocked("Pyro_hero")
    if pyro_unlocked == 0
        # ( "Pyro is not yet unlocked, unlock him" )
        unlockCharacter("Pyro_hero", " ")
        pyro_unlocked = isCharacterUnlocked("Pyro_hero")
        if pyro_unlocked == 1
            # ( "Pyro was not previously unlocked but he is on the roster" )
            # ( "He's been unlocked now, so show the dialog that confirms this" )
            createPopupDialogXML("dialogs/act2/savage/pyro_unlocked")
        endif 
    endif
endif

