# Generated by BehavEd
# ( "just spoke with Pyro, complete act2_obj_1a_1" )
completed = getObjective("act2_obj_1a_1", "COMPLETE" )
if completed == 0
     # ( "haven't completed act2_obj_1a_1 yet, so do it now" )
     objective ( "act2_obj_1a_1",  "EOBJCMD_COMPLETE" )
endif

