# Generated by BehavEd
# ( "Two different outcomes will trigger depending if player has Pyro on team or not." )
talk_with_pyro = getObjective("act2_obj_1a_1", "COMPLETE" )
if talk_with_pyro == 0
     talk_with_pyro = isActorOnTeam("pyro_hero" )
     if talk_with_pyro == 0
          # ( "NPC Pyro talks to player" )
          faceEntity("pyro", "_ACTIVE_HERO_" )
          startConversation("act2/savage/2_savage1_0040" )
     else
          # ( "If Pyro is deployed to team, he takes NPC Pyro's place in this scene." )
          lockControls(2.000 )
          setallaiactive("FALSE" )
          cameraFade(1.000, 0.500 )
          waittimed ( 0.500 )
          copyOriginAndAngles("pyro_hero", "sp_pyro01" )
          waittimed ( 1.000 )
          cameraFade(0.000, 1.000 )
          waittimed ( 0.500 )
          setallaiactive("TRUE" )
          faceEntity("Pyro_hero", "_ACTIVE_HERO_" )
          startConversation("act2/savage/2_savage1_0040" )
     endif
else
     remove ( "trigger_pyro", "trigger_pyro" )
endif

