# Generated by BehavEd
# ( "has the player found all of Iron Man's armor?" )
armor = getGameVarBitCount("r_imarmor" )
if armor == 4
     # ( "has Iron Man been unlocked?" )
     unlocked = getGameFlag("bonus5", 2 )
     if unlocked == 1
          # ( "Iron Man has been unlocked and would like to leave" )
          startConversation("bonus/5_ironman5_0010c" )
     else
          # ( "all armor found--prepare to unlock Iron Man" )
          startConversation("bonus/5_ironman5_0010b" )
     endif
else
     # ( "all armor not found--tell player to come back later" )
     startConversation("bonus/5_ironman5_0010a" )
endif

