# Generated by BehavEd
# ( "has the player spoken to Tony Stark before?" )
tony = getGameFlag("bonus5", 3 )
if tony == 1
     # ( "the player has spoken to Tony--disallow intro conversation" )
     allowConversation("FALSE" )
else
     # ( "the player has not spoken to Tony before--indicate the player has now done so" )
     setGameFlag("bonus5", 3, 1 )
endif

