# Generated by BehavEd
# ( "indicate Iron Man has been unlocked" )
setGameFlag("bonus5", 2, 1 )
# ( "unlock Iron Man" )
unlockCharacter("ironman", "" )
setSkin("tony", "1501" )
sound (  "PLAY_SOUND", "voice/ironman/unlock", "", "" )
spawnEffect("tony", "base/misc/misc_levelup", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
playanim (  "EA_MENU_ACTION", "tony", "NONE", "yippee" )
# ( "Tony concludes with an inspirational speech" )
waitsignal ( "yippee" )
startConversation("bonus/5_ironman5_0010c" )

