# Generated by BehavEd
# ( "WARNING--testing only!" )
# ( "have all three puzzles been solved?" )
puz_status = getGameFlag("bonus5", 1 )
if puz_status == 1
     # ( "all 3 puzzles have been solved..." )
     # ( "...torches and pit should be how the player left them" )
     act("b5trig_stone", "b5trig_stone" )
     act("switch_statue", "switch_statue" )
     killEntitySilent("sun_pillar" )
     act("spwnr_tony", "spwnr_tony" )
     waittimed ( 0.100 )
     actSilent("pit", "pit" )
     actSilent("rising_floor", "rising_floor" )
endif
# ( "has Iron Man been unlocked?" )
ironman = getGameFlag("bonus5", 2 )
if ironman == 1
     # ( "Iron Man has been unlocked--remove Tony" )
     waittimed ( 0.500 )
     remove ( "tony", "tony" )
endif

