# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept37.png" )
imageViewer("textures/concept/concept38.png" )
imageViewer("textures/concept/concept39.png" )

