# Generated by BehavEd
# ( "act3 rotating ice cannon" )
waittimed ( 0.500 )
# ( "do not run if a conversation is active, will be reset next time around" )
conv = getConversationActive( )
if conv == 0
     spawn("_OWNER_", "p3_ice_proj", "p3_ice_proj", " 26.000 0.000 48.000 ", " 0.000 0.000 0.000 " )
     waittimed ( 1.000 )
     alive = alive("_OWNER_" )
     if alive == 1
          # ( "do not run if a conversation is active, will be reset next time around" )
          conv = getConversationActive( )
          if conv == 0
               spawn("_OWNER_", "p3_ice_proj", "p3_ice_proj", " 0.000 26.000 48.000 ", " 0.000 0.000 1.570 " )
               waittimed ( 1.000 )
               alive = alive("_OWNER_" )
               if alive == 1
                    # ( "do not run if a conversation is active, will be reset next time around" )
                    conv = getConversationActive( )
                    if conv == 0
                         spawn("_OWNER_", "p3_ice_proj", "p3_ice_proj", " -26.000 0.000 48.000 ", " 0.000 0.000 3.140 " )
                         waittimed ( 1.000 )
                         alive = alive("_OWNER_" )
                         if alive == 1
                              # ( "do not run if a conversation is active, will be reset next time around" )
                              conv = getConversationActive( )
                              if conv == 0
                                   spawn("_OWNER_", "p3_ice_proj", "p3_ice_proj", " 0.000 -26.000 48.000 ", " 0.000 0.000 4.710 " )
                              endif
                         endif
                    endif
               endif
          endif
     endif
endif

