# Generated by BehavEd
# ( "canoptic hottub placement script" )
canopic_bs1 = getGameFlag("canopic", 1 )
if canopic_bs1 == 1
     # ( "origin1" )
     copyOriginAndAngles("canopic1_placement", "canopic1_position" )
     sound (  "PLAY_SOUND", "zone_shared/special/canopic_jar_place", "", "" )
     objective ( "act5_obj_1b_b",  "EOBJCMD_INCREMENT" )
     # ( "set a different flag to indicate we've place the jar in the hot tub" )
     setGameFlag("canopic", 11, 1 )
endif
canopic2_bs2 = getGameFlag("canopic", 2 )
if canopic2_bs2 == 1
     # ( "origin2" )
     copyOriginAndAngles("canopic2_placement", "canopic2_position" )
     sound (  "PLAY_SOUND", "zone_shared/special/canopic_jar_place", "", "" )
     objective ( "act5_obj_1b_b",  "EOBJCMD_INCREMENT" )
     # ( "set a different flag to indicate we've place the jar in the hot tub" )
     setGameFlag("canopic", 12, 1 )
endif
canopic3_bs3 = getGameFlag("canopic", 3 )
if canopic3_bs3 == 1
     # ( "origin3" )
     copyOriginAndAngles("canopic3_placement", "canopic3_position" )
     sound (  "PLAY_SOUND", "zone_shared/special/canopic_jar_place", "", "" )
     objective ( "act5_obj_1b_b",  "EOBJCMD_INCREMENT" )
     # ( "set a different flag to indicate we've place the jar in the hot tub" )
     setGameFlag("canopic", 13, 1 )
endif
canopic4_bs4 = getGameFlag("canopic", 4 )
if canopic4_bs4 == 1
     # ( "origin4" )
     copyOriginAndAngles("canopic4_placement", "canopic4_position" )
     sound (  "PLAY_SOUND", "zone_shared/special/canopic_jar_place", "", "" )
     objective ( "act5_obj_1b_b",  "EOBJCMD_INCREMENT" )
     # ( "set a different flag to indicate we've place the jar in the hot tub" )
     setGameFlag("canopic", 14, 1 )
endif
# ( "if all four have been placed, it's showtime" )
if canopic_bs1 == 1
     if canopic2_bs2 == 1
          if canopic3_bs3 == 1
               if canopic4_bs4 == 1
                    # ( "camera magic time!" )
                    lockControls(-1.000 )
                    setallaiactive("FALSE" )
                    waittimed ( 1.000 )
                    cameraFade(1.000, 1.000 )
                    waittimed ( 1.000 )
                    cameraToLocationAngles(" 8080.223 4591.498 188.727 ", " 7960.000 4470.000 41.637 ", 0.000 )
                    cameraFade(0.000, 1.000 )
                    act("box_charge", "box_charge" )
                    waittimed ( 3.000 )
                    act("box_beam01", "box_beam01" )
                    waittimed ( 0.900 )
                    cameraToLocationAngles(" 8152.013 6246.652 228.789 ", " 8000.000 6500.000 18.374 ", 0.000 )
                    act("box_charge", "box_charge" )
                    act("box_beam01", "box_beam01" )
                    waittimed ( 0.750 )
                    act("box_beam02", "box_beam02" )
                    waittimed ( 1.000 )
                    act("box_impact", "box_impact" )
                    # ( "enable glowing decal here" )
                    copyOriginAndAngles("sek_glow_dec", "glow_null" )
                    remove ( "sek_rusty_dec", "sek_rusty_dec" )
                    cameraShake(10.000, 3.000 )
                    sound (  "PLAY_SOUND", "zone_shared/fx/screen_shake", "", "" )
                    waittimed ( 2.000 )
                    act("box_impact", "box_impact" )
                    act("box_beam02", "box_beam02" )
                    killEntity("sek_wall" )
                    remove ( "box_impact", "box_impact" )
                    remove ( "sek_glow_dec", "sek_glow_dec" )
                    waittimed ( 1.000 )
                    cameraFocusToEntity("box_beam01", 200.000, 40.000, 0.000, 3.000 )
                    waittimed ( 2.000 )
                    cameraReset( )
                    setallaiactive("TRUE" )
                    remove ( "canopic_trigger", "canopic_trigger" )
                    objective ( "act5_obj_1b_b",  "EOBJCMD_COMPLETE" )
                    lockControls(0.100 )
               endif
          endif
     endif
endif

