# Generated by BehavEd
# ( "comment" )
objective ( "act5_obj_1b_b",  "EOBJCMD_SHOW" )
objective ( "act5_obj_1b_a",  "EOBJCMD_SHOW" )
canopic = getGameFlag("canopic", 1 )
if canopic == 1
     remove ( "canopic1", "canopic1" )
     # ( "have we placed the jar in the hot tub yet?" )
     hottub1 = getGameFlag("canopic", 11 )
     if hottub1 == 1
          copyOriginAndAngles("canopic1_placement", "canopic1_position" )
     endif
endif
canopic2 = getGameFlag("canopic", 2 )
if canopic2 == 1
     remove ( "canopic2", "canopic2" )
     # ( "have we placed the jar in the hot tub yet?" )
     hottub2 = getGameFlag("canopic", 12 )
     if hottub2 == 1
          copyOriginAndAngles("canopic2_placement", "canopic2_position" )
     endif
endif
canopic3 = getGameFlag("canopic", 3 )
if canopic3 == 1
     remove ( "canopic3", "canopic3" )
     # ( "have we placed the jar in the hot tub yet?" )
     hottub3 = getGameFlag("canopic", 13 )
     if hottub3 == 1
          copyOriginAndAngles("canopic3_placement", "canopic3_position" )
     endif
endif
canopic4 = getGameFlag("canopic", 4 )
if canopic4 == 1
     remove ( "canopic4", "canopic4" )
     # ( "have we placed the jar in the hot tub yet?" )
     hottub4 = getGameFlag("canopic", 14 )
     if hottub4 == 1
          copyOriginAndAngles("canopic4_placement", "canopic4_position" )
     endif
endif
canopic5 = getGameFlag("canopic", 5 )
if canopic5 == 1
     act("sek_lightbeam_end", "sek_lightbeam_end" )
     act("lightbeam_light", "lightbeam_light" )
     setEnable("light_switch", "FALSE" )
endif
complete = getObjective("act5_obj_1b_b", "COMPLETE" )
if complete == 1
     remove ( "canopic_trigger", "canopic_trigger" )
     remove ( "sek_rusty_dec", "sek_rusty_dec" )
     remove ( "sek_glow_dec", "sek_glow_dec" )
     killEntitySilent("sek_wall" )
endif

