# Generated by BehavEd
# ( "comment" )
cameraShake(7.000, 2.000 )
sound (  "PLAY_SOUND", "zone_shared/fx/screen_shake", "", "" )
waittimed ( 1.500 )
killEntity("anubis_baddie1" )
act("anubite_baddie1_spawner", "anubite_baddie1_spawner" )
waittimed ( 0.750 )
killEntity("anubis_baddie2" )
act("anubite_baddie2_spawner", "anubite_baddie2_spawner" )

