# Generated by BehavEd
# ( "comment" )
cameraShake(7.000, 2.000 )
sound (  "PLAY_SOUND", "zone_shared/fx/screen_shake", "", "" )
waittimed ( 1.500 )
killEntity("anubite_hall_stat6" )
act("anubite_hall_spawner6", "anubite_hall_spawner6" )
waittimed ( 0.750 )
killEntity("anubite_hall_stat5" )
act("anubite_hall_spawner5", "anubite_hall_spawner5" )

