# Generated by BehavEd
# ( "comment" )
cameraShake(7.000, 2.000 )
sound (  "PLAY_SOUND", "zone_shared/fx/screen_shake", "", "" )
waittimed ( 1.500 )
killEntity("anubite_hall_stat1" )
act("anubite_hall_spawner1", "anubite_hall_spawner1" )
waittimed ( 0.750 )
killEntity("anubite_hall_stat2" )
act("anubite_hall_spawner2", "anubite_hall_spawner2" )

