# Generated by BehavEd
# ( "comment" )
cameraShake(7.000, 2.000 )
sound (  "PLAY_SOUND", "zone_shared/fx/screen_shake", "", "" )
waittimed ( 1.500 )
killEntity("anubite_hall_stat8" )
act("anubite_hall_spawner8", "anubite_hall_spawner8" )
waittimed ( 0.750 )
killEntity("anubite_hall_stat7" )
act("anubite_hall_spawner7", "anubite_hall_spawner7" )

