# Generated by BehavEd
# ( "comment" )
cameraShake(7.000, 2.000 )
waittimed ( 1.500 )
killEntity("anubis_baddie03" )
act("anubite_baddie1_spawner01", "anubite_baddie1_spawner01" )
waittimed ( 0.750 )
killEntity("anubis_baddie04" )
act("anubite_baddie1_spawner02", "anubite_baddie1_spawner02" )

