# Generated by BehavEd
# ( "comment" )
cameraShake(6.000, 3.000 )
waittimed ( 1.500 )
killEntity("anubis_baddie05" )
act("anubite_baddie1_spawner04", "anubite_baddie1_spawner04" )
waittimed ( 0.750 )
killEntity("anubis_baddie06" )
act("anubite_baddie1_spawner03", "anubite_baddie1_spawner03" )

