# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept46.png" )
imageViewer("textures/concept/concept47.png" )
imageViewer("textures/concept/concept48.png" )

