# Generated by BehavEd
# ( "comment" )
lockControls(0.000 )
setallaiactive("FALSE" )
# ( "camera looks at the leader coming through the door" )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
cameraMove(" 2759.520 1600.310 134.390 ", 1.000 )
cameraPan(" 0.000 33.200 165.300 ", 0.000, "FALSE" )
waittimed ( 0.500 )
cameraFade(0.000, 0.500 )
# ( "moves the players to their spots" )
# ( "but checks to see if they are alive first" )
isHero1Alive = alive("_HERO1_" )
if isHero1Alive == 1
     # ( "hero1 is alive" )
     copyOriginAndAngles("_HERO1_", "herospot01" )
else
     # ( "hero1 is dead as a doornail" )
endif
isHero2Alive = alive("_HERO2_" )
if isHero2Alive == 1
     # ( "hero2 is alive" )
     copyOriginAndAngles("_HERO2_", "herospot02" )
else
     # ( "hero2 is dead as a doornail" )
endif
isHero3Alive = alive("_HERO3_" )
if isHero3Alive == 1
     # ( "hero3 is alive" )
     copyOriginAndAngles("_HERO3_", "herospot03" )
else
     # ( "hero3 is dead as a doornail" )
endif
isHero4Alive = alive("_HERO4_" )
if isHero4Alive == 1
     # ( "hero4 is alive" )
     copyOriginAndAngles("_HERO4_", "herospot04" )
else
     # ( "hero4 is dead as a doornail" )
endif
waittimed ( 1.000 )
copyOriginAndAngles("forcefield01", "field_spot01" )
sound (  "PLAY_SOUND", "zone_shared/object/laser_wall", "", "" )
waittimed ( 1.000 )
cameraMove(" 2951.890 1590.190 150.940 ", 1.000 )
cameraPan(" 0.000 38.000 13.900 ", 0.000, "FALSE" )
waittimed ( 1.000 )
setallaiactive("TRUE" )
enemiesNoTarget("TRUE" )
heroNoTarget("TRUE" )
copyOriginAndAngles("forcefield02", "field_spot02" )
# ( "locks the players in" )
waittimed ( 1.000 )
cameraMove(" 2944.590 1724.510 195.490 ", 1.000 )
cameraPan(" 0.000 40.200 252.700 ", 1.000, "FALSE" )
act("spawner_a", "spawner_a" )
act("spawner_b", "spawner_b" )
act("spawner_c", "spawner_c" )
waittimed ( 1.000 )
killEntity("break_fence_b" )
waittimed ( 0.500 )
killEntity("break_fence_a" )
killEntity("break_fence_c" )
waittimed ( 1.000 )
cameraReset( )
waittimed ( 0.500 )
lockControls(0.100 )
heroNoTarget("FALSE" )
enemiesNoTarget("FALSE" )

