# Generated by BehavEd
# ( "comment" )
lockControls(-1.000 )
heroNoTarget("TRUE" )
enemiesNoTarget("TRUE" )
cameraMove(" 3339.810 4918.320 249.170 ", 1.000 )
cameraPan(" 0.000 28.200 101.600 ", 1.000, "FALSE" )
waittimed ( 1.500 )
startConversation("act4/pens/pens2/4_pens2_0010" )

