# Generated by BehavEd
# ( "fade out and reset camera" )
waittimed ( 0.500 )
cameraFade(1.000, 0.500 )
waittimed ( 1.000 )
cameraReset( )
waittimed ( 1.000 )
# ( "fade in and unlock controls" )
cameraFade(0.000, 1.000 )
lockControls(0.100 )
setallaiactive("TRUE" )

