# Generated by BehavEd
# ( "zone script" )
setCurrentAct(3 )
emma = getGameFlag("madri_conv", 8 )
if emma == 1
     remove ( "trigger_touch01", "trigger_touch01" )
     remove ( "door_conv", "door_conv" )
     remove ( "door_emma", "door_emma" )
     remove ( "sp_emmafrost01", "sp_emmafrost01" )
     remove ( "emma_door_clip", "emma_door_clip" )
     waittimed ( 0.500 )
     remove ( "emma", "emma" )
endif
artifacts = getObjective("act3_obj_6a_a", "COMPLETE" )
if artifacts == 1
     persist = getZoneReset( )
     if persist == 1
          act("portal_looper", "portal_looper" )
          setEnable("zone_link03", "TRUE" )
          remove ( "artifact_con", "artifact_con" )
     endif
endif

