# Generated by BehavEd
# ( "comment" )
cameraFocusToEntity("door_emma", 300.000, 45.000, 85.000, 3.000 )
setEnable("door_emma", "TRUE" )
waittimed ( 1.500 )
act("door_emma", "door_emma" )
remove ( "emma", "emma" )
waittimed ( 1.500 )
setGameFlag("madri_conv", 9, 1 )
waittimed ( 2.000 )
remove ( "emma_door_clip", "emma_door_clip" )
setallaiactive("TRUE" )
cameraReset( )

