# Generated by BehavEd
# ( "comment" )
setGameFlag("madri_conv", 8, 1 )
setallaiactive("FALSE" )
waittimed ( 0.500 )
cameraFade(1.000, 0.500 )
waittimed ( 1.000 )
cameraToLocationAngles(" 5085.440 3363.757 367.477 ", " 4818.874 3239.042 0.000 ", 0.000 )
cameraFade(0.000, 1.000 )
hero1 = alive("_HERO1_" )
if hero1 > 0
     copyOriginAndAngles("_HERO1_", "p1spot01" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     copyOriginAndAngles("_HERO2_", "p2spot01" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     copyOriginAndAngles("_HERO3_", "p3spot01" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     copyOriginAndAngles("_HERO4_", "p4spot01" )
endif
copyOriginAndAngles("emma", "p1spot05" )
startConversation("act3/madri/madri2/3_madri2_0010" )
remove ( "door_conv", "door_conv" )
objective ( "act3_obj_5",  "EOBJCMD_SHOW" )
objective ( "act3_obj_5a",  "EOBJCMD_SHOW" )
objective ( "act3_obj_5b",  "EOBJCMD_SHOW" )
objective ( "act3_obj_5c",  "EOBJCMD_SHOW" )

