# Generated by BehavEd
# ( "This script tells the player that a new briefing is avaiable" )
briefings = getGameFlag("briefings", 15 )
if briefings == 0
     setGameFlag("briefings", 15, 1 )
     newMissionBriefing( )
endif

