# Generated by BehavEd
# ( "This script tells the player that a new briefing is avaiable" )
briefings = getGameFlag("briefings", 14 )
if briefings == 0
     setGameFlag("briefings", 14, 1 )
     newMissionBriefing( )
endif

