# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept07.png" )
imageViewer("textures/concept/concept08.png" )
imageViewer("textures/concept/concept09.png" )

