# Generated by BehavEd
# ( "This script tells the player that a new briefing is avaiable" )
briefings = getGameFlag("briefings", 18 )
if briefings == 0
     setGameFlag("briefings", 18, 1 )
     newMissionBriefing( )
endif

