# Generated by BehavEd
# ( "comment" )
drone_convo = getGameFlag("tunnels", 6 )
if drone_convo == 0
     setGameFlag("tunnels", 6, 1 )
     setallaiactive("FALSE" )
     lockControls(0.000 )
     # ( "This makes sure that the drones show up" )
     act("drone01", "drone01" )
     act("drone02", "drone02" )
     waittimed ( 0.500 )
     cameraMove(" 2631.000 8593.000 165.000 ", 2.000 )
     cameraPan(" 0.000 29.400 2.700 ", 2.000, "FALSE" )
     waittimed ( 2.000 )
     setallaiactive("TRUE" )
     lockControls(0.100 )
     objective ( "act1_drones",  "EOBJCMD_SHOW" )
     startConversation("act1/insect/insect1/1_INSECT1_0030" )
endif

