# Generated by BehavEd
# ( "comment" )
objective ( "act1_drones",  "EOBJCMD_INCREMENT" )
setGameFlag("tunnels", 20, 1 )
drones_downed = getObjective("act1_drones", "COUNT" )
if drones_downed == 12
     objective ( "act1_drones",  "EOBJCMD_COMPLETE" )
     spawn("_ACTIVATOR_", "beacon", "bacon", " 0.000 0.000 10.000 ", " 0.000 0.000 0.000 " )
     startConversation("act1/insect/insect1/1_INSECT1_0040" )
endif

