# Generated by BehavEd
# ( "is this the first visit to an insect tunnel?  either insect1 or insect4" )
visit = getGameFlag("tunnels", 23 )
if visit == 0
     # ( "this is the first visit to either insect1 or insect4--run conversation" )
     startConversation("act1/1_sometimeact1_0015" )
     # ( "indicate an insect tunnel has been visited" )
     setGameFlag("tunnels", 23, 1 )
endif
# ( "This script is unbreakable! ...written by Sean" )
# ( "checks completeness of the miniquest" )
# ( "if complete, removes all drones and doesn't check them" )
dronechk = getObjective("act1_drones", "COMPLETE" )
if dronechk == 1
     # ( "checks if homing beacon was grabbed" )
     gotbeacon = getGameFlag("tunnels", 1 )
     if gotbeacon == 0
          # ( "spawns HB if needed" )
          remove ( "bacon", "bacon" )
          spawn("hblocation", "beacon", "bacon", " 0.000 0.000 10.000 ", " 0.000 0.000 0.000 " )
     endif
     # ( "Need to wait to give the spawners time to appear" )
     waittimed ( 0.500 )
     # ( "This should remove all monsters name drones" )
     remove ( "drones", "drones" )
else
     # ( "if the drone conversation hasn't happened, don't bother checking drones" )
     dronechk1 = getGameFlag("tunnels", 6 )
     if dronechk1 == 1
          dronechk1 = getGameFlag("tunnels", 11 )
          if dronechk1 == 1
               remove ( "drone01", "drone01" )
          endif
          dronechk1 = getGameFlag("tunnels", 12 )
          if dronechk1 == 1
               remove ( "drone02", "drone02" )
          endif
          dronechk1 = getGameFlag("tunnels", 13 )
          if dronechk1 == 1
               remove ( "drone03", "drone03" )
          endif
          dronechk1 = getGameFlag("tunnels", 14 )
          if dronechk1 == 1
               remove ( "drone04", "drone04" )
          endif
          dronechk1 = getGameFlag("tunnels", 15 )
          if dronechk1 == 1
               remove ( "drone05", "drone05" )
          endif
          dronechk1 = getGameFlag("tunnels", 16 )
          if dronechk1 == 1
               remove ( "drone06", "drone06" )
          endif
          dronechk1 = getGameFlag("tunnels", 17 )
          if dronechk1 == 1
               remove ( "drone07", "drone07" )
          endif
          dronechk1 = getGameFlag("tunnels", 18 )
          if dronechk1 == 1
               remove ( "drone08", "drone08" )
          endif
          dronechk1 = getGameFlag("tunnels", 19 )
          if dronechk1 == 1
               remove ( "drone09", "drone09" )
          endif
          dronechk1 = getGameFlag("tunnels", 20 )
          if dronechk1 == 1
               remove ( "drone10", "drone10" )
          endif
          dronechk1 = getGameFlag("tunnels", 21 )
          if dronechk1 == 1
               remove ( "drone11", "drone11" )
          endif
          dronechk1 = getGameFlag("tunnels", 22 )
          if dronechk1 == 1
               remove ( "drone12", "drone12" )
          endif
     endif
endif

