# Generated by BehavEd
# ( "remove bridge puzzle" )
remove ( "bridgeclip10", "bridgeclip10" )
remove ( "bridgeclip09", "bridgeclip09" )
remove ( "bridge_trigger07", "bridge_trigger07" )
remove ( "bridgeclip2", "bridgeclip2" )
act("bridgeclip5", "bridgeclip5" )
act("bridgeclip6", "bridgeclip6" )

