# Generated by BehavEd
# ( "remove bridge puzzle" )
remove ( "bridge_trigger03", "bridge_trigger03" )
remove ( "bridgeclip3", "bridgeclip3" )
remove ( "bridgeclip1", "bridgeclip1" )
remove ( "bridgeclip08", "bridgeclip08" )
act("bridgeclip4", "bridgeclip4" )
act("bridgeclip7", "bridgeclip7" )

