# Generated by BehavEd
# ( "set current act and show main objective" )
setCurrentAct(1 )
setGameFlag("act1_visit", 2, 1 )
setEnable("2nd_objective", "FALSE" )
blah02 = getGameFlag("deadzone", 8 )
if blah02 == 1
     remove ( "relay_post_griz_cine", "relay_post_griz_cine" )
     remove ( "zone_exit_web_dead_e_dz01", "zone_exit_web_dead_e_dz01" )
else
     blah01 = getGameFlag("bosses", 2 )
     if blah01 == 1
          act("relay_post_griz_cine", "relay_post_griz_cine" )
          setGameFlag("deadzone", 8, 1 )
          remove ( "security_device_griz", "security_device_griz" )
          remove ( "sp_grizzly02", "sp_grizzly02" )
          remove ( "sp_grizzly01", "sp_grizzly01" )
          remove ( "trigger_grizzly01", "trigger_grizzly01" )
          remove ( "trigger_touch02", "trigger_touch02" )
          remove ( "harm_jet", "harm_jet" )
          remove ( "trigger_touch02", "trigger_touch02" )
          remove ( "fuel_cell", "fuel_cell" )
          remove ( "jet_effect", "jet_effect" )
          remove ( "loop_firewall", "loop_firewall" )
          remove ( "jet_effect01", "jet_effect01" )
          remove ( "lightent01", "lightent01" )
     endif
endif
sec_2 = getObjective("act1_obj_2a", "COMPLETE" )
if sec_2 == 1
     remove ( "security_device_dead_a_dz01", "security_device_dead_a_dz01" )
endif
reseter = getGameFlag("deadzone", 9 )
if reseter == 1
     remove ( "trigger_grizzly01", "trigger_grizzly01" )
endif
reseter = getGameFlag("deadzone", 10 )
if reseter == 1
     remove ( "trigger_griz_02", "trigger_griz_02" )
     reseter = getZoneReset( )
     if reseter == 1
          act("jet_effect", "jet_effect" )
          act("jet_effect01", "jet_effect01" )
          act("lightent01", "lightent01" )
          setEnable("fuel_cell", "TRUE" )
          reseter = getGameFlag("deadzone", 16 )
          if reseter == 1
               act("lightent01", "lightent01" )
          endif
     endif
endif
missiles = getObjective("radardish", "COMPLETE" )
if missiles == 1
     remove ( "missiles2_1", "missiles2_1" )
     remove ( "missiles2_2", "missiles2_2" )
     remove ( "missiles2_3", "missiles2_3" )
endif
fuelgone = getGameFlag("deadzone", 16 )
if fuelgone == 1
     setEnable("link_deadzone3", "TRUE" )
     waittimed ( 0.250 )
     remove ( "harm_jet", "harm_jet" )
     remove ( "fuel_cell", "fuel_cell" )
     remove ( "jet_effect", "jet_effect" )
     remove ( "jet_effect01", "jet_effect01" )
endif
grizzdev = getGameFlag("deadzone", 17 )
if grizzdev == 1
     remove ( "security_device_griz", "security_device_griz" )
endif
grizzdev = getGameFlag("deadzone", 18 )
if grizzdev == 1
     remove ( "secdev2", "secdev2" )
endif

