# Generated by BehavEd
# ( "run from the pre-overload console" )
overrideIsOff = getObjective("act3_obj_3a_a", "COMPLETE" )
if overrideIsOff == 0
     # ( "since the override is off, play the conversation telling the player to" )
     # ( "go fix the override" )
     startConversation("act3/infinite/infinite2/3_INFINITE2_0016" )
else
     act("gen_talk", "gen_talk" )
endif
# ( "we've had the pre_overload conv so enable pre_module or post_module" )
# ( "based on whether or not you have the decryption module (protocols flag 3)" )
module = getGameFlag("protocols", 3 )
if module == 1
     setEnable("post_module", "TRUE" )
else
     setEnable("pre_module", "TRUE" )
endif

