# Generated by BehavEd
# ( "comment" )
isObjectiveHidden = getGameFlag("protocols", 15 )
if isObjectiveHidden == 0
     # ( "thingy isn't enabled yet" )
     allowConversation("TRUE" )
else
     # ( "thingy has been enabled" )
     allowConversation("FALSE" )
endif

