# Generated by BehavEd
# ( "signal that decryption module has been used" )
setGameFlag("protocols", 6, 1 )
# ( "open door, remove triggers" )
act("module_door", "module_door" )
remove ( "pre_module", "pre_module" )
remove ( "post_module", "post_module" )

