# Generated by BehavEd
# ( "the overload now happens after visiting pre_overload the second time - Oz 2/28/05" )
# ( "====================" )
# ( "prepare safety override" )
remove ( "gen_powerup_trigger", "gen_powerup_trigger" )
setEnable("pre_overload", "TRUE" )
# ( "update objectives" )
objective ( "act3_obj_3a_a",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_3a_b",  "EOBJCMD_SHOW" )

