# Generated by BehavEd
# ( "comment" )
teleport = getGameFlag("protocols", 18 )
if teleport == 0
     startConversation("act3/infinite/infinite2/3_infinite2_0050" )
     setGameFlag("protocols", 18, 1 )
endif

