# Generated by BehavEd
# ( "comment" )
setReactToEnemies("_OWNER_", "FALSE" )
waittimed ( 0.100 )
setAIActive("_OWNER_", "FALSE" )
setNoCollide("_OWNER_", "TRUE" )
setInvulnerable("_OWNER_", "TRUE" )
setInvisible("_OWNER_", "FALSE" )
setReactToEnemies("_OWNER_", "TRUE" )
playanim (  "EA_ZONE2", "_OWNER_", "LOOP", "" )

