# Generated by BehavEd
# ( "intermittent freeze jet puzzle" )
setGameFlag("inf4_traps", 2, 1 )
act("door_counter", "door_counter" )
remove ( "freezejet_01", "freezejet_01" )
remove ( "freezejet_relay", "freezejet_relay" )
# ( "This disables the machinery" )
objective ( "act3_obj_3d_a",  "EOBJCMD_INCREMENT" )

