# Generated by BehavEd
# ( "intermittent flame jet puzzle" )
setGameFlag("inf4_traps", 4, 1 )
act("door_counter", "door_counter" )
remove ( "zapper_01", "zapper_01" )
remove ( "firejet_nav_blocker", "firejet_nav_blocker" )
# ( "This disables the machinery" )
objective ( "act3_obj_3d_a",  "EOBJCMD_INCREMENT" )

