# Generated by BehavEd
# ( "intermittent freeze jet puzzle" )
setGameFlag("inf4_traps", 3, 1 )
act("door_counter", "door_counter" )
remove ( "freezejet_02", "freezejet_02" )
remove ( "freezejet_nav_blocker01", "freezejet_nav_blocker01" )
remove ( "freezejet_relay2", "freezejet_relay2" )
objective ( "act3_obj_3d_a",  "EOBJCMD_INCREMENT" )

