# Generated by BehavEd
# ( "intermittent zapper puzzle" )
setGameFlag("inf4_traps", 1, 1 )
act("door_counter", "door_counter" )
remove ( "zapper_02", "zapper_02" )
remove ( "zapper_nav_blocker", "zapper_nav_blocker" )
# ( "This disables the machinery" )
setEnable("zap_inf_a_ip01", "FALSE" )
setEnable("zap_inf_a_ip02", "FALSE" )
objective ( "act3_obj_3d_a",  "EOBJCMD_INCREMENT" )

