# Generated by BehavEd
# ( "This script call tells the player that a new briefing is avaiable" )
briefings = getGameFlag("briefings", 6 )
if briefings == 0
     setGameFlag("briefings", 6, 1 )
     newMissionBriefing( )
endif

