# Generated by BehavEd
# ( "deadpool spawn script" )
# ( "check if we've met deadpool and don't have him do his intro stuff if we already have met him" )
metdp = getGameFlag("bosses", 24 )
if metdp != 1
     setAIActive("_OWNER_", "FALSE" )
     setNoClip("_OWNER_", "TRUE" )
     playanim (  "EA_ZONE1", "_OWNER_", "NONE", "jumped" )
     waitsignal ( "jumped" )
     setNoClip("_OWNER_", "FALSE" )
endif

