# Generated by BehavEd
# ( "death to deadpool" )
# ( "set flag to keep track of whether or not he was defeated" )
setDefaultTarget("" )
remove ( "arena_trigger", "arena_trigger" )
setGameFlag("bosses", 25, 1 )
setEnable("link_sewers3", "TRUE" )
objective ( "act4_obj_4b",  "EOBJCMD_COMPLETE" )
objective ( "act4_obj_4c",  "EOBJCMD_SHOW" )

