# Generated by BehavEd
# ( "enter the deadpool arena" )
setWaypointPath("deadpool", "", 0 )
setRecallActive("FALSE" )
setEngageEnemy("deadpool", "TRUE" )
setDefaultTarget("deadpool" )
attackEntityWithType("deadpool", "_ACTIVE_HERO_", "ANY", "FALSE" )

