# Generated by BehavEd
# ( "newyork5 zone script" )
deadpool = getObjective("act4_obj_4a", "HIDDEN" )
if deadpool == 0
     setEnable("dp_trigger", "TRUE" )
endif
# ( "check if we've met deadpool and set up the scene if we have" )
metdp = getGameFlag("bosses", 24 )
if metdp == 1
     remove ( "subway_explode", "subway_explode" )
     remove ( "dp_trigger", "dp_trigger" )
     # ( "check if we've BEAT deadpool and spawn him in if we haven't" )
     beatdp = getGameFlag("bosses", 25 )
     if beatdp == 1
          setEnable("link_sewers3", "TRUE" )
          setNoCollide("subway_explode", "TRUE" )
          actSilent("subway_explode", "subway_explode" )
     else
          act("sp_deadpool01", "sp_deadpool01" )
          setEnable("arena_trigger", "TRUE" )
     endif
endif

