# Generated by BehavEd
# ( "Script to run if player cancels a mission briefing from Sanctuary" )
cameraFade(1.000, 0.010 )
waittimed ( 0.020 )
lockControls(0.100 )
loadZone("act3/military/military1", "link_core_briefing" )

