# Generated by BehavEd
# ( "spawnscript for extraction points" )
unlocked = isExtractionPointUnlocked( )
if unlocked == 1
     # ( "already unlocked, turn this puppy on" )
     act("_OWNER_", "_OWNER_" )
else
     id = spawn("_OWNER_", "expt_trig", "expt_trig", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     setParent(id, "_OWNER_" )
endif

