# Generated by BehavEd
# ( "comment" )
# ( "defeated Stryfe" )
objective ( "act4_obj_3b",  "EOBJCMD_COMPLETE" )
# ( "destroyed Brain Trust" )
objective ( "act4_obj_3a",  "EOBJCMD_COMPLETE" )
# ( "return to mansion and talk to Banshee" )
objective ( "act4_obj_3c",  "EOBJCMD_SHOW" )

