# Generated by BehavEd
# ( "brain dies" )
sound (  "PLAY_SOUND", "boss_battles/stryfe/brain_dead", "", "" )
alive = alive("stryfe" )
deadbrains = getZoneVar("deadbrains" )
deadbrains = iadd(deadbrains, 1 )
setZoneVar("deadbrains", deadbrains )
if deadbrains >= 6
     if alive == 1
          playBossSound("voice/stryfe/kill_all_tanks", 0, 5.000 )
     endif
     objective ( "act4_obj_3a",  "EOBJCMD_COMPLETE" )
     act("stryfe_outro", "stryfe_outro" )
else
     if alive == 1
          playBossSound("voice/stryfe/kill_tank", 0, 5.000 )
     endif
endif

