# Generated by BehavEd
# ( "Set var at end of Cold Sore's monologue" )
cameraResetOldSchool( )
setEnable("stryfe_door", "FALSE" )
setDefaultTarget("stryfe" )
setAIActive("stryfe", "TRUE" )
act("BrainDemon01", "BrainDemon01" )
act("BrainDemon02", "BrainDemon02" )

