# Generated by BehavEd
# ( "When Cold Sore sees the X-Men he starts his monologue" )
act("stryfe_door", "stryfe_door" )
# ( "set objective -- defeat Stryfe" )
objective ( "act4_obj_3b",  "EOBJCMD_SHOW" )
copyOriginAndAngles("_HERO1_", "herospot01" )
copyOriginAndAngles("_HERO2_", "herospot02" )
copyOriginAndAngles("_HERO3_", "herospot03" )
copyOriginAndAngles("_HERO4_", "herospot04" )
cameraMove(" 2844.460 6560.860 111.089 ", 0.000 )
cameraPan(" 0.000 17.155 115.321 ", 0.000, "FALSE" )

