# Generated by BehavEd
# ( "if player has Mirrin card" )
mirrin_card_1 = getGameFlag("mirrin", 1 )
if mirrin_card_1 == 1
     startConversation("act4/pens/pens3/4_pens3_0041" )
     setEnable("Brain_Extraction_Control_Panel", "FALSE" )
else
     startConversation("act4/pens/pens3/4_pens3_0050" )
     setHintType("Merrin", "OBJECTIVE" )
endif

