# Generated by BehavEd
# ( "demon buddy access" )
lenzir_card_1 = getGameFlag("lenzir", 1 )
if lenzir_card_1 == 1
     setEnable("Psy_Panel", "FALSE" )
     setEnable("Brain_Test_Panel", "TRUE" )
     act("test_glow02", "test_glow02" )
     act("test_glow01", "test_glow01" )
     setGameFlag("test_brain", 1, 1 )
     startConversation("act4/pens/pens3/4_pens3_0070" )
else
     startConversation("act4/pens/pens3/4_pens3_0072" )
endif

