# Generated by BehavEd
# ( "if player has Lenzir and Schill vars he can access console 2" )
schill_card_1 = getGameFlag("schill", 1 )
if schill_card_1 == 1
     startConversation("act4/pens/pens3/4_pens3_0040" )
     setEnable("Pupae_Control", "FALSE" )
     remove ( "prison_forcefield_02_bred_e_bp01", "prison_forcefield_02_bred_e_bp01" )
     remove ( "prison_forcefield_02_bred_e_bp02", "prison_forcefield_02_bred_e_bp02" )
else
     startConversation("act4/pens/pens3/4_pens3_0051" )
     setHintType("Schill", "OBJECTIVE" )
endif

