# Generated by BehavEd
# ( "enter the stryfe arena" )
setWaypointPath("stryfe", "", 0 )
setInvulnerable("stryfe", "FALSE" )
setRecallActive("FALSE" )
setEngageEnemy("stryfe", "TRUE" )
setPatternSequence("stryfe", "start" )
setDefaultTarget("stryfe" )

