# Generated by BehavEd
# ( "If Schill dies set zone var schill to 1 and show pop-up dialogue informing player that he gained his access card" )
setGameFlag("lenzir", 1, 1 )
startConversation("act4/pens/pens3/4_pens3_0040a" )

