# Generated by BehavEd
# ( "leave the stryfe arena" )
setRecallActive("TRUE" )
setEngageEnemy("stryfe", "FALSE" )
setWaypointPath("stryfe", "stryfehome", 1 )
setDefaultTarget("" )
setInvulnerable("stryfe", "TRUE" )

