# Generated by BehavEd
# ( "Load script for pens3" )
# ( "check if brains have all been defeated" )
cameraFade(0.000, 1.000 )
checkBrains = getObjective("act4_obj_3a", "COMPLETE" )
if checkBrains == 1
     setZoneVar("deadbrains", 6 )
     setEnable("stryfe_outro", "FALSE" )
     waittimed ( 0.100 )
     setEnable("stryfe_outro", "TRUE" )
else
     setHintType("Brain_1", "objective" )
     setHintType("Brain_2", "objective" )
     setHintType("Brain_3", "objective" )
     setHintType("Brain_4", "objective" )
     setHintType("Brain_5", "objective" )
     setHintType("Brain_6", "objective" )
endif
# ( "check if stryfe is dead" )
stryfedead = getGameFlag("bosses", 23 )
if stryfedead == 1
     swapInStump("Brain_1" )
     swapInStump("Brain_2" )
     swapInStump("Brain_3" )
     swapInStump("Brain_4" )
     swapInStump("Brain_5" )
     swapInStump("Brain_6" )
     remove ( "stryfe_trigger", "stryfe_trigger" )
endif
banpen = getGameFlag("banholo", 1 )
if banpen == 0
     waittimed ( 1.000 )
     lockControls(-1.000 )
     heroNoTarget("TRUE" )
     enemiesNoTarget("TRUE" )
     cameraMove(" 2751.180 1326.450 146.270 ", 1.000 )
     cameraPan(" 0.000 31.700 73.500 ", 1.000, "FALSE" )
     waittimed ( 1.000 )
     setPartyLightColor(" 0.000 0.000 0.000 ", 0.500 )
     act("holo_glow", "holo_glow" )
     waittimed ( 0.250 )
     act("banshee", "banshee" )
     waittimed ( 0.250 )
     setGameFlag("banholo", 1, 1 )
     startConversation("act4/pens/pens3/4_pens3_0001" )
endif
if banpen == 1
     remove ( "prison_forcefield_02_bred_e_bp04", "prison_forcefield_02_bred_e_bp04" )
     remove ( "banshee", "banshee" )
     remove ( "clip_sinister01", "clip_sinister01" )
     remove ( "holo_glow", "holo_glow" )
endif

