# Generated by BehavEd
# ( "Spawns PsychicDemon_c near test console" )
act("psy_buddy", "psy_buddy" )
sound (  "PLAY_SOUND", "boss_battles/stryfe/spawn_creature", "", "" )
waittimed ( 0.250 )
setAIActive("psy_buddy1", "TRUE" )
setEngageEnemy("psy_buddy1", "TRUE" )
beATeamPlayer("psy_buddy1", "TRUE" )
setCanMove("psy_buddy1", "TRUE" )
objective ( "psychic_demon",  "EOBJCMD_COMPLETE" )

