# Generated by BehavEd
# ( "This script checks of the puzzle has been solve and if so it shows the open door" )
# ( "The heart game var is used decide what camera to use" )
chamber_door1 = getOpened("door_chamber_a01" )
chamber_door2 = getOpened("door_chamber_b01" )
chamber_door3 = getOpened("door_chamber_c01" )
chamber_door4 = getOpened("door_chamber_d01" )
if chamber_door1 == 1
     cameraToLocationAngles(" 4854.000 5685.000 344.000 ", " 4854.000 5613.000 275.000 ", 0.000 )
elif chamber_door2 == 1
     cameraToLocationAngles(" 5690.000 4879.000 323.000 ", " 5616.000 4878.000 256.000 ", 0.000 )
elif chamber_door3 == 1
     cameraToLocationAngles(" 4862.000 4150.000 263.000 ", " 4863.000 4227.000 200.000 ", 0.000 )
elif chamber_door4 == 1
     cameraToLocationAngles(" 4127.000 4855.000 307.000 ", " 4199.000 4857.000 237.000 ", 0.000 )
else
     debug("ERROR: The puzzle has been solve, but the camera wasn't set" )
endif
waittimed ( 8.000 )
cameraReset( )

