# Generated by BehavEd
# ( "comment" )
setallaiactive("TRUE" )
lockControls(0.100 )
# ( "This recloses the doors" )
act("door_chamber_b01", "door_chamber_b01" )
act("door_chamber_b02", "door_chamber_b02" )
cameraReset( )

