# Generated by BehavEd
# ( "sugarman death" )
dr = getDangerRoomActive( )
if dr == 1
     setDangerRoomSuccess( )
else
     objective ( "act3_obj_2f_a",  "EOBJCMD_COMPLETE" )
     setDefaultTarget("" )
     setGameFlag("bosses", 16, 1 )
     waittimed ( 4.000 )
     setEnable("big_red_button", "TRUE" )
     startConversation("act3/corein/corein4/3_corein4_0220" )
endif

