# Generated by BehavEd
# ( "zonescript, corein4" )
beatboss = getGameFlag("bosses", 16 )
if beatboss == 1
     remove ( "sugarman_trigger", "sugarman_trigger" )
     remove ( "arena_trigger", "arena_trigger" )
     corecomplete = getObjective("act3_obj_2f", "COMPLETE" )
     if corecomplete == 0
          setEnable("big_red_button", "TRUE" )
     else
          act("portal_loop", "portal_loop" )
          setEnable("link_military1", "TRUE" )
     endif
else
endif
pumpquest = getGameFlag("coolpumps", 3 )
if pumpquest == 0
     setGameFlag("coolpumps", 3, 1 )
else
     coolpumps1 = getGameFlag("coolpumps", 1 )
     coolpumps2 = getGameFlag("coolpumps", 2 )
     if coolpumps1 == 1
          copyOriginAndAngles("cool_tank_fake01", "cool_tank01" )
          remove ( "cool_tank01", "cool_tank01" )
          killEntity("cool_tank_fake01" )
     endif
     if coolpumps2 == 1
          copyOriginAndAngles("cool_tank_fake02", "cool_tank02" )
          remove ( "cool_tank02", "cool_tank02" )
          killEntity("cool_tank_fake02" )
     endif
endif
setGameFlag("act3_visit", 4, 1 )
# ( "check the sugarman door" )
doorcheck = getObjective("act3_obj_2e", "COMPLETE" )
if doorcheck == 1
     act("sugardoor", "sugardoor" )
endif

