# Generated by BehavEd
# ( "enter the omega red arena" )
setRecallActive("FALSE" )
setWaypointPath("sugarman", "", 0 )
setEngageEnemy("sugarman", "TRUE" )
setDefaultTarget("sugarman" )
attackEntityWithType("sugarman", "_ACTIVE_HERO_", "ANY", "FALSE" )

