# Generated by BehavEd
# ( "removes fake walls covering secret" )
display ( "Ignore the dropping screen, testing opening secret area." )
remove ( "remov_clip01", "remov_clip01" )
remove ( "T_ontariocore_B2C_W_A0", "T_ontariocore_B2C_W_A0" )
setEnable("hidden_door", "TRUE" )
act("secretscreen_01", "secretscreen_01" )

