# Generated by BehavEd
# ( "done talkin to sugarman" )
cameraResetOldSchool( )
dractive = getDangerRoomActive( )
if dractive == 0
     objective ( "act3_obj_2f_a",  "EOBJCMD_SHOW" )
     setEnable("arena_trigger", "TRUE" )
     setDefaultTarget("sugarman" )
     objective ( "act3_obj_2f_a",  "EOBJCMD_SHOW" )
endif

