# Generated by BehavEd
# ( "check if both blue reactor rods have been lowered" )
setEnable("b_master", "FALSE" )
bluereactors = getGameFlag("corestatus", 1 )
setGameFlag("corestatus", 3, 1 )
if bluereactors == 1
     # ( "act on sector_count" )
     # ( "complete the 'Activate' objective" )
     objective ( "act3_obj_2d_1",  "EOBJCMD_COMPLETE" )
     act("sector_count", "sector_count" )
     objective ( "act3_obj_2d",  "EOBJCMD_COMPLETE" )
     yellow_complete = getObjective("act3_obj_2c_1", "COMPLETE" )
     if yellow_complete == 0
          # ( "Finished blue, yellow not complete" )
          startConversation("act3/corein/corein3/3_corein3_0020" )
     else
          # ( "Finished blue, yellow complete" )
          # ( "fade out, lock controls, set camera" )
          cameraFade(1.000, 0.500 )
          waittimed ( 0.500 )
          lockControls(-1.000 )
          setallaiactive("FALSE" )
          # ( "move camera" )
          cameraToLocationAngles(" 2820.000 700.000 236.000 ", " 2820.000 850.000 1.000 ", 0.000 )
          cameraFocusToEntity("cam_targ", 300.000, 45.000, 155.000, 0.000 )
          cameraFocusToEntity("cam_targ", 300.000, 45.000, 205.000, 2.000 )
          # ( "fade in" )
          cameraFade(0.000, 0.500 )
          waittimed ( 1.000 )
          # ( "open magdoors" )
          act("magdoor", "magdoor" )
          setGameFlag("corestatus", 8, 1 )
          # ( "start conversation" )
          waittimed ( 1.000 )
          startConversation("act3/corein/corein3/3_corein3_0910" )
          objective ( "act3_obj_2e",  "EOBJCMD_SHOW" )
     endif
else
     # ( "activate b_radiation" )
     setEnable("b_radiation", "TRUE" )
     act("b_radiation", "b_radiation" )
     startConversation("act3/corein/corein3/3_corein3_0900" )
endif

