# Generated by BehavEd
# ( "remove harm_target b_radiation" )
remove ( "b_radiation", "b_radiation" )
# ( "signal blue sector rods have been lowered" )
objective ( "act3_obj_2d_1",  "EOBJCMD_SHOW" )
setGameFlag("corestatus", 1, 1 )
blue_master = getGameFlag("corestatus", 3 )
if blue_master == 0
     setHintType("b_master", "objective" )
     startConversation("act3/corein/corein3/3_corein3_0040" )
else
     act("sector_count", "sector_count" )
     yellow_complete = getObjective("act3_obj_2c_1", "COMPLETE" )
     if yellow_complete == 0
          # ( "Finished blue, yellow not complete" )
          startConversation("act3/corein/corein3/3_corein3_0050" )
          objective ( "act3_obj_2d_1",  "EOBJCMD_COMPLETE" )
     else
          # ( "Finished blue, yellow complete" )
          # ( "fade out, lock controls, set camera" )
          cameraFade(1.000, 0.500 )
          waittimed ( 0.500 )
          lockControls(-1.000 )
          setallaiactive("FALSE" )
          # ( "move camera" )
          cameraToLocationAngles(" 2820.000 700.000 236.000 ", " 2820.000 850.000 1.000 ", 0.000 )
          # ( "fade in" )
          cameraFade(0.000, 0.500 )
          waittimed ( 1.000 )
          # ( "open magdoors" )
          act("magdoor", "magdoor" )
          # ( "start conversation" )
          waittimed ( 1.000 )
          startConversation("act3/corein/corein3/3_corein3_0910" )
          objective ( "act3_obj_2d_1",  "EOBJCMD_COMPLETE" )
          objective ( "act3_obj_2e",  "EOBJCMD_SHOW" )
     endif
endif

