# Generated by BehavEd
# ( "check if both sectors complete" )
setGameFlag("act3_visit", 3, 1 )
sectorcheck = getGameFlag("corestatus", 7 )
if sectorcheck == 1
     remove ( "magdoor", "magdoor" )
     # ( "remove harm_targets" )
     remove ( "b_radiation", "b_radiation" )
     remove ( "y_radiation", "y_radiation" )
     # ( "make sure reactor rods are lowered" )
     act("b1reactor", "b1reactor" )
     act("b2reactor", "b2reactor" )
     act("y1reactor", "y1reactor" )
     act("y2reactor", "y2reactor" )
     # ( "disable reactor rod controls" )
     setEnable("b1rod_control", "FALSE" )
     setEnable("b2rod_control", "FALSE" )
     setEnable("y1rod_control", "FALSE" )
     setEnable("y2rod_control", "FALSE" )
     # ( "disable master controls" )
     setEnable("b_master", "FALSE" )
     setEnable("y_master", "FALSE" )
else
     # ( "checks the various reactors" )
     blue_done = getObjective("act3_obj_2d_1", "COMPLETE" )
     if blue_done == 1
          remove ( "b_radiation", "b_radiation" )
          act("b1reactor", "b1reactor" )
          act("b2reactor", "b2reactor" )
          setHintType("b_master", "objective" )
          setEnable("b1rod_control", "FALSE" )
          setEnable("b2rod_control", "FALSE" )
          setEnable("b_master", "FALSE" )
     else
          sectorcheck = getGameFlag("coolpumps", 4 )
          sectorcheck1 = getGameFlag("coolpumps", 5 )
          if sectorcheck == 1
               act("b1reactor", "b1reactor" )
               setEnable("b1rod_control", "FALSE" )
               # ( "if both rods are dropped, enable the master control" )
               if sectorcheck1 == 1
                    setEnable("b_master", "TRUE" )
               endif
          endif
          if sectorcheck1 == 1
               act("b2reactor", "b2reactor" )
               setEnable("b2rod_control", "FALSE" )
          endif
     endif
     yellow_done = getObjective("act3_obj_2c_1", "COMPLETE" )
     if yellow_done == 1
          remove ( "y_radiation", "y_radiation" )
          act("y1reactor", "y1reactor" )
          act("y2reactor", "y2reactor" )
          setHintType("y_master", "objective" )
          setEnable("y1rod_control", "FALSE" )
          setEnable("y2rod_control", "FALSE" )
          setEnable("y_master", "FALSE" )
     else
          sectorcheck = getGameFlag("coolpumps", 6 )
          sectorcheck1 = getGameFlag("coolpumps", 7 )
          if sectorcheck == 1
               act("y1reactor", "y1reactor" )
               setEnable("y1rod_control", "FALSE" )
               # ( "if both rods are dropped, enable the master control" )
               if sectorcheck1 == 1
                    setEnable("y_master", "TRUE" )
               endif
          endif
          if sectorcheck1 == 1
               act("y2reactor", "y2reactor" )
               setEnable("y2rod_control", "FALSE" )
          endif
     endif
endif
# ( "see if door is open and if it isn't, then it open it" )
is_door_open = getGameFlag("corestatus", 8 )
if is_door_open == 1
     remove ( "magdoor", "magdoor" )
endif

