# Generated by BehavEd
# ( "check if both yellow reactor rods have been lowered" )
setEnable("y_master", "FALSE" )
yellowreactors = getGameFlag("corestatus", 2 )
setGameFlag("corestatus", 4, 1 )
if yellowreactors == 1
     # ( "act on sector_count" )
     # ( "complete the 'Activate' objective" )
     objective ( "act3_obj_2c_1",  "EOBJCMD_COMPLETE" )
     act("sector_count", "sector_count" )
     objective ( "act3_obj_2c",  "EOBJCMD_COMPLETE" )
     blue_complete = getObjective("act3_obj_2d_1", "COMPLETE" )
     if blue_complete == 0
          # ( "Finished yellow, blue not complete" )
          startConversation("act3/corein/corein3/3_corein3_0120" )
     else
          # ( "Finished yellow, blue complete" )
          # ( "fade out, lock controls, set camera" )
          cameraFade(1.000, 0.500 )
          waittimed ( 0.500 )
          lockControls(-1.000 )
          setallaiactive("FALSE" )
          # ( "move camera" )
          cameraToLocationAngles(" 2820.000 700.000 236.000 ", " 2820.000 850.000 1.000 ", 0.000 )
          cameraFocusToEntity("cam_targ", 300.000, 45.000, 155.000, 0.000 )
          cameraFocusToEntity("cam_targ", 300.000, 45.000, 205.000, 2.000 )
          # ( "fade in" )
          cameraFade(0.000, 0.500 )
          waittimed ( 1.000 )
          # ( "open magdoors" )
          act("magdoor", "magdoor" )
          setGameFlag("corestatus", 8, 1 )
          # ( "start conversation" )
          waittimed ( 1.000 )
          startConversation("act3/corein/corein3/3_corein3_0910" )
          objective ( "act3_obj_2e",  "EOBJCMD_SHOW" )
     endif
else
     # ( "activate y_radiation" )
     setEnable("y_radiation", "TRUE" )
     act("y_radiation", "y_radiation" )
     startConversation("act3/corein/corein3/3_corein3_0900" )
endif

