# Generated by BehavEd
# ( "run conversation when prisoner reaches waypoint" )
setWaypointPath("prisoner", "", 0 )
waittimed ( 0.100 )
faceEntity("prisoner", "_ACTIVE_HERO_" )
startConversation("act1/insect/insect3/1_insect3_0060" )

