# Generated by BehavEd
# ( "This script figures out of the player has met Zealot yet and which script to called next" )
zealot_first_visit = getGameFlag("tunnels", 28 )
if zealot_first_visit == 0
     # ( "Show Zealot objective" )
     objective ( "act1_obj_3b",  "EOBJCMD_SHOW" )
     setGameFlag("tunnels", 28, 1 )
endif
# ( "if which_spot is 0  then the player has encountered Zealot outside the boss battle area" )
which_spot = getGameFlag("tunnels", 29 )
objective ( "act1_obj_3",  "EOBJCMD_SHOW" )
objective ( "act1_obj_3b",  "EOBJCMD_SHOW" )
if which_spot == 0
     # ( "This activates a trigger that calls the zealot_intro_finish script" )
     act("trigger_zealot_intro_finish", "trigger_zealot_intro_finish" )
     setGameFlag("tunnels", 29, 1 )
else
     # ( "This activates a  trigger that calls the zealot_again_finish script" )
     act("trigger_zealot_again_finish", "trigger_zealot_again_finish" )
     setGameFlag("tunnels", 29, 0 )
endif

