# Generated by BehavEd
# ( "player uses computer" )
# ( "Check to see if the objective telling the player to get the code has been revealed" )
codes_obj = getObjective("act1_obj_3c", "HIDDEN" )
if codes_obj == 1
     objective ( "act1_obj_3",  "EOBJCMD_SHOW" )
     objective ( "act1_obj_3c",  "EOBJCMD_SHOW" )
     startConversation("act1/insect/insect3/1_insect3_0050" )
else
     codes = getObjective("act1_obj_2", "COMPLETE" )
     if codes == 1
          cameraFade(1.000, 0.500 )
          enemiesNoTarget("TRUE" )
          heroNoTarget("TRUE" )
          lockControls(-1.000 )
          setNoCollide("link_genosha5", "TRUE" )
          # ( "indicate the door to genosha has been opened" )
          setGameFlag("tunnels", 32, 1 )
          remove ( "trig_computer", "trig_computer" )
          waittimed ( 0.500 )
          moveHeroesToEnt("hero_pos_reset" )
          waittimed ( 0.500 )
          cameraFade(0.000, 0.500 )
          waittimed ( 1.000 )
          cameraMove(" 5450.000 675.000 350.000 ", 2.000 )
          cameraPan(" 0.000 60.000 135.000 ", 2.000, "FALSE" )
          waittimed ( 1.000 )
          # ( " open door to genosha" )
          act("sp_genoshaprisoner_a01", "sp_genoshaprisoner_a01" )
          act("floor_door_bug_a_it01", "floor_door_bug_a_it01" )
          act("light_door", "light_door" )
          # ( "This gets rid of the objective arrow" )
          remove ( "trig_computer01", "trig_computer01" )
     else
          # ( "conversation saying 'we need more codes'" )
          startConversation("act1/insect/insect3/1_insect3_0055" )
     endif
endif
entranceFound = getObjective("act1_obj_3a", "COMPLETE" )
if entranceFound == 0
     objective ( "act1_obj_3a",  "EOBJCMD_COMPLETE" )
endif

