# Generated by BehavEd
# ( "This script checks to see if the all of the minion of zealot in the first encounter are dead" )
# ( "If yes, then a convesatin is called" )
first_henchmen_dead = alive("first_henchmen" )
if first_henchmen_dead == 0
     startConversation("act1/insect/insect3/1_insect3_0031" )
endif

