# Generated by BehavEd
# ( "enter the zealot arena" )
setWaypointPath("zealot", "", 0 )
setRecallActive("FALSE" )
setEngageEnemy("zealot", "TRUE" )
setDefaultTarget("zealot" )
attackEntityWithType("zealot", "_ACTIVE_HERO_", "ANY", "FALSE" )

