# Generated by BehavEd
# ( "set current act and show main objective" )
setGameFlag("act1_visit", 6, 1 )
genosha_door_mentioned = getObjective("act1_obj_3a", "HIDDEN" )
if genosha_door_mentioned == 1
     objective ( "act1_obj_3",  "EOBJCMD_SHOW" )
     objective ( "act1_obj_3a",  "EOBJCMD_SHOW" )
     startConversation("act1/insect/insect3/1_insect3_0005" )
endif
meet_minions = getGameFlag("insect", 1 )
if meet_minions == 1
     remove ( "zealot_minions_intro", "zealot_minions_intro" )
endif
# ( "If all the queens are dead then then the queens shouldn't be spawned" )
# ( "Give a pause to allow the queens to spawn" )
waittimed ( 0.500 )
queen1_dead = getGameFlag("tunnels", 2 )
queen2_dead = getGameFlag("tunnels", 3 )
queen3_dead = getGameFlag("tunnels", 4 )
if queen1_dead == 1
     remove ( "Queen_1", "Queen_1" )
     remove ( "trigger_touch02", "trigger_touch02" )
endif
if queen2_dead == 1
     remove ( "Queen_2", "Queen_2" )
     remove ( "trigger_queen02", "trigger_queen02" )
endif
if queen3_dead == 1
     remove ( "Queen_3", "Queen_3" )
     remove ( "trigger_zealot_intro", "trigger_zealot_intro" )
endif
trigger_zealot_intro_used = getGameFlag("insect", 3 )
trigger_touch02_used = getGameFlag("insect", 4 )
if trigger_zealot_intro_used == 1
     remove ( "trigger_zealot_intro", "trigger_zealot_intro" )
endif
if trigger_touch02_used == 1
     remove ( "trigger_touch02", "trigger_touch02" )
endif
zealot_defeated = getObjective("act1_obj_3b", "COMPLETE" )
if zealot_defeated == 1
     remove ( "arena_trigger", "arena_trigger" )
     remove ( "trigger_touch01", "trigger_touch01" )
     remove ( "trigger_touch02", "trigger_touch02" )
     remove ( "trigger_zealot_intro", "trigger_zealot_intro" )
endif
# ( "has the door to genosha been opened?" )
door = getGameFlag("tunnels", 32 )
# ( "If Zealot is dead and the door hasn't been enabled then enable the trigger" )
door_enabled = getObjective("act1_obj_3b", "COMPLETE" )
if door == 1
     # ( "door has been opened--remove trigger and open door" )
     remove ( "trig_computer", "trig_computer" )
     remove ( "trig_computer01", "trig_computer01" )
     remove ( "prisoner", "prisoner" )
     remove ( "blink_portal_loop", "blink_portal_loop" )
     act("floor_door_bug_a_it01", "floor_door_bug_a_it01" )
     act("light_door", "light_door" )
     setEnable("link_genosha5", "TRUE" )
elif door_enabled == 1
     setEnable("trig_computer", "TRUE" )
endif

