# Generated by BehavEd
# ( "This spawn script makes sure the first queen is not destroyed ..." )
# ( "... before the intro conversation is played" )
first_queen_sighted = getGameFlag("tunnels", 25 )
if first_queen_sighted == 1
     setAIActive("_OWNER_", "TRUE" )
else
     setAIActive("_OWNER_", "FALSE" )
endif
setInvisible("_OWNER_", "FALSE" )

