# Generated by BehavEd
# ( "Third queen dead, set game flag 4 to 1" )
sound (  "PLAY_SOUND", "zone_shared/special/queen_bee", "_OWNER_", "" )
setGameFlag("tunnels", 4, 1 )
objective ( "act1_queens",  "EOBJCMD_INCREMENT" )
queen_dead = getObjective("act1_queens", "COMPLETE" )
if queen_dead == 1
     startConversation("act1/insect/insect3/1_insect3_0020" )
endif

