# Generated by BehavEd
# ( "comment" )
spawnEffect("blink_portal_loop", "map/common/scr_blinkportal_s", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
waittimed ( 0.300 )
act("blink_portal_loop", "blink_portal_loop" )
waittimed ( 2.000 )
fade("prisoner", 0.000, 1.000, "TRUE" )
waittimed ( 1.000 )
act("blink_portal_loop", "blink_portal_loop" )
spawnEffect("blink_portal_loop", "map/common/scr_blinkportal_c", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
remove ( "prisoner", "prisoner" )
waittimed ( 0.300 )
remove ( "blink_portal_loop", "blink_portal_loop" )

