# Generated by BehavEd
# ( "This script is only called if the player hasn't seen any other queens" )
first_queen_seen = getGameFlag("tunnels", 25 )
if first_queen_seen == 0
     act("Queen_2", "Queen_2" )
     setallaiactive("FALSE" )
     lockControls(0.000 )
     waittimed ( 0.500 )
     overrideFocusToEntity("Queen_2", 0.000 )
     waittimed ( 2.000 )
     setallaiactive("TRUE" )
     lockControls(0.100 )
     setAIActive("Queen_2", "TRUE" )
     startConversation("act1/insect/insect3/1_insect3_0010" )
endif
# ( "Set the queen back to be vunerable" )
setInvulnerable("Queen_2", "FALSE" )

