# Generated by BehavEd
# ( "********************************************************************************************************" )
# ( "The zealot_intro and zealot_again script are called from two different locations in insect3" )
# ( "Each of the above mentioned scripts will call a convesation" )
# ( "If the player has not met Zealot then the insect30 convesation is called" )
# ( "otherwise the insect32 convesation is called" )
# ( "Both of these conversation call the same script, chose_end_script" )
# ( "The chose_end_script will figure out which script should be called next" )
# ( "********************************************************************************************************" )
setallaiactive("FALSE" )
lockControls(0.000 )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
hero_alive = alive("_HERO1_" )
if hero_alive == 1
     copyOriginAndAngles("_HERO1_", "herospot05" )
endif
hero_alive = alive("_HERO2_" )
if hero_alive == 1
     copyOriginAndAngles("_HERO2_", "herospot06" )
endif
hero_alive = alive("_HERO3_" )
if hero_alive == 1
     copyOriginAndAngles("_HERO3_", "herospot07" )
endif
hero_alive = alive("_HERO4_" )
if hero_alive == 1
     copyOriginAndAngles("_HERO4_", "herospot08" )
endif
act("trigger_relay_zealot02", "trigger_relay_zealot02" )
copyOriginAndAngles("Queen_1", "queen_spot01" )
cameraToLocationAngles(" 1024.000 1721.000 229.000 ", " 1062.000 1785.000 162.000 ", 0.000 )
waittimed ( 0.500 )
cameraFade(0.000, 1.000 )
# ( "The following var is used to figure out which script to call" )
# ( "******************************************" )
# ( "It should call zealot_again_finished" )
# ( "******************************************" )
setGameFlag("tunnels", 29, 1 )
lockControls(0.100 )
setallaiactive("TRUE" )
zealot_first_visit = getGameFlag("tunnels", 28 )
if zealot_first_visit == 0
     setGameFlag("tunnels", 28, 1 )
     # ( "This is the first time the player has seen Zealot" )
     startConversation("act1/insect/insect3/1_insect3_0030" )
else
     startConversation("act1/insect/insect3/1_insect3_0032" )
endif
# ( "This makes sure the trigger is never callled again" )
setGameFlag("insect", 4, 1 )

