# Generated by BehavEd
# ( "Spawns terror leaders if all Queens aren't dead" )
setRecallActive("FALSE" )
queen1_dead = getGameFlag("tunnels", 2 )
if queen1_dead == 1
     remove ( "Queen_1", "Queen_1" )
endif
queen2_dead = getGameFlag("tunnels", 3 )
if queen2_dead == 1
     remove ( "Queen_2", "Queen_2" )
     remove ( "trigger_queen02", "trigger_queen02" )
endif
queen3_dead = getGameFlag("tunnels", 4 )
if queen3_dead == 1
     remove ( "Queen_3", "Queen_3" )
endif
queen_kill = getObjective("act1_queens", "COUNT" )
if queen_kill == 0
     act("terror_boss_01", "terror_boss_01" )
     act("terror_boss_02", "terror_boss_02" )
     act("terror_boss_03", "terror_boss_03" )
endif
if queen_kill == 1
     act("terror_boss_01", "terror_boss_01" )
     act("terror_boss_02", "terror_boss_02" )
endif
if queen_kill == 2
     act("terror_boss_01", "terror_boss_01" )
endif
metzealot = getGameFlag("bosses", 3 )
if metzealot == 0
     setGameFlag("bosses", 3, 1 )
     setallaiactive("FALSE" )
     lockControls(0.000 )
     setAmbientLightColor(" 0.100 0.100 0.100 " )
     cameraFade(1.000, 1.000 )
     waittimed ( 1.000 )
     copyOriginAndAngles("_HERO1_", "herospot09" )
     copyOriginAndAngles("_HERO2_", "herospot10" )
     copyOriginAndAngles("_HERO3_", "herospot11" )
     copyOriginAndAngles("_HERO4_", "herospot12" )
     cameraToLocationAngles(" 4219.000 654.000 132.000 ", " 4308.000 664.000 87.000 ", 0.000 )
     waittimed ( 0.500 )
     cameraFade(0.000, 1.000 )
     waittimed ( 1.000 )
     lockControls(0.100 )
     setallaiactive("TRUE" )
     # ( "play zealot's conversation" )
     startCharConversation("act1/insect/insect3/1_insect3_0034", "magneto", "act1/insect/insect3/1_insect3_0035" )
else
     setEnable("arena_trigger", "TRUE" )
     setDefaultTarget("zealot" )
endif

