# Generated by BehavEd
# ( "shows great door and plays conv about it" )
mon_comp = getGameFlag("monument2", 3 )
if mon_comp == 0
     setGameFlag("monument2", 3, 1 )
     lockControls(-1.000 )
     setallaiactive("FALSE" )
     cameraFade(1.000, 0.750 )
     waittimed ( 0.750 )
     cameraToLocationAngles(" 8110.920 5592.820 265.750 ", " 8196.771 5614.700 219.360 ", 0.000 )
     waittimed ( 0.250 )
     cameraFade(0.000, 0.500 )
     waittimed ( 2.000 )
     cameraFade(1.000, 0.750 )
     waittimed ( 0.750 )
     cameraReset( )
     waittimed ( 0.250 )
     cameraFade(0.000, 0.500 )
     lockControls(0.100 )
     startConversation("act2/monument/monument2/2_MONUMENT2_0010" )
endif

