# Generated by BehavEd
# ( "enable great door cut scene" )
playanim (  "EA_USE_BUTTON", "_ACTIVE_HERO_", "NONE", "" )
sound (  "PLAY_SOUND", "zone_shared/special/place_stone", "", "" )
copyOriginAndAngles("mon1_statue_comp", "monument1_statue" )
remove ( "mon1_flame", "mon1_flame" )
remove ( "mon1_obj", "mon1_obj" )
remove ( "monument1_statue", "monument1_statue" )
objective ( "act2_obj_5c",  "EOBJCMD_INCREMENT" )
setGameFlag("monument2", 1, 1 )
waittimed ( 0.250 )
act("relay01", "relay01" )

