# Generated by BehavEd
# ( "check monument4's stone" )
# ( "COMMENT THIS OUT" )
# ( "END COMMENT THIS OUT" )
reset = getZoneReset( )
mon_comp = getGameFlag("monument2", 1 )
if mon_comp == 1
     # ( "stone placed." )
     if reset == 1
          copyOriginAndAngles("mon1_statue_comp", "monument1_statue" )
     endif
     remove ( "monument1_statue", "monument1_statue" )
     remove ( "mon1_flame", "mon1_flame" )
else
     mon_comp = getObjective("act2_obj_5a", "COMPLETE" )
     if mon_comp == 1
          setEnable("monument1_statue", "TRUE" )
          setHintType("mon1_obj", "objective" )
     endif
endif
# ( "check monument4's stone" )
mon_comp = getGameFlag("monument2", 2 )
if mon_comp == 1
     # ( "stone placed." )
     if reset == 1
          copyOriginAndAngles("mon1_statue_comp", "monument1_statue" )
     endif
     remove ( "monument4_statue", "monument4_statue" )
     remove ( "mon4_flame", "mon4_flame" )
else
     mon_comp = getObjective("act2_obj_5b", "COMPLETE" )
     if mon_comp == 1
          setEnable("monument4_statue", "TRUE" )
          setHintType("mon4_obj", "objective" )
     endif
endif
# ( "if puzzle is complete, open the door, remove whatever not needed" )
mon_comp = getObjective("act2_obj_5c", "COUNT" )
if mon_comp == 2
     actSilent("Great_Door", "Great_Door" )
     setEnable("link_monument3", "TRUE" )
endif
setGameFlag("act2_visit", 2, 1 )

