# Generated by BehavEd
# ( "enable great door cut scene" )
playanim (  "EA_USE_BUTTON", "_ACTIVE_HERO_", "NONE", "" )
sound (  "PLAY_SOUND", "zone_shared/special/place_stone", "", "" )
copyOriginAndAngles("mon4_statue_comp", "monument4_statue" )
remove ( "mon4_flame", "mon4_flame" )
remove ( "mon4_obj", "mon4_obj" )
remove ( "monument4_statue", "monument4_statue" )
objective ( "act2_obj_5c",  "EOBJCMD_INCREMENT" )
setGameFlag("monument2", 2, 1 )
waittimed ( 0.250 )
act("relay01", "relay01" )

