# Generated by BehavEd
# ( "move party from block hallway to Twilight01" )
setallaiactive("FALSE" )
lockControls(-1.000 )
cameraFade(1.000, 0.500 )
waittimed ( 0.750 )
killEntity("secret_wall_01" )
hero1 = alive("_HERO1_" )
if hero1 > 0
     copyOriginAndAngles("_HERO1_", "playerA24" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     copyOriginAndAngles("_HERO2_", "playerA27" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     copyOriginAndAngles("_HERO3_", "playerA25" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     copyOriginAndAngles("_HERO4_", "playerA26" )
endif
waittimed ( 0.750 )
cameraFade(0.000, 0.500 )
setallaiactive("TRUE" )
lockControls(0.100 )

