# Generated by BehavEd
# ( "This checks if both the core and infinite quests are done" )
# ( "If both are done then it sets a variable to make the conversation with Profx available" )
# ( "Check to see if the Talk to Angel objective is enabled.  It should only be enable if the mission is done" )
core_done = getObjective("act3_obj_2g", "COMPLETE" )
infinite_done = getObjective("act3_obj_4b", "COMPLETE" )
once_only = getGameFlag("act3_que", 5 )
waittimed ( 2.000 )
if core_done == 1
     if infinite_done == 1
          if once_only == 0
               # ( "This unlocks the madri quest" )
               setGameFlag("act3_que", 5, 1 )
               # ( "This is the main objective for Madri" )
               objective ( "act3_obj_6",  "EOBJCMD_SHOW" )
               # ( "This objective is to talk to Profx" )
               objective ( "act3_obj_6a_1",  "EOBJCMD_SHOW" )
               waittimed ( 2.000 )
               # ( "This conversation should tell the player to talk to profx" )
               setHintType("profx", "importanttalk" )
               startConversation("act3/military/3_military1_055_001" )
          endif
     endif
endif

