# Generated by BehavEd
# ( "This enables the congrats from Angel" )
core_done = getObjective("act3_obj_2g", "COMPLETE" )
# ( "If the core is done, then we don't want to show the conversation" )
if core_done == 0
     core_done = getObjective("act3_obj_2g", "HIDDEN" )
     if core_done == 0
          objective ( "act3_obj_2g",  "EOBJCMD_COMPLETE" )
          allowConversation("TRUE" )
     else
          allowConversation("FALSE" )
     endif
else
     allowConversation("FALSE" )
endif

