# Generated by BehavEd
# ( "This loads the first Madri map" )
# ( "This objectives tells the player to use the X-Jet" )
objective ( "act3_obj_6a_2",  "EOBJCMD_COMPLETE" )
loadZone("act3/madri/madri1", "link_madri1" )

