# Generated by BehavEd
# ( "This loads the first core map" )
# ( "This objectives tells the player to use the X-Jet" )
objective ( "act3_obj_2a_2",  "EOBJCMD_COMPLETE" )
loadZone("act3/corein/corein1", "link_corein1" )

