# Generated by BehavEd
# ( "This loads the first infinite map" )
# ( "This objectives tells the player to use the X-Jet" )
objective ( "act3_obj_3a_2",  "EOBJCMD_COMPLETE" )
loadZone("act3/infinite/infinite1", "link_infinite1" )

