# Generated by BehavEd
# ( "This enables the congrats from Heather" )
infinite_done = getObjective("act3_obj_4b", "COMPLETE" )
# ( "This makes sure that the conversion is only played once after the objective is completed" )
if infinite_done == 0
     infinite_done = getObjective("act3_obj_4b", "HIDDEN" )
     if infinite_done == 0
          # ( "This completes the objective to talk to Heather" )
          objective ( "act3_obj_4b",  "EOBJCMD_COMPLETE" )
          allowConversation("TRUE" )
     else
          allowConversation("FALSE" )
     endif
else
     allowConversation("FALSE" )
endif

