# Generated by BehavEd
# ( "This allows a conversation to be play on profx about madri" )
# ( "-" )
# ( "If we've defeated Holocaust, we've shown act3_obj_6g, 'Talk to ProfessorX'." )
# ( "Therefore, if act3_obj_6g is showing, complete it here since we're talking to ProfX" )
gHidden = getObjective("act3_obj_6g", "HIDDEN" )
if gHidden == 0
     # ( "not hidden, therefore complete it" )
     objective ( "act3_obj_6g",  "EOBJCMD_COMPLETE" )
     # ( "give it a chance to sink in...wait a bit" )
     waittimed ( 0.100 )
endif
madri_done = getObjective("act3_obj_6", "COMPLETE" )
if madri_done == 1
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

