# Generated by BehavEd
# ( "This is the load script for the zone" )
# ( "This unlocks the extraction point" )
extractionUnlock("" )
setCurrentAct(3 )
profx = getGameFlag("act3_que", 4 )
if profx == 0
     cameraFade(1.000, 0.000 )
     lockControls(0.000 )
     setallaiactive("FALSE" )
     waittimed ( 0.500 )
     cameraToLocationAngles(" 1528.000 1568.000 -16.000 ", " 1555.000 1654.000 -59.000 ", 0.000 )
     copyOriginAndAngles("_HERO1_", "hero_spot01" )
     copyOriginAndAngles("_HERO2_", "hero_spot02" )
     copyOriginAndAngles("_HERO3_", "hero_spot03" )
     copyOriginAndAngles("_HERO4_", "hero_spot04" )
     # ( "This script unlocks the core quests" )
     objective ( "act3_obj_2",  "EOBJCMD_SHOW" )
     objective ( "act3_obj_2a_1",  "EOBJCMD_SHOW" )
     # ( "This unlocks the conversation with Angel about the Core" )
     setGameFlag("act3_que", 6, 1 )
     # ( "This script unlocks the infinite quests" )
     objective ( "act3_obj_3",  "EOBJCMD_SHOW" )
     objective ( "act3_obj_3a_1",  "EOBJCMD_SHOW" )
     # ( "This unlocks the conversation with Heather about the Core" )
     setGameFlag("act3_que", 7, 1 )
     # ( "******************************************" )
     setGameFlag("act3_que", 4, 1 )
     # ( "This marks that Beast has been capture, in case the plaeyr goes back to act 1" )
     setGameFlag("act1_visit", 17, 1 )
     cameraFade(0.000, 1.000 )
     waittimed ( 1.000 )
     lockControls(0.100 )
     setallaiactive("TRUE" )
     startConversation("act3/military/3_military1_0010" )
endif
# ( "If infinite is done then there is no reason to mark Heather importanttalk=true" )
infinite_hidden = getObjective("act3_obj_4", "COMPLETE" )
if infinite_hidden == 0
     # ( "Insert a wait to allow things to settle" )
     waittimed ( 0.500 )
     # ( "If the last talk to Heather conversation is shown then Heather needs to be marked importanttalk=true" )
     infinite_done = getObjective("act3_obj_4b", "HIDDEN" )
     # ( "If the player has already talk to Heather then she shouldn't have importanttalk=true" )
     infinite_introduced = getObjective("act3_obj_3a_1", "COMPLETE" )
     if infinite_done == 0
          setHintType("heather", "importanttalk" )
     elif infinite_introduced == 1
          setHintType("heather", "talk" )
     endif
endif
# ( "If core is done then there is no reason to mark Angel importanttalk=true" )
core_hidden = getObjective("act3_obj_2", "COMPLETE" )
if core_hidden == 0
     # ( "Insert a wait to allow things to settle" )
     waittimed ( 0.500 )
     # ( "If the last talk to Angel conversation is shown then Angel needs to be marked importanttalk=true" )
     core_done = getObjective("act3_obj_2g", "HIDDEN" )
     # ( "If the player has already talk to angel then she shouldn't have importanttalk=true" )
     core_introduced = getObjective("act3_obj_2a_1", "COMPLETE" )
     if core_done == 0
          setHintType("angel", "importanttalk" )
     elif core_introduced == 1
          setHintType("angel", "talk" )
     endif
endif
# ( "This checks if profx should have the importanttalk=true" )
act3_done = getObjective("act3_obj_6", "COMPLETE" )
if act3_done == 0
     obj_6a1_talk_to_profx = getObjective("act3_obj_6a_1", "HIDDEN" )
     # ( "Need to check if the first madri object (talk to Profx) is shown and incomplete" )
     if obj_6a1_talk_to_profx == 0
          obj6a1_done = getObjective("act3_obj_6a_1", "COMPLETE" )
          if obj6a1_done == 0
               setHintType("profx", "importanttalk" )
          endif
     endif
     obj6g_talk_to_profx = getObjective("act3_obj_6g", "HIDDEN" )
     if obj6g_talk_to_profx == 0
          obj6g_done = getObjective("act3_obj_6g", "COMPLETE" )
          if obj6g_done == 0
               setHintType("profx", "importanttalk" )
          endif
     endif
endif
# ( "If the talk to Profx is not hidden then Angel has been captured" )
angel_captured = getObjective("act3_obj_6f", "COMPLETE" )
if angel_captured == 1
     # ( "Angel being gone has to be tracked for the other acts" )
     setGameFlag("angel_gone", 1, 1 )
     waittimed ( 0.500 )
     # ( "Angel has turned into Archangel, so he should be removed" )
     remove ( "angel", "angel" )
endif
numBeacons = getGameVarBitCount("beaconact3" )
if numBeacons >= 4
     # ( "you have all the beacons, activate portal next to Forge" )
     setEnable("blink_to_bonuses", "TRUE" )
     setEnable("link_bonus3", "TRUE" )
     waittimed ( 0.500 )
     act("blink_to_bonuses", "blink_to_bonuses" )
endif

