# Generated by BehavEd
# ( "This checks if both the core and infinite quests are done" )
# ( "If both are done then it sets a variable to make the conversation with Profx available" )
core_done = getObjective("act3_obj_2g", "COMPLETE" )
infinite_done = getObjective("act3_obj_4b", "COMPLETE" )
if core_done == 1
     if infinite_done == 1
          # ( "The player has talked to prof about madri now" )
          objective ( "act3_obj_6a_1",  "EOBJCMD_COMPLETE" )
          allowConversation("TRUE" )
     else
          allowConversation("FALSE" )
     endif
else
     allowConversation("FALSE" )
endif

