# Generated by BehavEd
# ( "This completes a military complex mini quest" )
objective ( "act3_obj_2a_1",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_2a_2",  "EOBJCMD_SHOW" )
# ( "This unlocks quest for xjet" )
setGameFlag("act3_que", 1, 1 )
# ( "This changes the status of Angel so that he no longer has importanttalk=true" )
setHintType("angel", "talk" )

