# Generated by BehavEd
# ( "This completes a military complex mini quest" )
# ( "This unlocks quest for xjet" )
setGameFlag("act3_que", 3, 1 )
objective ( "act3_obj_3a_1",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_3a_2",  "EOBJCMD_SHOW" )
# ( "This changes the status of Heather so that she no longer has importanttalk=true" )
setHintType("heather", "talk" )

