# Generated by BehavEd
# ( "Used in monster spawnscripts to make them instantly come after the player." )
setAIActive("_OWNER_", "FALSE" )
playanim (  "EA_ZONE1", "_OWNER_", "NONE", "" )
waittimed ( 0.125 )
setAIActive("_OWNER_", "TRUE" )

