# Generated by BehavEd
# ( "comment" )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
cameraToLocationAngles(" 5859.781 793.785 270.427 ", " 6415.915 1504.665 -230.466 ", 0.000 )
cameraFade(0.000, 1.000 )
setEnable("blink_portal_trig1", "TRUE" )

