# Generated by BehavEd
# ( "comment" )
act("clipup1", "clipup1" )
act("clipup2", "clipup2" )
# ( "this one spawns IN a dynamic clip to invalidate navs" )
act("clipup3", "clipup3" )
act("clipup4", "clipup4" )

