# Generated by BehavEd
# ( "comment" )
deadzone = getGameFlag("deadzone", 20 )
if deadzone == 0
     startConversation("act1/deadzone/deadzone1/1_DEADZONE1_0040" )
     setGameFlag("deadzone", 20, 1 )
endif

