# Generated by BehavEd
# ( "comment" )
lockControls(-1.000 )
cameraFocusToEntity("camera_inlet02", 300.000, 40.000, 0.000, 3.000 )
waittimed ( 3.100 )
heroalive = alive("_HERO1_" )
if heroalive == 1
     copyOriginAndAngles("_hero1_", "p1spot01" )
endif
heroalive = alive("_HERO2_" )
if heroalive == 1
     copyOriginAndAngles("_hero2_", "p2spot01" )
endif
heroalive = alive("_HERO3_" )
if heroalive == 1
     copyOriginAndAngles("_hero3_", "p3spot01" )
endif
heroalive = alive("_HERO4_" )
if heroalive == 1
     copyOriginAndAngles("_hero4_", "p4spot01" )
endif
cameraReset( )
lockControls(0.100 )

