# Generated by BehavEd
# ( "complete act1_obj_1 as soon as you talk to Blink, but not before" )
objective ( "act1_obj_1",  "EOBJCMD_COMPLETE" )
startCharConversation("act1/deadzone/deadzone1/1_deadzone1_0030", "toad", "act1/deadzone/deadzone1/1_deadzone1_0031" )

