# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept16.png" )
imageViewer("textures/concept/concept17.png" )
imageViewer("textures/concept/concept18.png" )

