# Generated by BehavEd
# ( "This script figures out if the third condition of 3_infinite1_0015 should be played" )
engineering = getObjective("act3_obj_3a", "COMPLETE" )
maintenance = getObjective("act3_obj_3b", "COMPLETE" )
fusion_core = getObjective("act3_obj_3c", "COMPLETE" )
assembly = getObjective("act3_obj_3d", "COMPLETE" )
computer = getObjective("act3_obj_4", "COMPLETE" )
if engineering == 1
     if maintenance == 1
          if fusion_core == 1
               if assembly == 1
                    if computer == 0
                         allowConversation("TRUE" )
                    else
                         allowConversation("FALSE" )
                    endif
               else
                    allowConversation("FALSE" )
               endif
          else
               allowConversation("FALSE" )
          endif
     else
          allowConversation("FALSE" )
     endif
else
     allowConversation("FALSE" )
endif

