# Generated by BehavEd
# ( "This script figures out if the first condition of 3_infinite1_0015 should be played" )
engineering = getObjective("act3_obj_3a", "COMPLETE" )
maintenance = getObjective("act3_obj_3b", "COMPLETE" )
fusion_core = getObjective("act3_obj_3c", "COMPLETE" )
if engineering == 1
     if maintenance == 1
          if fusion_core == 1
               allowConversation("FALSE" )
          else
               allowConversation("TRUE" )
          endif
     else
          allowConversation("TRUE" )
     endif
else
     allowConversation("TRUE" )
endif

