# Generated by BehavEd
# ( "This script checks if the other areas of the infinite factory have been destroyed" )
# ( "This checks if the engineering section has been destroyed" )
sound (  "PLAY_SOUND", "zone_shared/object/beep2", "", "" )
engineering_done = getObjective("act3_obj_3a", "COMPLETE" )
# ( "This checks if the Maintenance section has been destroyed" )
maintenance_done = getObjective("act3_obj_3b", "COMPLETE" )
# ( "This checks if the Fusion Core section has been destroyed" )
fusion_core_done = getObjective("act3_obj_3c", "COMPLETE" )
run_once = getGameFlag("act3_que", 8 )
if 0 == 1
     setGameFlag("act3_que", 8, 1 )
     lockControls(0.000 )
     heroNoTarget("TRUE" )
     setEnable("double_door_20x40_inf_a_ip01", "TRUE" )
     setEnable("double_door_20x40_inf_a_ip02", "TRUE" )
     setEnable("trigger_inf4", "FALSE" )
     act("behemoth01", "behemoth01" )
     act("behemoth02", "behemoth02" )
     waittimed ( 0.100 )
     cameraMove(" 4253.240 742.350 192.690 ", 1.000 )
     cameraPan(" 0.000 36.100 185.600 ", 0.000, "FALSE" )
     waittimed ( 1.000 )
     act("double_door_20x40_inf_a_ip01", "double_door_20x40_inf_a_ip01" )
     act("double_door_20x40_inf_a_ip02", "double_door_20x40_inf_a_ip02" )
     waittimed ( 3.000 )
     lockControls(0.100 )
     heroNoTarget("FALSE" )
     cameraResetOldSchool( )
else
     if engineering_done == 1
          if maintenance_done == 1
               if fusion_core_done == 1
                    if run_once == 0
                         setGameFlag("act3_que", 8, 1 )
                         lockControls(0.000 )
                         heroNoTarget("TRUE" )
                         setEnable("double_door_20x40_inf_a_ip01", "TRUE" )
                         setEnable("double_door_20x40_inf_a_ip02", "TRUE" )
                         setEnable("trigger_inf4", "FALSE" )
                         act("behemoth01", "behemoth01" )
                         act("behemoth02", "behemoth02" )
                         waittimed ( 0.100 )
                         cameraMove(" 4253.240 742.350 192.690 ", 1.000 )
                         cameraPan(" 0.000 36.100 185.600 ", 0.000, "FALSE" )
                         waittimed ( 1.000 )
                         act("double_door_20x40_inf_a_ip01", "double_door_20x40_inf_a_ip01" )
                         act("double_door_20x40_inf_a_ip02", "double_door_20x40_inf_a_ip02" )
                         waittimed ( 3.000 )
                         lockControls(0.100 )
                         heroNoTarget("FALSE" )
                         cameraResetOldSchool( )
                    endif
               endif
          endif
     else
          startConversation("act3/infinite/infinite1/3_infinite1_0080" )
     endif
endif

