# Generated by BehavEd
# ( "You have obtained the Decryption Module!" )
setGameFlag("protocols", 3, 1 )
remove ( "decryption_module", "decryption_module" )
startConversation("act3/infinite/infinite1/3_infinite1_0070" )

