# Generated by BehavEd
# ( "does Guardian need the boss light?" )
boss_light = getGameFlag("protocols", 16 )
if boss_light == 0
     # ( "indicate the boss light has been used...it's only needed once, for Guardian's intro" )
     setGameFlag("protocols", 16, 1 )
     # ( "Guardian's intro has not been run--so turn on the boss light" )
     waittimed ( 1.000 )
     setBossPartyLightEntity("hudson" )
endif

