# Generated by BehavEd
# ( "comment" )
visited = getGameFlag("act3_visit", 6 )
if visited == 0
     lockControls(0.000 )
     act("sp_jameshudson01", "sp_jameshudson01" )
     waittimed ( 1.000 )
     # ( "camera move?" )
     cameraMove(" 4831.050 609.320 172.760 ", 1.000 )
     cameraPan(" 0.000 39.100 41.800 ", 1.000, "FALSE" )
     waittimed ( 2.500 )
     lockControls(0.100 )
     # ( "Hudson limps on screen" )
     startCharConversation("act3/infinite/infinite1/3_infinite1_0010", "wolverine", "act3/infinite/infinite1/3_infinite1_0011" )
     objective ( "act3_obj_3",  "EOBJCMD_SHOW" )
     objective ( "act3_obj_3a",  "EOBJCMD_SHOW" )
     objective ( "act3_obj_3b",  "EOBJCMD_SHOW" )
     objective ( "act3_obj_3c",  "EOBJCMD_SHOW" )
endif

