# Generated by BehavEd
# ( "infinite1 zone script" )
# ( "has the door to infinite4 been opened?" )
door = getGameFlag("act3_que", 8 )
if door == 1
     setEnable("trigger_inf4", "FALSE" )
     setEnable("double_door_20x40_inf_a_ip01", "TRUE" )
     setEnable("double_door_20x40_inf_a_ip02", "TRUE" )
     actSilent("double_door_20x40_inf_a_ip01", "double_door_20x40_inf_a_ip01" )
     actSilent("double_door_20x40_inf_a_ip02", "double_door_20x40_inf_a_ip01" )
endif
# ( "has the decryption module been picked up?" )
module = getGameFlag("protocols", 3 )
if module == 1
     # ( "module has been picked up previously--remove it" )
     remove ( "decryption_module", "decryption_module" )
endif
visited = getGameFlag("act3_visit", 5 )
spy_codes = getGameFlag("protocols", 8 )
bridge1 = getGameFlag("protocols", 9 )
bridge2 = getGameFlag("protocols", 10 )
# ( "This is for the initial conversation with Havok and James Hudson." )
int_conversation = getGameFlag("protocols", 11 )
infinite2 = getObjective("act3_obj_3a", "COMPLETE" )
infinite3 = getObjective("act3_obj_3b", "COMPLETE" )
infinite5 = getObjective("act3_obj_3c", "COMPLETE" )
if visited == 0
     setGameFlag("act3_visit", 5, 1 )
     setGameFlag("protocols", 11, 1 )
     waittimed ( 1.000 )
     startCharConversation("act3/infinite/infinite1/3_infinite1_0010", "wolverine", "act3/infinite/infinite1/3_infinite1_0011" )
endif
if spy_codes == 1
     remove ( "spy_codes", "spy_codes" )
     waittimed ( 0.500 )
     setHintType("spy007", "importanttalk" )
     # ( "have the codes been given to the spy?" )
     spy_codes = getObjective("help_spy", "COMPLETE" )
     if spy_codes == 1
          # ( "the spy has the codes already--remove him" )
          waittimed ( 0.500 )
          remove ( "spy007", "spy007" )
     endif
endif
if bridge1 == 1
     # ( "This is for a behemoth bridge" )
     act("bridge01", "bridge01" )
     # ( "This removes the scripted event of the bridge falling" )
     remove ( "trigger_bridge01", "trigger_bridge01" )
     remove ( "trigger_bridge02", "trigger_bridge02" )
     remove ( "trigger_bridge03", "trigger_bridge03" )
endif
if bridge2 == 1
     # ( "This is for a behemoth bridge" )
     act("bridge02", "bridge02" )
     # ( "This removes the scripted event of the bridge falling" )
     remove ( "trigger_bridge03", "trigger_bridge03" )
endif
if int_conversation == 1
     remove ( "initial_conversation", "initial_conversation" )
     act("sp_jameshudson01", "sp_jameshudson01" )
endif
if infinite2 == 1
     # ( "infinite2 has been shut down" )
     copyOriginAndAngles("screen_b_off", "screen_b_on" )
     remove ( "screen_b_on", "screen_b_on" )
endif
if infinite3 == 1
     # ( "infinite3 has been shut down" )
     copyOriginAndAngles("screen_c_off", "screen_c_on" )
     remove ( "screen_c_on", "screen_c_on" )
endif
if infinite5 == 1
     # ( "infinite5 has been shut down" )
     copyOriginAndAngles("screen_d_off", "screen_d_on" )
     remove ( "screen_d_on", "screen_d_on" )
endif

