# Generated by BehavEd
# ( "This console gives you the codes for the Infinite Spy" )
setHintType("spy007", "importanttalk" )
setGameFlag("protocols", 8, 1 )
met_spy = getGameFlag("protocols", 14 )
if met_spy == 1
     # ( "If met_spy == 1, then the player has met the spy" )
     # ( "x-31 protocol codes downloaded." )
     startConversation("act3/infinite/infinite1/3_infinite1_0035" )
else
     startConversation("act3/infinite/infinite1/3_infinite1_0040" )
endif

