# Generated by BehavEd
# ( "This script is called by the dept H spy" )
# ( "If set to 1 then the player has the codes" )
protocols = getGameFlag("protocols", 8 )
if protocols == 1
     met_before = getGameFlag("protocols", 14 )
     if met_before == 1
          # ( "This completes the spy objective" )
          objective ( "help_spy",  "EOBJCMD_COMPLETE" )
          # ( "Returned the Genetic Code to McKenzie after having already met him." )
          startConversation("act3/infinite/infinite1/3_infinite1_0050" )
     else
          # ( "The player has now met the spy for the firs time." )
          setGameFlag("protocols", 14, 1 )
          # ( "This shows the spy objective" )
          objective ( "help_spy",  "EOBJCMD_SHOW" )
          # ( "This completes the spy objective" )
          objective ( "help_spy",  "EOBJCMD_COMPLETE" )
          # ( "Meet McKenzie for first time, player already has genetic code." )
          startConversation("act3/infinite/infinite1/3_infinite1_0060" )
     endif
else
     # ( "This shows the spy objective" )
     objective ( "help_spy",  "EOBJCMD_SHOW" )
     # ( "The player has now met the spy for the firs time." )
     setGameFlag("protocols", 14, 1 )
     # ( "Meet Department H spy first time" )
     startConversation("act3/infinite/infinite1/3_infinite1_0030" )
endif

