# Generated by BehavEd
# ( "comment" )
setReactToEnemies("_OWNER_", "FALSE" )
setAIActive("_OWNER_", "FALSE" )
setNoClip("_OWNER_", "TRUE" )
playanim (  "EA_ZONE1", "_OWNER_", "NONE", "" )
waittimed ( 0.700 )
setAIActive("_OWNER_", "TRUE" )
setNoClip("_OWNER_", "FALSE" )

