# Generated by BehavEd
# ( "comment" )
lockControls(-1.000 )
enemiesNoTarget("TRUE" )
heroNoTarget("TRUE" )
cameraFocusToEntity("matt2_bubbles", 400.000, 35.000, 240.000, 0.750 )
waittimed ( 6.000 )
cameraReset( )
lockControls(0.100 )
heroNoTarget("FALSE" )
enemiesNoTarget("FALSE" )

