# Generated by BehavEd
# ( "comment" )
setCurrentAct(3 )
artifacts = getObjective("act3_obj_6b_a", "COMPLETE" )
if artifacts == 1
     remove ( "artifact_pure", "artifact_pure" )
     remove ( "door_artifact", "door_artifact" )
     remove ( "artifact_pure", "artifact_pure" )
     act("portal_pure_start", "portal_pure_start" )
     setEnable("link_madri1", "TRUE" )
endif
offering = getGameFlag("offering", 6 )
if offering == 1
     remove ( "door_artifact", "door_artifact" )
     remove ( "offering_artifact_trig1", "offering_artifact_trig1" )
     act("offering_artifact_flame", "offering_artifact_flame" )
endif
altar = getObjective("act3_obj_5a", "COMPLETE" )
if altar == 1
     swapInStump("stepford_altar" )
     remove ( "matt_spawner", "matt_spawner" )
     remove ( "matt_bubbles", "matt_bubbles" )
     remove ( "matt1_spawner", "matt2_spawner" )
     remove ( "matt1_bubbles", "matt1_bubbles" )
     remove ( "matt2_spawner", "matt2_spawner" )
     remove ( "matt2_bubbles", "matt2_bubbles" )
     remove ( "matt3_spawner", "matt3_spawner" )
     remove ( "matt3_bubbles", "matt3_bubbles" )
     remove ( "matt4_spawner", "matt4_spawner" )
     remove ( "matt4_bubbles", "matt4_bubbles" )
     remove ( "matt5_spawner", "matt5_spawner" )
     remove ( "matt5_bubbles", "matt5_bubbles" )
     remove ( "matt6_spawner", "matt6_spawner" )
     remove ( "matt6_bubbles", "matt6_bubbles" )
     remove ( "matt7_bubbles", "matt7_bubbles" )
     remove ( "door_last", "door_last" )
     remove ( "trigger_touch01", "trigger_touch01" )
endif

