# Generated by BehavEd
# ( "comment" )
setGameFlag("offering", 1, 1 )
act("offering_flame1", "offering_flame1" )
remove ( "offering_trigger1", "offering_trigger1" )
act("offering_relay", "offering_relay" )

