# Generated by BehavEd
# ( "comment" )
setGameFlag("offering", 2, 1 )
act("offering_flame2", "offering_flame2" )
remove ( "offering_trigger2", "offering_trigger2" )
act("offering_relay", "offering_relay" )

