# Generated by BehavEd
# ( "no longer requires moneys" )
setGameFlag("offering", 4, 1 )
act("offering_flame4", "offering_flame4" )
remove ( "offering_trigger4", "offering_trigger4" )
act("offering_relay", "offering_relay" )

