# Generated by BehavEd
# ( "comment" )
offering1 = getGameFlag("offering", 1 )
if offering1 == 1
     offering2 = getGameFlag("offering", 2 )
     if offering2 == 1
          offering3 = getGameFlag("offering", 3 )
          if offering3 == 1
               offering4 = getGameFlag("offering", 4 )
               if offering4 == 1
                    setallaiactive("FALSE" )
                    cameraFade(1.000, 0.500 )
                    waittimed ( 0.500 )
                    cameraFade(0.000, 0.500 )
                    cameraMove(" 2515.950 3899.975 190.502 ", 0.000 )
                    cameraPan(" 0.000 25.000 180.000 ", 0.000, "FALSE" )
                    waittimed ( 2.000 )
                    setEnable("offering_door", "TRUE" )
                    waittimed ( 0.100 )
                    act("offering_door", "offering_door" )
                    waittimed ( 2.000 )
                    cameraFade(1.000, 0.500 )
                    waittimed ( 0.500 )
                    cameraReset( )
                    cameraFade(0.000, 0.500 )
                    setallaiactive("TRUE" )
               endif
          endif
     endif
endif

