# Generated by BehavEd
# ( "comment" )
setGameFlag("offering", 3, 1 )
act("offering_flame3", "offering_flame3" )
remove ( "offering_trigger3", "offering_trigger3" )
act("offering_relay", "offering_relay" )

