# Generated by BehavEd
# ( "comment" )
setCurrentAct(3 )
remove ( "matt_spawner", "matt_spawner" )
remove ( "matt_bubbles", "matt_bubbles" )
remove ( "matt1_spawner", "matt2_spawner" )
remove ( "matt1_bubbles", "matt1_bubbles" )
remove ( "matt2_spawner", "matt2_spawner" )
remove ( "matt2_bubbles", "matt2_bubbles" )
remove ( "matt3_spawner", "matt3_spawner" )
remove ( "matt3_bubbles", "matt3_bubbles" )
remove ( "matt4_spawner", "matt4_spawner" )
remove ( "matt4_bubbles", "matt4_bubbles" )
remove ( "matt5_spawner", "matt5_spawner" )
remove ( "matt5_bubbles", "matt5_bubbles" )
remove ( "matt6_spawner", "matt6_spawner" )
remove ( "matt6_bubbles", "matt6_bubbles" )
remove ( "matt7_bubbles", "matt7_bubbles" )
setEnable("door_last", "TRUE" )
offering = getGameFlag("offering", 5 )
if offering == 0
     setallaiactive("FALSE" )
     cameraFade(1.000, 0.500 )
     waittimed ( 0.500 )
     cameraMove(" 2339.513 6212.832 221.423 ", 0.000 )
     cameraPan(" 0.000 30.000 90.000 ", 0.000, "FALSE" )
     cameraFade(0.000, 0.500 )
     waittimed ( 1.000 )
     act("door_last", "door_last" )
     waittimed ( 1.000 )
     cameraFade(1.000, 0.500 )
     waittimed ( 0.500 )
     cameraReset( )
     cameraFade(0.000, 0.500 )
     setallaiactive("TRUE" )
     setGameFlag("offering", 5, 1 )
     objective ( "act3_obj_5a",  "EOBJCMD_COMPLETE" )
     var1 = getObjective("act3_obj_5a", "COMPLETE" )
     var2 = getObjective("act3_obj_5b", "COMPLETE" )
     var3 = getObjective("act3_obj_5c", "COMPLETE" )
     if var1 == 1
          if var2 == 1
               if var3 == 1
                    # ( "all three altars have been destroyed" )
                    getObjective("act3_obj_5", "COMPLETE" )
                    startConversation("act3/madri/3_SOMETIMEMADRI_0010" )
               endif
          endif
     endif
     # ( "plays conv if this is first stepford altar destroyed" )
     first_stepford = getGameFlag("madri_conv", 5 )
     if first_stepford == 0
          startConversation("act3/madri/3_SOMETIMEMADRI_0012" )
          setGameFlag("madri_conv", 5, 1 )
     endif
endif

