# Generated by BehavEd
# ( "This script loads the intro movie for act2 and loads the savage land map" )
startMovie("Cine03", "afterMovie" )
waitsignal ( "afterMovie" )
# ( "Unlock Age of Apocalypse skins" )
unlockCharacter("", "aoa" )
loadZone("act3/military/military1", "link_military1" )

