# Generated by BehavEd
# ( "comment" )
activator = getID("_ACTIVATOR_" )
owner = getID("_OWNER_" )
if activator != owner
     act("_OWNER_", "_OWNER_" )
     extractionPoint("_OWNER_" )
else
     extractionUnlock("" )
endif

