# Generated by BehavEd
# ( "enter the omega red arena" )
setWaypointPath("red", "", 0 )
setRecallActive("FALSE" )
setEngageEnemy("red", "TRUE" )
setDefaultTarget("red" )
attackEntityWithType("red", "_ACTIVE_HERO_", "ANY", "FALSE" )

