# Generated by BehavEd
# ( "comment" )
met = getGameFlag("bosses", 12 )
if met == 0
     setGameFlag("bosses", 12, 1 )
     lockControls(-1.000 )
     setallaiactive("FALSE" )
     cameraMove(" 1311.740 5906.330 -39.047 ", 1.000 )
     cameraPan(" 0.000 20.000 85.000 ", 1.000, "FALSE" )
     waittimed ( 1.500 )
     copyOriginAndAngles("_HERO1_", "herospot01" )
     copyOriginAndAngles("_HERO2_", "herospot02" )
     copyOriginAndAngles("_HERO3_", "herospot03" )
     copyOriginAndAngles("_HERO4_", "herospot04" )
     lockControls(0.100 )
     setallaiactive("TRUE" )
     startConversation("act2/monument/monument3/2_monument3_0020" )
else
     waittimed ( 0.200 )
     setDefaultTarget("red" )
     waittimed ( 20.000 )
     act("minion_spawner", "minion_spawner" )
endif

