# Generated by BehavEd
# ( "spawn minions if not too many" )
minions = getZoneVar("minions" )
if minions < 4
     act("minion01", "minion01" )
     minions2 = iadd(minions, 1 )
     if minions < 3
          act("minion02", "minion02" )
          minions2 = iadd(minions2, 1 )
     endif
     setZoneVar("minions", minions2 )
endif

