# Generated by BehavEd
# ( "has the tech station been used?" )
station = getGameFlag("monument3", 1 )
if station == 1
     # ( "station has been used--lower pillar, remove flame" )
     act("tech_pillar", "tech_pillar" )
     remove ( "tech_flame", "tech_flame" )
     remove ( "relay_station", "relay_station" )
endif
# ( "has omega red been defeated?" )
red_check = getGameFlag("bosses", 13 )
if red_check == 1
     # ( "omega red has been defeated--remove him!" )
     waittimed ( 1.000 )
     remove ( "red", "red" )
     remove ( "trig_red", "trig_red" )
     remove ( "red_arena", "red_arena" )
     # ( "the teleporter and zone_link to mikhail's ship must be active" )
     act("light_teleporter01", "light_teleporter01" )
     act("portal_loop", "portal_loop" )
     setEnable("link_mikhail", "TRUE" )
endif

