# Generated by BehavEd
# ( "indicate omega red has been defeated" )
remove ( "minion_spawner", "minion_spawner" )
remove ( "minion01", "minion01" )
remove ( "minion02", "minion02" )
setDefaultTarget("" )
setGameFlag("bosses", 13, 1 )
killEntity("or_minion" )
objective ( "act2_obj_6",  "EOBJCMD_SHOW" )
waittimed ( 4.000 )
# ( "the x-men will now celebrate by having a conversation" )
remove ( "red_arena", "red_arena" )
startConversation("act2/monument/monument3/2_monument3_0030" )

