# Generated by BehavEd
# ( "This script checks which conversatoin should be called" )
# ( "This checks to see if players has seen the gateway yet" )
seen_gateway = getObjective("act2_obj_5c", "HIDDEN" )
if seen_gateway == 0
     startConversation("act2/monument/2_sometime2_0020" )
else
     startConversation("act2/monument/2_sometime2_0030" )
endif

