# Generated by BehavEd
# ( "if player has the Breath artifact, enable zone transporter, and if he does not, just start dialogue" )
setCurrentAct(3 )
breath_artifact = getObjective("act3_obj_6d_a", "COMPLETE" )
if breath_artifact == 1
     # ( "you have the artifact and you're at the altar" )
     setOrigin("dummy_breath", " 7508.476 2460.048 38.592 " )
     act("breath_fire", "breath_fire" )
     objective ( "act3_obj_6d",  "EOBJCMD_COMPLETE" )
     remove ( "breath_trigger", "breath_trigger" )
     act("relay01", "relay01" )
     copyOriginAndAngles("cuckoo", "cuckoo_null4" )
     fadeIn("cuckoo", 2.000 )
else
     # ( "you don't have the artifact but you're at the altar" )
     startConversation("act3/madri/madri1/3_MADRI1_0034" )
     objective ( "act3_obj_6d_a",  "EOBJCMD_SHOW" )
endif

