# Generated by BehavEd
# ( "comment" )
setGameFlag("artifacts", 1, 1 )
setGameFlag("artifacts", 2, 1 )
setGameFlag("artifacts", 3, 1 )
setGameFlag("artifacts", 4, 1 )
setGameFlag("artifacts", 5, 1 )

