# Generated by BehavEd
# ( "if player has the consumption artifact, enable zone transporter, and if he does not, just start dialogue" )
setCurrentAct(3 )
consumption_artifact = getObjective("act3_obj_6a_a", "COMPLETE" )
if consumption_artifact == 1
     # ( "you have the artifact and you're at the altar" )
     setOrigin("dummy_con", " 8698.854 1982.720 38.592 " )
     act("con_fire", "con_fire" )
     act("relay01", "relay01" )
     setGameFlag("minddoor", 3, 1 )
     remove ( "consume_trigger", "consume_trigger" )
     objective ( "act3_obj_6a",  "EOBJCMD_COMPLETE" )
     copyOriginAndAngles("cuckoo", "cuckoo_null2" )
     fadeIn("cuckoo", 2.000 )
else
     # ( "you don't have the artifact but you're at the altar" )
     objective ( "act3_obj_6a_a",  "EOBJCMD_SHOW" )
     startConversation("act3/madri/madri1/3_MADRI1_0030" )
endif

