# Generated by BehavEd
# ( "if player has the heart artifact, enable zone transporter, and if he does not, just start dialogue" )
setCurrentAct(3 )
heart_artifact = getObjective("act3_obj_6c_a", "COMPLETE" )
if heart_artifact == 1
     # ( "you have the artifact and you're at the altar" )
     setOrigin("dummy_heart", " 8698.854 2459.063 38.592 " )
     act("heart_fire", "heart_fire" )
     objective ( "act3_obj_6c",  "EOBJCMD_COMPLETE" )
     remove ( "heart_trigger", "heart_trigger" )
     act("relay01", "relay01" )
     copyOriginAndAngles("cuckoo", "cuckoo_null3" )
     fadeIn("cuckoo", 2.000 )
else
     # ( "you don't have the artifact but you're at the altar" )
     objective ( "act3_obj_6c_a",  "EOBJCMD_SHOW" )
     startConversation("act3/madri/madri1/3_MADRI1_0032" )
endif

