# Generated by BehavEd
# ( "set current act and show main objective" )
objective ( "act3_obj_6",  "EOBJCMD_SHOW" )
objective ( "act3_obj_6a_1",  "EOBJCMD_SHOW" )
objective ( "act3_obj_6a_1",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_6a_2",  "EOBJCMD_SHOW" )
objective ( "act3_obj_6a_2",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_6a_3",  "EOBJCMD_SHOW" )
# ( "consumption done" )
consumption_done = getObjective("act3_obj_6a", "COMPLETE" )
if consumption_done == 1
     setOrigin("dummy_con", " 8698.854 1982.720 38.592 " )
     act("con_fire", "con_fire" )
     setGameFlag("minddoor", 3, 1 )
     remove ( "consume_trigger", "consume_trigger" )
endif
check = getObjective("act3_obj_6a_a", "COMPLETE" )
if check == 1
     setEnable("link01_madri2", "TRUE" )
     act("portal_con_start", "portal_con_start" )
     act("portal_loop_con", "portal_loop_con" )
     setHintType("consume_trigger", "objective" )
endif
# ( "purity done" )
purity_done = getObjective("act3_obj_6b", "COMPLETE" )
if purity_done == 1
     setOrigin("dummy_purity", " 7508.333 1976.448 38.592 " )
     act("purity_fire", "purity_fire" )
     setGameFlag("minddoor", 1, 1 )
     remove ( "purity_trigger", "purity_trigger" )
endif
check = getObjective("act3_obj_6b_a", "COMPLETE" )
if check == 1
     setEnable("link_madri3", "TRUE" )
     act("portal_pure_start", "portal_pure_start" )
     act("portal_loop_pure", "portal_loop_pure" )
     setHintType("purity_trigger", "objective" )
endif
# ( "heart done" )
heart_done = getObjective("act3_obj_6c", "COMPLETE" )
if heart_done == 1
     setOrigin("dummy_heart", " 8698.854 2459.063 38.592 " )
     act("heart_fire", "heart_fire" )
     setGameFlag("minddoor", 4, 1 )
     remove ( "heart_trigger", "heart_trigger" )
endif
check = getObjective("act3_obj_6c_a", "COMPLETE" )
if check == 1
     setEnable("link_madri4", "TRUE" )
     act("portal_hearth_start", "portal_heart_start" )
     act("portal_loop_heart", "portal_loop_heart" )
     setHintType("heart_trigger", "objective" )
endif
# ( "breath done" )
breath_done = getObjective("act3_obj_6d", "COMPLETE" )
if breath_done == 1
     setOrigin("dummy_breath", " 7508.476 2460.048 38.592 " )
     act("breath_fire", "breath_fire" )
     setGameFlag("minddoor", 2, 1 )
     remove ( "breath_trigger", "breath_trigger" )
endif
check = getObjective("act3_obj_6d_a", "COMPLETE" )
if check == 1
     setEnable("link_madri5", "TRUE" )
     act("portal_breath_start", "portal_breath_start" )
     act("portal_loop_breath", "portal_loop_breath" )
     setHintType("breath_trigger", "objective" )
endif
# ( "mind done" )
if purity_done == 1
     if consumption_done == 1
          if heart_done == 1
               if breath_done == 1
                    remove ( "door_mind1", "door_mind1" )
                    remove ( "mind_trigger01", "mind_trigger01" )
               endif
          endif
     endif
endif
mind_done = getObjective("act3_obj_6e", "COMPLETE" )
if mind_done == 1
     act("door_mind1", "door_mind1" )
     remove ( "mind_trigger01", "mind_trigger01" )
     remove ( "mind_trigger", "mind_trigger" )
     copyOriginAndAngles("dummy_mind", "relay_mind" )
     setEnable("link_madri7", "TRUE" )
     act("portal_loop_holo", "portal_loop_holo" )
endif
check = getObjective("act3_obj_6e_a", "COMPLETE" )
if check == 1
     setEnable("link_madri6", "TRUE" )
     act("portal_mind_start", "portal_mind_start" )
     act("portal_loop_mind", "portal_loop_mind" )
     setHintType("mind_trigger", "objective" )
endif
# ( "if conv 1 done" )
altar_conv_complete = getGameFlag("madri_conv", 1 )
if altar_conv_complete == 1
     remove ( "altar_room_trigger_1", "altar_room_trigger_1" )
     remove ( "altar_room_trigger_2", "altar_room_trigger_2" )
     remove ( "altar_room_trigger_3", "altar_room_trigger_3" )
     remove ( "altar_room_trigger_4", "altar_room_trigger_4" )
     remove ( "priest_1_s", "priest_1_s" )
     remove ( "priest_2_s", "priest_2_s" )
     remove ( "priest_3_s", "priest_3_s" )
     remove ( "priest_4_s", "priest_4_s" )
     remove ( "priest_leader_1_s", "priest_leader_1_s" )
     remove ( "priest_leader_2_s", "priest_leader_2_s" )
     remove ( "hellhound_2_s", "hellhound_2_s" )
     remove ( "hellhound_1_s", "hellhound_1_s" )
     remove ( "hellhound_3_s", "hellhound_3_s" )
     remove ( "hellhound_4_s", "hellhound_4_s" )
endif
# ( "if conv 2 done" )
dontDoThisConv = getGameFlag("madri_conv", 2 )
if dontDoThisConv == 1
     remove ( "conv_2_trigger", "conv_2_trigger" )
endif
# ( "if conv 3 done" )
opening_conv = getGameFlag("madri_conv", 3 )
if opening_conv == 0
     setGameFlag("madri_conv", 3, 1 )
     objective ( "act3_obj_6a_3",  "EOBJCMD_SHOW" )
     startConversation("act3/madri/madri1/3_MADRI1_0010" )
endif

