# Generated by BehavEd
# ( "Show mind_artifact objective completel enable mind chamber doors, remove door triggers" )
mind_artifact = getObjective("act3_obj_6e_a", "COMPLETE" )
if mind_artifact == 1
     # ( "you have the artifact and you're at the altar" )
     copyOriginAndAngles("dummy_mind", "relay_mind" )
     act("mind_fire", "mind_fire" )
     setEnable("link_madri6", "TRUE" )
     setEnable("link_angel", "TRUE" )
     act("portal_holo_start", "portal_holo_start" )
     waittimed ( 0.750 )
     act("portal_loop_holo", "portal_loop_holo" )
     remove ( "portal_holo_start", "portal_holo_start" )
     remove ( "mind_trigger01", "mind_trigger01" )
     objective ( "act3_obj_6e",  "EOBJCMD_COMPLETE" )
     act("relay01", "relay01" )
     copyOriginAndAngles("cuckoo", "cuckoo_null6" )
     fade("cuckoo", 0.500, 2.000, "TRUE" )
else
     # ( "you don't have the artifact but you're at the altar" )
     objective ( "act3_obj_6a_a",  "EOBJCMD_SHOW" )
     startConversation("act3/madri/madri1/3_MADRI1_0038" )
endif

