# Generated by BehavEd
# ( "Show mind_artifact objective completel enable mind chamber doors, remove door triggers" )
setGameFlag("artifacts", 5, 1 )
setEnable("door_mind1", "TRUE" )
remove ( "mind_trigger01", "mind_trigger01" )

