# Generated by BehavEd
# ( "if player has the Purity artifact, enable zone transporter, and if he does not, just start dialogue" )
setCurrentAct(3 )
purity_artifact = getObjective("act3_obj_6b_a", "COMPLETE" )
if purity_artifact == 1
     # ( "you have the artifact and you're at the altar" )
     objective ( "act3_obj_6b",  "EOBJCMD_COMPLETE" )
     setOrigin("dummy_purity", " 7508.333 1976.448 38.592 " )
     act("purity_fire", "purity_fire" )
     act("relay01", "relay01" )
     remove ( "purity_trigger", "purity_trigger" )
     copyOriginAndAngles("cuckoo", "cuckoo_null1" )
     fadeIn("cuckoo", 2.000 )
else
     # ( "you don't have the artifact but you're at the altar" )
     objective ( "act3_obj_6b_a",  "EOBJCMD_SHOW" )
     startConversation("act3/madri/madri1/3_MADRI1_0036" )
endif

