# Generated by BehavEd
# ( "plays conversation based on how many artifacts placed" )
placed = iadd(0, 0 )
check = getObjective("act3_obj_6a", "COMPLETE" )
if check == 1
     placed = iadd(placed, 1 )
endif
check = getObjective("act3_obj_6b", "COMPLETE" )
if check == 1
     placed = iadd(placed, 1 )
endif
check = getObjective("act3_obj_6c", "COMPLETE" )
if check == 1
     placed = iadd(placed, 1 )
endif
check = getObjective("act3_obj_6d", "COMPLETE" )
if check == 1
     placed = iadd(placed, 1 )
endif
check = getObjective("act3_obj_6e", "COMPLETE" )
if check == 1
     placed = iadd(placed, 1 )
endif
# ( "plays conversation based on how many artifacts placed" )
if placed == 1
     # ( "spawn cuckoos here someday" )
     startConversation("act3/madri/madri1/3_MADRI1_0040" )
elif placed == 2
     # ( "spawn cuckoos here someday" )
     startConversation("act3/madri/madri1/3_MADRI1_0050" )
elif placed == 3
     # ( "spawn cuckoos here someday" )
     startConversation("act3/madri/madri1/3_MADRI1_0060" )
elif placed == 4
     # ( "spawn cuckoos here someday" )
     setallaiactive("FALSE" )
     cameraFade(1.000, 0.500 )
     waittimed ( 0.500 )
     cameraFade(0.000, 0.500 )
     cameraMove(" 8099.486 2565.989 311.508 ", 0.000 )
     cameraPan(" 0.000 40.000 90.000 ", 0.000, "FALSE" )
     waittimed ( 2.000 )
     act("door_mind1", "door_mind1" )
     remove ( "mind_trigger01", "mind_trigger01" )
     waittimed ( 2.000 )
     cameraFade(1.000, 0.500 )
     waittimed ( 0.500 )
     cameraReset( )
     cameraFade(0.000, 0.500 )
     setallaiactive("TRUE" )
     startConversation("act3/madri/madri1/3_MADRI1_0070" )
elif placed == 5
     # ( "spawn cuckoos here someday" )
     setEnable("link_madri7", "TRUE" )
     act("portal_mind_start", "portal_mind_start" )
     act("portal_loop_mind", "portal_loop_mind" )
     startConversation("act3/madri/madri1/3_MADRI1_0080" )
endif

