# Generated by BehavEd
# ( "comment" )
setGameFlag("tunnels", 7, 1 )
objective ( "a1_cluster",  "EOBJCMD_INCREMENT" )
clustercount = getObjective("a1_cluster", "COUNT" )
if clustercount == 4
     objective ( "a1_cluster",  "EOBJCMD_COMPLETE" )
     startConversation("act1/insect/insect2/1_INSECT2_0020" )
endif

