# Generated by BehavEd
# ( "This shows the eggs cluster" )
heroNoTarget("TRUE" )
enemiesNoTarget("TRUE" )
lockControls(0.000 )
cameraMove(" 741.000 1278.000 296.000 ", 2.000 )
cameraPan(" 0.000 45.000 49.300 ", 0.000, "FALSE" )
waittimed ( 2.000 )
lockControls(0.100 )
heroNoTarget("FALSE" )
enemiesNoTarget("FALSE" )
objective ( "a1_cluster",  "EOBJCMD_SHOW" )
startConversation("act1/insect/insect2/1_INSECT2_0010" )

