# Generated by BehavEd
# ( "has the destroy cluster quest been shown?" )
questchk = getObjective("a1_cluster", "HIDDEN" )
if questchk == 0
     # ( "quest is shown--remove conversation/objective trigger" )
     remove ( "trig_cluster", "trig_cluster" )
endif
# ( "has cluster1 been destroyed?" )
clusterchk = getGameFlag("tunnels", 7 )
if clusterchk == 1
     # ( "cluster has been destroyed--remove it" )
     remove ( "cluster1", "cluster1" )
endif
# ( "has cluster2 been destroyed?" )
clusterchk = getGameFlag("tunnels", 8 )
if clusterchk == 1
     # ( "cluster has been destroyed--remove it" )
     remove ( "cluster2", "cluster2" )
endif
# ( "has cluster3 been destroyed?" )
clusterchk = getGameFlag("tunnels", 9 )
if clusterchk == 1
     # ( "cluster has been destroyed--remove it" )
     remove ( "cluster3", "cluster3" )
endif
# ( "has cluster4 been destroyed?" )
clusterchk = getGameFlag("tunnels", 10 )
if clusterchk == 1
     # ( "cluster has been destroyed--remove it" )
     remove ( "cluster4", "cluster4" )
endif

