# Generated by BehavEd
# ( "comment" )
# ( " found Queen flag" )
waittimed ( 1.000 )
setGameFlag("tower", 1, 1 )
objective ( "act4_obj_5a",  "EOBJCMD_COMPLETE" )
objective ( "act4_obj_5b",  "EOBJCMD_SHOW" )
cameraFocusToEntity("p2spot01", 256.000, 40.000, 190.000, 1.000 )
startConversation("act4/tower/tower2/4_tower2_0010" )

