# Generated by BehavEd
# ( "comment" )
# ( "already talked to Queen flag." )
setGameFlag("tower", 3, 1 )
startConversation("act4/tower/tower2/4_tower2_0020" )
objective ( "act4_obj_5c",  "EOBJCMD_COMPLETE" )

