# Generated by BehavEd
# ( "comment" )
playanim (  "EA_IDLE1", "_OWNER_", "LOOP", "" )
waittimed ( 0.500 )
rem_scar1 = getGameFlag("rem_scar", 1 )
if rem_scar1 ==  1
     remove ( "scarlett_rescue1", "scarlett_rescue1" )
endif

