# Generated by BehavEd
# ( "comment" )
act("scarlet_teleffect", "scarlet_teleffect" )
waittimed ( 0.500 )
remove ( "scarlett_rescue1", "scarlett_rescue1" )
lockControls(0.100 )
waittimed ( 1.500 )
remove ( "scarlet_teleffect", "scarlet_teleffect" )
setGameFlag("rem_scar", 1, 1 )
objective ( "act4_obj_5",  "EOBJCMD_COMPLETE" )

