# Generated by BehavEd
# ( "comment" )
# ( "if so, remove the conversation trigger" )
# ( "have we already found Queen?" )
tow_check1 = getGameFlag("tower", 1 )
if tow_check1 ==  1
     remove ( "find_scarlett_convo", "find_scarlett_convo" )
endif
waittimed ( 0.250 )
# ( "have we disabled the power already?" )
# ( "if so, remove the 4 generators, effects, jail force field, change lighting" )
tow_check2 = getGameFlag("tower", 2 )
if tow_check2 ==  1
     remove ( "scarlett_barrier_jail", "scarlett_barrier_jail" )
     remove ( "core_relay", "core_relay" )
     setAmbientLightColor(" 0.380 0.000 0.000 " )
     waittimed ( 0.250 )
     killEntity("gen1" )
     killEntity("gen2" )
     killEntity("gen3" )
     killEntity("gen4" )
     remove ( "gen1_fx", "gen1_fx" )
     remove ( "gen2_fx", "gen2_fx" )
     remove ( "gen3_fx", "gen3_fx" )
     remove ( "gen4_fx", "gen4_fx" )
     act("flux_beam", "flux_beam" )
     setEnable("find_scarlett_convo", "FALSE" )
     setEnable("rescued_scarlett_convo", "TRUE" )
     act("power_light", "power_light" )
     setHintType("scarlett_rescue", "importanttalk" )
endif
waittimed ( 0.250 )
# ( "have we rescued the black queen?" )
# ( "if so, nix her" )
tow_check3 = getGameFlag("tower", 3 )
if tow_check3 ==  1
     waittimed ( 0.250 )
     remove ( "scarlett_barrier_jail", "scarlett_barrier_jail" )
     remove ( "core_relay", "core_relay" )
     remove ( "p2spot01", "p2spot01" )
     remove ( "scarlet_teleffect", "scarlet_teleffect" )
     remove ( "rescued_scarlett_convo", "rescued_scarlett_convo" )
endif
waittimed ( 1.000 )
rem_scar1 = getGameFlag("rem_scar", 1 )
if rem_scar1 ==  1
     remove ( "scarlett_rescue1", "scarlett_rescue1" )
     remove ( "scarlett_rescue", "scarlett_rescue" )
endif

