# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept10.png" )
imageViewer("textures/concept/concept11.png" )
imageViewer("textures/concept/concept12.png" )

