# Generated by BehavEd
# ( "retract slow pylon" )
waittimed ( 1.000 )
pid = getParentID("_OWNER_" )
act(pid, pid )
setNoCollideNoTickle(pid, "TRUE" )
# ( "create a replacement for myself" )
tid = spawn(pid, "turnon_trig", "turnon_trig", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
setParent(tid, pid )
# ( "remove myself, effectively removing the harment attached to it." )
killEntity("_OWNER_" )

