# Generated by BehavEd
# ( "deploy slow pylon" )
pid = getParentID("_OWNER_" )
act(pid, pid )
setNoCollideNoTickle(pid, "FALSE" )
tid = spawn(pid, "slow_trigr", "slow_trigr", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
setParent(tid, "_OWNER_" )

