# Generated by BehavEd
# ( "comment" )
# ( "comment" )
lockControls(0.000 )
heroNoTarget("TRUE" )
# ( "camera looks at the leader coming through the door" )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
cameraMove(" 1638.840 4159.430 144.810 ", 1.000 )
cameraPan(" 0.000 27.400 80.200 ", 0.000, "FALSE" )
waittimed ( 1.000 )
cameraFade(0.000, 0.500 )
# ( "moves the players to their spots" )
# ( "but checks to see if they are alive first" )
isHero1Alive = alive("_HERO1_" )
if isHero1Alive == 1
     # ( "hero1 is alive" )
     copyOriginAndAngles("_HERO1_", "herospot01" )
else
     # ( "hero1 is dead as a doornail" )
endif
isHero2Alive = alive("_HERO2_" )
if isHero2Alive == 1
     # ( "hero2 is alive" )
     copyOriginAndAngles("_HERO2_", "herospot02" )
else
     # ( "hero2 is dead as a doornail" )
endif
isHero3Alive = alive("_HERO3_" )
if isHero3Alive == 1
     # ( "hero3 is alive" )
     copyOriginAndAngles("_HERO3_", "herospot03" )
else
     # ( "hero3 is dead as a doornail" )
endif
isHero4Alive = alive("_HERO4_" )
if isHero4Alive == 1
     # ( "hero4 is alive" )
     copyOriginAndAngles("_HERO4_", "herospot04" )
else
     # ( "hero4 is dead as a doornail" )
endif
act("ambush_leader", "ambush_leader" )
act("ambush_larry", "ambush_larry" )
act("ambush_curly", "ambush_curly" )
act("ambush_moe", "ambush_moe" )
waittimed ( 2.000 )
cameraMove(" 1719.780 4211.870 155.070 ", 1.000 )
cameraPan(" 0.000 32.400 244.300 ", 0.000, "FALSE" )
waittimed ( 2.000 )
# ( "locks the players in" )
copyOriginAndAngles("forcefield02", "field_spot01" )
waittimed ( 1.000 )
lockControls(0.100 )
cameraResetOldSchool( )
heroNoTarget("FALSE" )

