# Generated by BehavEd
# ( "power puzzle - charge and destroy generator" )
act("loop_sparks04", "loop_sparks04" )
waittimed ( 1.000 )
awardXPToPlayable(4000 )
waittimed ( 0.500 )
killEntity("machine_02" )

