# Generated by BehavEd
# ( "power puzzle - charge and destroy generator" )
act("loop_sparks02", "loop_sparks02" )
waittimed ( 1.000 )
awardXPToPlayable(4000 )
waittimed ( 0.500 )
killEntity("machine_01" )

