# Generated by BehavEd
# ( "WARNING - objective testing...do not use" )
# ( "which prisoners have been rescued on previous visits?" )
a01 = getGameFlag("prisoners", 4 )
if a01 == 1
     # ( "prisoner has been rescued already -- target for destruction!" )
     remove ( "prisoner_a01", "prisoner_a01" )
endif
a02 = getGameFlag("prisoners", 5 )
if a02 == 1
     # ( "prisoner has been rescued already -- target for destruction!" )
     remove ( "prisoner_a02", "prisoner_a02" )
endif
a03 = getGameFlag("prisoners", 6 )
if a03 == 1
     # ( "prisoner has been rescued already -- target for destruction!" )
     remove ( "prisoner_a03", "prisoner_a03" )
endif
b01 = getGameFlag("prisoners", 7 )
if b01 == 1
     # ( "prisoner has been rescued already -- target for destruction!" )
     remove ( "prisoner_b01", "prisoner_b01" )
endif
b02 = getGameFlag("prisoners", 8 )
if b02 == 1
     # ( "prisoner has been rescued already -- target for destruction!" )
     remove ( "prisoner_b02", "prisoner_b02" )
endif
b03 = getGameFlag("prisoners", 9 )
if b03 == 1
     # ( "prisoner has been rescued already -- target for destruction!" )
     remove ( "prisoner_b03", "prisoner_b03" )
endif
sinicheck = getGameFlag("prisoners", 21 )
if sinicheck == 1
     remove ( "sp_mrsinister01", "sp_mrsinister01" )
     remove ( "siniprisoner1", "siniprisoner1" )
     remove ( "siniprisoner2", "siniprisoner2" )
     remove ( "trigger_sinister", "trigger_sinister" )
     setGameFlag("prisoners", 22, 1 )
else
     # ( "if you met sinister in IPP, don't spawn him." )
     sinicheck = getGameFlag("bosses", 17 )
     if sinicheck == 1
          remove ( "sp_mrsinister01", "sp_mrsinister01" )
          remove ( "siniprisoner1", "siniprisoner1" )
          remove ( "siniprisoner2", "siniprisoner2" )
          remove ( "trigger_sinister", "trigger_sinister" )
          setGameFlag("prisoners", 21, 1 )
          setGameFlag("prisoners", 22, 1 )
     endif
endif

