# Generated by BehavEd
# ( "act on counter, increment objective" )
setZoneVar("talktalk", 0 )
objective ( "act1_obj_5c",  "EOBJCMD_INCREMENT" )
# ( "after thanking the player, prisoner fades and is removed" )
spawnEffect("_OWNER_", "map/common/scr_blinkportal_s", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
fade("_OWNER_", 0.000, 3.000, "TRUE" )
waittimed ( 0.300 )
spawnEffect("_OWNER_", "map/common/scr_blinkportal_c", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
remove ( "_OWNER_", "_OWNER_" )
# ( "have all genosha2 prisoners been rescued?" )
gen2 = getObjective("act1_obj_5c", "COMPLETE" )
if gen2 == 1
     # ( "have all genosha1 prisoners been rescued?" )
     gen1 = getObjective("act1_obj_5b", "COMPLETE" )
     if gen1 == 1
          startConversation("act1/genosha/genosha2/1_GENOSHA2_0011" )
     endif
endif

