# Generated by BehavEd
isTalk = getZoneVar("talktalk" )
if isTalk == 0
     setZoneVar("talktalk", 1 )
     # ( "indicate this prisoner has been rescued" )
     setGameFlag("prisoners", 9, 1 )
     # ( "the prisoner thanks the X-men before disappearing" )
     startConversation("act1/genosha/genosha2/1_genosha2_0036" )
else
     waittimed ( 1.000 )
     setEnable("_OWNER_", "TRUE" )
     setHintType("_OWNER_", "importanttalk" )
endif

