# Generated by BehavEd
# ( "rescued prisoner 1!" )
# ( "checks to be sure the dudes aren't dead :(" )
playanim (  "EA_IDLE1", "sin_prisoner1", "NONE", "" )
setNoGravity("sin_prisoner1", "FALSE" )
dudes = getGameFlag("prisoners", 22 )
if dudes == 0
     setZoneFlag("sin_p", 1, 1 )
     savedboth = getZoneFlag("sin_p", 2 )
     if savedboth == 1
          setallaiactive("FALSE" )
          setGameFlag("prisoners", 22, 1 )
          setGameFlag("prisoners", 23, 1 )
          timerStart(-1.000, 0.000, "" )
          waittimed ( 0.500 )
          cameraFade(1.000, 1.000 )
          waittimed ( 1.000 )
          cameraFocusToEntity("prisoner_cam", 512.000, 40.000, 195.000, 0.000 )
          cameraFade(0.000, 1.000 )
          startConversation("act1/genosha/genosha2/1_GENOSHA2_0030" )
     endif
endif

