# Generated by BehavEd
# ( "makes Mr. Sinister push button" )
faceEntity("sinister", "controlpanel" )
playanim (  "EA_USE_BUTTON", "sinister", "NONE", "button" )
waitsignal ( "button" )
faceEntity("sinister", "_HERO1_" )

