# Generated by BehavEd
# ( "kills the dudes not saved :(" )
timerStart(-1.000, 0.000, "" )
setGameFlag("prisoners", 22, 1 )
prisoner = getZoneFlag("sin_p", 1 )
if prisoner == 0
     killEntity("scanner01" )
     spawnEffect("sin_prisoner1", "map/infinite/scr_clonespawner", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     remove ( "sin_prisoner1", "sin_prisoner1" )
     act("sinmonster1", "sinmonster1" )
else
     fade("sin_prisoner1", 0.000, 1.000, "TRUE" )
     remove ( "sin_prisoner1", "sin_prisoner1" )
endif
prisoner = getZoneFlag("sin_p", 2 )
if prisoner == 0
     killEntity("scanner02" )
     spawnEffect("sin_prisoner1", "map/infinite/scr_clonespawner", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     remove ( "sin_prisoner2", "sin_prisoner2" )
     act("sinmonster2", "sinmonster2" )
else
     fade("sin_prisoner2", 0.000, 1.000, "TRUE" )
     remove ( "sin_prisoner2", "sin_prisoner2" )
endif

