# Generated by BehavEd
# ( "DR Bastion script" )
act("sp_bastion01", "sp_bastion01" )
waittimed ( 4.000 )
setCombatNode("bastion", "power_xtreme" )
waittimed ( 1.000 )
act("bastion_sentinel01", "bastion_sentinel01" )
act("bastion_sentinel02", "bastion_sentinel02" )

