# Generated by BehavEd
# ( "if you've freed Pyro and he hasn't said his farewell speech, play it now" )
ava_save = getGameFlag("prisoners", 2 )
if ava_save == 1
     ava_save = getGameFlag("prisoners", 3 )
     if ava_save == 0
          setGameFlag("prisoners", 3, 1 )
          startCharConversation("act1/genosha/genosha3/1_GENOSHA3_0030", "sunfire", "act1/genosha/genosha3/1_GENOSHA3_0031" )
     endif
endif

