# Generated by BehavEd
# ( "Starts conversation with Pyro asking to be freed." )
act("avalanche01", "avalanche01" )
lockControls(-1.000 )
setallaiactive("FALSE" )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
moveHeroesToEnt("pyro_place" )
cameraFocusToEntity("avalanche", 450.000, 30.000, 160.000, 0.000 )
cameraFade(0.000, 1.000 )
waittimed ( 0.750 )
startCharConversation("act1/genosha/genosha3/1_genosha3_0010", "gambit", "act1/genosha/genosha3/1_genosha3_0011" )

