# Generated by BehavEd
# ( "genosha3 zonescript" )
setGameFlag("act1_visit", 10, 1 )
ava_free = getGameFlag("prisoners", 2 )
ava_free2 = getGameFlag("act1_visit", 17 )
if ava_free == 1
     remove ( "computer_burned_out_01_b_gn01", "computer_burned_out_01_b_gn01" )
     remove ( "trigger_touch02", "trigger_touch02" )
     remove ( "trigger_touch01", "trigger_touch01" )
     remove ( "ff_avalanche", "ff_avalanche" )
     remove ( "avalanche01", "avalanche01" )
     pyro_byebye = getGameFlag("prisoners", 3 )
     if pyro_byebye == 0
          remove ( "avalanche", "avalanche" )
          act("avalanche02", "avalanche02" )
     else
          remove ( "avalanche", "avalanche" )
          remove ( "avalanche02", "avalanche02" )
     endif
elif ava_free2 == 1
     remove ( "computer_burned_out_01_b_gn01", "computer_burned_out_01_b_gn01" )
     remove ( "trigger_touch02", "trigger_touch02" )
     remove ( "trigger_touch01", "trigger_touch01" )
     remove ( "ff_avalanche", "ff_avalanche" )
     remove ( "avalanche01", "avalanche01" )
     remove ( "avalanche", "avalanche" )
     remove ( "avalanche02", "avalanche02" )
endif
bigdoor = getGameFlag("prisoners", 24 )
if bigdoor == 1
     remove ( "bigdoor", "bigdoor" )
     setEnable("openbigdoor", "FALSE" )
     setEnable("link_genosha4", "TRUE" )
endif
pyrogen1 = getGameFlag("prisoners", 26 )
pyrogen2 = getGameFlag("prisoners", 27 )
if pyrogen1 == 1
     swapInStump("pyro_gener1" )
     remove ( "light_comp1", "light_comp1" )
     if pyrogen2 == 1
          swapInStump("pyro_gener2" )
          remove ( "light_comp2", "light_comp2" )
          remove ( "pyrodoor", "pyrodoor" )
          remove ( "pyrodoor_spark", "pyrodoor_spark" )
          setEnable("door_hint", "FALSE" )
     endif
elif pyrogen2 == 1
     swapInStump("pyro_gener2" )
     remove ( "light_comp2", "light_comp2" )
endif

