# Generated by BehavEd
# ( "comment" )
act("ss_energydemon_b12", "ss_energydemon_b12" )
act(" ss_energydemon_b14", " ss_energydemon_b14" )
act(" ss_energydemon_b13", " ss_energydemon_b13" )
act("bigdoor", "bigdoor" )
setEnable("link_genosha4", "TRUE" )
timerStart(30.000, 0.000, "act1/genosha/genosha3/dooropened" )

