# Generated by BehavEd
# ( "comment" )
playanim (  "EA_PAIN_ELECTRIC", "avalanche", "NONE", "" )
allowsnd = getObjective("act1_avalanche", "HIDDEN" )
if allowsnd == 0
     sound (  "PLAY_SOUND", "voice/pyro/yelp", "avalanche", "" )
endif

