# Generated by BehavEd
# ( "corein2 zonescript" )
visited = getGameFlag("act3_visit", 2 )
if visited == 0
     setGameFlag("act3_visit", 2, 1 )
endif
# ( "checks reactor security quests" )
obj_complete = getObjective("act3_obj_2b", "COMPLETE" )
if obj_complete == 1
     remove ( "ff_1", "ff_1" )
     remove ( "console_core_Sec_Reac", "console_core_Sec_Reac" )
     remove ( "console03_core_b_oc02", "console03_core_b_oc02" )
endif
obj_complete = getObjective("act3_obj_2b_a", "COMPLETE" )
if obj_complete == 1
     remove ( "console_core_Int", "console_core_Int" )
     setEnable("door_generator1", "FALSE" )
     remove ( "magnacarta_door1", "magnacarta_door1" )
     remove ( "magnacarta_door2", "magnacarta_door2" )
     remove ( "trigger_hint_FF", "trigger_hint_FF" )
endif

