# Generated by BehavEd
# ( "comment" )
objective ( "act3_obj_2b_a",  "EOBJCMD_COMPLETE" )
waittimed ( 1.000 )
act("elec_hit", "elec_hit" )
act("magnacarta_door2", "magnacarta_door2" )
act("magnacarta_door1", "magnacarta_door1" )
setHintType("console_core_Int", "none" )
startConversation("act3/corein/corein2/3_COREIN2_0007" )

