# Generated by BehavEd
# ( "start conv that hints at internal force field deactivation process" )
startConversation("act3/corein/corein2/3_corein2_0005" )
objective ( "act3_obj_2b_a",  "EOBJCMD_SHOW" )
setEnable("door_generator1", "TRUE" )

