# Generated by BehavEd
# ( "comment" )
cameraFade(1.000, 0.000 )
cameraToLocationAngles(" 6751.361 1307.861 470.810 ", " 6576.000 1668.000 0.000 ", 0.000 )
# ( "give smart ents 1 second to spawn in after we change cam location" )
waittimed ( 1.000 )
cameraFade(0.000, 1.000 )
waittimed ( 2.000 )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
cameraReset( )
cameraFade(0.000, 1.000 )

