# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept25.png" )
imageViewer("textures/concept/concept26.png" )
imageViewer("textures/concept/concept27.png" )

