# Generated by BehavEd
# ( "gets how many codes have been grabbed" )
codes = iadd(0, 0 )
codes2 = getObjective("act1_obj_2a", "COMPLETE" )
if codes2 == 1
     codes = iadd(codes, 1 )
endif
codes2 = getObjective("act1_obj_2b", "COMPLETE" )
if codes2 == 1
     codes = iadd(codes, 1 )
endif
codes2 = getObjective("act1_obj_2c", "COMPLETE" )
if codes2 == 1
     codes = iadd(codes, 1 )
endif
# ( "allows conversation 1 if only 1 code has been grabbed" )
if codes == 3
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

