# Generated by BehavEd
# ( "show objective" )
cameraFade(1.000, 0.500 )
waittimed ( 0.750 )
remove ( "cin_dude", "cin_dude" )
waittimed ( 0.500 )
cameraFade(0.000, 0.500 )
objective ( "act2_obj_2",  "EOBJCMD_COMPLETE" )
objective ( "act2_obj_2a",  "EOBJCMD_COMPLETE" )
objective ( "act2_obj_3",  "EOBJCMD_SHOW" )
objective ( "act2_obj_3a",  "EOBJCMD_SHOW" )
setGameFlag("gen_comp1", 1, 1 )

