# Generated by BehavEd
# ( "comment" )
setInvisible("_OWNER_", "FALSE" )
setReactToEnemies("_OWNER_", "FALSE" )
setEngageEnemy("_OWNER_", "FALSE" )
time = randomInt(0, 2 )
waittimed ( time )
attackEntityWithType("_OWNER_", "power_transmitter1", "ANY", "TRUE" )

