# Generated by BehavEd
# ( "comment" )
act("atmos_beam02", "atmos_beam02" )
act("atmos_fire02", "atmos_fire02" )
act("fire1_light01", "fire1_light01" )
cameraFocusToEntity("power_transmitter2", 300.000, 45.000, 0.000, 1.000 )
waittimed ( 3.000 )
gameover (  "GAMEOVER_GENERATOR" )

