# Generated by BehavEd
# ( "comment" )
act("atmos_beam03", "atmos_beam03" )
act("atmos_fire03", "atmos_fire03" )
act("fire1_light02", "fire1_light02" )
cameraFocusToEntity("power_transmitter3", 300.000, 45.000, 0.000, 1.000 )
waittimed ( 3.000 )
gameover (  "GAMEOVER_GENERATOR" )

