# Generated by BehavEd
# ( "add one to the number of hits this has taken" )
hits = getZoneVar("gen2hits" )
hits = iadd(hits, 1 )
setZoneVar("gen2hits", hits )
if hits >= 200
     # ( "kill this thing if it has taken enough hits" )
     killEntity("_OWNER_" )
else
     # ( "figure out what its health should be (based on 20 hits)" )
     healthmax = getHealthMax("_OWNER_" )
     thresh = fmul(hits, 0.005 )
     hthresh = fsub(1.000000, thresh )
     # ( "set new health" )
     newhealth = fmul(hthresh, healthmax )
     setHealth("_OWNER_", newhealth )
endif

