# Generated by BehavEd
# ( "comment" )
gen_comp = getGameFlag("gen_comp1", 1 )
if gen_comp == 1
     remove ( "first_trigger", "first_trigger" )
     remove ( "trigger_touch02", "trigger_touch02" )
     remove ( "trigger_touch03", "trigger_touch03" )
     remove ( "trigger_touch01", "trigger_touch01" )
     setRecallActive("TRUE" )
     killEntitySilent("power_transmitter1" )
     setEnable("link_savage1", "TRUE" )
     setEnable("link_jungle5", "TRUE" )
     remove ( "shocktroop1_3", "shocktroop1_3" )
     remove ( "shocktroop1_2", "shocktroop1_2" )
     remove ( "shocktroop1_1", "shocktroop1_1" )
     remove ( "cine_dude", "cine_dude" )
     remove ( "shocktroop1_07", "shocktroop1_07" )
     remove ( "shocktroop1_05", "shocktroop1_05" )
     remove ( "last_troop10", "last_troop10" )
     remove ( "last_troop05", "last_troop05" )
     remove ( "shocktroop1_04", "shocktroop1_04" )
     remove ( "shocktroop1_06", "shocktroop1_06" )
     remove ( "atmos_beam1", "atmos_beam1" )
endif
checkend = getGameFlag("jungle2", 1 )
if checkend == 1
     setEnable("miss_comp", "FALSE" )
endif
checkend1 = getGameFlag("jungle2", 2 )
if checkend == 1
     setEnable("first_trigger", "FALSE" )
else
     setRecallActive("FALSE" )
endif

