# Generated by BehavEd
# ( "if act2_obj_2a is not complete and plyer tries to leave the map" )
gen_complete = getObjective("act2_obj_2a", "COMPLETE" )
if gen_complete == 1
     setEnable("link_jungle5", "TRUE" )
     setEnable("link_savage1", "TRUE" )
     setRecallActive("TRUE" )
     remove ( "trigger_touch01", "trigger_touch01" )
     remove ( "trigger_touch03", "trigger_touch03" )
else
     startConversation("act2/jungle/jungle2/2_jungle2_0030" )
endif

