# Generated by BehavEd
# ( "spawn processor aggressors at processor2 for round 2" )
waittimed ( 0.250 )
act("final1", "final1" )
act("final2", "final2" )
act("final3", "final3" )
act("final4", "final4" )
waittimed ( 0.250 )
remove ( "attack2time_relay02", "attack2time_relay02" )
waittimed ( 0.250 )
startConversation("act2/jungle/jungle2/2_jungle2_0015a" )

