# Generated by BehavEd
# ( "spawn processor aggressors at processor2 for round 2" )
waittimed ( 60.000 )
setEnable("shocktroop1_04", "TRUE" )
setEnable("shocktroop1_06", "TRUE" )
setEnable("shocktroop1_05", "TRUE" )
act("last_troop05", "last_troop05" )
act("shocktroop1_05", "shocktroop1_05" )
act("shocktroop1_06", "shocktroop1_06" )
act("shocktroop1_04", "shocktroop1_04" )
remove ( "attack2_relay02", "attack2_relay02" )
waittimed ( 0.250 )
startConversation("act2/jungle/jungle2/2_jungle2_0015a" )

