# Generated by BehavEd
# ( "spawn processor aggressors at processor3" )
waittimed ( 60.000 )
act("last_troop1", "last_troop1" )
act("last_troop4", "last_troop4" )
act("last_troop3", "last_troop3" )
act("last_troop07", "last_troop07" )
remove ( "attack2_relay", "attack2_relay" )
waittimed ( 0.250 )
startConversation("act2/jungle/jungle2/2_jungle2_0015a" )

