# Generated by BehavEd
# ( "spawn processor aggressors at processor3" )
act("last_troop07", "last_troop07" )
act("last_troop3", "last_troop3" )
act("last_troop4", "last_troop4" )
act("last_troop1", "last_troop1" )
showHealthBar("power_transmitter3", "TRUE" )
remove ( "attack2time_relay03", "attack2time_relay03" )
waittimed ( 0.250 )
startConversation("act2/jungle/jungle2/2_jungle2_0015a" )

