# Generated by BehavEd
# ( "This script randomly picks a baddy spawner and spawns in a baddy" )
random_spawn = randomInt(1, 4 )
crazy3_check = getZoneVar("checkcheck" )
crazy3_check = iadd(crazy3_check, 1 )
setZoneVar("checkcheck", crazy3_check )
if crazy3_check == 45
     remove ( "last_troop2", "last_troop2" )
     remove ( "last_troop09", "last_troop09" )
     remove ( "cin_troop1", "cin_troop1" )
     remove ( "last_troop08", "last_troop08" )
     remove ( "shocktroop1_07", "shocktroop1_07" )
     remove ( "last_troop10", "last_troop10" )
     waittimed ( 0.250 )
     act("miss_comp", "miss_comp" )
     waittimed ( 0.250 )
     killEntity("last_troop08" )
     killEntity("cin_troop1" )
     killEntity("last_troop09" )
     killEntity("last_troop2" )
     killEntity("last_troop07" )
     killEntity("last_troop3" )
     killEntity("last_troop4" )
     killEntity("last_troop1" )
     killEntity("shocktroop1_04" )
     killEntity("shocktroop1_06" )
     killEntity("shocktroop1_05" )
     killEntity("attacker2_last" )
     killEntity("attacker3_last" )
     killEntity("attacker3w2" )
     killEntity("attacker2_3" )
     killEntity("attacker3_2" )
     killEntity("attacker3_1" )
else
     if random_spawn == 1
          act("last_troop10", "last_troop10" )
     endif
     if random_spawn == 2
          act("shocktroop1_07", "shocktroop1_07" )
     endif
     if random_spawn == 3
          act("last_troop05", "last_troop05" )
     endif
endif

