# Generated by BehavEd
# ( "comment" )
act("last_troop1", "last_troop1" )
act("last_troop2", "last_troop2" )
act("last_troop3", "last_troop3" )
act("last_troop4", "last_troop4" )
startConversation("act2/jungle/jungle2/2_jungle2_0015a" )

