# Generated by BehavEd
# ( "This script randomly picks a baddy spawner and spawns in a baddy" )
random_spawn = randomInt(1, 4 )
crazy2_check = getZoneVar("checkcheck" )
crazy2_check = iadd(crazy2_check, 1 )
setZoneVar("checkcheck", crazy2_check )
if crazy2_check == 23
     remove ( "last_troop07", "last_troop07" )
     remove ( "last_troop3", "last_troop3" )
     remove ( "last_troop4", "last_troop4" )
     remove ( "last_troop1", "last_troop1" )
     remove ( "last_troop2", "last_troop2" )
     remove ( "last_troop09", "last_troop09" )
     remove ( "last_troop08", "last_troop08" )
     remove ( "cin_troop1", "cin_troop1" )
     act("attack2_relay02", "attack2_relay02" )
     waittimed ( 0.500 )
     killEntity("last_troop07" )
     killEntity("last_troop3" )
     killEntity("last_troop4" )
     killEntity("last_troop1" )
     killEntity("shocktroop1_04" )
     killEntity("shocktroop1_06" )
     killEntity("shocktroop1_05" )
else
     if random_spawn == 1
          act("last_troop07", "last_troop07" )
     endif
     if random_spawn == 2
          act("last_troop3", "last_troop3" )
     endif
     if random_spawn == 3
          act("last_troop4", "last_troop4" )
     endif
     if random_spawn == 4
          act("last_troop1", "last_troop1" )
     endif
endif

