# Generated by BehavEd
# ( "This script randomly picks a optic spawner and spawns in a opticcrawler" )
random_spawn = randomInt(1, 3 )
crazy1_check = getZoneVar("checkcheck" )
crazy1_check = iadd(crazy1_check, 1 )
setZoneVar("checkcheck", crazy1_check )
if crazy1_check == 11
     setEnable("shocktroop1_04", "FALSE" )
     setEnable("shocktroop1_05", "FALSE" )
     setEnable("shocktroop1_06", "FALSE" )
     act("attack2_relay", "attack2_relay" )
     killEntity("shocktroop1_04" )
     killEntity("shocktroop1_06" )
     killEntity("shocktroop1_05" )
else
     if random_spawn == 1
          act("shocktroop1_04", "shocktroop1_04" )
     endif
     if random_spawn == 2
          act("shocktroop1_05", "shocktroop1_05" )
     endif
     if random_spawn == 3
          act("shocktroop1_06", "shocktroop1_06" )
     endif
endif

