# Generated by BehavEd
# ( "open all door_guardians" )
act("door_guardian", "door_guardian" )
# ( "indicate the guardian has been defeated" )
setGameFlag("monument4", 2, 1 )
# ( "enable blink portal" )
setRecallActive("TRUE" )

