# Generated by BehavEd
# ( "WARNING -- objective testing only -- do not use" )
# ( "has the map been visited before?" )
first_visit = getGameFlag("monument4", 1 )
if first_visit == 0
     setGameFlag("monument4", 1, 1 )
     objective ( "act2_obj_4",  "EOBJCMD_SHOW" )
     objective ( "act2_obj_4a",  "EOBJCMD_SHOW" )
     startConversation("act2/monument/monument4/2_monument4_0020" )
endif
guardian_defeated = getGameFlag("monument4", 2 )
if guardian_defeated == 1
     killEntity("guardian_statue" )
     remove ( "guardian", "guardian" )
     remove ( "trig_stone", "trig_stone" )
     setEnable("switch_west", "FALSE" )
     setEnable("switch_east", "FALSE" )
endif
# ( "has the west switch been used?" )
west = getGameFlag("monument4", 3 )
if west == 1
     setEnable("switch_west", "FALSE" )
endif
# ( "has the east switch been used?" )
east = getGameFlag("monument4", 4 )
if east == 1
     setEnable("switch_east", "FALSE" )
endif
# ( "has the stone been taken?" )
check_stone = getObjective("act2_obj_5b", "COMPLETE" )
if check_stone == 1
     remove ( "guardian_pedestal_stone_e_mo01", "guardian_pedestal_stone_e_mo01" )
     remove ( "trig_stone", "trig_stone" )
endif
# ( "door_guardians should be open unless the player is actually fighting the guardian" )
# ( "are door_guardians open?" )
check_door = getOpened("door_guardian" )
if check_door == 0
     # ( "door_guardians are closed -- open them" )
     act("door_guardian", "door_guardian" )
endif

