# Generated by BehavEd
# ( "comment" )
setReactToEnemies("_OWNER_", "FALSE" )
playanim (  "EA_ZONE1", "_OWNER_", "NONE", "" )
waittimed ( 2.500 )
setNoClip("_OWNER_", "FALSE" )
setNoGravity("_OWNER_", "FALSE" )
setReactToEnemies("_OWNER_", "TRUE" )

