# Generated by BehavEd
# ( "spawn the first wave of clawbeasts" )
# ( "successive attackers spawned by having monster_deathtargets act on spawners" )
act("spwnr_pitbeast1a", "spwnr_pitbeast1a" )
waittimed ( 0.500 )
act("spwnr_pitbeast2a", "spwnr_pitbeast2a" )
waittimed ( 0.500 )
act("spwnr_pitbeast3a", "spwnr_pitbeast3a" )
waittimed ( 0.500 )
act("spwnr_pitbeast4a", "spwnr_pitbeast4a" )

