# Generated by BehavEd
# ( "has the west switch been used?" )
check_west = getGameFlag("monument4", 3 )
if check_west == 1
     # ( "west switch has been used" )
     # ( "has the east switch been used?" )
     check_east = getGameFlag("monument4", 4 )
     if check_east == 1
          # ( "both switches have been used -- guardian doesn't attack" )
          objective ( "act2_obj_5b",  "EOBJCMD_COMPLETE" )
          remove ( "trig_stone", "trig_stone" )
          setEnable("guardian_statue", "FALSE" )
          # ( "comment" )
          setEnable("switch_west", "FALSE" )
          setEnable("switch_east", "FALSE" )
          # ( "This checks to see if players has seen the gateway yet" )
          seen_gateway = getObjective("act2_obj_5c", "HIDDEN" )
          if seen_gateway == 1
               startConversation("act2/monument/monument4/2_sometime2_0020" )
          else
               startConversation("act2/monument/monument4/2_sometime2_0030" )
          endif
     else
          # ( "east switch has not been used" )
          startConversation("act2/monument/monument4/2_monument1_0040" )
     endif
else
     # ( "west switch has not been used" )
     startConversation("act2/monument/monument4/2_monument1_0040" )
endif

