# Generated by BehavEd
# ( "guardian stone has been taken" )
remove ( "trig_stone", "trig_stone" )
remove ( "guardian_pedestal_stone_e_mo01", "guardian_pedestal_stone_e_mo01" )
setEnable("switch_west", "FALSE" )
setEnable("switch_east", "FALSE" )
# ( "This checks to see if players has seen the gateway yet" )
seen_gateway = getObjective("act2_obj_5c", "HIDDEN" )
if seen_gateway == 1
     startConversation("act2/monument/monument4/2_sometime2_0020" )
else
     startConversation("act2/monument/monument4/2_sometime2_0030" )
endif

