# Generated by BehavEd
# ( "has the west switch been used?" )
check_west = getGameFlag("monument4", 3 )
if check_west == 1
     # ( "west switch has been used" )
     # ( "has the east switch been used?" )
     check_east = getGameFlag("monument4", 4 )
     if check_east == 1
          # ( "both switches have been used -- guardian doesn't attack" )
          objective ( "act2_obj_5b",  "EOBJCMD_COMPLETE" )
          setEnable("guardian_statue", "FALSE" )
     else
          # ( "east switch has not been used -- guardian attacks" )
          act("guardian_statue", "guardian_statue" )
     endif
else
     # ( "west switch has not been used  -- guardian attacks" )
     act("guardian_statue", "guardian_statue" )
endif

