# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept04.png" )
imageViewer("textures/concept/concept05.png" )
imageViewer("textures/concept/concept06.png" )

