# Generated by BehavEd
# ( "comment" )
xpips = getZoneVar("xpips" )
xpips = iadd(xpips, 1 )
setZoneVar("xpips", xpips )
if xpips >= 4
     setZoneVar("xpips", 0 )
     act("koh_x_pip", "koh_x_pip" )
endif

