# Generated by BehavEd
# ( "This shows the guy attack the barrel" )
attackEntityWithType("barrel_attacker", "plasma_barrel_first_one", "ATTACK", "TRUE" )
waittimed ( 1.000 )
overrideFocusToEntity("barrel_attacker", 1.000 )
waittimed ( 2.000 )
cameraReset( )

