# Generated by BehavEd
# ( "This script checks of the perimeter3 objectives have been completed" )
# ( "If not then the Nick Fury conversaiton is played that tells the player they can't leave." )
perm3_done = getObjective("act4_obj_1a", "COMPLETE" )
if perm3_done == 1
     act("zone_teleporter", "zone_teleporter" )
     setEnable("link_perimeter4", "TRUE" )
     setEnable("zone_console", "FALSE" )
else
     startConversation("act4/perimeter/perimeter3/4_perimeter3_0020" )
endif

