# Generated by BehavEd
# ( "This script checks of the perimeter3 objectives have been completed" )
# ( "Havok can't pick you up until guns are destroyed." )
perm3_done = getObjective("act4_obj_1a", "COMPLETE" )
if perm3_done == 1
     startConversation("act4/perimeter/perimeter3/4_perimeter3_0040" )
else
     startConversation("act4/perimeter/perimeter3/4_perimeter3_0020" )
endif

