# Generated by BehavEd
# ( "This script plays the landing animation for sentinels" )
sound (  "PLAY_SOUND", "char/sent_m/descend", "_OWNER_", "" )
setInvisible("_OWNER_", "FALSE" )
faceEntity("_OWNER_", "_ACTIVATOR_" )
setDestroyObjects("_OWNER_", "TRUE" )
# ( "This is really only usedful if the first mission animation is the landing animation" )
playanim (  "EA_ZONE3", "_OWNER_", "", "" )
spawnEffectBone("_OWNER_", "bip01 pelvis", "char/sent/special_landing" )
spawnEffectBone("_OWNER_", "Bip01 L Toe0", "char/sent/special_jet" )
spawnEffectBone("_OWNER_", "Bip01 R Toe0", "char/sent/special_jet" )

