# Generated by BehavEd
# ( "If generator 2 is destroyed then increment the matrix quest" )
perimeter3_defense_matrix = getObjective("act4_obj_1a", "COMPLETE" )
if perimeter3_defense_matrix == 0
     spawnEffect("shield_gen_per_3", "map/perimeter/large_satelite_explode", " 0.000 0.000 120.000 ", " 0.000 0.000 0.000 " )
     sound (  "PLAY_SOUND", "zone_shared/special/generator_explosion", "shield_gen_per_1", "" )
     spawn("shield_gen_per_3", "shield_gen_per_b_pp_d", "large_stump02", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     remove ( "shield_gen_per_3", "shield_gen_per_3" )
     waittimed ( 1.000 )
     objective ( "act4_obj_1a",  "EOBJCMD_INCREMENT" )
     # ( "**********************************" )
     # ( "This checks to see of the timer should be removed" )
     check_obj = getObjective("act4_obj_1a", "COMPLETE" )
     if check_obj == 1
          timerStart(0.000, 0.000, "" )
     else
          timerAdd(120.000 )
     endif
     # ( "**********************************" )
     waittimed ( 1.000 )
     sound (  "PLAY_SOUND", "zone_shared/special/big_gun_explosion", "big_guns_pp09", "" )
     killEntity("big_guns_pp09" )
     spawnEffect("big_guns_pp09", "map/perimeter/large_gun_explode", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     waittimed ( 1.000 )
     sound (  "PLAY_SOUND", "zone_shared/special/big_gun_explosion", "big_guns_pp12", "" )
     killEntity("big_guns_pp12" )
     spawnEffect("big_guns_pp12", "map/perimeter/large_gun_explode", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     waittimed ( 1.000 )
     sound (  "PLAY_SOUND", "zone_shared/special/big_gun_explosion", "big_guns_pp11", "" )
     killEntity("big_guns_pp11" )
     spawnEffect("big_guns_pp11", "map/perimeter/large_gun_explode", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     waittimed ( 1.000 )
     sound (  "PLAY_SOUND", "zone_shared/special/big_gun_explosion", "big_guns_pp10", "" )
     killEntity("big_guns_pp10" )
     spawnEffect("big_guns_pp10", "map/perimeter/large_gun_explode", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
endif

