# Generated by BehavEd
# ( "This is the death scrip for the last generator" )
perimeter3_defense_matrix = getObjective("act4_obj_1a", "COMPLETE" )
if perimeter3_defense_matrix == 0
     spawnEffect("shield_gen_per_4", "map/perimeter/large_satelite_explode", " 0.000 0.000 360.000 ", " 0.000 0.000 0.000 " )
     sound (  "PLAY_SOUND", "zone_shared/special/big_gun_explosion", "shield_gen_per_1", "" )
     spawn("shield_gen_per_4", "shield_gen_per_b_pp_d", "large_stump02", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     remove ( "shield_gen_per_4", "shield_gen_per_4" )
     waittimed ( 1.000 )
     objective ( "act4_obj_1a",  "EOBJCMD_INCREMENT" )
     # ( "**********************************" )
     # ( "This checks to see of the timer should be removed" )
     check_obj = getObjective("act4_obj_1a", "COMPLETE" )
     if check_obj == 1
          timerStart(0.000, 0.000, "" )
     else
          timerAdd(30.000 )
     endif
     # ( "**********************************" )
     waittimed ( 1.000 )
     sound (  "PLAY_SOUND", "zone_shared/special/big_gun_explosion", "big_guns_pp14", "" )
     killEntity("big_guns_pp14" )
     spawnEffect("big_guns_pp14", "map/perimeter/large_gun_explode", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     waittimed ( 1.000 )
     sound (  "PLAY_SOUND", "zone_shared/special/big_gun_explosion", "big_guns_pp13", "" )
     killEntity("big_guns_pp13" )
     spawnEffect("big_guns_pp13", "map/perimeter/large_gun_explode", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     waittimed ( 1.000 )
     sound (  "PLAY_SOUND", "zone_shared/special/big_gun_explosion", "big_guns_pp15", "" )
     killEntity("big_guns_pp15" )
     spawnEffect("big_guns_pp15", "map/perimeter/large_gun_explode", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     waittimed ( 1.000 )
     sound (  "PLAY_SOUND", "zone_shared/special/big_gun_explosion", "big_guns_pp16", "" )
     killEntity("big_guns_pp16" )
     spawnEffect("big_guns_pp16", "map/perimeter/large_gun_explode", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
endif

