# Generated by BehavEd
# ( "comment" )
waittimed ( 1.000 )
startConversation("act4/perimeter/perimeter3/4_perimeter3_0010" )
# ( "This shows the gun" )
cameraToLocationAngles(" 2545.000 1774.000 229.000 ", " 2525.000 1688.000 183.000 ", 0.000 )
waittimed ( 2.000 )
# ( "This shows the generator" )
cameraToLocationAngles(" 3536.000 1992.000 314.000 ", " 3444.000 1974.000 280.000 ", 2.000 )

