# Generated by BehavEd
# ( "comment" )
lockControls(0.000 )
heroNoTarget("TRUE" )
cameraMove(" 3215.000 3391.000 298.000 ", 2.000 )
cameraPan(" 0.000 33.400 43.300 ", 2.000, "FALSE" )
waittimed ( 2.500 )
act("ss_first_sentinel01", "ss_first_sentinel01" )
waittimed ( 2.200 )
enemiesNoTarget("TRUE" )
lockControls(0.100 )
startConversation("act4/perimeter/perimeter3/4_perimeter3_0030" )

