# Generated by BehavEd
# ( "comment" )
act("fx_teleport", "fx_teleport" )
sound (  "PLAY_SOUND", "boss_battles/angel/apoc_beaming_out", "", "" )
copyOriginAndAngles("archangel", "fx_teleport" )
remove ( "apoc", "apoc" )
remove ( "beast", "beast" )
remove ( "sabre", "sabre" )
setInvisible("archangel", "FALSE" )

