# Generated by BehavEd
# ( "when the pillars come tumblin' down" )
playBossSound("voice/archangel/beam_crazy", 0, 5.000 )
act("fx_teleport", "fx_teleport" )
copyOriginAndAngles("archangel", "wp_teleport03" )
act("beamsoundloop", "beamsoundloop" )
act("wp_teleport03", "wp_teleport03" )
setDefaultTarget("archangel" )
setPatternSequence("archangel", "archangel3" )
remove ( "armp_fx01", "armp_fx01" )
remove ( "armp_fx02", "armp_fx02" )
remove ( "armp_fx03", "armp_fx03" )
remove ( "armp_fx04", "armp_fx04" )

