# Generated by BehavEd
# ( "comment" )
cameraResetOldSchool( )
cameraSetClipPlane(15000.000 )
objective ( "act4_Obj_6b",  "EOBJCMD_COMPLETE" )
objective ( "act4_Obj_6c",  "EOBJCMD_SHOW" )
setDefaultTarget("archangel" )
setallaiactive("TRUE" )
waittimed ( 0.200 )
setPatternSequence("archangel", "angel5" )

