# Generated by BehavEd
# ( "angel lands on a podium" )
heroNoTarget("TRUE" )
enemiesNoTarget("TRUE" )
cameraMove(" 448.392 620.089 1528.130 ", 1.000 )
cameraPan(" 2.264 45.435 140.983 ", 1.000, "FALSE" )
waittimed ( 3.000 )
cameraResetOldSchool( )
cameraSetClipPlane(15000.000 )
enemiesNoTarget("FALSE" )
heroNoTarget("FALSE" )

