# Generated by BehavEd
# ( "when his perches are all gone" )
waittimed ( 0.100 )
playBossSound("voice/archangel/final_taunt", 0, 5.000 )
setInvulnerable("archangel", "TRUE" )
setPatternSequence("archangel", "archangel4" )
setInvulnerable("archangel", "FALSE" )

