# Generated by BaconWizard17
# ( "No script was called after the conversation after defeating Angel, so I added this one" )

angel_unlocked = isCharacterUnlocked("angel_hero")
if angel_unlocked == 0
    # ( "Angel is not yet unlocked, unlock him" )
    unlockCharacter("angel_hero", " ")
    angel_unlocked = isCharacterUnlocked("angel_hero")
    if angel_unlocked == 1
        # ( "Angel was not previously unlocked but he is on the roster" )
        # ( "He's been unlocked now, so show the dialog that confirms this" )
        createPopupDialogXML("dialogs/act4/tower/angel_unlocked")
    endif 
endif 