# Generated by BehavEd
# ( "enter the sinister arena" )
setRecallActive("FALSE" )
setEngageEnemy("sin_ice", "TRUE" )
attackEntityWithType("sin_ice", "_ACTIVE_HERO_", "ANY", "FALSE" )
setEngageEnemy("sin_storm", "TRUE" )
attackEntityWithType("sin_storm", "_ACTIVE_HERO_", "ANY", "FALSE" )
setEngageEnemy("sin_cyc", "TRUE" )
attackEntityWithType("sin_cyc", "_ACTIVE_HERO_", "ANY", "FALSE" )
setEngageEnemy("sin_wolv", "TRUE" )
attackEntityWithType("sin_wolv", "_ACTIVE_HERO_", "ANY", "FALSE" )

