# Generated by BehavEd
# ( "leave the sinister arena" )
setRecallActive("TRUE" )
setEngageEnemy("sin_ice", "FALSE" )
setWaypointPath("sin_ice", "sinicehome", 1 )
setEngageEnemy("sin_storm", "FALSE" )
setWaypointPath("sin_storm", "sinstormhome", 1 )
setEngageEnemy("sin_cyc", "FALSE" )
setWaypointPath("sin_cyc", "sincychome", 1 )
setEngageEnemy("sin_wolv", "FALSE" )
setWaypointPath("sin_wolv", "sinwolvhome", 1 )

