# Generated by BehavEd
# ( "comment" )
cameraMove(" 4284.690 3960.570 127.904 ", 0.500 )
cameraPan(" 0.000 20.000 199.768 ", 0.500, "FALSE" )
waittimed ( 0.500 )
act("sp_sin_ice01", "sp_sin_ice01" )

