# Generated by BehavEd
# ( "comment" )
act("sp_mrsinister02", "sp_mrsinister02" )
fade("mrsinister2", 0.500, 0.000, "TRUE" )
copyOriginAndAngles("glow2", "glow2_spot" )
cameraMove(" 4431.330 4278.620 82.799 ", 0.000 )
cameraPan(" 0.000 20.000 88.879 ", 0.000, "FALSE" )
startConversation("act3/infinite/infinite6/3_infinite6_0025" )

