# Generated by BehavEd
# ( "remove oz_explosion since it is now precached" )
remove ( "oz_explosion", "oz_explosion" )
# ( "ensure the player can't use Blink's portal" )
setRecallActive("TRUE" )
# ( "is door_trap open?" )
status = getOpened("door_trap" )
if status == 0
     actSilent("door_trap", "door_trap" )
endif
# ( "is door_security open?" )
status = getOpened("door_security" )
if status == 0
     actSilent("door_security", "door_security" )
endif
# ( "start the opening cutscene" )
lockControls(-1.000 )
setallaiactive("FALSE" )
cameraFocusToEntity("cam_prof", 128.000, 30.000, 0.000, 0.000 )
# ( "fade in" )
cameraFade(0.000, 1.000 )
waittimed ( 1.000 )
startConversation("act0/tutorial/tutorial1/1_introlevel_0020" )

