# Generated by BehavEd
# ( "deploy slow pylon" )
pid = getParentID("_OWNER_" )
act(pid, pid )
setNoCollideNoTickle(pid, "FALSE" )
tid = spawn(pid, "p_nul_trig", "p_nul_trig", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
setParent(tid, "_OWNER_" )

