# Generated by Ryan
# Recall spawn script 
# this entity must turn itself on automatically
active = isBlinkPortalActive()
if active == 1
     setEnable('_OWNER_','TRUE')
     act('_OWNER_','_OWNER_')
endif	
