# Generated by BehavEd
# ( "set current act" )
setGameFlag("act1_visit", 3, 1 )
setEnable("2nd_objective", "FALSE" )
beatgriz = getGameFlag("bosses", 2 )
if beatgriz == 1
     remove ( "arena_trigger", "arena_trigger" )
     remove ( "grizz_trigger", "grizz_trigger" )
     copyOriginAndAngles("security_device01", "Grizzly_spawner" )
     setEnable("security_device01", "TRUE" )
     remove ( "Grizzly_spawner", "Grizzly_spawner" )
endif
deadzone = getObjective("act1_obj_2c", "COMPLETE" )
if deadzone == 1
     remove ( "security_device01", "security_device01" )
endif
radar = getObjective("radardish", "COMPLETE" )
if radar == 1
     killEntitySilent("radar_dish" )
endif

