# Generated by BehavEd
# ( "comment" )
metgriz = getGameFlag("bosses", 1 )
if metgriz == 0
     waittimed ( 0.250 )
     setGameFlag("bosses", 1, 1 )
     lockControls(-1.000 )
     setallaiactive("FALSE" )
     waittimed ( 0.250 )
     cameraFocusToEntity("griz_cine", 300.000, 25.000, 0.000, 2.000 )
     waittimed ( 2.500 )
     setBossPartyLightEntity("grizzly" )
     setBossPartyLightColor(" 0.650 0.390 0.160 " )
     startConversation("act1/deadzone/deadzone3/1_DEADZONE3_0010" )
else
     setEnable("arena_trigger", "TRUE" )
     setDefaultTarget("grizzly" )
endif

