# Generated by BehavEd
# ( "comment" )
setBossPartyLightColor(" 0.000 0.000 0.000 " )
waittimed ( 0.250 )
cameraReset( )
waittimed ( 0.250 )
lockControls(0.100 )
setallaiactive("TRUE" )
setEnable("arena_trigger", "TRUE" )
setDefaultTarget("grizzly" )

