# Generated by BehavEd
# ( "killed grizzly" )
remove ( "arena_trigger", "arena_trigger" )
setGameFlag("bosses", 2, 1 )
waittimed ( 4.000 )
setRecallActive("TRUE" )
setDefaultTarget("" )
startConversation("act1/deadzone/deadzone3/1_DEADZONE3_0020" )
copyOriginAndAngles("security_device01", "grizzly" )
setEnable("security_device01", "TRUE" )

