# Generated by BehavEd
# ( "comment" )
metgriz = getGameFlag("bosses", 1 )
if metgriz == 0
     setAIActive("Grizzly", "FALSE" )
else
     attackEntityWithType("grizzly", "_ACTIVE_HERO_", "ANY", "FALSE" )
endif

