# Generated by BehavEd
# ( "enter the grizzly arena" )
setRecallActive("FALSE" )
setEngageEnemy("grizzly", "TRUE" )
setDefaultTarget("grizzly" )
attackEntityWithType("grizzly", "_ACTIVE_HERO_", "ANY", "FALSE" )

