# Generated by BehavEd
# ( "complete objective first" )
objective ( "act1_obj_2c",  "EOBJCMD_COMPLETE" )
# ( "now run conversation that checks how many codes we have" )
startConversation("act1/1_sometimeact1_0010" )
# ( "if this was the last of three modules picked up, complete overall objective" )
# ( "keith -- actually, I just added another subquest to objective 2" )
# ( "requiring you to talk to Angel but only after finding all three modules." )
# ( "That's how you complete act1_obj_2." )

