# Generated by BehavEd
# ( "This script tells the player that a new briefing is avaiable" )
briefings = getGameFlag("briefings", 12 )
if briefings == 0
     setGameFlag("briefings", 12, 1 )
     newMissionBriefing( )
endif

