# Generated by BehavEd
# ( "spawnscript for act1 homing beacons" )
count = getGameVarBitCount("beaconact4" )
if count >= 4
     setEnable("_OWNER_", "FALSE" )
     setInvisible("_OWNER_", "TRUE" )
     setNoCollide("_OWNER_", "TRUE" )
     myname = getName("_OWNER_" )
     tid = spawn("_OWNER_", "beacon_chest4", myname, " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     setParent(tid, "_OWNER_" )
endif

