# Generated by BehavEd
# ( "have the X-men tried to fool the Infinite interrogator?" )
response = getGameFlag("newyork", 8 )
if response == 0
     # ( "the fooling has not been attempted yet..." )
     # ( "disallow the response that ends the chat" )
     disallowResponse( )
endif

