# Generated by BehavEd
# ( "remove the holodisk" )
remove ( "disk", "disk" )
# ( "indicate the holodisk has been found" )
objective ( "act4_obj_2b",  "EOBJCMD_COMPLETE" )
# ( "are the x-men wearing clever disguises?" )
disguise_check = getZoneVar("disguise" )
if disguise_check == 1
     # ( "has the player talked to shaw in newyork2?" )
     talk = getObjective("act4_obj_2a", "COMPLETE" )
     if talk == 1
          # ( "shaw has been talked to" )
          faceEntity("inf_leader", "_ACTIVE_HERO_" )
          startConversation("act4/newyork/newyork4/4_newyork3_0040a" )
          # ( "tell the player to return the holodisk to shaw" )
          objective ( "act4_obj_2e",  "EOBJCMD_SHOW" )
     else
          # ( "shaw has not been talked to" )
          faceEntity("inf_leader", "_ACTIVE_HERO_" )
          startConversation("act4/newyork/newyork4/4_newyork3_0040b" )
     endif
else
     # ( "has the player talked to shaw in newyork2?" )
     talk = getObjective("act4_obj_2a", "COMPLETE" )
     if talk == 1
          # ( "shaw has been talked to--tell the player to return the holodisk to shaw" )
          objective ( "act4_obj_2e",  "EOBJCMD_SHOW" )
     else
          # ( "shaw has not been talked to" )
          startConversation("act4/newyork/newyork4/4_newyork3_0040c" )
     endif
endif

