# Generated by BehavEd
# ( "WARNING--objective testing only--do not use" )
# ( "have the infinite uniforms been found?" )
uniforms = getGameFlag("newyork", 2 )
if uniforms == 1
     # ( "the uniforms have been found--remove them" )
     remove ( "uniforms", "uniforms" )
endif
# ( "has the force field been lowered?" )
field = getGameFlag("newyork", 4 )
if field == 1
     # ( "the force field has been lowered--remove it" )
     remove ( "field", "field" )
     remove ( "trig_recogsys", "trig_recogsys" )
     # ( "spawn the infinites in the guard post" )
     act("s_inf_leader", "s_inf_leader" )
     act("s_inf", "s_inf" )
endif
# ( "has the holodisk become an objective?" )
diskobj = getObjective("act4_obj_2b", "HIDDEN" )
if diskobj == 0
     # ( "the holodisk is an objective--make sure it's hinttype=objective" )
     setHintType("disk", "objective" )
endif
# ( "has the holodisk been found?" )
disk = getObjective("act4_obj_2b", "COMPLETE" )
if disk == 1
     remove ( "disk", "disk" )
endif

