# Generated by BehavEd
# ( "does the player have the infinite uniforms?" )
uniforms = getGameFlag("newyork", 2 )
if uniforms == 1
     # ( "because the heroes will be disguised, combat is locked" )
     lockCombat("TRUE" )
     # ( "there is no further need for trig_recogsys" )
     remove ( "trig_recogsys", "trig_recogsys" )
     # ( "the player has the uniforms and can now get inside the guard post" )
     startConversation("act4/newyork/newyork4/4_newyork3_0020" )
else
     # ( "the player doesn't have the uniforms, but receives a helpful hint" )
     startConversation("act4/newyork/newyork4/4_newyork3_0010" )
endif

