# Generated by BehavEd
# ( "remove the uniforms" )
remove ( "uniforms", "uniforms" )
# ( "indicate the uniforms have been found" )
setGameFlag("newyork", 2, 1 )
# ( "the team celebrates the finding of the uniforms with a conversation" )
startConversation("act4/newyork/newyork4/4_newyork3_0030" )

