# Generated by BehavEd
# ( "common script all j#_2_c# scripts run for loopfx/lighting changes" )
waittimed ( 0.750 )
act("loopfx", "loopfx" )
setPartyLightColor(" 0.170 0.350 0.380 ", 0.000 )
# ( "add party and ambient light changes here" )
setHintType("hintrock1", "none" )
setHintType("hintrock2", "objective" )

