# Generated by BehavEd
# ( "enter the sauron arena" )
setWaypointPath("sauron", "", 0 )
setRecallActive("FALSE" )
setEngageEnemy("sauron", "TRUE" )
setDefaultTarget("sauron" )
attackEntityWithType("sauron", "_ACTIVE_HERO_", "ANY", "FALSE" )

