# Generated by BehavEd
# ( "common script all c#_2_j# scripts run for loopfx/lighting changes" )
waittimed ( 0.750 )
act("loopfx", "loopfx" )
setPartyLightColor(" 0.830 0.600 0.000 ", 0.000 )
# ( "add party and ambient light changes here" )
setHintType("hintrock1", "objective" )
setHintType("hintrock2", "none" )

