# Generated by BehavEd
# ( "zone script" )
saurondead = getGameFlag("bosses", 11 )
if saurondead == 1
     setEnable("link1_monument1", "TRUE" )
     remove ( "trigger_touch01", "trigger_touch01" )
     remove ( "sauron_spawn", "sauron_spawn" )
     remove ( "arena_trigger", "arena_trigger" )
endif

