# Generated by BehavEd
# ( "FIGHT" )
setAIActive("sauron", "TRUE" )
setDefaultTarget("sauron" )
heroNoTarget("FALSE" )
enemiesNoTarget("FALSE" )
lockControls(0.100 )
cameraResetOldSchool( )
objective ( "act2_obj_3b",  "EOBJCMD_SHOW" )
setEnable("arena_trigger", "TRUE" )

