# Generated by BehavEd
# ( "sauron's deathscript" )
dr = getDangerRoomActive( )
if dr == 1
     setDangerRoomSuccess( )
else
     objective ( "act2_obj_3b",  "EOBJCMD_COMPLETE" )
     remove ( "arena_trigger", "arena_trigger" )
     setGameFlag("bosses", 11, 1 )
     setDefaultTarget("" )
     waittimed ( 3.000 )
     setEnable("link1_monument1", "TRUE" )
     startConversation("act2/jungle/jungle5/2_JUNGLE5_0030" )
endif

