# Generated by BehavEd
# ( "sauron intro" )
metsauron = getGameFlag("bosses", 10 )
if metsauron == 0
     waittimed ( 0.100 )
     setAIActive("sauron", "FALSE" )
     setGameFlag("bosses", 10, 1 )
     heroNoTarget("TRUE" )
     enemiesNoTarget("TRUE" )
     lockControls(-1.000 )
     waittimed ( 0.250 )
     cameraPan(" 0.095 3.598 89.716 ", 1.000, "FALSE" )
     cameraMove(" 10803.000 9588.290 72.666 ", 1.000 )
     waittimed ( 1.250 )
     startConversation("act2/jungle/jungle5/2_JUNGLE5_0020" )
else
     waittimed ( 0.500 )
     setDefaultTarget("sauron" )
     attackEntityWithType("sauron", "_ACTIVE_HERO_", "ANY", "FALSE" )
     setEnable("arena_trigger", "TRUE" )
endif

