# Generated by BehavEd
# ( "comment" )
cameraResetOldSchool( )
lockControls(0.100 )
heroNoTarget("FALSE" )
enemiesNoTarget("FALSE" )
attackEntityWithType("joe", "_HERO1_", "_ANY_", "TRUE" )
attackEntityWithType("moe", "_HERO1_", "_ANY_", "TRUE" )
attackEntityWithType("cap_carnage", "_HERO1_", "_ANY_", "TRUE" )

