# Generated by BehavEd
# ( "comment" )
act("ss_shockcaptain_a01", "ss_shockcaptain_a01" )
act("ss_shocktroop_a02", "ss_shocktroop_a02" )
act("ss_shocktroop_a03", "ss_shocktroop_a03" )
trap = getGameFlag("jungle5", 1 )
if trap == 0
     waittimed ( 0.500 )
     lockControls(-1.000 )
     heroNoTarget("TRUE" )
     enemiesNoTarget("TRUE" )
     cameraFocusToEntity("cap_carnage", 384.000, 45.000, 180.000, 2.000 )
     waittimed ( 2.250 )
     setHintType("cap_carnage", "importanttalk" )
     waittimed ( 1.000 )
     setHintType("cap_carnage", "none" )
     setZoneVar("lasertrap", 1 )
     # ( "conversation here" )
     startConversation("act2/jungle/jungle5/2_JUNGLE5_0050" )
endif

