# Generated by BaconWizard17
# ( "No script was called after the conversation after defeating Sauron, so I added this one" )

sauron_unlocked = isCharacterUnlocked("sauron_hero")
if sauron_unlocked == 0
    # ( "Sauron is not yet unlocked, unlock him" )
    unlockCharacter("sauron_hero", " ")
    sauron_unlocked = isCharacterUnlocked("sauron_hero")
    if sauron_unlocked == 1
        # ( "Sauron was not previously unlocked but he is on the roster" )
        # ( "He's been unlocked now, so show the dialog that confirms this" )
        createPopupDialogXML("dialogs/act2/jungle/sauron_unlocked")
    endif 
endif 