# Generated by BehavEd
# ( "comment" )
setInvulnerable("statue_abyss", "FALSE" )
setInvulnerable("statue_apoc", "TRUE" )
setInvulnerable("statue_death", "TRUE" )
setInvulnerable("statue_angel", "TRUE" )
cameraFocusToEntity("statue_abyss", 360.000, 45.000, 180.000, 2.000 )
setHintType("statue_abyss", "objective" )
waittimed ( 2.500 )
cameraReset( )
lockControls(0.100 )
heroNoTarget("FALSE" )
enemiesNoTarget("FALSE" )

