# Generated by BehavEd
# ( "comment" )
# ( "players from hall to pit" )
cameraFade(1.000, 1.000 )
waittimed ( 0.500 )
copyOriginAndAngles("_HERO1_", "hero1place02" )
copyOriginAndAngles("_HERO2_", "hero2place02" )
copyOriginAndAngles("_HERO3_", "hero3place02" )
copyOriginAndAngles("_HERO4_", "hero4place02" )
cameraToLocationAngles(" 2196.190 3099.500 -63.660 ", " 2157.650 3158.780 -134.370 ", 0.000 )
waittimed ( 0.500 )
cameraFade(0.000, 1.000 )
cameraResetOldSchool( )

