# Generated by BehavEd
# ( "players from pit to hall" )
cameraFade(1.000, 1.000 )
waittimed ( 0.500 )
copyOriginAndAngles("_HERO1_", "hero1place01" )
copyOriginAndAngles("_HERO2_", "hero2place01" )
copyOriginAndAngles("_HERO3_", "hero3place01" )
copyOriginAndAngles("_HERO4_", "hero4place01" )
cameraToLocationAngles(" 1709.720 3795.800 -44.530 ", " 1780.230 3790.380 -115.240 ", 0.000 )
cameraFade(0.000, 1.000 )
cameraResetOldSchool( )

