# Generated by BehavEd
# ( "comment" )
cameraShake(4.000, 3.000 )
killEntity("statuebad05" )
act("statueanubite05", "statueanubite05" )
waittimed ( 0.500 )
killEntity("statuebad06" )
act("statueanubite06", "statueanubite06" )

