# Generated by BehavEd
# ( "comment" )
cameraShake(4.000, 3.000 )
killEntity("statuebad01" )
act("statueanubite01", "statueanubite01" )
waittimed ( 0.500 )
killEntity("statuebad02" )
act("statueanubite02", "statueanubite02" )

