# Generated by BehavEd
# ( "calculate health percentage" )
stage = getZoneVar("stage" )
stage = iadd(stage, 1 )
health = getHealth("_OWNER_" )
healthmax = getHealthMax("_OWNER_" )
hamt = fdiv(health, healthmax )
# ( "figure out what the theshold for the next stage should be" )
thresh = fmul(stage, 0.330 )
hthresh = fsub(1.000000, thresh )
if hamt < hthresh
     newhealth = fmul(healthmax, hthresh )
     setHealth("_OWNER_", newhealth )
     setZoneVar("stage", stage )
endif

