# Generated by BehavEd
# ( "This script keeps track of the number of sentinels killed" )
cur_sntls = getZoneVar("deadsents" )
cur_sntls = iadd(cur_sntls, 1 )
setZoneVar("deadsents", cur_sntls )
spawnedsents = getZoneVar("spndsents" )
if cur_sntls >= spawnedsents
     setZoneVar("deadsents", 0 )
     waittimed ( 10.000 )
     act("sentinel_wave", "sentinel_wave" )
endif

