# Generated by BehavEd
# ( "This script checks if Bastoin is defeated" )
dr = getDangerRoomActive( )
if dr == 0
     perm5_done = getObjective("act4_obj_1c", "COMPLETE" )
     if perm5_done == 1
          # ( "Turn the effect of the teleport on" )
          act("zone_teleport_per_e_pp01", "zone_teleport_per_e_pp01" )
          setEnable("link_perimeter4", "TRUE" )
          setEnable("zone_console", "FALSE" )
     else
          startConversation("common/finish_obj" )
     endif
else
     startConversation("common/finish_obj" )
endif

