# Generated by BehavEd
# ( "This is the load script for the bastion battle perimeter zone" )
setInvisible("floaters", "TRUE" )
setInvisible("landers", "TRUE" )
setInvisible("landers2", "TRUE" )
setInvisible("landers3", "TRUE" )
dr = getDangerRoomActive( )
if dr == 0
     beatim = getGameFlag("bosses", 21 )
     if beatim == 1
          remove ( "trigger_reveal_bastion", "trigger_reveal_bastion" )
     else
          setRecallActive("FALSE" )
     endif
     # ( "This is the teleport sound" )
     sound (  "PLAY_SOUND", "zone_shared/special/teleporter_spawn", "_HERO1_", "" )
endif

