# Generated by BehavEd
# ( "Bastion uses this script to summon more sentinel" )
cur_health = getHealth("_OWNER_" )
max_health = getHealthMax("_OWNER_" )
# ( "Depending on what Bastion health is, is how many sentinels he summons" )
per_health = fdiv(cur_health, max_health )
sentinels_dead = alive("bastion_sentinel" )
num_sentinels = getZoneVar("sntls" )
if sentinels_dead == 0
     if per_health > 0.800000
          debug("Bastion health is more than 80%" )
     elif per_health > 0.700000
          debug("Bastion health is less than 80%" )
     elif per_health > 0.600000
          debug("Bastion health is less than 70%" )
     elif per_health > 0.500000
          debug("Bastion health is less than 60%" )
     elif per_health > 0.400000
          debug("Bastion health is less than 50%" )
     elif per_health > 0.300000
          debug("Bastion health is less than 40%" )
     elif per_health > 0.200000
          debug("Bastion health is less than 30%" )
     endif
     # ( "This combat node summons sentinels" )
     setCombatNode("bastion", "power_xtreme" )
     waittimed ( 1.000 )
     act("summon_sentinels", "summon_sentinels" )
     act("summon_sentinels", "summon_sentinels" )
elif num_sentinels < 4
     # ( "This repopulates the scene with sentinels" )
     # ( "This combat node summons sentinels" )
     setCombatNode("bastion", "power_xtreme" )
     waittimed ( 1.000 )
     act("summon_sentinels", "summon_sentinels" )
     act("summon_sentinels", "summon_sentinels" )
     act("summon_sentinels", "summon_sentinels" )
     act("summon_sentinels", "summon_sentinels" )
endif

