# Generated by BehavEd
# ( "Talk to blob while he's holding up the wall" )
heroNoTarget("TRUE" )
enemiesNoTarget("TRUE" )
bombs = getObjective("act1_obj_4", "COMPLETE" )
if bombs == 0
     # ( "talk to blob without defusing bombs" )
     startConversation("act1/genosha/genosha5/1_genosha5_0065" )
else
     # ( "if you defused bombs, but haven't helped blob, he whines" )
     startConversation("act1/genosha/genosha5/1_genosha5_0067" )
endif

