# Generated by BehavEd
# ( "blob leaving convo" )
blob_leaves = getObjective("Help_Blob", "COMPLETE" )
if blob_leaves == 1
     blob_leaves = getGameFlag("genosha5", 10 )
     if blob_leaves == 0
          # ( "sanity check" )
          blob_leaves = alive("blob" )
          if blob_leaves == 1
               setallaiactive("FALSE" )
               lockControls(-1.000 )
               setGameFlag("genosha5", 10, 1 )
               cameraFade(1.000, 1.000 )
               waittimed ( 1.000 )
               spawn("_ACTIVE_HERO_", "herospot1", "herospot2", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
               moveHeroesToEnt("herospot1" )
               copyOriginAndAngles("blob", "blobspot1" )
               cameraFocusToEntity("blob", 450.000, 40.000, 180.000, 0.000 )
               cameraFade(0.000, 1.000 )
               waittimed ( 0.750 )
               startConversation("act1/genosha/genosha5/1_GENOSHA5_0075" )
          else
               setGameFlag("genosha5", 10, 1 )
          endif
     endif
endif

