# Generated by BehavEd
# ( "fade out and reset camera" )
spawnEffect("blob", "map/common/scr_blinkportal_s", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
waittimed ( 0.500 )
spawnEffect("blob", "map/common/scr_blinkportal_c", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
remove ( "Blob", "Blob" )
# ( "fade in and unlock controls" )
cameraFade(1.000, 0.500 )
waittimed ( 1.000 )
moveHeroesToEnt("herospot2" )
cameraResetOldSchool( )
cameraFade(0.000, 1.000 )
waittimed ( 1.000 )
lockControls(0.100 )
setallaiactive("TRUE" )

blob_unlocked = isCharacterUnlocked("Blob_hero")
if blob_unlocked == 0
    # ( "Blob is not yet unlocked, unlock him" )
    unlockCharacter("Blob_hero", " ")
    blob_unlocked = isCharacterUnlocked("Blob_hero")
    if blob_unlocked == 1
        # ( "Blob was not previously unlocked but he is on the roster" )
        # ( "He's been unlocked now, so show the dialog that confirms this" )
        createPopupDialogXML("dialogs/act1/genosha/genosha5/blob_unlocked")
    endif 
endif 