# Generated by BehavEd
# ( "Blob's Spawnscript" )
# ( "add blob holding up the wall animation here" )
waittimed ( 0.500 )
playanim (  "EA_ZONE1", "_OWNER_", "LOOP", "" )
setScale("_OWNER_", 1.125 )
setInvulnerable("_OWNER_", "TRUE" )
setCanMove("_OWNER_", "FALSE" )
setReactToEnemies("_OWNER_", "FALSE" )

