# Generated by BehavEd
# ( "checks if you're a brotherhood member or not" )
brother = getBrotherhood("_ACTIVATOR_" )
if brother == 1
     act("door_locked", "door_locked" )
     setEnable("lock_console", "FALSE" )
endif

