# Generated by BehavEd
# ( "lock controls" )
lockControls(-1.000 )
setallaiactive("FALSE" )
# ( "move camera to captain vereese" )
cameraFocusToEntity("camera_01", 380.000, 30.000, 335.000, 2.000 )
waittimed ( 2.000 )
startConversation("act1/genosha/genosha5/1_genosha5_0080" )

