# Generated by BehavEd
# ( "during Blob conv, move camera to see baddy" )
act("terror_spawn01", "terror_spawn01" )
act("terror_spawn02", "terror_spawn02" )
act("armorspawn02", "armorspawn02" )
act("armorspawn01", "armorspawn01" )
act("demon_spawn01", "demon_spawn01" )
cameraPan(" 0.000 33.000 41.700 ", 1.000, "FALSE" )

