# Generated by BehavEd
# ( "WARNING -- objective testing only -- do not use" )
# ( "has this map been visited before?" )
gen5_visit = getGameFlag("act1_visit", 12 )
if gen5_visit == 0
     # ( "if this map hasn't been visited before, indicate that visitation has been achieved" )
     setGameFlag("act1_visit", 12, 1 )
     # ( "a conversation runs upon the map's first visitation" )
     startConversation("act1/genosha/genosha5/1_genosha5_0010" )
     # ( "indicate we've used security codes to enter Genosha" )
     objective ( "act1_obj_3c",  "EOBJCMD_COMPLETE" )
endif
# ( "has the airship captain been met before?" )
captain = getGameFlag("genosha5", 1 )
if captain == 1
     # ( "if captain has been met, remove spawner and trigger" )
     remove ( "spawner_captain", "spawner_captain" )
     remove ( "trig_captain", "trig_captain" )
     # ( "which airship moorings have been destroyed already?" )
     # ( "mooring1_nw" )
     mooring = getGameFlag("genosha5", 2 )
     if mooring == 1
          # ( "mooring has already been destroyed -- annihilate!" )
          killEntity("mooring1_nw" )
     else
          setHintType("mooringob_1nw", "objective" )
     endif
     # ( "mooring1_sw" )
     mooring = getGameFlag("genosha5", 3 )
     if mooring == 1
          # ( "mooring has already been destroyed -- annihilate!" )
          killEntity("mooring1_sw" )
     else
          setHintType("mooringob_1sw", "objective" )
     endif
     # ( "mooring1_ne" )
     mooring = getGameFlag("genosha5", 4 )
     if mooring == 1
          # ( "mooring has already been destroyed -- annihilate!" )
          killEntity("mooring1_ne" )
     else
          setHintType("mooringob_1ne", "objective" )
     endif
     # ( "mooring1_se" )
     mooring = getGameFlag("genosha5", 5 )
     if mooring == 1
          # ( "mooring has already been destroyed -- annihilate!" )
          killEntity("mooring1_se" )
     else
          setHintType("mooringob_1se", "objective" )
     endif
     # ( "mooring2_nw" )
     mooring = getGameFlag("genosha5", 6 )
     if mooring == 1
          # ( "mooring has already been destroyed -- annihilate!" )
          killEntity("mooring2_nw" )
     else
          setHintType("mooringob_2nw", "objective" )
     endif
     # ( "mooring2_sw" )
     mooring = getGameFlag("genosha5", 7 )
     if mooring == 1
          # ( "mooring has already been destroyed -- annihilate!" )
          killEntity("mooring2_sw" )
     else
          setHintType("mooringob_2sw", "objective" )
     endif
     # ( "mooring2_ne" )
     mooring = getGameFlag("genosha5", 8 )
     if mooring == 1
          # ( "mooring has already been destroyed -- annihilate!" )
          killEntity("mooring2_ne" )
     else
          setHintType("mooringob_2ne", "objective" )
     endif
     # ( "mooring2_se" )
     mooring = getGameFlag("genosha5", 9 )
     if mooring == 1
          # ( "mooring has already been destroyed -- annihilate!" )
          killEntity("mooring2_se" )
     else
          setHintType("mooringob_2se", "objective" )
     endif
endif
# ( "check completeness of blob" )
blob = getObjective("help_blob", "COMPLETE" )
if blob == 1
     act("girder_move", "girder_move" )
     remove ( "blocknavs1", "blocknavs1" )
     setPathIgnore("blocknavs2", "FALSE" )
     remove ( "blob_talk", "blob_talk" )
     remove ( "waterloop", "waterloop" )
     remove ( "trigger_girder", "trigger_girder" )
     remove ( "trig_Blob_1", "trig_Blob_1" )
     remove ( "trig_Blob_02", "trig_Blob_02" )
     remove ( "trig_Blob_03", "trig_Blob_03" )
     remove ( "sp_blob01", "sp_blob01" )
     remove ( "sp_blob02", "sp_blob02" )
     waittimed ( 0.500 )
     remove ( "blobnone", "blobnone" )
     # ( "checks blob farewell speech" )
     blob = getGameFlag("genosha5", 10 )
     if blob == 1
          remove ( "trigger_touch02", "trigger_touch02" )
          remove ( "trigger_touch03", "trigger_touch03" )
          remove ( "blob", "blob" )
     else
          setInvulnerable("blob", "TRUE" )
          beATeamPlayer("blob", "TRUE" )
          # ( "if you saved blob and left via blink and walked back, remove talk triggers" )
          blob = getZoneReset( )
          if blob == 1
               remove ( "trigger_touch02", "trigger_touch02" )
               remove ( "trigger_touch03", "trigger_touch03" )
               setGameFlag("genosha5", 10, 1 )
          endif
     endif
endif
# ( "check the bombs" )
bombs = getObjective("act1_obj_4a", "HIDDEN" )
if bombs == 0
     setHintType("detonator_01", "objective" )
     setHintType("detonator_02", "objective" )
     remove ( "trig_Blob_1", "trig_Blob_1" )
     remove ( "trig_Blob_02", "trig_Blob_02" )
     remove ( "trig_Blob_03", "trig_Blob_03" )
     # ( "check bomb1's state" )
     bombs = getGameFlag("genosha5", 11 )
     if bombs == 1
          remove ( "detonator_01", "detonator_01" )
          remove ( "lightent01", "lightent01" )
          act("bomb_01", "bomb_01" )
     endif
     # ( "bomb2" )
     bombs = getGameFlag("genosha5", 12 )
     if bombs == 1
          remove ( "detonator_02", "detonator_02" )
          remove ( "lightent02", "lightent02" )
          act("bomb_02", "bomb_02" )
     endif
endif
magstatue = getGameFlag("prisoners", 28 )
if magstatue == 1
     remove ( "trigger_touch01", "trigger_touch01" )
endif

