# Generated by BehavEd
# ( "comment" )
setGameFlag("prisoners", 28, 1 )
setallaiactive("FALSE" )
lockControls(2.000 )
cameraFocusToEntity("statue_magneto_gen_b_gn02", 350.000, 45.000, 180.000, 1.500 )
waittimed ( 2.000 )
cameraResetOldSchool( )
setallaiactive("TRUE" )
# ( "one conversation if leader is x-man" )
# ( "one conversation if leader is magneto" )
# ( "another conversation if leader is brotherhood" )
magnetoOnTeam = isActorOnTeam("magneto" )
if magnetoOnTeam == 1
     startConversation("act1/genosha/genosha5/1_genosha5_0121" )
else
     startConversation("act1/genosha/genosha5/1_genosha5_0120" )
endif

