# Generated by BehavEd
# ( "is mooring being destroyed for the first time?" )
m2_se = getGameFlag("genosha5", 9 )
if m2_se == 0
     # ( "indicate mooring has been destroyed" )
     setGameFlag("genosha5", 9, 1 )
     # ( "increment objective" )
     objective ( "act1_obj_5a",  "EOBJCMD_INCREMENT" )
     # ( "is this the last mooring to be destroyed?" )
     obj_5a_status = getObjective("act1_obj_5a", "COMPLETE" )
     if obj_5a_status == 1
          # ( "truly this is the last mooring, run a conversation" )
          startConversation("act1/genosha/genosha5/1_genosha5_0090" )
     endif
endif

