# Generated by BehavEd
# ( "spawn baddies when Blob thanks X-Men" )
waittimed ( 0.500 )
cameraReset( )
waittimed ( 1.000 )
lockControls(0.100 )
enemiesNoTarget("FALSE" )
heroNoTarget("FALSE" )
setReactToEnemies("blob", "TRUE" )
setEngageEnemy("blob", "TRUE" )
beATeamPlayer("blob", "TRUE" )
setAIActive("blob", "TRUE" )

