# Generated by BehavEd
# ( "first button pressed" )
# ( "camera cut?" )
cameraToLocationAngles(" 2478.890 -1250.600 204.450 ", " 2564.510 -1220.920 162.160 ", 0.000 )
setHintType("butt_01", "none" )
act("butt_01", "butt_01" )
act("statue_butt1", "statue_butt1" )
setGameFlag("monument1", 2, 1 )
waittimed ( 0.500 )
act("torchfire_01", "torchfire_01" )
waittimed ( 1.250 )
cameraReset( )
butts = getGameFlag("monument1", 3 )
if butts == 0
     startConversation("act2/monument/monument1/2_MONUMENT1_0030" )
else
     startConversation("act2/monument/monument1/2_MONUMENT1_0050" )
endif

