# Generated by BehavEd
# ( "first button pressed" )
# ( "camera cut?" )
cameraToLocationAngles(" 2122.900 -1004.930 232.390 ", " 2053.600 -1045.800 173.000 ", 0.000 )
setHintType("butt_02", "none" )
act("butt_02", "butt_02" )
act("statue_butt2", "statue_butt2" )
setGameFlag("monument1", 3, 1 )
waittimed ( 0.500 )
act("torchfire_02", "torchfire_02" )
waittimed ( 1.250 )
cameraReset( )
butts = getGameFlag("monument1", 2 )
if butts == 0
     startConversation("act2/monument/monument1/2_MONUMENT1_0030" )
else
     startConversation("act2/monument/monument1/2_MONUMENT1_0050" )
endif

