# Generated by BehavEd
# ( "grab the stone?" )
butt1 = getGameFlag("monument1", 2 )
butt2 = getGameFlag("monument1", 3 )
if butt1 == 1
     if butt2 == 1
          remove ( "mystic_stone", "mystic_stone" )
          objective ( "act2_obj_5a",  "EOBJCMD_COMPLETE" )
          act("stone_relay", "stone_relay" )
     else
          startConversation("act2/monument/monument1/2_MONUMENT1_0040" )
     endif
else
     startConversation("act2/monument/monument1/2_MONUMENT1_0040" )
endif

