# Generated by BehavEd
# ( "guardian dies, give us the stone and complete objective" )
setRecallActive("TRUE" )
act("kojakdoor", "kojakdoor" )
remove ( "kojakdoor", "kojakdoor" )
remove ( "statue_butt1", "statue_butt1" )
remove ( "statue_butt2", "statue_butt2" )

