# Generated by BehavEd
# ( "removes extra power triggers" )
remove ( "trigger_power01", "trigger_power01" )
remove ( "trigger_power02", "trigger_power02" )
remove ( "trigger_power03", "trigger_power03" )

