# Generated by BehavEd
# ( "This is turn on when both quests for periemter 3 and 4 are done" )
p3_done = getObjective("act4_obj_1a", "COMPLETE" )
p4_done = getObjective("act4_obj_1b", "COMPLETE" )
if p3_done == 1
     if p4_done == 1
          # ( "If p3_done and p3_done are = 1 then the zone link to perimeter 5 is enabled" )
          setEnable("zone_link02", "TRUE" )
     else
          display ( "Transported could not be activated" )
     endif
else
     display ( "Transported could not be activated" )
endif

