# Generated by BehavEd
# ( "This script has a sentinel fly by a perimeter platform" )
setInvisible("_OWNER_", "FALSE" )
setNoGravity("_OWNER_", "TRUE" )
setNoClip("_OWNER_", "TRUE" )
setNoCollide("_OWNER_", "TRUE" )
playanim (  "EA_ZONE1", "_OWNER_", "STOP", "" )
waittimed ( 6.000 )
sound (  "PLAY_SOUND", "zone_shared/special/sent_fly_past", "_OWNER_", "" )
waittimed ( 7.000 )
remove ( "_OWNER_", "_OWNER_" )

