# Generated by BehavEd
# ( "This a death script for bastion" )
dr = getDangerRoomActive( )
if dr == 1
     setDangerRoomSuccess( )
else
     setGameFlag("bosses", 21, 1 )
     setDefaultTarget("" )
     setInvisible("floaters", "TRUE" )
     setInvisible("landers", "TRUE" )
     setInvisible("landers2", "TRUE" )
     setInvisible("landers3", "TRUE" )
     setRecallActive("TRUE" )
     remove ( "sentinel_wave", "sentinel_wave" )
     waittimed ( 4.000 )
     killEntitySilent("bastion_sentinel" )
     # ( "This turns on the portal" )
     # ( "Defeate  Bastion Quest" )
     objective ( "act4_obj_1c",  "EOBJCMD_COMPLETE" )
     startConversation("act4/perimeter/perimeter5/4_perimeter5_0020" )
endif

