# Generated by BehavEd
# ( "spawns sentinels around bastion" )
whodidit = getName("_ACTIVATOR_" )
playanim (  "EA_POWER2", "bastion", "NONE", "animdone" )
waittimed ( 1.000 )
setZoneVar("spndsents", 4 )
stage = getZoneVar("stage" )
spawner = getNearestMonsterSpawner("bastion", 480.000 )
act(spawner, spawner )
spawner = getNearestMonsterSpawner("bastion", 480.000 )
act(spawner, spawner )
spawner = getNearestMonsterSpawner("bastion", 480.000 )
act(spawner, spawner )
spawner = getNearestMonsterSpawner("bastion", 480.000 )
act(spawner, spawner )
if stage >= 1
     setZoneVar("spndsents", 5 )
     spawner = getNearestMonsterSpawner("bastion", 480.000 )
     act(spawner, spawner )
endif
if stage >= 2
     setZoneVar("spndsents", 6 )
     spawner = getNearestMonsterSpawner("bastion", 480.000 )
     act(spawner, spawner )
endif

