# Generated by BehavEd
# ( "Script to run if player cancels a mission briefing from Avalon" )
cameraFade(1.000, 0.010 )
waittimed ( 0.020 )
lockControls(0.100 )
loadZone("act2/savage/savage1", "link_ant_metal_briefing" )

