# Generated by BehavEd
# ( "2000moneys is set to let you buy your way out of L.D." )
# ( "bit 1 true = got enough money!" )
setZoneVar("painthresh", 80 )
metladyd = getGameFlag("bosses", 5 )
if metladyd == 0
     setGameFlag("bosses", 5, 1 )
     setEnable("trigger_use01", "FALSE" )
     cameraFade(1.000, 1.000 )
     setRecallActive("FALSE" )
     waittimed ( 0.500 )
     lockControls(-1.000 )
     mymoney = getInventoryCount("MONEY" )
     if mymoney >= 2000
          setZoneFlag("2000moneys", 1, 1 )
     else
          setZoneFlag("2000moneys", 1, 0 )
     endif
     waittimed ( 0.500 )
     cameraToLocationAngles(" 2882.890 3708.460 98.410 ", " 2825.040 3645.490 46.570 ", 0.000 )
     heroNoTarget("TRUE" )
     enemiesNoTarget("TRUE" )
     controlPlayerHeroWithAI(-1.000 )
     copyOriginAndAngles("_HERO1_", "fake_dude04" )
     copyOriginAndAngles("_HERO2_", "fake_dude03" )
     copyOriginAndAngles("_HERO3_", "fake_dude02" )
     copyOriginAndAngles("_HERO4_", "fake_dude01" )
     setWaypointPath("_HERO1_", "herod", 1 )
     setWaypointPath("_HERO2_", "heroc", 1 )
     setWaypointPath("_HERO3_", "herob", 1 )
     setWaypointPath("_HERO4_", "heroa", 1 )
     cameraFade(0.000, 1.000 )
     waittimed ( 2.000 )
     controlPlayerHeroWithAI(0.100 )
     setallaiactive("FALSE" )
     act("deathstrike", "deathstrike" )
     setWaypointPath("_HERO1_", "", 1 )
     setWaypointPath("_HERO2_", "", 1 )
     setWaypointPath("_HERO3_", "", 1 )
     setWaypointPath("_HERO4_", "", 1 )
     waittimed ( 0.100 )
     setAIActive("lady_ds", "FALSE" )
     wolv = isActorOnTeam("wolverine" )
     xman = amIAnXman("_ACTIVATOR_" )
     if wolv == 1
          startConversation("act1/genosha/genosha1/1_GENOSHA1_0041" )
     elif xman == 1
          startConversation("act1/genosha/genosha1/1_GENOSHA1_0040" )
     else
          startConversation("act1/genosha/genosha1/1_GENOSHA1_0042" )
     endif
else
     setRecallActive("FALSE" )
     act("deathstrike", "deathstrike" )
     waittimed ( 0.300 )
     setDefaultTarget("lady_ds" )
endif

