# Generated by BehavEd
# ( "Lady Deathstryke's pain script" )
notdead = alive("_OWNER_" )
if notdead == 1
     recharging = getZoneVar("recharging" )
     health = getHealth("_OWNER_" )
     healthmax = getHealthMax("_OWNER_" )
     if recharging == 1
          # ( "stop recharging" )
          act("stop_charging", "stop_charging" )
     elif recharging == 3
          # ( "on her way to recharging, but stuck.. go back to middle" )
          # ( "set next threshhold to 20% less than current" )
          curpercent = fdiv(health, healthmax )
          percent = fsub(curpercent, 0.200 )
          percent = fmul(percent, 100.000 )
          setZoneVar("painthresh", percent )
          # ( "go to the middle of the arena" )
          setPatternSequence("lady_ds", "lds3" )
          setZoneVar("recharging", 0 )
     else
          painthresh = getZoneVar("painthresh" )
          painthreshf = fdiv(painthresh, 100.000 )
          hamt = fdiv(health, healthmax )
          if hamt <= painthreshf
               # ( "go recharge" )
               newhealth = fmul(painthreshf, healthmax )
               setHealth("_OWNER_", newhealth )
               recharging = getZoneVar("recharging" )
               if recharging != 2
                    setPatternSequence("_OWNER_", "lds1" )
                    setZoneVar("recharging", 2 )
                    # ( "failsafe incase she gets stuck pathing somewhere" )
                    waittimed ( 5.000 )
                    recharging = getZoneVar("recharging" )
                    if recharging == 2
                         setZoneVar("recharging", 3 )
                    endif
               endif
          endif
     endif
endif

