# Generated by BehavEd
# ( "This is the death script for lady deathstrike" )
dr = getDangerRoomActive( )
if dr == 0
     awardXPToPlayable(2500 )
endif
setGameFlag("bosses", 6, 1 )
waittimed ( 3.000 )
act("ready_doors", "ready_doors" )
act("open_doors", "open_doors" )
setDefaultTarget("" )
setRecallActive("TRUE" )
startConversation("act1/genosha/genosha1/1_GENOSHA1_0050" )

