# Generated by BehavEd
# ( "recharge 0.1% per .1 seconds (10% in 10 seconds)" )
notdead = alive("lady_ds" )
if notdead == 1
     sound (  "PLAY_SOUND", "boss_battles/lds/regen", "lady_ds", "" )
     health = getHealth("lady_ds" )
     healthmax = getHealthMax("lady_ds" )
     bonus = fmul(0.003000, healthmax )
     newhealth = fadd(health, bonus )
     setHealth("lady_ds", newhealth )
endif

