# Generated by BehavEd
# ( "if you paid her, L.D. leaves." )
act("ready_doors", "ready_doors" )
act("open_doors", "open_doors" )
setEnable("trigger_use01", "FALSE" )
mymoney = getInventoryCount("MONEY" )
newmoney = isub(mymoney, 2000 )
setInventoryCount("MONEY", newmoney )
setGameFlag("bosses", 6, 1 )
fade("lady_ds", 0.000, 1.500, "TRUE" )
waittimed ( 1.500 )
remove ( "lady_ds", "lady_ds" )
heroNoTarget("FALSE" )
enemiesNoTarget("FALSE" )
setallaiactive("TRUE" )
lockControls(0.100 )
cameraResetOldSchool( )

deathstrike_unlocked = isCharacterUnlocked("ladyd")
if deathstrike_unlocked == 0
    # ( "Lady Deathstrike is not yet unlocked, unlock her" )
    unlockCharacter("ladyd", " ")
    deathstrike_unlocked = isCharacterUnlocked("ladyd")
    if deathstrike_unlocked == 1
        # ( "Lady Deathstrike was not previously unlocked but she is on the roster" )
        # ( "She's been unlocked now, so show the dialog that confirms this" )
        createPopupDialogXML("dialogs/act1/genosha/deathstrike_unlocked")
    endif 
endif 