# Generated by BehavEd
# ( "comment" )
heroNoTarget("FALSE" )
enemiesNoTarget("FALSE" )
lockControls(0.100 )
setCanMove("lady_ds", "TRUE" )
setEnable("trigger_use01", "FALSE" )
setallaiactive("TRUE" )
setAIActive("lady_ds", "TRUE" )
setDefaultTarget("lady_ds" )
cameraResetOldSchool( )

