# Generated by BehavEd
# ( "This is the zone load script for genosha1" )
# ( "if you beat lady deathstrike, remove her and open doors" )
beat_deathstrike = getGameFlag("bosses", 6 )
if beat_deathstrike == 1
     remove ( "trigger_touch02", "trigger_touch02" )
     act("door_inv_03", "door_inv_03" )
     act("dd01", "dd01" )
else
     setRecallActive("FALSE" )
endif
# ( "checks status on prisoners" )
# ( "spawns prisoners if they're not saved." )
prisoners = getGameFlag("prisoners", 10 )
if prisoners == 0
     act("g1_prisoner_01", "g1_prisoner_01" )
endif
prisoners = getGameFlag("prisoners", 11 )
if prisoners == 0
     act("g1_prisoner_02", "g1_prisoner_02" )
endif
prisoners = getGameFlag("prisoners", 12 )
if prisoners == 0
     act("g1_prisoner_03", "g1_prisoner_03" )
endif
prisoners = getGameFlag("prisoners", 13 )
if prisoners == 0
     act("g1_prisoner_04", "g1_prisoner_04" )
endif
prisoners = getGameFlag("prisoners", 14 )
if prisoners == 0
     act("g1_prisoner_05", "g1_prisoner_05" )
endif
prisoners = getGameFlag("prisoners", 15 )
if prisoners == 0
     act("g1_prisoner_06", "g1_prisoner_06" )
endif
prisoners = getGameFlag("prisoners", 16 )
if prisoners == 0
     act("g1_prisoner_07", "g1_prisoner_07" )
endif
prisoners = getGameFlag("prisoners", 17 )
if prisoners == 0
     act("g1_prisoner_08", "g1_prisoner_08" )
endif
prisoners = getGameFlag("prisoners", 18 )
if prisoners == 0
     act("g1_prisoner_09", "g1_prisoner_09" )
endif
prisoners = getGameFlag("prisoners", 19 )
if prisoners == 0
     act("g1_prisoner_10", "g1_prisoner_10" )
endif
prisoners = getGameFlag("prisoners", 20 )
if prisoners == 0
     act("g1_prisoner_11", "g1_prisoner_11" )
endif
prisoners = getGameFlag("prisoners", 25 )
if prisoners == 1
     remove ( "sp_genoshaprisoner_a15", "sp_genoshaprisoner_a15" )
     waittimed ( 0.500 )
     remove ( "caleb", "caleb" )
     remove ( "door_secret_gen_a_gn01", "door_secret_gen_a_gn01" )
     remove ( "remove_out1", "remove_out1" )
     remove ( "remove_out2", "remove_out2" )
endif
# ( "if this is the first visit, prof x talks to you" )
profxtalk = getGameFlag("act1_visit", 8 )
if profxtalk == 0
     setGameFlag("act1_visit", 8, 1 )
     startConversation("act1/genosha/genosha1/1_GENOSHA1_0010" )
     newMissionBriefing( )
endif

