# Generated by BehavEd
# ( "comment" )
objective ( "act1_obj_5b",  "EOBJCMD_INCREMENT" )
setGameFlag("prisoners", 15, 1 )
prisonercount = getObjective("act1_obj_5b", "COUNT" )
if prisonercount == 1
     startConversation("act1/genosha/genosha1/1_GENOSHA1_0020" )
elif prisonercount == 11
     objective ( "act1_obj_5b",  "EOBJCMD_COMPLETE" )
     allprisoners = getObjective("act1_obj_5c", "COMPLETE" )
     if allprisoners == 1
          fade("_OWNER_", 0.000, 2.000, "TRUE" )
          waittimed ( 2.000 )
          remove ( "_OWNER_", "_OWNER_" )
          startConversation("act1/genosha/genosha2/1_GENOSHA2_0011" )
     else
          startConversation("act1/genosha/genosha1/1_GENOSHA1_0035" )
     endif
else
     startConversation("act1/genosha/genosha1/1_GENOSHA1_0035" )
endif

