# Generated by BehavEd
# ( "Thi script shows the player where the secret door is." )
setEnable("door_secret_gen_a_gn01", "TRUE" )
setEnable("door_inv_secret", "TRUE" )
cameraToLocationAngles(" 4977.000 3858.000 157.000 ", " 4974.000 3943.000 104.000 ", 0.000 )
waittimed ( 1.000 )
act("door_secret_gen_a_gn01", "door_secret_gen_a_gn01" )
remove ( "remove_out1", "remove_out1" )
remove ( "remove_out2", "remove_out2" )
setGameFlag("prisoners", 25, 1 )
remove ( "caleb", "caleb" )
waittimed ( 3.000 )
cameraReset( )

