# Generated by BaconWizard17
# ( "No script was called after the conversation after defeating Lady Deathstrike, so I added this one" )

deathstrike_unlocked = isCharacterUnlocked("ladyd")
if deathstrike_unlocked == 0
    # ( "Lady Deathstrike is not yet unlocked, unlock her" )
    unlockCharacter("ladyd", " ")
    deathstrike_unlocked = isCharacterUnlocked("ladyd")
    if deathstrike_unlocked == 1
        # ( "Lady Deathstrike was not previously unlocked but she is on the roster" )
        # ( "She's been unlocked now, so show the dialog that confirms this" )
        createPopupDialogXML("dialogs/act1/genosha/genosha1/deathstrike_unlocked")
    endif 
endif 