# Generated by BehavEd
# ( "garokk spawn script" )
metgarokk = getGameFlag("bosses", 8 )
setGameFlag("gar_friends", 1, 1 )
if metgarokk == 1
     waittimed ( 0.200 )
     setPatternSequence("_OWNER_", "garokk2" )
endif

