# Generated by BehavEd
# ( "move party from pit cave entrance to regular cave entrance" )
hero1 = alive("_HERO1_" )
if hero1 > 0
     act("entrapping_vines_jun_a_ju01", "entrapping_vines_jun_a_ju01" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     act("entrapping_vines_jun_a_ju04", "entrapping_vines_jun_a_ju04" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     act("entrapping_vines_jun_a_ju02", "entrapping_vines_jun_a_ju02" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     act("entrapping_vines_jun_a_ju03", "entrapping_vines_jun_a_ju03" )
endif

