# Generated by BehavEd
# ( "meet and greet with Garrok" )
heroNoTarget("TRUE" )
enemiesNoTarget("TRUE" )
waittimed ( 0.250 )
lockControls(-1.000 )
cameraFocusToEntity("boss_camera01", 300.000, 25.000, 0.000, 3.000 )
waittimed ( 0.750 )
setWaypointPath("garok", "garokkpath", 1 )
waittimed ( 3.000 )
# ( "set met garokk flag" )
setGameFlag("bosses", 8, 1 )
startConversation("act2/jungle/jungle1/2_jungle1_0030" )

