# Generated by BehavEd
# ( "enter the omega red arena" )
setWaypointPath("garok", "", 0 )
setRecallActive("FALSE" )
setEngageEnemy("mystique", "TRUE" )
setEngageEnemy("garok", "TRUE" )
setDefaultTarget("garok" )
attackEntityWithType("garok", "_ACTIVE_HERO_", "ANY", "FALSE" )

