# Generated by BehavEd
# ( "zone script" )
metmyst1 = getGameFlag("meetmyst", 1 )
if metmyst1 == 1
     remove ( "trigger_touch02", "trigger_touch02" )
     remove ( "sp_mystique01", "sp_mystique01" )
endif
if metmyst1 == 0
     waittimed ( 0.500 )
     startConversation("act2/jungle/jungle1/2_jungle1_0010" )
endif
metgarokk = getGameFlag("bosses", 8 )
if metgarokk == 1
     remove ( "dynamic_clip01", "dynamic_clip01" )
     remove ( "dynamic_clip02", "dynamic_clip02" )
     remove ( "dynamic_clip03", "dynamic_clip03" )
     remove ( "dynamic_clip04", "dynamic_clip04" )
     remove ( "dynamic_clip05", "dynamic_clip05" )
     remove ( "dynamic_clip06", "dynamic_clip06" )
     remove ( "dynamic_clip07", "dynamic_clip07" )
     remove ( "dynamic_clip08", "dynamic_clip08" )
     remove ( "dynamic_clip09", "dynamic_clip09" )
     remove ( "dynamic_clip10", "dynamic_clip10" )
     remove ( "dynamic_clip11", "dynamic_clip11" )
     remove ( "dynamic_clip12", "dynamic_clip12" )
     remove ( "dynamic_clip13", "dynamic_clip13" )
     remove ( "dynamic_clip14", "dynamic_clip14" )
     remove ( "dynamic_clip15", "dynamic_clip15" )
     remove ( "dynamic_clip16", "dynamic_clip16" )
     remove ( "relay01", "relay01" )
     remove ( "relay02", "relay02" )
     remove ( "relay03_notarget", "relay03_notarget" )
     remove ( "mystique_terror", "mystique_terror" )
     setEnable("mystique02", "TRUE" )
     setEnable("arena_trigger", "TRUE" )
     beatgarokk = getGameFlag("bosses", 9 )
     if beatgarokk == 1
          remove ( "mystique02", "mystique02" )
          remove ( "arena_trigger", "arena_trigger" )
          remove ( "sp_garokk01", "sp_garokk01" )
          setEnable("trigger_touch12", "TRUE" )
          setEnable("trigger_touch08", "TRUE" )
     endif
endif
setCurrentAct(2 )

