# Generated by BehavEd
# ( "mystique leaves in a huff" )
act("sp_mystique01", "sp_mystique01" )
lockControls(-1.000 )
heroNoTarget("TRUE" )
enemiesNoTarget("TRUE" )
waittimed ( 0.250 )
cameraMove(" 4021.840 2245.070 150.510 ", 2.000 )
cameraPan(" 0.000 41.400 337.400 ", 2.000, "FALSE" )
setWaypointPath("mystique", "mystique", 1 )
waittimed ( 2.500 )
playanim (  "EA_TALKING_04", "mystique", "NONE", "" )
startCharConversation("act2/jungle/jungle1/2_jungle1_0020", "rogue", "act2/jungle/jungle1/2_jungle1_0021" )

