# Generated by BehavEd
# ( "leave the omega red arena" )
setRecallActive("TRUE" )
setEngageEnemy("mystique", "FALSE" )
setEngageEnemy("garok", "FALSE" )
setWaypointPath("garok", "garokkhome", 1 )
setDefaultTarget("" )

