# Generated by BehavEd
# ( "move party from tiger pit cave entrance to secret cave entrance" )
setallaiactive("FALSE" )
lockControls(-1.000 )
setEnable("trigger_cavelight01", "TRUE" )
cameraFade(1.000, 0.500 )
waittimed ( 0.750 )
hero1 = alive("_HERO1_" )
if hero1 > 0
     copyOriginAndAngles("_HERO1_", "playerA01" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     copyOriginAndAngles("_HERO2_", "playerA02" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     copyOriginAndAngles("_HERO3_", "playerA03" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     copyOriginAndAngles("_HERO4_", "playerA04" )
endif
waittimed ( 0.750 )
copyOriginAndAngles("boulder_move01", "boulder_fall01" )
copyOriginAndAngles("boulder_move02", "boulder_fall02" )
copyOriginAndAngles("dynamic_clip_pit01", "dynamic_clip_pit" )
cameraFade(0.000, 0.500 )
waittimed ( 0.500 )
cameraShake(3.000, 4.000 )
act("effect_cave-in", "effect_cave-in" )
act("effect_cave-in05", "effect_cave-in05" )
sound (  "PLAY_SOUND", "zone_shared/special/rocks_falling", "", "" )
setallaiactive("TRUE" )
lockControls(0.100 )

