# Generated by BehavEd
# ( "move party from regular cave to boss fight island" )
setEnable("trigger_outsideight02", "TRUE" )
cameraFade(1.000, 0.500 )
act("sp_garokk01", "sp_garokk01" )
metgarokk = getGameFlag("bosses", 8 )
if metgarokk == 0
     act("mystique_terror", "mystique_terror" )
else
     act("mystique02", "mystique02" )
     waittimed ( 0.100 )
     setWaypointPath("mystique", "", 0 )
endif
waittimed ( 0.500 )
setallaiactive("FALSE" )
lockControls(-1.000 )
copyOriginAndAngles("_HERO1_", "playerA17" )
copyOriginAndAngles("_HERO2_", "playerA18" )
copyOriginAndAngles("_HERO3_", "playerA19" )
copyOriginAndAngles("_HERO4_", "playerA20" )
lockControls(0.100 )
waittimed ( 0.500 )
cameraFade(0.000, 0.500 )
waittimed ( 0.500 )
setallaiactive("TRUE" )

