# Generated by BehavEd
# ( "move party from regular cave to boss fight island" )
setallaiactive("FALSE" )
lockControls(-1.000 )
setEnable("trigger_cavelight03", "TRUE" )
cameraFade(1.000, 0.500 )
waittimed ( 0.750 )
hero1 = alive("_HERO1_" )
if hero1 > 0
     copyOriginAndAngles("_HERO1_", "playerA25" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     copyOriginAndAngles("_HERO2_", "playerA26" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     copyOriginAndAngles("_HERO3_", "playerA27" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     copyOriginAndAngles("_HERO4_", "playerA28" )
endif
killEntity("boulder_giant_jun_m_ju02" )
waittimed ( 0.750 )
cameraFade(0.000, 0.500 )
waittimed ( 0.500 )
setallaiactive("TRUE" )
lockControls(0.100 )

