# Generated by BehavEd
# ( "move party from tele pad in Garokk's area to level entrance" )
setallaiactive("FALSE" )
lockControls(-1.000 )
cameraFade(1.000, 0.500 )
waittimed ( 0.750 )
hero1 = alive("_HERO1_" )
if hero1 > 0
     copyOriginAndAngles("_HERO1_", "playerA33" )
endif
hero2 = alive("_HERO2_" )
if hero2 > 0
     copyOriginAndAngles("_HERO2_", "playerA34" )
endif
hero3 = alive("_HERO3_" )
if hero3 > 0
     copyOriginAndAngles("_HERO3_", "playerA35" )
endif
hero4 = alive("_HERO4_" )
if hero4 > 0
     copyOriginAndAngles("_HERO4_", "playerA36" )
endif
waittimed ( 0.750 )
cameraFade(0.000, 0.500 )
waittimed ( 0.500 )
setallaiactive("TRUE" )
lockControls(0.100 )

