startMovie("cine01","waitSignal")
waitsignal("waitSignal")
loadMapChooseTeam("act0/tutorial/tutorial1")
unlockCharacter("Cable"," ")
unlockCharacter("Cannonball"," ")
unlockCharacter("Darkphoenix"," ")
unlockCharacter("Jubilee"," ")
unlockCharacter("Magma"," ")
unlockCharacter("Psylocke"," ")
unlockCharacter("Xman"," ")