# Generated by BehavEd
# ( "open the doors so the team can leave" )
act("ambush_door01", "ambush_door01" )
act("ambush_door02", "ambush_door02" )
# ( "enable the Blink Portal" )
setRecallActive("TRUE" )

