# Generated by BehavEd
# ( "has tower entry conversation been run?" )
check = getGameFlag("sewers", 3 )
if check == 1
     # ( "tower entry conversation has been run--remove trigger" )
     remove ( "trig_tower", "trig_tower" )
endif

