# Generated by BehavEd
# ( "comment" )
setAIActive("_OWNER_", "FALSE" )
setNoCollide("_OWNER_", "TRUE" )
uniquename = getIDString("_OWNER_" )
playanim (  "EA_ZONE1", "_OWNER_", "NONE", uniquename )
waitsignal ( uniquename )
setAIActive("_OWNER_", "TRUE" )
setNoCollide("_OWNER_", "FALSE" )

