# Generated by BehavEd
# ( "comment" )
fan_blade = getGameFlag("sewers", 1 )
if fan_blade == 1
     copyOriginAndAngles("fan_puzzle_slower", "fan_puzzle" )
     remove ( "fan_puzzle", "fan_puzzle" )
     act("fan_puzzle_slower", "fan_puzzle_slower" )
     setEnable("trigger_beacon", "TRUE" )
     setEnable("fan_generator", "FALSE" )
     remove ( "fan_light", "fan_light" )
     remove ( "find_fan_conv", "find_fan_conv" )
     remove ( "find_beacon_trigger", "find_beacon_trigger" )
     # ( "has the homing beacon been picked up?" )
     beacon = getGameFlag("sewers", 2 )
     if beacon == 1
          # ( "homing beacon has been picked up--remove trigger" )
          remove ( "trigger_beacon", "trigger_beacon" )
     endif
endif

