# Generated by BehavEd
copyOriginAndAngles("treasure_chest01", "treasure_spot" )
spawnEffect("treasure_chest01", "base/item/item_pickup", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
fade("treasure_chest01", 1.000, 2.000, "FALSE" )

