# Generated by BehavEd
# ( "comment" )
cameraFade(1.000, 0.500 )
waittimed ( 0.500 )
lockControls(-1.000 )
heroNoTarget("TRUE" )
enemiesNoTarget("TRUE" )
cameraFade(0.000, 0.500 )
startConversation("act4/sewers/sewers2/4_SEWERS2_0010" )

