# Generated by BehavEd
# ( "to secret area" )
cameraFade(1.000, 1.000 )
heroNoTarget("TRUE" )
enemiesNoTarget("TRUE" )
waittimed ( 1.000 )
# ( "moves all living heros to specified entity" )
moveHeroesToEnt("home" )
cameraReset( )
cameraFade(0.000, 1.000 )
waittimed ( 0.250 )
heroNoTarget("FALSE" )
enemiesNoTarget("FALSE" )

