# Generated by BehavEd
# ( "has the keycard been found?" )
sewers2 = getGameFlag("sewers", 4 )
if sewers2 == 1
     # ( "keycard has been found already--remove it from the world" )
     remove ( "keycard", "keycard" )
endif
# ( "has Banshee been found?" )
sewers2 = getGameFlag("sewers", 5 )
if sewers2 == 1
     # ( "Banshee has been found already--destroy him!" )
     waittimed ( 0.500 )
     remove ( "banshee_ent", "banshee_ent" )
     remove ( "trig_banshee", "trig_banshee" )
endif
# ( "has the water drain been shut off?" )
sewers2 = getGameFlag("sewers", 6 )
if sewers2 == 1
     # ( "water drain has been shut off already--disable switch, remove fx" )
     setEnable("switch_drain", "FALSE" )
     remove ( "water_puzzle_drain", "water_puzzle_drain" )
     # ( "the data disc needs to be in place if it hasn't been picked up yet" )
     copyOriginAndAngles("data_disc_sewers", "null01" )
endif

