startMovie("i102", "afterMovie1")
waitsignal("afterMovie1")
startMovie("i101", "afterMovie2")
waitsignal("afterMovie2")
startMovie("i103", "afterMovie3")
waitsignal("afterMovie3")
startMovie("i105", "afterMovie4")
waitsignal("afterMovie4")
startMovie("i104", "afterMovie5")
waitsignal("afterMovie5")
startMovie("i106", "afterMovie6")
waitsignal("afterMovie6")
mainMenuExit()
