# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept40.png" )
imageViewer("textures/concept/concept41.png" )
imageViewer("textures/concept/concept42.png" )

