# Generated by BehavEd
# ( "script called from Coolant Console to dump coolant tank contents" )
act("cool_tank_01", "cool_tank_01" )
act("cool_tank_02", "cool_tank_02" )
debug("KA-BOOM! Oh-my-god! The tanks blew! The whole place is comin' down 'round us! AAAHH!" )
setGameFlag("protocols", 2, 1 )
objective ( "act3_obj_3b_a",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_3b",  "EOBJCMD_COMPLETE" )
remove ( "trigger_CDO", "trigger_CDO" )
act("shaker", "shaker" )

