# Generated by BehavEd
# ( "if player has CDO_Command = 1 game var, grant access to computer and allow coolant dump" )
setCurrentAct(3 )
# ( "changing to protocols 1" )
protocols = getGameFlag("protocols", 1 )
objective ( "CDO_Command",  "EOBJCMD_SHOW" )
if protocols == 1
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

