# Generated by BehavEd
# ( "plays crane toppling animation" )
setGameFlag("inf_tanks", 6, 1 )
killEntity("giant_crane_01" )
remove ( "crane_push_trigger01", "crane_push_trigger01" )
remove ( "crane_push_trigger", "crane_push_trigger" )
sound (  "PLAY_SOUND", "zone_shared/mover/crane_pushed", "", "" )
waittimed ( 1.750 )
cameraShake(10.000, 3.000 )
remove ( "roller_clippage", "roller_clippage" )
killEntity("roller1" )
sound (  "PLAY_SOUND", "zone_shared/special/break_rollers", "", "" )
killEntity("roller2" )

