# Generated by BehavEd
# ( "comment" )
setGameFlag("inf_tanks", 5, 1 )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
cameraToLocationAngles(" 17396.828 15562.790 271.912 ", " 17572.189 15650.850 0.000 ", 0.000 )
cameraFade(0.000, 1.000 )
startConversation("act3/infinite/infinite3/3_INFINITE3_0015" )

