# Generated by BehavEd
# ( "makes maintenance droids ingnore enemies for 3 seconds before aggro" )
setReactToEnemies("wp_maintenance_droid_08", "FALSE" )
waittimed ( 5.000 )
setReactToEnemies("wp_maintenance_droid_08", "TRUE" )

