# Generated by BehavEd
# ( "comment" )
setEnable("conduit_powerpuzz", "TRUE" )
setEnable("generator_powerpuz1", "TRUE" )
setEnable("generator_powerpuz2", "TRUE" )
setEnable("tank_push_trigger1", "TRUE" )
setEnable("tank_push_trigger2", "TRUE" )
setInvulnerable("dna_cradle1", "FALSE" )
setInvulnerable("dna_cradle2", "FALSE" )
setHintType("cool_tank_falling02", "OBJECTIVE" )
setHintType("cool_tank_falling1", "OBJECTIVE" )

