# Generated by BehavEd
# ( "set current act and show main objective" )
setCurrentAct(3 )
visited = getGameFlag("act3_visit", 7 )
if visited == 0
     # ( "conversation with hudson here" )
     startConversation("act3/infinite/infinite3/3_INFINITE3_0010" )
     setInvulnerable("dna_cradle1", "TRUE" )
     setInvulnerable("dna_cradle2", "TRUE" )
     objective ( "act3_obj_3b_a",  "EOBJCMD_SHOW" )
endif
setGameFlag("act3_visit", 7, 1 )
protocols = getGameFlag("inf_tanks", 5 )
if protocols == 1
     waittimed ( 1.000 )
     remove ( "trigger_CDO", "trigger_CDO" )
     setEnable("conduit_powerpuzz", "TRUE" )
     setEnable("generator_powerpuz1", "TRUE" )
     setEnable("generator_powerpuz2", "TRUE" )
     setEnable("tank_push_trigger1", "TRUE" )
     setEnable("tank_push_trigger2", "TRUE" )
     setInvulnerable("dna_cradle1", "FALSE" )
     setInvulnerable("dna_cradle2", "FALSE" )
     setHintType("cool_tank_falling02", "OBJECTIVE" )
     setHintType("cool_tank_falling1", "OBJECTIVE" )
endif
tanks_of_victory = getGameFlag("inf_tanks", 1 )
if tanks_of_victory == 1
     copyOriginAndAngles("cool_tank_01", "tankswap01" )
     swapInStump("cool_tank_01" )
     remove ( "cool_tank_falling1", "cool_tank_falling1" )
     remove ( "tank_push_trigger1", "tank_push_trigger1" )
     swapInStump("dna_cradle1" )
     setEnable("generator_powerpuz2", "FALSE" )
     setEnable("conduit_powerpuzz", "FALSE" )
endif
tanks_of_victory = getGameFlag("inf_tanks", 2 )
if tanks_of_victory == 1
     copyOriginAndAngles("cool_tank_02", "tankswap02" )
     swapInStump("cool_tank_02" )
     remove ( "cool_tank_falling02", "cool_tank_falling02" )
     remove ( "tank_push_trigger2", "tank_push_trigger2" )
     swapInStump("dna_cradle2" )
     setEnable("generator_powerpuz1", "FALSE" )
     setEnable("conduit_powerpuzz", "FALSE" )
endif
tanks_of_victory = getGameFlag("inf_tanks", 3 )
if tanks_of_victory == 1
     remove ( "cool_tank_falling1", "cool_tank_falling1" )
     remove ( "tank_push_trigger1", "tank_push_trigger1" )
     swapInStump("dna_cradle1" )
     setEnable("generator_powerpuz2", "FALSE" )
     setEnable("conduit_powerpuzz", "FALSE" )
endif
tanks_of_victory = getGameFlag("inf_tanks", 4 )
if tanks_of_victory == 1
     remove ( "cool_tank_falling02", "cool_tank_falling02" )
     remove ( "tank_push_trigger2", "tank_push_trigger2" )
     swapInStump("dna_cradle2" )
     setEnable("generator_powerpuz1", "FALSE" )
     setEnable("conduit_powerpuzz", "FALSE" )
endif
crane_of_topple = getGameFlag("inf_tanks", 6 )
if crane_of_topple == 1
     killEntity("giant_crane_01" )
     remove ( "crane_push_trigger01", "crane_push_trigger01" )
     remove ( "crane_push_trigger", "crane_push_trigger" )
     remove ( "roller_clippage", "roller_clippage" )
     killEntity("roller1" )
     killEntity("roller2" )
endif
beat_it = getObjective("act3_obj_3b", "COMPLETE" )
if beat_it == 1
     # ( "prepare teleporter" )
     act("teleporter", "teleporter" )
     remove ( "no_go_trigger", "no_go_trigger" )
     setEnable("link_center", "TRUE" )
     setEnable("teleport_chat", "TRUE" )
endif

