# Generated by BehavEd
# ( "cuckoo gets to an altar" )
act("cuckoo_minion_spawner", "cuckoo_minion_spawner" )
playCombatNodeTrigger("_ACTIVATOR_", "powerup_noknock", 70 )
setAIActive("_ACTIVATOR_", "FALSE" )
setWaypointPath("_ACTIVATOR_", "", 0 )
copyOriginAndAngles("_ACTIVATOR_", "_OWNER_" )
setNoCollide("_ACTIVATOR_", "FALSE" )
playanim (  "EA_POWER4", "_ACTIVATOR_", "LOOP", "" )

