# Generated by BehavEd
# ( "calculate health percentage" )
stage = getZoneVar("c2_stage" )
stage = iadd(stage, 1 )
health = getHealth("_OWNER_" )
healthmax = getHealthMax("_OWNER_" )
hamt = fdiv(health, healthmax )
# ( "figure out what the theshold for the next stage should be" )
thresh = fmul(stage, 0.333 )
hthresh = fsub(1.000000, thresh )
if hamt < hthresh
     setZoneVar("c2_stage", stage )
     newhealth = fmul(hthresh, healthmax )
     setHealth("_OWNER_", newhealth )
     # ( "do the stuff" )
     act("cuckoo_stages", "_OWNER_" )
     if stage >= 2
          setBossUndying("_OWNER_", "FALSE" )
     endif
endif

