# Generated by BehavEd
# ( "comment" )
setWaypointPath("_ACTIVATOR_", "", 0 )
setEngageEnemy("_ACTIVATOR_", "TRUE" )
attackEntityWithType("_ACTIVATOR_", "_ACTIVE_HERO_", "attacklight1", "FALSE" )
setNoClip("_ACTIVATOR_", "FALSE" )

