# Generated by BehavEd
# ( "spawn minions for the cuckoos" )
setEnable("cuckoo_door01", "TRUE" )
act("cuckoo_door01", "cuckoo_door01" )
act("sp_cuckooMA", "sp_cuckooMA" )
waittimed ( 0.100 )
setEnable("cuckoo_door02", "TRUE" )
act("cuckoo_door02", "cuckoo_door02" )
act("sp_cuckooMB", "sp_cuckooMB" )

