# Generated by BehavEd
# ( "all the fake cuckoos do this" )
setEngageEnemy("_OWNER_", "FALSE" )
setNoCollide("_OWNER_", "TRUE" )
setNoClip("_OWNER_", "TRUE" )
fade("_OWNER_", 0.500, 0.000, "TRUE" )
# ( "safety reset just incase something goes horribly wrong" )
waittimed ( 5.000 )
setNoClip("_OWNER_", "FALSE" )

