# Generated by BehavEd
# ( "holocaust's pain script" )
# ( "calculate health percentage" )
stage = getZoneVar("h_stage" )
stage = iadd(stage, 1 )
health = getHealth("_OWNER_" )
healthmax = getHealthMax("_OWNER_" )
hamt = fdiv(health, healthmax )
# ( "figure out what the theshold for the next stage should be" )
thresh = getZoneVar("painthresh" )
hthresh = fdiv(thresh, 100.000 )
if hthresh < 0.750000
     if stage == 1
          hthresh = fadd(0.000, 0.750 )
          dostage = iadd(0, 1 )
     endif
endif
if hthresh < 0.500000
     if stage == 2
          hthresh = fadd(0.000, 0.500 )
          dostage = iadd(0, 1 )
     endif
endif
if hthresh < 0.250000
     if stage == 3
          hthresh = fadd(0.000, 0.250 )
          dostage = iadd(0, 1 )
     endif
endif
if hamt < hthresh
     if hthresh > 0.05
          # ( "-- do the stuff --" )
          newhealth = fmul(hthresh, healthmax )
          setHealth("_OWNER_", newhealth )
          if dostage == 1
               # ( "spawn in a cuckoo" )
               setZoneVar("h_stage", stage )
               # ( "cuckoo #1 returns" )
               if stage == 1
                    # ( "cuckoo #1 returns" )
                    setZoneVar("painthresh", 65 )
                    cameraMove(" 1121.950 1635.410 284.585 ", 1.000 )
                    cameraPan(" 0.000 24.700 4.816 ", 1.000, "FALSE" )
                    lockControls(-1.000 )
                    setInvulnerable("holocaust", "TRUE" )
                    playCombatNodeTrigger("holocaust", "powerup_invul", 71 )
                    enemiesNoTarget("TRUE" )
                    heroNoTarget("TRUE" )
                    # ( "comment" )
                    setEnable("topright_door", "TRUE" )
                    act("topright_door", "topright_door" )
                    act("sp_cuckooZ", "sp_cuckooZ" )
                    waittimed ( 2.000 )
                    lockControls(0.100 )
                    killEntity("right_forcefield" )
                    showHealthBar("cuckoo_altar01", "TRUE" )
                    setInvulnerable("cuckoo_altar01", "FALSE" )
                    setEnable("cuckoo_altar01", "TRUE" )
                    startConversation("act3/madri/madri7/3_madri7_0025" )
               endif
               # ( "cuckoo #2 returns" )
               if stage == 2
                    # ( "cuckoo #2 returns" )
                    setZoneVar("painthresh", 40 )
                    cameraMove(" 1296.720 1635.650 284.585 ", 1.000 )
                    cameraPan(" 0.000 24.681 174.835 ", 1.000, "FALSE" )
                    sound (  "PLAY_SOUND", "voice/stepfordcuckoo/altar", "", "" )
                    lockControls(-1.000 )
                    setInvulnerable("holocaust", "TRUE" )
                    playCombatNodeTrigger("holocaust", "powerup_invul", 71 )
                    enemiesNoTarget("TRUE" )
                    heroNoTarget("TRUE" )
                    # ( "comment" )
                    setEnable("topleft_door", "TRUE" )
                    act("topleft_door", "topleft_door" )
                    act("sp_cuckooZZ", "sp_cuckooZZ" )
                    waittimed ( 2.000 )
                    killEntity("left_forcefield" )
                    showHealthBar("cuckoo_altar02", "TRUE" )
                    setInvulnerable("cuckoo_altar02", "FALSE" )
                    setEnable("cuckoo_altar02", "TRUE" )
                    waittimed ( 1.000 )
                    cameraReset( )
                    lockControls(0.100 )
                    sound (  "PLAY_SOUND", "voice/holocaust/sc_power", "", "" )
                    enemiesNoTarget("FALSE" )
                    heroNoTarget("FALSE" )
               endif
               # ( "cuckoo #3 returns" )
               if stage == 3
                    # ( "cuckoo #3 returns" )
                    cameraMove(" 1146.870 1498.300 284.585 ", 1.000 )
                    cameraPan(" 0.000 24.681 64.835 ", 1.000, "FALSE" )
                    sound (  "PLAY_SOUND", "voice/stepfordcuckoo/altar", "", "" )
                    setZoneVar("painthresh", 15 )
                    lockControls(-1.000 )
                    playCombatNodeTrigger("holocaust", "powerup_invul", 71 )
                    setInvulnerable("holocaust", "TRUE" )
                    setBossUndying("holocaust", "FALSE" )
                    enemiesNoTarget("TRUE" )
                    heroNoTarget("TRUE" )
                    # ( "comment" )
                    setEnable("topright_door", "TRUE" )
                    act("topright_door", "topright_door" )
                    act("sp_cuckooZZZ", "sp_cuckooZZZ" )
                    waittimed ( 2.000 )
                    killEntity("top_forcefield" )
                    showHealthBar("cuckoo_altar03", "TRUE" )
                    setEnable("cuckoo_altar03", "TRUE" )
                    setInvulnerable("cuckoo_altar03", "FALSE" )
                    waittimed ( 1.000 )
                    lockControls(0.100 )
                    cameraReset( )
                    sound (  "PLAY_SOUND", "voice/holocaust/sc_power", "", "" )
                    enemiesNoTarget("FALSE" )
               endif
          else
               # ( "suck minion" )
               setPatternSequence("holocaust", "suck_life" )
               # ( "set next pain threshhold" )
               act("stop_sucking", "stop_sucking" )
          endif
     endif
endif

