# Generated by BehavEd
# ( "comment" )
donethat = getGameFlag("bosses", 19 )
# ( "Ryan, I'm not entirely sure if this objective should be completed within" )
# ( "the confines of one of these conditions. It just has to be completed" )
# ( "when you enter this map for the first time. --kf 6/21/05" )
objective ( "act3_obj_6a_3",  "EOBJCMD_COMPLETE" )
if donethat == 1
     remove ( "battle_trigger", "battle_trigger" )
     remove ( "top_forcefield", "top_forcefield" )
     remove ( "left_forcefield", "left_forcefield" )
     remove ( "right_forcefield", "right_forcefield" )
     swapInStump("cuckoo_altar01" )
     swapInStump("cuckoo_altar02" )
     swapInStump("cuckoo_altar03" )
else
     setRecallActive("FALSE" )
endif

