# Generated by BehavEd
# ( "spawn holocaust" )
setInvulnerable("holocaust", "TRUE" )
setZoneVar("painthresh", 90 )
act("holocaust_spawnfx", "holocaust_spawnfx" )
playCombatNodeTrigger("_ACTIVATOR_", "powerup_fist", 70 )
playanim (  "EA_ZONE1", "_OWNER_", "NONE", "" )

