# Generated by BehavEd
# ( "end holointro" )
cameraReset( )
setInvulnerable("holocaust", "FALSE" )
setDefaultTarget("holocaust" )
enemiesNoTarget("FALSE" )
heroNoTarget("FALSE" )
# ( "lazy hack - this entity needs to be acted on 4 times to work." )
act("minion_spawner", "minion_spawner" )
act("minion_spawner", "minion_spawner" )
waittimed ( 0.100 )
act("minion_spawner", "minion_spawner" )
act("minion_spawner", "minion_spawner" )

