# Generated by BehavEd
# ( "comment" )
lockControls(-1.000 )
setallaiactive("FALSE" )
cameraMove(" 1268.140 1393.540 32.711 ", 2.000 )
cameraPan(" 0.000 9.794 104.724 ", 2.000, "FALSE" )
startConversation("act3/madri/madri7/3_madri7_0010" )
lockControls(0.100 )

