# Generated by BehavEd
# ( "comment" )
copyOriginAndAngles("_HERO1_", "herospot01" )
copyOriginAndAngles("_HERO2_", "herospot02" )
copyOriginAndAngles("_HERO3_", "herospot03" )
copyOriginAndAngles("_HERO4_", "herospot04" )
cameraResetOldSchool( )
setNoCollide("illusioncuckoo2_", "TRUE" )
fade("illusioncuckoo2_", 0.500, 0.000, "TRUE" )
setNoCollide("illusioncuckoo1_", "TRUE" )
fade("illusioncuckoo1_", 0.500, 0.000, "TRUE" )
setallaiactive("TRUE" )

