# Generated by BehavEd
# ( "minion spawns" )
setEnable("_OWNER_", "FALSE" )
setEngageEnemy("_OWNER_", "FALSE" )
setNoCollide("_OWNER_", "TRUE" )
setNoClip("_OWNER_", "TRUE" )
waittimed ( 0.100 )
setInvisible("_OWNER_", "FALSE" )
# ( "safety reset just incase something goes horribly wrong" )
waittimed ( 5.000 )
setNoClip("_OWNER_", "FALSE" )
setNoCollide("_OWNER_", "FALSE" )

