# Generated by BehavEd
# ( "comment" )
setNoClip("_ACTIVATOR_", "FALSE" )
setEnable("_ACTIVATOR_", "TRUE" )
setWaypointPath("_ACTIVATOR_", "", 0 )
setEngageEnemy("_ACTIVATOR_", "TRUE" )
attackEntityWithType("_ACTIVATOR_", "_ACTIVE_HERO_", "attacklight1", "FALSE" )
setNoCollide("_ACTIVATOR_", "FALSE" )

