# Generated by BehavEd
# ( "post death conversation" )
setDefaultTarget("" )
cameraToLocationAngles(" 1282.321 1299.631 153.799 ", " 1185.920 1507.342 0.000 ", 0.000 )
setEnable("blink_link", "TRUE" )
cameraResetOldSchool( )
objective ( "act3_obj_6f",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_6g",  "EOBJCMD_SHOW" )
waittimed ( 0.250 )
act("blink_portal_s", "blink_portal_s" )
waittimed ( 0.250 )
act("blink_portal1", "blink_portal1" )
remove ( "blink_portal_s", "blink_portal_s" )

