# Generated by BehavEd
# ( "set next threshhold to 10% less than current" )
health = getHealth("holocaust" )
healthmax = getHealthMax("holocaust" )
curpercent = fdiv(health, healthmax )
percent = fsub(curpercent, 0.100 )
percent = fmul(percent, 100.000 )
setZoneVar("painthresh", percent )

