# Generated by BehavEd
# ( "prof x doesn't need his wheelchair because his cell is already equipped with a chair" )
setSegmentVisible("_OWNER_", "1101_chair", "0" )
# ( "prof x should be demonstrating his amazing sitting-in-a-chair animation" )
playanim (  "EA_ZONE4", "_OWNER_", "LOOP", "" )

