# Generated by BehavEd
# ( "Makes trip mine EXPLODE! awesome" )
killEntity("trip_mine_02" )
spawn("trip_las_02", "oz_explosion", "blast2", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
killEntity("trip_las_02" )
remove ( "trip_clip_02", "trip_clip_02" )

