# Generated by BehavEd
# ( "Makes trip mine EXPLODE! awesome" )
killEntity("trip_mine_03" )
spawn("trip_las_03", "oz_explosion", "blast3", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
killEntity("trip_las_03" )
remove ( "trip_clip_03", "trip_clip_03" )

