# Generated by BehavEd
# ( "enable zone link" )
setEnable("link_tower4", "TRUE" )
setEnable("tele_loop", "TRUE" )
remove ( "ffield_beast", "ffield_beast" )
act("tele_prize", "tele_prize" )
waittimed ( 0.500 )
copyOriginAndAngles("treasure_chest02", "tele_prize" )
waittimed ( 0.500 )
remove ( "tele_prize", "tele_prize" )

