# Generated by BehavEd
# ( "focus on sabertooth and teleport him away" )
waittimed ( 0.250 )
playanim (  "EA_PAIN_HIGH2", "sabertooth", "NONE", "" )
waittimed ( 0.250 )
playanim (  "EA_PAIN_ELECTRIC", "sabertooth", "NONE", "" )
act("tele_saber", "tele_saber" )
waittimed ( 0.750 )
remove ( "sabertooth", "sabertooth" )
waittimed ( 0.250 )
act("tele_saber", "tele_saber" )
waittimed ( 1.000 )
cameraFocusToEntity("beast_camera", 200.000, 25.000, 180.000, 1.000 )

