# Generated by BehavEd
# ( "tower3 zone script" )
setCurrentAct(4 )
beastend = getGameFlag("beastngang", 1 )
if beastend == 1
     remove ( "ffield_beast", "ffield_beast" )
     remove ( "beast01", "beast01" )
     remove ( "sabretooth01", "sabretooth01" )
     waittimed ( 0.250 )
     remove ( "beast", "beast" )
     remove ( "sabertooth", "sabertooth" )
     setEnable("link_tower4", "TRUE" )
     remove ( "trigger_touch02", "trigger_touch02" )
endif

