# Generated by BehavEd
# ( "Script to run if player cancels a mission briefing from Egypt" )
cameraFade(1.000, 0.010 )
waittimed ( 0.020 )
lockControls(0.100 )
loadZone("act5/teleport/teleport1", "link_great_seal_briefing" )

