# Generated by BehavEd
# ( "change anbient" )
lockControls(-1.000 )
setallaiactive("FALSE" )
setInvulnerable("b_orbis_at02", "FALSE" )
setInvulnerable("b_orbis_at01", "FALSE" )
cameraMove(" 1348.450 1126.930 190.340 ", 1.000 )
cameraPan(" 0.000 28.300 89.500 ", 1.000, "FALSE" )
waittimed ( 2.000 )
act("effect_scanner", "effect_scanner" )
sound (  "PLAY_SOUND", "zone_shared/special/ny_scanner", "", "" )
waittimed ( 2.000 )
startConversation("act4/tower/tower1/4_tower1_0080" )

