# Generated by BehavEd
# ( "This script spawns in guys to attack the player" )
# ( "While the teleport pad is charging" )
prelates_defeated = getZoneVar("prelates" )
opticcralwers_defeated = getZoneVar("cralwers" )
dead_person = getName("_OWNER_" )
puzzle_done = getGameFlag("tower", 3 )
if puzzle_done == 0
     # ( "This increments the count for prelates or opticcralwers" )
     if dead_person == "prelate"
          prelates_defeated = iadd(prelates_defeated, 1 )
          setZoneVar("prelates", prelates_defeated )
          # ( "The number in each wave is hard coded" )
          if prelates_defeated == 1
               act("ss_prelate_wave02", "ss_prelate_wave02" )
               act("ss_prelate_wave04", "ss_prelate_wave04" )
          elif prelates_defeated == 3
               act("ss_prelate_wave02", "ss_prelate_wave02" )
               act("ss_prelate_wave04", "ss_prelate_wave04" )
          elif prelates_defeated == 5
               act("ss_prelate_wave02", "ss_prelate_wave02" )
               act("ss_prelate_wave04", "ss_prelate_wave04" )
               act("ss_prelate_wave05", "ss_prelate_wave05" )
          elif prelates_defeated == 8
               act("ss_prelate_wave02", "ss_prelate_wave02" )
               act("ss_prelate_wave04", "ss_prelate_wave04" )
               act("ss_prelate_wave05", "ss_prelate_wave05" )
          elif prelates_defeated == 11
               act("ss_prelate_wave01", "ss_prelate_wave01" )
               act("ss_prelate_wave02", "ss_prelate_wave02" )
               act("ss_prelate_wave04", "ss_prelate_wave04" )
               act("ss_prelate_wave05", "ss_prelate_wave05" )
          elif prelates_defeated == 15
               waittimed ( 5.000 )
               act("ss_prelate_wave01", "ss_prelate_wave01" )
               act("ss_prelate_wave02", "ss_prelate_wave02" )
               act("ss_prelate_wave03", "ss_prelate_wave03" )
               act("ss_prelate_wave04", "ss_prelate_wave04" )
               act("ss_prelate_wave05", "ss_prelate_wave05" )
          endif
     endif
     if dead_person == "opticcrawler"
          act("opticcralwers_waves", "opticcralwers_waves" )
     endif
endif

