# Generated by BehavEd
# ( "This script randomly picks a optic spawner and spawns in a opticcrawler" )
spawner = randomInt(1, 2 )
puzzle_done = getGameFlag("tower", 3 )
crawler_check = getZoneVar("checkcheck" )
crawler_check = iadd(crawler_check, 1 )
setZoneVar("checkcheck", crawler_check )
if puzzle_done == 0
     if crawler_check == 2
          if spawner == 1
               act("ss_opticcrawler_wave01", "ss_opticcrawler_wave01" )
               act("ss_opticcrawler_wave04", "ss_opticcrawler_wave04" )
               crawler_check = isub(crawler_check, 2 )
               setZoneVar("checkcheck", crawler_check )
          elif spawner == 2
               act("ss_opticcrawler_wave02", "ss_opticcrawler_wave02" )
               act("ss_opticcrawler_wave03", "ss_opticcrawler_wave03" )
               crawler_check = isub(crawler_check, 2 )
               setZoneVar("checkcheck", crawler_check )
          endif
     endif
endif

