# Generated by BehavEd
# ( "Makes Prelates coming from teleports run" )
# ( " from their spawn points rather than standing around" )
attackEntityWithType("_OWNER_", "_ACTIVE_HERO_", "_ANY_", "TRUE" )

