# Generated by BehavEd
# ( "This is the zone script for Acpoc tower, level 1" )
setCurrentAct(4 )
setInvulnerable("b_orbis_at01", "TRUE" )
setInvulnerable("b_orbis_at02", "TRUE" )
# ( "if we just arrived here from sewers for the first time, complete an objective" )
firstTime = getObjective("act4_obj_4c", "COMPLETE" )
if firstTime == 0
     # ( "first time here" )
     objective ( "act4_obj_4c",  "EOBJCMD_COMPLETE" )
     startConversation("act4/tower/tower1/4_tower1_0070" )
     objective ( "act4_obj_6",  "EOBJCMD_SHOW" )
     objective ( "act4_obj_6a",  "EOBJCMD_SHOW" )
endif
maindoor = getGameFlag("gen_kill1", 1 )
if maindoor == 1
     remove ( "gen_killed_relay", "gen_killed_relay" )
     waittimed ( 0.250 )
     killEntitySilent("b_orbis_at02" )
     killEntitySilent("b_orbis_at01" )
     setEnable("apoc_door_at01", "TRUE" )
     waittimed ( 0.250 )
     remove ( "effect_scanner", "effect_scanner" )
     remove ( "trigger_use01", "trigger_use01" )
     remove ( "loop_effect03", "loop_effect03" )
endif
# ( "This first variable checks if the the prelate puzzle has been solved" )
prelate_puzzle = getGameFlag("tower", 1 )
# ( "This makes sure that the correct pad is in place" )
teleport_pad = getGameFlag("tower1", 3 )
if teleport_pad == 1
     setEnable("teleport_pad_warmup", "FALSE" )
     setEnable("teleport_pad", "TRUE" )
     copyOriginAndAngles("teleport_pad", "teleport_pad_spot" )
     remove ( "warm_up_start", "warm_up_start" )
     remove ( "warm_up", "warm_up" )
     remove ( "wakeup_prelates", "wakeup_prelates" )
endif
# ( "This checks of the secrete storage area has been access" )
# ( "The key is located in tower2 on the statue" )
if prelate_puzzle == 0
     act("ss_prelate_a01", "ss_prelate_a01" )
     act("ss_prelate_a02", "ss_prelate_a02" )
else
     act("ss_prelate_a04", "ss_prelate_a04" )
     act("ss_prelate_a03", "ss_prelate_a03" )
     remove ( "prelate_ff_a", "prelate_ff_a" )
     remove ( "prelate_ff_b", "prelate_ff_b" )
     remove ( "prelate_ff_c", "prelate_ff_c" )
endif
if teleport_pad == 1
     moveToEntity("teleport_pad", "teleport_pad_spot" )
     remove ( "teleport_pad_warmup", "teleport_pad_warmup" )
endif

