# Generated by BehavEd
# ( "This script is the spawn script for the prelate puzzle" )
setAIActive("prelate_guard_left", "TRUE" )
setAIActive("prelate_guard_right", "TRUE" )
setInvulnerable("prelate_guard_left", "FALSE" )
setInvulnerable("prelate_guard_right", "FALSE" )

