# Generated by BehavEd
# ( "This script call tells the player that a new briefing is avaiable" )
briefing = getGameFlag("briefings", 2 )
if briefing == 0
     setGameFlag("briefings", 2, 1 )
     newMissionBriefing( )
endif

