# Generated by BehavEd
# ( "This script call tells the player that a new briefing is avaiable" )
briefings = getGameFlag("briefings", 3 )
if briefings == 0
     setGameFlag("briefings", 3, 1 )
     newMissionBriefing( )
endif

