# Generated by BehavEd
# ( "This script loads the intro movie for act4 and loads the mansion map" )
startMovie("Cine04", "afterMovie" )
waitsignal ( "afterMovie" )
# ( "Unlock Civilian, Future, Weapon X, Winter" )
unlockCharacter("", "weaponx" )
unlockCharacter("", "future" )
unlockCharacter("", "civilian" )
unlockCharacter("", "winter" )
loadZone("act4/mansion/mansion1", "link_mansion1" )

