# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept28.png" )
imageViewer("textures/concept/concept29.png" )
imageViewer("textures/concept/concept30.png" )

