# Generated by BehavEd
# ( "Stryfe death objective check" )
spawn("stryfe", "cold_sore", "cold_sore", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
setDefaultTarget("" )
checkBrains = getZoneFlag("allbrains", 1 )
if checkBrains == 1
     # ( "brains are all dead, stryfe is dead...talk to Banshee at mansion" )
     act("stryfe_outro", "stryfe_outro" )
else
     # ( "brains are not all dead.  They will resurrect styfe" )
     deadbrains = getZoneVar("deadbrains" )
     act("BrainDemon01", "BrainDemon01" )
     if deadbrains >= 2
          act("BrainDemon02", "BrainDemon02" )
     endif
     if deadbrains >= 3
          act("BrainDemon03", "BrainDemon03" )
     endif
     if deadbrains >= 5
          act("BrainDemon04", "BrainDemon04" )
     endif
     waittimed ( 10.000 )
     checkBrains = getZoneFlag("allbrains", 1 )
     if checkBrains == 0
          act("Brain_1", "Brain_1" )
          act("Brain_2", "Brain_2" )
          act("Brain_3", "Brain_3" )
          act("Brain_4", "Brain_4" )
          act("Brain_5", "Brain_5" )
          act("Brain_6", "Brain_6" )
          seenres = getZoneVar("seenres" )
          if seenres == 0
               setZoneVar("seenres", 1 )
               overrideFocusToEntity("stryfe", 2.000 )
          endif
          playBossSound("voice/stryfe/resurrect", 0, 5.000 )
          act("cold_sore", "cold_sore" )
          waittimed ( 0.200 )
          spawnEffect("stryfe", "map/pens/scr_braintank_resurrect", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
          playanim (  "EA_GETUP_ON_FRONT1", "styfe", "NONE", "" )
          setDefaultTarget("stryfe" )
          sound (  "PLAY_SOUND", "boss_battles/stryfe/ressurect_stryfe", "", "" )
          waittimed ( 0.500 )
          # ( "give stryfe less health for each brain dead" )
          deadbrains = getZoneVar("deadbrains" )
          deadper = fmul(deadbrains, 0.167 )
          deadper = fsub(1.000, deadper )
          maxhealth = getHealthMax("stryfe" )
          newhealth = fmul(maxhealth, deadper )
          setHealth("stryfe", newhealth )
     endif
endif

