# Generated by BehavEd
# ( "dr_boss5 loadscript" )
act("cold_sore", "cold_sore" )
waittimed ( 0.250 )
setDefaultTarget("stryfe" )
showHealthBar("Brain_1", "TRUE" )
showHealthBar("Brain_2", "TRUE" )
showHealthBar("Brain_3", "TRUE" )
showHealthBar("Brain_4", "TRUE" )
showHealthBar("Brain_5", "TRUE" )
showHealthBar("Brain_6", "TRUE" )

