# Generated by BehavEd
# ( "check when all brains are dead and when stryfe is dead" )
# ( "Do the following when a brain is killed AND when Stryfe is killed" )
checkBrains = getZoneFlag("allbrains", 1 )
if checkBrains == 1
     checkStryfe = alive("stryfe" )
     if checkStryfe == 0
          setDangerRoomSuccess( )
     endif
endif

