startMovie("i102", "afterMovie1")
waitsignal("afterMovie1")
startMovie("i101", "afterMovie2")
waitsignal("afterMovie2")
startMovie("i103", "afterMovie3")
waitsignal("afterMovie3")
startMovie("i104", "afterMovie4")
waitsignal("afterMovie4")
startMovie("i105", "afterMovie5")
waitsignal("afterMovie5")
unlockHardDifficulty( )
mainMenuExit()