# Generated by BehavEd
# ( "lady d starts recharging" )
setPatternSequence("lady_ds", "lds2" )
setZoneVar("recharging", 1 )
setEnable("recharger", "TRUE" )
act("recharger", "recharger" )
playanim (  "EA_ZONE1", "lady_ds", "NONE", "squat" )
waitsignal ( "squat" )
playanim (  "EA_ZONE2", "lady_ds", "LOOP", "" )
# ( "she only recharges for so long" )
waittimed ( 9.000 )
act("stop_charging", "stop_charging" )

