# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept43.png" )
imageViewer("textures/concept/concept44.png" )
imageViewer("textures/concept/concept45.png" )

