# Generated by BehavEd
# ( "comment" )
beastdeaths = getZoneVar("beastdeaths" )
newbd = iadd(beastdeaths, 1 )
setZoneVar("beastdeaths", newbd )
waittimed ( 20.000 )
sinisteralive = alive("sinister" )
if sinisteralive == 1
     playBossSound("voice/sinister/beast_ko", 0, 5.000 )
     setPatternSequence("sinister", "sinister5" )
endif

