# Generated by BehavEd
# ( "This shows the quest if the level was loaded directly" )
sinister_defeated = getGameFlag("bosses", 28 )
push_puzzle_done = getGameFlag("act5_visit", 4 )
homing_beacon = getGameFlag("act5_visit", 9 )
tech_station = getGameFlag("act5_visit", 10 )
data_disc = getGameFlag("act5_visit", 11 )
if sinister_defeated == 1
     act("exit_door", "exit_door" )
     setEnable("beast_user", "FALSE" )
     setEnable("nuller01", "FALSE" )
     setEnable("nuller02", "FALSE" )
     setEnable("nuller03", "FALSE" )
     setEnable("nuller04", "FALSE" )
     remove ( "null_harm01", "null_harm01" )
     remove ( "null_harm02", "null_harm02" )
     remove ( "null_harm03", "null_harm03" )
     remove ( "null_harm04", "null_harm04" )
     remove ( "boss_start_trigger", "boss_start_trigger" )
     remove ( "sp_beastboss01", "sp_beastboss01" )
     remove ( "sp_mrsinisterboss01", "sp_mrsinisterboss01" )
endif
if push_puzzle_done == 1
     act("column_10x40ft_push_egypt_m_eg01", "column_10x40ft_push_egypt_m_eg01" )
     setEnable("door_egypt_a_eg14", "TRUE" )
     setEnable("door_egypt_a_eg04", "TRUE" )
     setEnable("door_egypt_a_eg05", "TRUE" )
     setEnable("door_egypt_a_eg15", "TRUE" )
     remove ( "push_column", "push_column" )
     remove ( "move_column", "move_column" )
endif
if homing_beacon == 1
     remove ( "homing_beacon_act5_01", "homing_beacon_act5_01" )
endif
if tech_station == 1
     setEnable("tech_station_health01", "FALSE" )
endif
if data_disc == 1
     remove ( "data_disc01", "data_disc01" )
endif

