# Generated by BehavEd
# ( "This is called when the player enters the area" )
setPartyLightColor(" 1.000 0.750 0.000 ", 1.000 )
metim = getGameFlag("bosses", 27 )
if metim == 1
     # ( "enter the sinister arena" )
     setWaypointPath("sinister", "", 0 )
     setWaypointPath("beast", "", 0 )
     setRecallActive("FALSE" )
     setEngageEnemy("sinister", "TRUE" )
     setEngageEnemy("beast", "TRUE" )
     setDefaultTarget("sinister" )
     attackEntityWithType("sinister", "_ACTIVE_HERO_", "ANY", "FALSE" )
     attackEntityWithType("beast", "_ACTIVE_HERO_", "ANY", "FALSE" )
endif

