# Generated by BehavEd
# ( "use pylon01" )
setPatternSequence("sinister", "sinister2" )
setEnable("nuller02", "FALSE" )
waittimed ( 20.000 )
setEnable("nuller02", "TRUE" )
act("nuller02", "nuller02" )
setEnable("nuller02", "FALSE" )
waittimed ( 3.000 )
setEnable("_OWNER_", "TRUE" )
setEnable("nuller02", "TRUE" )

