# Generated by BehavEd
# ( "use pylon01" )
setPatternSequence("sinister", "sinister4" )
setEnable("nuller04", "FALSE" )
waittimed ( 20.000 )
setEnable("nuller04", "TRUE" )
act("nuller04", "nuller04" )
setEnable("nuller04", "FALSE" )
waittimed ( 3.000 )
setEnable("_OWNER_", "TRUE" )
setEnable("nuller04", "TRUE" )

