# Generated by BehavEd
# ( "use pylon03" )
setPatternSequence("sinister", "sinister3" )
setEnable("nuller03", "FALSE" )
waittimed ( 20.000 )
setEnable("nuller03", "TRUE" )
act("nuller03", "nuller03" )
setEnable("nuller03", "FALSE" )
waittimed ( 3.000 )
setEnable("_OWNER_", "TRUE" )
setEnable("nuller03", "TRUE" )

