# Generated by BehavEd
# ( "use pylon01" )
setPatternSequence("sinister", "sinister1" )
setEnable("nuller01", "FALSE" )
waittimed ( 20.000 )
setEnable("nuller01", "TRUE" )
act("nuller01", "nuller01" )
setEnable("nuller01", "FALSE" )
waittimed ( 3.000 )
setEnable("_OWNER_", "TRUE" )
setEnable("nuller01", "TRUE" )

