# Generated by BehavEd
# ( "leave the sinister arena" )
setPartyLightColor(" 1.000 0.870 0.200 ", 1.500 )
setRecallActive("TRUE" )
setEngageEnemy("sinister", "FALSE" )
setEngageEnemy("beast", "FALSE" )
setWaypointPath("sinister", "sinisterhome", 1 )
setWaypointPath("beast", "beasthome", 1 )
setDefaultTarget("" )

