# Generated by BehavEd
# ( "resurrector is used" )
beastalive = alive("beast" )
if beastalive == 0
     sinisteralive = alive("sinister" )
     if sinisteralive == 0
          # ( "move beast, set up camera" )
          lockControls(-1.000 )
          setRecallActive("TRUE" )
          setallaiactive("FALSE" )
          overrideFocusToEntity("beast", 5.000 )
     else
          playBossSound("voice/sinister/res_beast", 0, 5.000 )
          seenit = getZoneVar("seenbeast" )
          if seenit == 0
               setZoneVar("seenbeast", 1 )
               lockControls(-1.000 )
               overrideFocusToEntity("sinister", 2.000 )
          endif
          setWaypointPath("_ACTIVATOR_", "", 0 )
          playanim (  "EA_USE_BUTTON", "sinister", "NONE", "" )
          if seenit == 0
               waittimed ( 2.000 )
               overrideFocusToEntity("beast", 4.000 )
          else
               waittimed ( 0.500 )
          endif
     endif
     setEnable("beast", "TRUE" )
     resurrect("beast" )
     setAIActive("beast", "FALSE" )
     waittimed ( 3.250 )
     # ( "make beast have 20 percent less health each time he's brought back" )
     beasthealth = getHealthMax("beast" )
     beastdeaths = getZoneVar("beastdeaths" )
     healthper = fmul(beastdeaths, 0.200 )
     newhp = fsub(1.000, healthper )
     if newhp < 0.100000
          newhp = fadd(1.000, 0.100 )
     endif
     newhealth = fmul(newhp, beasthealth )
     setHealth("beast", newhealth )
     setAIActive("beast", "TRUE" )
     if sinisteralive == 0
          # ( "activate final cutscene" )
          setallaiactive("TRUE" )
          startConversation("act5/egypt/egypt1/5_egypt1_0020" )
     else
          # ( "back to fighting" )
          lockControls(0.100 )
          attackEntityWithType("beast", "_ACTIVE_HERO_", "ANY", "FALSE" )
          attackEntityWithType("sinister", "_ACTIVE_HERO_", "ANY", "FALSE" )
     endif
endif
lockControls(0.100 )
# ( "turn off animation on the resurrector ent" )
setHintType("ressurector", "none" )
act("ressurector", "ressurector" )
setEnable("beast", "FALSE" )

