# Generated by BehavEd
# ( "This spawns the scarab" )
playanim (  "EA_ZONE1", "_OWNER_", "NONE", "" )
sound (  "PLAY_SOUND", "zone_shared/special/scarbs_crawling", "_OWNER_", "" )
setNoClip("_OWNER_", "TRUE" )
setInvulnerable("_OWNER_", "TRUE" )
setInvisible("_OWNER_", "FALSE" )
waittimed ( 1.000 )
setInvulnerable("_OWNER_", "FALSE" )
setNoClip("_OWNER_", "FALSE" )

