# Generated by BehavEd
# ( "beat apoc" )
stage = getZoneVar("stage" )
stage = iadd(stage, 1 )
if stage <= 2
     if stage == 2
          setPatternSequence("apocalypse", "cutscene" )
     endif
     # ( "go to middle and get big" )
     setInvulnerable("apocalypse", "TRUE" )
     playanim (  "EA_POWER1_START", "apocalypse", "NONE", "" )
     waittimed ( 0.900 )
     lockControls(-1.000 )
     setallaiactive("FALSE" )
     if stage == 1
          cameraMove(" 202.121 -308.534 254.014 ", 0.500 )
          cameraPan(" -1.690 34.476 125.217 ", 0.500, "FALSE" )
          act("teleport_middle", "teleport_middle" )
     else
          cameraMove(" 202.121 -308.534 254.014 ", 0.000 )
          cameraPan(" -1.690 34.476 125.217 ", 0.000, "FALSE" )
     endif
     waittimed ( 0.500 )
     copyOriginAndAngles("apocalypse", "teleport_middle" )
     waittimed ( 0.500 )
     act("apoc_teleport_fx", "apoc_teleport_fx" )
     playanim (  "EA_ZONE2", "apocalypse", "NONE", "" )
     sound (  "PLAY_SOUND", "boss_battles/apoc/apoc_grows", "apocalypse", "" )
     sound (  "PLAY_SOUND", "voice/apocalypse/grow", "apocalypse", "" )
     # ( "play grow effects" )
     act("fx_machine", "fx_machine" )
     forcefieldon = alive("apoc_forcefield" )
     if forcefieldon == 1
          remove ( "apoc_forcefield", "apoc_forcefield" )
          sound (  "PLAY_SOUND", "boss_battles/apoc/apoc_forcefield_down", "apoc_forcefield", "" )
     endif
     setActorScaleTimed("apocalypse", 2.860, 1.000 )
     waittimed ( 2.000 )
     if stage == 2
          # ( "do some checks to see if the player needs a hint showing the generators" )
          apocgametip = getZoneFlag("apocgametip", 6 )
          if apocgametip == 0
               apocgametip = getZoneFlag("apocgametip", 4 )
               if apocgametip == 0
                    setZoneFlag("apocgametip", 4, 1 )
               else
                    apocgametip = getZoneFlag("apocgametip", 5 )
                    if apocgametip == 0
                         setZoneFlag("apocgametip", 5, 1 )
                         # ( "player hasn't figured out to go do a generator yet, go show 'em" )
                         setZoneFlag("apocgametip", 6, 1 )
                         cameraPan(" 1.629 44.667 89.076 ", 2.000, "FALSE" )
                         cameraMove(" -3137.420 -159.948 328.244 ", 2.000 )
                         waittimed ( 4.000 )
                    endif
               endif
          endif
     endif
     cameraReset( )
     lockControls(0.100 )
     setallaiactive("TRUE" )
     if stage == 1
          setZoneVar("stage", stage )
          setPatternSequence("apocalypse", "apoc2" )
          waittimed ( 0.100 )
          setEnable("apoc_machine", "TRUE" )
     else
          setEnable("genl", "FALSE" )
          setInvisible("left_generator_forcefield", "TRUE" )
          setNoCollide("left_generator_forcefield", "TRUE" )
          setEnable("genl", "FALSE" )
          setInvulnerable("left_generator", "FALSE" )
          showHealthBar("left_generator", "TRUE" )
          setEnable("genr", "FALSE" )
          setInvisible("right_generator_forcefield", "TRUE" )
          setNoCollide("right_generator_forcefield", "TRUE" )
          setEnable("genr", "FALSE" )
          setInvulnerable("right_generator", "FALSE" )
          showHealthBar("right_generator", "TRUE" )
          setPatternSequence("apocalypse", "middle" )
     endif
     hmax = getHealthMax("apocalypse" )
     setHealth("apocalypse", hmax )
     setInvulnerable("apocalypse", "FALSE" )
elif stage == 3
     # ( "swap with the horseman with the most health" )
     besthealth = getHealth("archangel" )
     bestguy = getID("archangel" )
     nexthealth = getHealth("mikhail" )
     if nexthealth > besthealth
          bestguy = getID("mikhail" )
          besthealth = getHealth("mikhail" )
     endif
     nexthealth = getHealth("abyss" )
     if nexthealth > besthealth
          bestguy = getID("abyss" )
          besthealth = getHealth("abyss" )
     endif
     nexthealth = getHealth("holocaust" )
     if nexthealth > besthealth
          bestguy = getID("holocaust" )
          besthealth = getHealth("holocaust" )
     endif
     # ( "where the action happens" )
     setDefaultTarget("" )
     copyOriginAndAngles("horseman_null", "apocalypse" )
     copyOriginAndAngles("apocalypse", bestguy )
     copyOriginAndAngles(bestguy, "horseman_null" )
     killEntity(bestguy )
     setActorScaleTimed("apocalypse", 2.860, 0.500 )
     hmax = getHealthMax("apocalypse" )
     setHealth("apocalypse", hmax )
     waittimed ( 1.000 )
     setDefaultTarget("apocalypse" )
else
    # ( "you won" )
    objective ( "act5_obj_2",  "EOBJCMD_COMPLETE" )
    objective ( "act5_obj_2a",  "EOBJCMD_COMPLETE" )
    setGameFlag("bosses", 31, 1 )
    unlockHardDifficulty( )
    
    # ( "UNLOCK CHARACTERS" )
    # ( "Emma Frost" )
    emma_unlocked = isCharacterUnlocked("Emmafrost_hero")
    if emma_unlocked == 0
        # ( "Emma Frost is not yet unlocked, unlock her" )
        unlockCharacter("Emmafrost_hero", "" )
        emma_unlocked = isCharacterUnlocked("Emmafrost_hero")
        if emma_unlocked == 1
            # ( "Emma Frost was not previously unlocked but she is on the roster" )
            # ( "She's been unlocked now, so show the dialog that confirms this" )
            createPopupDialogXML("dialogs/act5/egypt6/emma_unlocked")
        endif 
    endif
    
    # ( "Polaris" )
    polaris_unlocked = isCharacterUnlocked("Polaris")
    if polaris_unlocked == 0
        # ( "Polaris is not yet unlocked, unlock her" )
        unlockCharacter("Polaris", "" )
        polaris_unlocked = isCharacterUnlocked("Polaris")
        if polaris_unlocked == 1
            # ( "Polaris was not previously unlocked but she is on the roster" )
            # ( "She's been unlocked now, so show the dialog that confirms this" )
            createPopupDialogXML("dialogs/act5/egypt6/polaris_unlocked")
        endif 
    endif
    
    # ( "Quicksilver" )
    quicks_unlocked = isCharacterUnlocked("Quicksilver_hero")
    if quicks_unlocked == 0
        # ( "Quicksilver is not yet unlocked, unlock him" )
        unlockCharacter("Quicksilver_hero", "" )
        quicks_unlocked = isCharacterUnlocked("Quicksilver_hero")
        if quicks_unlocked == 1
            # ( "Quicksilver was not previously unlocked but he is on the roster" )
            # ( "He's been unlocked now, so show the dialog that confirms this" )
            createPopupDialogXML("dialogs/act5/egypt6/quicks_unlocked")
        endif 
    endif
    
    # ( "Sabretooth" )
    sabre_unlocked = isCharacterUnlocked("Sabretooth_hero")
    if sabre_unlocked == 0
        # ( "Sabretooth is not yet unlocked, unlock him" )
        unlockCharacter("Sabretooth_hero", "" )
        sabre_unlocked = isCharacterUnlocked("Sabretooth_hero")
        if sabre_unlocked == 1
            # ( "Sabretooth was not previously unlocked but he is on the roster" )
            # ( "He's been unlocked now, so show the dialog that confirms this" )
            createPopupDialogXML("dialogs/act5/egypt6/sabre_unlocked")
        endif 
    endif
    # ( "END UNLOCK CHARACTERS" )
    
    waittimed ( 1.000 )
    startMovie("Cine06", "waa" )
    waitsignal ( "waa" )
    startMovie("cine07", "gameover" )
    waitsignal ( "gameover" )
    openmenu("credits_end" )
endif

