# Generated by BehavEd
# ( "Apocalypse's pain script" )
stage = getZoneVar("stage" )
stage = iadd(stage, 1 )
if stage >= 2
     # ( "calculate health percentage" )
     health = getHealth("_OWNER_" )
     healthmax = getHealthMax("_OWNER_" )
     hamt = fdiv(health, healthmax )
     # ( "scale apoc according to his health using fancy algebra" )
     a = fmul(hamt, 1.460 )
     scale = fadd(a, 1.400 )
     setActorScaleTimed("apocalypse", scale, 0.300 )
     act("spawn_a_pip", "_OWNER_" )
endif

