# Generated by BehavEd
# ( "comment" )
objective ( "act5_obj_2a",  "EOBJCMD_SHOW" )
setDefaultTarget("apocalypse" )
setInvulnerable("apocalypse", "FALSE" )
setallaiactive("TRUE" )
attackEntityWithType("apocalypse", "_ACTIVE_HERO_", "ANY", "FALSE" )
setEnable("south_enable", "TRUE" )
remove ( "herospot01", "herospot01" )
remove ( "herospot02", "herospot02" )
remove ( "herospot03", "herospot03" )
remove ( "herospot04", "herospot04" )

