# Generated by BehavEd
# ( "comment" )
setInvulnerable("apocalypse", "TRUE" )
playanim (  "EA_POWER1_START", "apocalypse", "NONE", "" )
waittimed ( 0.900 )
lockControls(-1.000 )
setallaiactive("FALSE" )
copyOriginAndAngles("apoc_out", "apocalypse" )
cameraMove(" 202.121 -308.534 254.014 ", 0.500 )
cameraPan(" -1.690 34.476 125.217 ", 0.500, "FALSE" )
waittimed ( 0.500 )
copyOriginAndAngles("apocalypse", "teleport_middle" )
waittimed ( 0.500 )
stage = getZoneVar("stage" )
playanim (  "EA_ZONE2", "apocalypse", "NONE", "" )
# ( "play grow effects" )
act("fx_machine", "fx_machine" )
if stage == 2
     setActorScaleTimed("apocalypse", 1.600, 1.000 )
endif
if stage == 4
     setActorScaleTimed("apocalypse", 2.000, 1.000 )
endif
if stage == 6
     remove ( "apoc_forcefield", "apoc_forcefield" )
     setActorScaleTimed("apocalypse", 2.860, 1.000 )
endif
waittimed ( 1.500 )
# ( "apoc doesn't go back to you in the last stage" )
if stage != 6
     playanim (  "EA_POWER1_START", "apocalypse", "NONE", "" )
     waittimed ( 0.900 )
     copyOriginAndAngles("apocalypse", "apoc_out" )
endif
waittimed ( 0.500 )
cameraReset( )
lockControls(0.100 )
setallaiactive("TRUE" )
if stage == 2
     setPatternSequence("apocalypse", "apoc2" )
endif
if stage == 4
     setPatternSequence("apocalypse", "apoc3" )
endif
if stage == 6
     setPatternSequence("apocalypse", "apoc4" )
endif
setInvulnerable("apocalypse", "FALSE" )

