# Generated by BehavEd
# ( "comment" )
remove ( "apoc_forcefield", "apoc_forcefield" )
setEnable("apoc_machine", "TRUE" )
setActorScaleTimed("apocalypse", 2.860, 1.000 )
setZoneVar("stage", 1 )
setPatternSequence("apocalypse", "apoc2" )

