# Generated by BehavEd
# ( "shrink the player" )
a1 = alive("left_generator" )
if a1 == 1
     playBossSound("voice/apocalypse/first_destroy", 0, 5.000 )
else
     a1 = alive("right_generator" )
     if a1 == 1
          playBossSound("voice/apocalypse/first_destroy", 3, 5.000 )
     endif
endif
setPatternSequence("apocalypse", "shrink" )

