# Generated by BehavEd
# ( "shrink the player" )
a1 = alive("left_generator" )
if a1 == 1
     sound (  "PLAY_SOUND", "voice/apocalypse/first_destroy", "", "" )
else
     a1 = alive("right_generator" )
     if a1 == 1
          sound (  "PLAY_SOUND", "voice/apocalypse/first_destroy", "", "" )
     endif
endif
setPatternSequence("apocalypse", "shrink" )
