# Generated by BehavEd
# ( "make the player big" )
ai = getAIControlled("_ACTIVATOR_" )
if ai != 1
     maxhealth = getHealthMax("_ACTIVATOR_" )
     setHealth("_ACTIVATOR_", maxhealth )
     playBossSound("voice/apocalypse/use", 0, 5.000 )
     setZoneVar("herobig", 1 )
     setHintType("apoc_machine", "none" )
     setEnable("left_generator", "TRUE" )
     setEnable("right_generator", "TRUE" )
     # ( "clear out all the anubites" )
     remove ( "newbie", "newbie" )
     setEnable("right_hall_trigger", "TRUE" )
     setEnable("left_hall_trigger", "TRUE" )
     setDestroyObjects("_ACTIVATOR_", "TRUE" )
     setActorHuge("_ACTIVATOR_", "TRUE" )
     playCombatNodeTrigger("_ACTIVATOR_", "power_noknockdown", 73 )
     playCombatNodeTrigger("_ACTIVATOR_", "powerup_quaddamage", 73 )
     playCombatNodeTrigger("_ACTIVATOR_", "powerup_nogrow", 73 )
     lockControls(1.000 )
     playanim (  "EA_ZONE2", "_ACTIVATOR_", "NONE", "" )
     waittimed ( 0.100 )
     # ( "inform apoc that the player has gotten big" )
     setPatternSequence("apocalypse", "huge" )
     apocgametip = getZoneFlag("apocgametip", 1 )
     if apocgametip == 0
          setZoneFlag("apocgametip", 1, 1 )
          waittimed ( 1.000 )
          createPopupDialogXml("act5/egypt6/powers_hint" )
     endif
endif

