# Generated by BehavEd
# ( "shrink 'em" )
setZoneVar("herobig", 0 )
setHintType("apoc_machine", "objective" )
apocgametip = getZoneFlag("apocgametip", 2 )
if apocgametip == 0
     setZoneFlag("apocgametip", 2, 1 )
     waittimed ( 1.000 )
     createPopupDialogXml("act5/egypt6/getsmall_hint" )
endif

