# Generated by BehavEd
# ( "break thru left doors" )
setZoneFlag("apocgametip", 6, 1 )
playanim (  "EA_POWER1_START", "apocalypse", "NONE", "" )
waittimed ( 1.000 )
copyOriginAndAngles("apocalypse", "apoc_left_spot" )
setPatternSequence("apocalypse", "generator" )
alive = alive("left_generator" )
if alive == 1
     setEnable("left_generator", "FALSE" )
     setInvulnerable("left_generator", "TRUE" )
     showHealthBar("left_generator", "FALSE" )
     setEnable("genl", "TRUE" )
     setInvisible("left_generator_forcefield", "FALSE" )
     setNoCollide("left_generator_forcefield", "FALSE" )
endif

