# Generated by BehavEd
# ( "make apoc go and guard the generator" )
setZoneFlag("apocgametip", 6, 1 )
playanim (  "EA_POWER1_START", "apocalypse", "NONE", "" )
waittimed ( 1.000 )
copyOriginAndAngles("apocalypse", "apoc_right_spot" )
setPatternSequence("apocalypse", "generator" )
# ( "set up the generator" )
alive = alive("right_generator" )
if alive == 1
     setEnable("right_generator", "FALSE" )
     setInvulnerable("right_generator", "TRUE" )
     showHealthBar("right_generator", "FALSE" )
     setEnable("genr", "TRUE" )
     setInvisible("right_generator_forcefield", "FALSE" )
     setNoCollide("right_generator_forcefield", "FALSE" )
endif

