# Generated by BehavEd
# ( "spawn a big pip" )
big = getZoneVar("herobig" )
if big == 1
     hurter = getName("_ACTIVATOR_" )
     if hurter == 'apocalypse'
          # ( "apoc" )
          r1 = randomInt(-3, 3 )
          r1 = imul(r1, 100.000 )
          r2 = randomInt(-3, 3 )
          r2 = imul(r2, 100.000 )
          vel = strveci(r1, r2, 300 )
          pipid = spawn("_ACTIVATOR_", "timepip", "timepip", " 0.000 0.000 120.000 ", " 0.000 0.000 0.000 " )
          setVelocity(pipid, vel )
     elif hurter == 'right_generator'
          # ( "right generator" )
          x = randomInt(-2, -5 )
          x = imul(x, 100.000 )
          y = randomInt(-4, 4 )
          y = imul(y, 100.000 )
          vel = strveci(x, y, 100 )
          pipid = spawn("_ACTIVATOR_", "timepip", "timepip", " 0.000 0.000 200.000 ", " 0.000 0.000 0.000 " )
          setVelocity(pipid, vel )
     elif hurter == 'left_generator'
          # ( "left generator" )
          x = randomInt(-3, 3 )
          x = imul(x, 100.000 )
          y = randomInt(-2, -5 )
          y = imul(y, 100.000 )
          vel = strveci(x, y, 100 )
          pipid = spawn("_ACTIVATOR_", "timepip", "timepip", " 0.000 0.000 200.000 ", " 0.000 0.000 0.000 " )
          setVelocity(pipid, vel )
     else
          # ( "anubites" )
          r1 = randomInt(-1, 1 )
          r1 = imul(r1, 100.000 )
          r2 = randomInt(-1, 1 )
          r2 = imul(r2, 100.000 )
          vel = strveci(r1, r2, 300 )
          pipid = spawn("_ACTIVATOR_", "timepip", "timepip", " 0.000 0.000 60.000 ", " 0.000 0.000 0.000 " )
          setVelocity(pipid, vel )
     endif
     waittimed ( 0.400 )
     setNoClip(pipid, "FALSE" )
endif

