# Generated by BehavEd
# ( "get a little bigger" )
setPatternSequence("apocalypse", "addtime" )
apocgametip = getZoneFlag("apocgametip", 3 )
if apocgametip == 0
     setZoneFlag("apocgametip", 3, 1 )
     createPopupDialogXml("act5/egypt6/bigpip_hint" )
endif

