# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept34.png" )
imageViewer("textures/concept/concept35.png" )
imageViewer("textures/concept/concept36.png" )

