# Generated by BehavEd
# ( "comment" )
# ( "have I been to this map before? if so, don't do intro conversation" )
beenHereBefore = getGameFlag("act3_visit", 1 )
if beenHereBefore == 0
     setGameFlag("act3_visit", 1, 1 )
     startConversation("act3/corein/corein1/3_corein1_0010" )
endif
beenHereBefore = getObjective("act3_obj_2a", "COMPLETE" )
if beenHereBefore == 1
     # ( "replace with act silent" )
     setEnable("Security_Panel", "FALSE" )
     setHintType("Security_Panel", "none" )
     act("door_double", "door_double" )
endif

