# Generated by BehavEd
# ( "comment" )
act("door_double", "door_double" )
setEnable("Security_Panel", "FALSE" )
objective ( "act3_obj_2a",  "EOBJCMD_COMPLETE" )
objective ( "act3_obj_2b",  "EOBJCMD_SHOW" )

