# Generated by BehavEd
# ( "This script figures out which conversatio to allow" )
security_codes = getObjective("act1_obj_2", "HIDDEN" )
if security_codes == 1
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

