# Generated by BehavEd
# ( "checks if you've gotten security codes, if not doesn't spawn insects" )
questcomp = getObjective("act1_obj_2b", "COMPLETE" )
if questcomp == 1
     act("ss_brood_a14", "ss_brood_a14" )
     act("ss_brood_a16", "ss_brood_a16" )
     act("ss_brood_a18", "ss_brood_a18" )
endif
# ( "shows homing beacon. conversation here?" )
enemiesNoTarget("TRUE" )
heroNoTarget("TRUE" )
lockControls(-1.000 )
waittimed ( 0.100 )
cameraFocusToEntity("homing_beacon", 384.000, 45.000, 117.500, 3.000 )
waittimed ( 3.000 )
enemiesNoTarget("FALSE" )
heroNoTarget("FALSE" )
createPopupDialogXml("act1/insect/insect4/fly_hint" )

