# Generated by BehavEd
# ( "has the player heard about the cerci in the mission briefing?" )
cerci = getGameFlag("sanctuary", 28 )
if cerci == 0
     # ( "player has not heard about the cerci" )
     # ( "is this the first time player has seen the cerci?" )
     cerci = getGameFlag("tunnels", 5 )
     if cerci == 0
          # ( "player has not seen the cerci before" )
          lockControls(-1.000 )
          setallaiactive("FALSE" )
          # ( "show the cerci in all their insectoid glory" )
          act("cerci01", "cerci01" )
          act("cerci02", "cerci02" )
          waittimed ( 0.500 )
          cameraMove(" 8940.000 3350.000 150.000 ", 2.000 )
          cameraPan(" 0.000 30.000 90.000 ", 2.000, "FALSE" )
          waittimed ( 2.000 )
          # ( "indicate the cerci have been seen and run conversation" )
          setGameFlag("tunnels", 5, 1 )
          startConversation("act1/1_SOMETIMEACT1_0020" )
     endif
endif

