# Generated by BehavEd
# ( "is this the first visit to an insect tunnel?  either insect1 or insect4" )
visit = getGameFlag("tunnels", 23 )
if visit == 1
     remove ( "trigger_sometime015", "trigger_sometime015" )
endif
# ( "checks for quest completed, if so, spawns monsters, removes security code" )
questcomp = getObjective("act1_obj_2b", "COMPLETE" )
if questcomp == 1
     remove ( "security_codes", "security_codes" )
     copyOriginAndAngles("rock_fall01", "rockfall_point01" )
     # ( "spawn monsters in rest of map" )
     # ( "staggered to avoid errors" )
     act("relay_spawner01", "relay_spawner01" )
     waittimed ( 0.500 )
     act("relay_spawner02", "relay_spawner02" )
     waittimed ( 0.500 )
     act("relay_spawner03", "relay_spawner03" )
     waittimed ( 0.500 )
     act("relay_spawner04", "relay_spawner04" )
     waittimed ( 0.500 )
     act("relay_spawner05", "relay_spawner05" )
     waittimed ( 0.500 )
     act("relay_spawner06", "relay_spawner06" )
     waittimed ( 0.500 )
     act("relay_spawner07", "relay_spawner07" )
     waittimed ( 0.500 )
     act("relay_spawner08", "relay_spawner08" )
     waittimed ( 0.500 )
     act("relay_spawner09", "relay_spawner09" )
endif
homing = getGameFlag("tunnels", 24 )
if homing == 1
     remove ( "hint_fly01", "hint_fly01" )
endif
got_codes = getGameFlag("codes", 2 )
if got_codes == 1
     remove ( "security_codes", "security_codes" )
endif

