# Generated by BehavEd
# ( "this is the first visit to either insect1 or insect4--run conversation" )
startConversation("act1/1_sometimeact1_0015" )
# ( "indicate an insect tunnel has been visited" )
setGameFlag("tunnels", 23, 1 )

