# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept31.png" )
imageViewer("textures/concept/concept32.png" )
imageViewer("textures/concept/concept33.png" )

