# Generated by BehavEd
# ( "comment" )
waittimed ( 0.500 )
imageViewer("textures/concept/concept19.png" )
imageViewer("textures/concept/concept20.png" )
imageViewer("textures/concept/concept21.png" )

