# Generated by BehavEd
# ( "This checks of the briefing should be shown" )
# ( "This checks if Beast has been saved and if so, then a new mission briefing is available" )
gather_codes = getGameFlag("act5_visit", 3 )
if gather_codes == 0
     disallowResponse( )
endif

