# Generated by BehavEd
# ( "This script randomly take an objects and phases it in and out of reality" )
phaseWaitTime = randomInt(1, 10 )
if phaseWaitTime < 4
     int_alphafade = randomInt(15, 50 )
     float_alphafade = fdiv(int_alphafade, 100.000 )
     waittimed ( 2.000 )
     # ( "Object starts to fade out" )
     spawnEffect("_OWNER_", "map/tower/scr_smalltele", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     fade("_OWNER_", float_alphafade, 2.000, "TRUE" )
     waittimed ( 1.000 )
     # ( "Object disappears" )
     sound (  "PLAY_SOUND", "zone_shared/special/teleport_out", "_OWNER_", "" )
     fade("_OWNER_", 0.000, 0.500, "TRUE" )
     waittimed ( phaseWaitTime )
     sound (  "PLAY_SOUND", "zone_shared/special/teleport_in", "_OWNER_", "" )
     spawnEffect("_OWNER_", "map/tower/scr_tele_actor", " 0.000 0.000 0.000 ", " 0.000 0.000 0.000 " )
     fade("_OWNER_", 1.000, 1.000, "TRUE" )
     # ( "This allow gravity to kick in" )
endif

