# Generated by BehavEd
# ( "This script will not play the intro conversation with ProfX if Beast is aready resuced" )
beast_rescued = getGameFlag("act5_visit", 3 )
if beast_rescued == 1
     allowConversation("FALSE" )
endif

