# Generated by BehavEd
# ( "This is the load script for the zone" )
# ( "This unlocks the extraction point" )
extractionUnlock("" )
setCurrentAct(5 )
first_vist = getGameFlag("act5_visit", 1 )
second_vist = getGameFlag("act5_visit", 2 )
beast = getGameFlag("act5_visit", 3 )
# ( "Beast's NPC only appears if he has been defeated and Beast is not on the active team" )
if beast == 1
     beast_on_team = isActorOnTeam("beast_hero" )
     if beast_on_team == 0
          # ( "If Beast is not on the active team, talk to NPC Beast" )
          act("sp_beast01", "sp_beast01" )
          # ( "The following would normally be called from mark_briefing5_20" )
          briefings = getGameFlag("briefings", 18 )
          if briefings == 0
               setGameFlag("briefings", 18, 1 )
               newMissionBriefing( )
          endif
     else
          # (redundancy to make sure NPC Beast doesn't spawn)
          remove("Beast", "Beast" )
     endif
endif
if first_vist == 0
     setallaiactive("FALSE" )
     lockControls(0.000 )
     cameraFade(1.000, 0.000 )
     waittimed ( 1.000 )
     copyOriginAndAngles("_HERO1_", "hero_spot01" )
     copyOriginAndAngles("_HERO2_", "hero_spot02" )
     copyOriginAndAngles("_HERO3_", "hero_spot03" )
     copyOriginAndAngles("_HERO4_", "hero_spot04" )
     cameraToLocationAngles(" 1375.000 1883.000 127.000 ", " 1391.000 1796.000 81.000 ", 0.000 )
     waittimed ( 0.500 )
     cameraFade(0.000, 1.000 )
     waittimed ( 1.000 )
     setGameFlag("act5_visit", 1, 1 )
     lockControls(0.100 )
     objective ( "act5_obj_2",  "EOBJCMD_SHOW" )
     objective ( "act5_obj_2a",  "EOBJCMD_SHOW" )
     setallaiactive("TRUE" )
     startConversation("act5/teleport/5_teleport1_0010" )
elif second_vist == 0
     # ( "This spawns in the new profx and removes the old" )
     setGameFlag("act5_visit", 2, 1 )
     remove ( "profx_intro", "profx_intro" )
     act("sp_profx02", "sp_profx02" )
else
     act("sp_profx02", "sp_profx02" )
endif
numBeacons = getGameVarBitCount("beaconact5" )
if numBeacons >= 4
     # ( "you have all the beacons, activate portal next to Forge" )
     setEnable("blink_to_bonuses", "TRUE" )
     setEnable("link_bonus5", "TRUE" )
     waittimed ( 0.500 )
     act("blink_to_bonuses", "blink_to_bonuses" )
endif

