# Generated by BehavEd
# ( "This script checks which conversatoin should be called" )
# ( "This checks if the other stones has been found" )
# ( "*******************************************" )
# ( "The stone objectives must be updated before this conversation is called" )
# ( "*******************************************" )
stone1 = getObjective("act2_obj_5a", "COMPLETE" )
stone2 = getObjective("act2_obj_5b", "COMPLETE" )
if stone1 == 1
     objective ( "act2_obj_5c",  "EOBJCMD_SHOW" )
     if stone2 == 1
          # ( "If true than the first start condition should be mark false" )
          # ( "This will allow the second start condiction to be called" )
          allowConversation("FALSE" )
     endif
elif stone2 == 1
     objective ( "act2_obj_5c",  "EOBJCMD_SHOW" )
endif

