# Generated by BehavEd
# ( "remove Block02_Move power trigger" )
waittimed ( 1.000 )
remove ( "Block02_Move", "Block02_Move" )
sound (  "PLAY_SOUND", "zone_shared/mover/wall_mover", "", "" )
setEnable("Block03_Move", "TRUE" )
setEnable("Block03_Push", "TRUE" )

