# Generated by BehavEd
# ( "test" )
# ( "test" )
setCurrentAct(5 )
setGameFlag("act5_visit", 3, 1 )
waittimed ( 1.000 )
objective ( "find_sun_crys",  "EOBJCMD_SHOW" )
setCurrentAct(5 )
anubis_comp = getObjective("act5_obj_1a", "COMPLETE" )
sekmet_comp = getObjective("act5_obj_1b", "COMPLETE" )
sun_crys = getObjective("find_sun_crys", "COMPLETE" )
finished_1 = getGameFlag("finished", 1 )
if anubis_comp == 1
     if sun_crys == 1
          if finished_1 == 1
               if sekmet_comp == 1
                    remove ( "crys_ped_fire_lt", "crys_ped_fire_lt" )
                    remove ( "sun_crys_harm", "sun_crys_harm" )
                    remove ( "crys_fire_loop", "crys_fire_loop" )
                    setEnable("sun_crystal_ped_emp01", "TRUE" )
               endif
          endif
     endif
endif
if anubis_comp == 1
     act("anubis_complete", "anubis_complete" )
endif
if sekmet_comp == 1
     act("skemet_complete", "skemet_complete" )
endif
puzzles = getGameFlag("egyptpuz", 16 )
if puzzles == 1
     act("force_field_03", "force_field_03" )
endif
end = getGameFlag("finished", 2 )
if end == 1
     copyOriginAndAngles("sun_crystal_comp", "sun_crystal_ped_emp01" )
     setEnable("crys_light01", "TRUE" )
     act("crys_light01", "crys_light01" )
     remove ( "sun_crystal_ped_emp01", "sun_crystal_ped_emp01" )
     remove ( "anubis_complete", "anubis_complete" )
     remove ( "skemet_complete", "skemet_complete" )
     setEnable("crys_zone_1", "TRUE" )
     copyOriginAndAngles("statue_giant_seal01", "leftstatnull" )
     copyOriginAndAngles("statue_giant_seal02", "rightstatnull" )
     remove ( "statue_giant_seal03", "statue_giant_seal03" )
     remove ( "statue_giant_seal04", "statue_giant_seal04" )
     act("statue_giant_seal01", "statue_giant_seal01" )
     act("statue_giant_seal02", "statue_giant_seal02" )
     setEnable("Flash", "TRUE" )
     act("Flash", "Flash" )
     act("sun_crystal", "sun_crystal" )
     remove ( "Flash", "Flash" )
     setEnable("door_giant_seal_egypt_e_eg01", "TRUE" )
     act("door_giant_seal_egypt_e_eg01", "door_giant_seal_egypt_e_eg01" )
     act("door_giant_seal_egypt_e_eg01", "door_giant_seal_egypt_e_eg01" )
     act("crys_zone_2", "crys_zone_2" )
     setEnable("crys_zone_1", "FALSE" )
     setEnable("crys_zone_2", "TRUE" )
     setEnable("link_egypt5", "TRUE" )
endif
sun_crys = getObjective("find_sun_crys", "COMPLETE" )
if sun_crys == 1
     copyOriginAndAngles("sun_crystal_ped_emp", "sun_crystal_ped_full" )
     waittimed ( 0.250 )
     remove ( "crys_light", "crys_light" )
     remove ( "sun_crystal_ped_full", "sun_crystal_ped_full" )
     act("force_field_01", "force_field_01" )
     waittimed ( 0.500 )
     act("force_field_02", "force_field_02" )
     setEnable("crys_anubis_spawn", "TRUE" )
endif

