# Generated by BehavEd
# ( "swap out ped with missing crystal and lower FF" )
copyOriginAndAngles("sun_crystal_ped_emp", "sun_crystal_ped_full" )
remove ( "crys_light", "crys_light" )
waittimed ( 0.500 )
act("force_field_01", "force_field_01" )
waittimed ( 0.500 )
act("force_field_02", "force_field_02" )
objective ( "find_sun_crys",  "EOBJCMD_COMPLETE" )
setEnable("crys_anubis_spawn", "TRUE" )
complete_a = getObjective("act5_obj_1a", "COMPLETE" )
complete_b = getObjective("act5_obj_1b", "COMPLETE" )
setGameFlag("finished", 1, 1 )
if complete_a == 1
     if complete_b == 1
          remove ( "crys_ped_fire_lt", "crys_ped_fire_lt" )
          remove ( "sun_crys_harm", "sun_crys_harm" )
          remove ( "crys_fire_loop", "crys_fire_loop" )
          setEnable("sun_crystal_ped_emp01", "TRUE" )
     endif
endif

