# Generated by BehavEd
# ( "move party from block hallway to Twilight01" )
setallaiactive("FALSE" )
lockControls(-1.000 )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
moveHeroesToEnt("playerA01" )
waittimed ( 1.000 )
cameraFade(0.000, 1.000 )
setallaiactive("TRUE" )
lockControls(0.100 )

