# Generated by BehavEd
# ( "comment" )
playanim (  "EA_STUCK", "_ACTIVATOR_", "NONE", "" )
waittimed ( 1.500 )
fade("_OWNER_", 0.000, 1.000, "TRUE" )
waittimed ( 1.000 )
remove ( "_OWNER_", "_OWNER_" )

