# Generated by BehavEd
# ( "fade out and reset camera" )
cameraFade(1.000, 0.500 )
waittimed ( 0.500 )
cameraReset( )
# ( "fade in and unlock controls" )
cameraFade(0.000, 1.000 )
waittimed ( 1.000 )
lockControls(0.100 )
setallaiactive("TRUE" )
# ( "update objectives" )
objective ( "act3_obj_2f",  "EOBJCMD_SHOW" )

