# Generated by BehavEd
# ( "destroyed coolant pump. yay!" )
objective ( "act3_obj_2e",  "EOBJCMD_INCREMENT" )
setGameFlag("coolpumps", 1, 1 )
doorcheck = getObjective("act3_obj_2e", "COMPLETE" )
if doorcheck == 1
     # ( "both pumps destroyed" )
     # ( "fade out, lock controls, set camera" )
     cameraFade(1.000, 0.500 )
     waittimed ( 0.500 )
     lockControls(-1.000 )
     setallaiactive("FALSE" )
     # ( "move camera" )
     cameraToLocationAngles(" 1265.000 1774.000 236.000 ", " 1265.000 1950.000 1.000 ", 0.000 )
     # ( "fade in" )
     cameraFade(0.000, 0.500 )
     waittimed ( 1.000 )
     # ( "open sugardoor" )
     act("sugardoor", "sugardoor" )
     # ( "start conversation" )
     waittimed ( 1.000 )
     startConversation("act3/corein/corein4/3_corein4_0920" )
else
     # ( "one pump destroyed, one pump left" )
     startConversation("act3/corein/corein4/3_corein4_0010" )
endif

