# Generated by BehavEd
# ( "lock controls" )
lockControls(-1.000 )
setallaiactive("FALSE" )
# ( "move camera and spawn portal" )
cameraFocusToEntity("link_military1", 360.000, 45.000, 225.000, 1.000 )
waittimed ( 2.000 )
act("portal_spawn", "portal_spawn" )
waittimed ( 0.750 )
act("portal_loop", "portal_loop" )
setEnable("link_military1", "TRUE" )
waittimed ( 1.000 )
startConversation("act3/corein/corein4/3_corein4_0910b" )

