# Generated by BehavEd
# ( "Intro of Sugahman" )
met = getGameFlag("bosses", 15 )
if met == 0
     cameraMove(" 1403.780 2937.000 -62.230 ", 0.000 )
     cameraPan(" 0.867 9.963 119.924 ", 0.000, "FALSE" )
     copyOriginAndAngles("_HERO1_", "herospot01" )
     copyOriginAndAngles("_HERO2_", "herospot02" )
     copyOriginAndAngles("_HERO3_", "herospot03" )
     copyOriginAndAngles("_HERO4_", "herospot04" )
     # ( "Sugerman's conversation" )
     startConversation("act3/corein/corein4/3_corein4_0210" )
     # ( "set the var that keeps track of the fact we've talked to sugarman" )
     setGameFlag("bosses", 15, 1 )
else
     setEnable("arena_trigger", "TRUE" )
     setDefaultTarget("sugarman" )
endif

