# Generated by BehavEd
# ( "comment" )
lockControls(0.000 )
cameraFade(1.000, 1.000 )
waittimed ( 1.000 )
cameraMove(" 2613.140 3596.380 365.470 ", 1.000 )
cameraPan(" 0.000 46.000 91.100 ", 0.000, "FALSE" )
waittimed ( 1.000 )
cameraFade(0.000, 0.500 )
# ( "moves the players to their spots" )
# ( "but checks to see if they are alive first" )
isHero1Alive = alive("_HERO1_" )
if isHero1Alive == 1
     # ( "hero1 is alive" )
     copyOriginAndAngles("_HERO1_", "herospot01" )
else
     # ( "hero1 is dead as a doornail" )
endif
isHero2Alive = alive("_HERO2_" )
if isHero2Alive == 1
     # ( "hero2 is alive" )
     copyOriginAndAngles("_HERO2_", "herospot02" )
else
     # ( "hero2 is dead as a doornail" )
endif
isHero3Alive = alive("_HERO3_" )
if isHero3Alive == 1
     # ( "hero3 is alive" )
     copyOriginAndAngles("_HERO3_", "herospot03" )
else
     # ( "hero3 is dead as a doornail" )
endif
isHero4Alive = alive("_HERO4_" )
if isHero4Alive == 1
     # ( "hero4 is alive" )
     copyOriginAndAngles("_HERO4_", "herospot04" )
else
     # ( "hero4 is dead as a doornail" )
endif
heroNoTarget("TRUE" )
act("ambush_behemoth", "ambush_behemoth" )
# ( "in with the behemoth" )
waittimed ( 2.000 )
# ( "locks the players in" )
act("ambush_door01", "ambush_door01" )
act("ambush_door02", "ambush_door02" )
act("sound_doors", "sound_doors" )
waittimed ( 1.000 )
lockControls(0.100 )
cameraResetOldSchool( )
heroNoTarget("FALSE" )
waittimed ( 2.000 )
act("steve_spawner", "steve_spawner" )
act("tony_spawner", "tony_spawner" )

