# Generated by BehavEd
# ( "this is the zone script for infinite5" )
protocols = getGameFlag("protocols", 7 )
if protocols == 1
     killEntitySilent("fusion_core" )
endif
beenHere = getGameFlag("act3_visit", 9 )
if beenHere == 0
     setGameFlag("act3_visit", 9, 1 )
     startConversation("act3/infinite/infinite5/3_infinite5_0010" )
endif

