# Generated by BehavEd
# ( "protocol flag 3 = Decryption Module Key from infinite1" )
# ( "1 = Decryption Module , 0 = No Decryption Module" )
protocols = getGameFlag("protocols", 3 )
if protocols == 1
     act("door_tech01", "door_tech01" )
     act("door_tech02", "door_tech02" )
     remove ( "trigger_tech_door01", "trigger_tech_door02" )
     # ( "update objectives" )
     allowConversation("FALSE" )
else
     # ( "Access Denied: Decryption Module Not Present" )
     allowConversation("TRUE" )
endif

