# Generated by BehavEd
# ( "comment" )
waittimed ( 0.100 )
remove ( "air_skull_placement_trigger", "air_skull_placement_trigger" )
lockControls(-1.000 )
copyOriginAndAngles("air_skull_placement", "air_skull_null" )
lockControls(0.100 )
objective ( "act2_obj_4a_d1",  "EOBJCMD_COMPLETE" )
act("skull_relay", "skull_relay" )

