# Generated by BehavEd
# ( "comment" )
remove ( "air_skull", "air_skull" )
setEnable("air_skull_placement_trigger", "TRUE" )
objective ( "act2_obj_4a_d",  "EOBJCMD_SHOW" )
objective ( "act2_obj_4a_d",  "EOBJCMD_COMPLETE" )
objective ( "act2_obj_4a_d1",  "EOBJCMD_SHOW" )

