# Generated by BehavEd
# ( "comment" )
waittimed ( 0.100 )
remove ( "earth_skull_placement_trigger", "earth_skull_placement_trigger" )
lockControls(-1.000 )
copyOriginAndAngles("earth_skull_placement", "earth_skull_null" )
lockControls(0.100 )
objective ( "act2_obj_4a_c1",  "EOBJCMD_COMPLETE" )
act("skull_relay", "skull_relay" )

