# Generated by BehavEd
# ( "comment" )
remove ( "earth_skull", "earth_skull" )
setEnable("earth_skull_placement_trigger", "TRUE" )
objective ( "act2_obj_4a_c",  "EOBJCMD_SHOW" )
objective ( "act2_obj_4a_c",  "EOBJCMD_COMPLETE" )
objective ( "act2_obj_4a_c1",  "EOBJCMD_SHOW" )

