# Generated by BehavEd
# ( "comment" )
waittimed ( 0.100 )
remove ( "fire_skull_placement_trigger", "fire_skull_placement_trigger" )
lockControls(-1.000 )
copyOriginAndAngles("fire_skull_placement", "fire_skull_null" )
lockControls(0.100 )
objective ( "act2_obj_4a_a1",  "EOBJCMD_COMPLETE" )
act("skull_relay", "skull_relay" )

