# Generated by BehavEd
# ( "comment" )
remove ( "fire_skull", "fire_skull" )
setEnable("fire_skull_placement_trigger", "TRUE" )
objective ( "act2_obj_4a_a",  "EOBJCMD_SHOW" )
objective ( "act2_obj_4a_a",  "EOBJCMD_COMPLETE" )
objective ( "act2_obj_4a_a1",  "EOBJCMD_SHOW" )

