# Generated by BehavEd
# ( "comment" )
remove ( "jolly_rancher_monkey", "jolly_rancher_monkey" )
setGameFlag("skullpickup", 5, 1 )
objective ( "act2_obj_4a",  "EOBJCMD_COMPLETE" )
objective ( "act2_obj_4b",  "EOBJCMD_SHOW" )
startConversation("act2/monument/monument5/2_monument5_0030" )

