# Generated by BehavEd
# ( "these should be shown before you get to this map." )
skull = getObjective("act2_obj_4a_a", "HIDDEN" )
if skull == 0
     waittimed ( 0.500 )
     remove ( "trigger_touch01", "trigger_touch01" )
     remove ( "trigger_use01", "trigger_use01" )
     setHintType("fire_skull", "objective" )
     setHintType("air_skull", "objective" )
     setHintType("water_skull", "objective" )
     setHintType("earth_skull", "objective" )
endif
skull_bs = getObjective("act2_obj_4a_d", "COMPLETE" )
if skull_bs == 1
     remove ( "air_skull", "air_skull" )
     # ( "have we placed the skull on the altar yet?" )
     altar1 = getObjective("act2_obj_4a_d1", "COMPLETE" )
     if altar1 == 1
          copyOriginAndAngles("air_skull_placement", "air_skull_null" )
          remove ( "air_skull_placement_trigger", "air_skull_placement_trigger" )
     else
          setEnable("air_skull_placement_trigger", "TRUE" )
     endif
endif
skull_bs2 = getObjective("act2_obj_4a_b", "COMPLETE" )
if skull_bs2 == 1
     remove ( "water_skull", "water_skull" )
     # ( "have we placed the skull on the altar yet?" )
     altar2 = getObjective("act2_obj_4a_b1", "COMPLETE" )
     if altar2 == 1
          copyOriginAndAngles("water_skull_placement", "water_skull_null" )
          remove ( "water_skull_placement_trigger", "water_skull_placement_trigger" )
     else
          setEnable("water_skull_placement_trigger", "TRUE" )
     endif
endif
skull_bs3 = getObjective("act2_obj_4a_a", "COMPLETE" )
if skull_bs3 == 1
     remove ( "fire_skull", "fire_skull" )
     remove ( "fire_large01", "fire_large01" )
     # ( "have we placed the skull on the altar yet?" )
     altar3 = getObjective("act2_obj_4a_a1", "COMPLETE" )
     if altar3 == 1
          copyOriginAndAngles("fire_skull_placement", "fire_skull_null" )
          remove ( "fire_skull_placement_trigger", "fire_skull_placement_trigger" )
     else
          setEnable("fire_skull_placement_trigger", "TRUE" )
     endif
endif
skull_bs4 = getObjective("act2_obj_4a_c", "COMPLETE" )
if skull_bs4 == 1
     remove ( "earth_skull", "earth_skull" )
     swapInStump("avalanche_finger_cage_b_mo01" )
     # ( "have we placed the skull on the altar yet?" )
     altar4 = getObjective("act2_obj_4a_c1", "COMPLETE" )
     if altar4 == 1
          copyOriginAndAngles("earth_skull_placement", "earth_skull_null" )
          remove ( "earth_skull_placement_trigger", "earth_skull_placement_trigger" )
     else
          setEnable("earth_skull_placement_trigger", "TRUE" )
     endif
endif
# ( "this is for the vibranium idol" )
skull_bs5 = getObjective("act2_obj_4a", "COMPLETE" )
# ( "have we already picked this sucker up?" )
if skull_bs5 == 1
     # ( "yes? ok then remove it." )
     remove ( "trigger_use01", "trigger_use01" )
     remove ( "jolly_rancher_monkey", "jolly_rancher_monkey" )
     remove ( "idol_trigger", "idol_trigger" )
endif
skullreturn = iadd(0, 0 )
skull = getObjective("act2_obj_4a_a1", "COMPLETE" )
skullreturn = iadd(skullreturn, skull )
skull = getObjective("act2_obj_4a_b1", "COMPLETE" )
skullreturn = iadd(skullreturn, skull )
skull = getObjective("act2_obj_4a_c1", "COMPLETE" )
skullreturn = iadd(skullreturn, skull )
skull = getObjective("act2_obj_4a_d1", "COMPLETE" )
skullreturn = iadd(skullreturn, skull )
if skullreturn >= 1
     act("altar1_rise", "altar1_rise" )
     remove ( "trigger_touch01", "trigger_touch01" )
endif
if skullreturn >= 2
     act("altar2_rise", "altar2_rise" )
endif
if skullreturn >= 3
     act("altar3_rise", "altar3_rise" )
endif
if skullreturn == 4
     waittimed ( 0.100 )
     act("altar4_rise", "altar4_rise" )
     setEnable("idol_trigger", "TRUE" )
     setHintType("jolly_rancher_monkey", "objective" )
     reset = getZoneReset( )
     if reset == 1
          act("jolly_rancher_monkey", "jolly_rancher_monkey" )
     endif
endif

