# Generated by BehavEd
# ( "comment" )
objective ( "act2_obj_4a_a",  "EOBJCMD_SHOW" )
objective ( "act2_obj_4a_b",  "EOBJCMD_SHOW" )
objective ( "act2_obj_4a_c",  "EOBJCMD_SHOW" )
objective ( "act2_obj_4a_d",  "EOBJCMD_SHOW" )
setHintType("fire_skull", "objective" )
setHintType("air_skull", "objective" )
setHintType("water_skull", "objective" )
setHintType("earth_skull", "objective" )

