# Generated by BehavEd
# ( "comment" )
remove ( "water_skull", "water_skull" )
setEnable("water_skull_placement_trigger", "TRUE" )
objective ( "act2_obj_4a_b",  "EOBJCMD_SHOW" )
objective ( "act2_obj_4a_b",  "EOBJCMD_COMPLETE" )
objective ( "act2_obj_4a_b1",  "EOBJCMD_SHOW" )

