# Generated by BehavEd
# ( "comment" )
waittimed ( 0.100 )
remove ( "water_skull_placement_trigger", "water_skull_placement_trigger" )
lockControls(-1.000 )
copyOriginAndAngles("water_skull_placement", "water_skull_null" )
lockControls(0.100 )
objective ( "act2_obj_4a_b1",  "EOBJCMD_COMPLETE" )
act("skull_relay", "skull_relay" )

